### ISSUE TITLE
Solution insert codeblock

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#100]
It is not possible to use **lstlisting** in solution mode.
Error: ! Paragraph ended before \lst@next was complete.
Example
`
\begin{solution}
\begin{lstlisting}[style=Java]
...
\end{lstlisting}
\end{solution}
`

**Comment by TeXhackse** [comment]
Thank you for the report. I fixed that and will include it to the next release. I am not sure if I will mamage to prepare a new release this week. A Quickfix would be 

```
\ExplSyntaxOn
\def\solution{
\bool_if:NTF \l_TUDa_ex_solution_bool \TUDa_ex_solutionheader: \iffalse
}
\def\endsolution{
	\bool_if:NF \l_TUDa_ex_solution_bool \fi
}
\ExplSyntaxOff
```
