### ISSUE TITLE
Task change default text

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#101]
Is it possible to change the default text of \begin{task}?
For example, instead of task 5 to V5/ H5 or similar.

**Comment by TeXhackse** [comment]
„task“ ist saved to \taskname. So you can do 
```
\renewcommand*{taskname}{Whateveryouwant}
```
If you want to define it language dependent have a look at KOMA-Script's `\defcaptionname`

**Comment by Zentox** [comment]
My phrasing was unfortunate. For example. \begin{task} would print "Task 5.1 ":" Titelei", how can I change this to eg. V5 without "**:**".

\ renewcommand * {\ taskname} {V} does not work
\ renewcommand * {\ taskformat} {V \ tasksep \ thetask {}} works, but how can I print without a colon?

**Comment by TeXhackse** [comment]
```
\renewcommand*{\taskname}{V}
```
works, but only after Babel has been initialized. Sorry I forgot to tell you about that. So It has to be set right behind `\begin{document}`. The better way would be
```
\renewcaptionname{english}{\taskname}{V}
```
The space + colon are set in `\tasksep`. So you can do 
```
\renewcommand*{\tasksep}{}
```
Or whatever you want as a seperator.

General Hint: You can use `\meaning` to print the meaning of a macro, or `\show` to show it on the command line,  so 
```
\meaning\tasksep
``` 
would tell you about the colon being a part of it.

**Comment by Zentox** [comment]
`\renewcommand*{\tasksep}{}`
This does not help, as it is only the space between \ taskname and \ thetask.
`
\renewcaptionname{english}{\taskname}{V}`
This works.

```
\renewcommand*{\thetask}{Titelei}
\begin{task}{}
...
\end{task}
```

This returns Task Titelei without the ":".
The old one returns Task 5.1: Title with ":".
```
\begin{task}{Titel}
...
\end{task}
```
Is there a prettier way to remove the colon because `\renewcommand*{\tasksep}{}` does not work and writing `\renewcommand*{\thetask}{Text}` before every `\begin{task}{}` does not look good.

I apologize for the many questions and thank you in advance.

**Comment by TeXhackse** [comment]
crap. sorry that was my fault.  I mixed something up.

There is no hook for the colon. The colon is only added, when the task gets a title. I think about changing that in the future. The tasksep is the one between taskname and number.

The colon currently is set in 
```
\renewcommand*\sectionlinesformat[4]{%
\parbox{\linewidth}{
	\rule[5\g_TUDa_titlerule_dim]{\linewidth}{\g_TUDa_titlerule_dim}\par\nointerlineskip
	\@hangfrom{%
		\hskip #2#3}{
		\tl_if_eq:nnT {#1} {task} {
			\exp_args:No \tl_if_empty:nF {#4}
				{:~}
		}
		#4\rule[-\dp\strutbox]{0pt}{\dp\strutbox}\par}\nointerlineskip
		\skip_vertical:n {\TUDa_titlerule_sep: -\dp\strutbox}
	\smash{\rule{\linewidth}{\g_TUDa_titlerule_dim}}
}}
```

You can change that only by redefining that macro. So e.g. do it like this:
```
\makeatletter
\def\TUDa@tasktotitlesep{<insert your seperator here>}
\ExplSyntaxOn
\renewcommand*\sectionlinesformat[4]{%
\parbox{\linewidth}{
	\rule[5\g_TUDa_titlerule_dim]{\linewidth}{\g_TUDa_titlerule_dim}\par\nointerlineskip
	\@hangfrom{%
		\hskip #2#3}{
		\tl_if_eq:nnT {#1} {task} {
			\exp_args:No \tl_if_empty:nF {#4}
				{ \TUDa@tasktotitlesep}
		}
		#4\rule[-\dp\strutbox]{0pt}{\dp\strutbox}\par}\nointerlineskip
		\skip_vertical:n {\TUDa_titlerule_sep: -\dp\strutbox}
	\smash{\rule{\linewidth}{\g_TUDa_titlerule_dim}}
}}
\ExplSyntaxOff
\makeatother
```

Sorry for my misstake once again. I will think about ading that hook in general
