### ISSUE TITLE
CTAN version 2.03 won't compile!

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#102]
This is already fixed and we increased the CTAN version number to 2.03a. 
But if you update your distribution right in this short period where the buggy version is distributed, just wait a bit for the next update. 

This is an informing issue, so you don't try to debug it. 
I also adjusted the deployment process, so this won't happen again.

**Comment by open711** [comment]
I waited until V2.03a was available on MiKTeX. Today was also the oberdiek package updated. Resulting in an error:
"! LaTeX Error: File `kvoptions.sty' not found. Type X to quit or <RETURN> to proceed, or enter new name. (Default extension: sty) Enter file name: ! Emergency stop."
Minimal example is the DEMO-TUDaPhD.tex.

Is that problem related to the oberdiek or tuda-package?

**Comment by TeXhackse** [comment]
This only means, that you did not install kvoptions.sty

I did not add any other packages. So I guess it's oberdiek. But it has nothing to do with that one either. You can simply install that package using mikTeX. Then you should be fine.

**Comment by TeXhackse** [comment]
I close this as all mirrors now seem to be synced.

**Comment by TeXhackse** [comment]
@open711 maybe you saw it already, but #105  might be interesting for you as well, since kvoptions currently seems to be no part of MikTeX atm
