### ISSUE TITLE
Exercise Subtask Title: No Value

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#103]
Is it possible to change the Text of a subtask?
```
\begin{task}{Titelei}
\begin{subtask}
Text 1
\end{subtask}
\begin{subtask}{Test}
Text 2
\end{subtask}
```
![Exercise](https://user-images.githubusercontent.com/46193012/69905873-a9182c80-13ba-11ea-915c-00c5f6c98731.png)

**Comment by TeXhackse** [comment]
Thanks for the report. this is a bug. the -NoValue- shouldn't be printed.
And yes you can  change that by adding an optional argument. 
```
\begin{subtask}[title]
…
```
The definition can be fixed by adding the following to your preamble:
```
\makeatletter
\NewDocumentEnvironment{subtask}{o}{%
	\@subtask{\IfNoValueF{#1}{#1}}%
      }{}
\makeatother
```
