### ISSUE TITLE
"Darmstadt - D17" not required anymore

### ISSUE THREAD

**Issue by marklaz** [tudace/tuda_latex_templates#107]
Looking at the official pages concerning formal requirements on title page etc. (https://www.tu-darmstadt.de/forschen/wissenschaftlicher_nachwuchs_tu/promotionsinteressierte_tu/artikel_details_de_en_176641.de.jsp) shows that the statement "Darmstadt - D17" does not seem to be required anymore.

Therefore, I would suggest to add the line "\publishers{Darmstadt <year of publication>}" into DEMO_TUDaPhD.tex, which should be suffcient.

**Comment by TeXhackse** [comment]
Hm. I'd like to wait with the removal, since it might change some running projects. So I will add a Message for the next release + add some information in the documentation.

And finally remove that for the next major one. Otherwise users might get confused about that change.

**Comment by marklaz** [comment]
I did not want to suggest a removal. Let us keep the class files as they are and only change the DEMO file mentioned above. That should do from my side.

**Comment by TeXhackse** [comment]
okay. It's mentioned in the DEMO file already, but I can add it there in title data in the sources as well.
