### ISSUE TITLE
Unicode-Math breaks font

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#109]
I assume this may be due to the changes for #42.
Here's a comparison of pdfa=true and pdfa=false with `\usepackage{unicode-math}`

pdfa=true
![unicode-math](https://user-images.githubusercontent.com/2090520/70041787-0fb96800-15be-11ea-8bb5-51941d30137d.png)

pdfa=false
![pdfa-false](https://user-images.githubusercontent.com/2090520/70041764-04fed300-15be-11ea-88c6-127bdbb5cf29.png)

Also since you're now sticking to T1 fonts for pdfa compatibility anyway, I don't see any reason not to switch back to mathdesign for the math fonts as discussed in #19.
If the codebase didn't change significantly, this should be easily possible similar to this [experiment](https://github.com/tudace/tuda_latex_templates/commit/7f904120b7a58372b4c634f1725c88e9e6874da5) but the `\usepackage[charter]{mathdesign}` should be before all possible inclusions of `fontspec` IIRC.

This would indirectly solve my problem because I wouldn't need `unicode-math` for a more fitting math font setup anymore.

**Comment by TeXhackse** [comment]
Short answer: *unicode-math* uses luaotfload. luaotfload disables the Type1 font loader. You should not load fontspec at all. This would overwrite all settings done to Type1 as you just realiazed.

If you want to use mathdesign, you still can load it yourself. So you don't rely on unicode math. It's your choice. Thats why we did not change the default at all. And probably won''t do that in the future.

**Comment by StefanFabian** [comment]
I didn't load fontspec but I assumed the class does.

Great, I've just tried it and mathdesign now works. Back when I opened the original font issue #19, including it broke the headings etc.

**Comment by TeXhackse** [comment]
I thought you loaded unicode-math?

uncode-math loades fontspec => you did it ;-)

The class only loads fontspec if you are using xelatex or lualatex and pdfa=false.

**Comment by StefanFabian** [comment]
> I thought you loaded unicode-math?
>
> uncode-math loades fontspec => you did it ;-)

See? It wasn't me :P

Yeah, I'm absolutely fine with whatever makes the math font not look like shit and actually matches the text font. I still think it should be the default (maybe with an option to disable) since the normal math font does not fit Charter or Roboto at all.

**Comment by TeXhackse** [comment]
> Yeah, I'm absolutely fine with whatever makes the math font not look like shit and actually matches the text font. I still think it should be the default (maybe with an option to disable) since the normal math font does not fit Charter or Roboto at all.

I'd prefer that as well. Sadly in most cases CD is created by Designers and fonts in most cases don't have a math alphabet. If youl would have one (even if its non-free) it wouldn't be a problem to include that. Sadly neither Roboto nor Charter have any math characters. So the only way is to mix it up. But we discussed that before ;-)
