### ISSUE TITLE
Anpassung der Titelseite (Matrikelnummer)

### ISSUE THREAD

**Issue by Alfonso1991** [tudace/tuda_latex_templates#110]
Ist es möglich auf der ersten Seite die Matrikelnummer zu plazieren?

Erst hatte ich versucht, sie in die Namensdefinition zu setzen( \author[Name]{Name | Matrikelnummer}), dann erscheint sie aber auch in der "Erklärung zur Abschlussarbeit". 

Ist es auch Allgemein möglich den Text auf der ersten Seite zu ändern?

Zum Beispiel, das man diesen Text erhält?

Masterarbeit   
Max Mustermann | 12345678   
Studiengang

**Comment by TeXhackse** [comment]
Jein. Also ja, mögich ist alles ;-) 

Grundsätzlich ist das aber nicht vorgesehen. Das Autor-Feld soll ja auch nur den Autor bekommen. Wennwann wäre ein Extra Feld eine Option, das aber kein Bestandteil der mir vorliegenden Vorgaben war.

Die wohl einfachste Option wäre, das `\author` Macro zwischen `\maketitle` und `\affidavit` noch einmal mit geändertem Wert aufzurufen. Das ist zwar eigentlich nicht Sinn der Sache, funktioniert jedoch.

**Comment by marklaz** [comment]
Ich bitte um die Ergänzung eines Feldes Matrikelnummer, das bei Bedarf befüllt werden kann und auf das dann mit einem Makro zugegriffen werden kann, um es an beliebiger Stelle zu ergänzen.

**Comment by TeXhackse** [comment]
Okay, ihr kriegt ein `\StudentID` Makro.

**Comment by TeXhackse** [comment]
Ist drin. Ergänzung der Doku mach ich jetzt, dann ist das direkt im Release.
