### ISSUE TITLE
How to set math fonts to main font (Charter)?

### ISSUE THREAD

**Issue by rindPHI** [tudace/tuda_latex_templates#111]
Hello,

when I use \mathit, \mathrm etc., the font looks different from the main text font. Unfortunately, I cannot set the math fonts using the mathspec package, since the usepackage directive alone gives me a fatal TeX error (obviously, mathspec requires XeTeX). I cannot load fontspec either since this seems to conflict with some other packages (I get errors like "command \acute already defined). I'd be happy for advice on how to unify the math fonts with the main fonts in the TU theme.

I'm using LuaLaTeX with a recent TeXLive installation.

Thanks and Best Regards,
Dominic

**Comment by rindPHI** [comment]
OK, I traced it down a little finally. Obviously, one may not import _mathtools_.
I wanted to point out that I obtain the following warning:

```
LaTeX Font Info:    Try loading font information for TU+XCharter-TLF on input line 45.
LaTeX Font Info:    No file TUXCharter-TLF.fd. on input line 45.


LaTeX Font Warning: Font shape `TU/XCharter-TLF/m/n' undefined
(Font)              using `TU/lmr/m/n' instead on input line 45.
```

Might this be related to the problem that my math fonts are not set in Charter?

**Comment by rindPHI** [comment]
I found a solution: It's sufficient to add the import `\usepackage{mathastext}`. Then I can also continue using _mathtools_. I'll leave this issue open for now since I'm interested in finding out whether it's intended that the math fonts are different from the main fonts, and whether anybody knows the origin of that Charter-related warning shown before.

**Comment by TeXhackse** [comment]
*mathastext* is no solution at all :/

Anyway:
As written in the Demo files: the pdfa-mode enforces Type1 fonts. 
Thats why loading fontspec is a bad idea about it. 

Generally when using fontspec you should load all ams packages *before loading fontspec*

Beside that: Charter has no real math font! There are some *crafted* variants to be used together with that. Some have been discussed in #19. The simply variant to keep pdfa valid is to use mathdesign. 

If you don't need a pdfa and use fontspec you can also find some variants there.

**Comment by rindPHI** [comment]
Thanks for the quick answer!

mathdesign seems to be a nice solution, however it can also not be used together with amsmath and amsfonts, which is a pity... (OK, it's only a package warning, maybe there are no serious problems--I didn't check--but that doesn't produce comfortable feelings ;) )

My main goal is to unify the **serif fonts**, since the default (probably latin modern) font does not seem nice together with the font in the TU design. Ah, and the caligraphic letters don't look nice with mathtools (Charter), they're all too curly. So the `setmathrm` command would be ideal for me, but if that breaks anything (as it seems), I'd just give up. The crafted solutions in the referenced issue also don't work directly (compilation errors). Thank you very much anyway!

**Comment by rindPHI** [comment]
Ah, the following seems to work (which unifies the roman fonts, that's all I wanted actually):

```
\DeclareMathAlphabet{\mathrm}{OT1}{\familydefault}{m}{n}
```

**Comment by TeXhackse** [comment]
> mathdesign seems to be a nice solution, however it can also not be used together with amsmath and amsfonts, which is a pity... (OK, it's only a package warning, maybe there are no serious problems--I didn't check--but that doesn't produce comfortable feelings ;) )

This is only due to the order you load the packages. Usually first load all ams packages and font changing ones afterwards.

Problem with mixing up fonts might result in crappy kerning. Just to warn you. I'll close this one then.
