### ISSUE TITLE
Literatur nicht im Inhaltsverzeichnis

### ISSUE THREAD

**Issue by Alfonso1991** [tudace/tuda_latex_templates#112]
Wenn ich meine Datei plotte, erscheint die Literatur nicht im Inhaltsverzeichnis.
Habe das jetzt folgendermaßen gelöst:

`\addcontentsline{toc}{chapter}{Literatur}
\printbibliography`

Falls es noch jemanden betrifft.

**Comment by TeXhackse** [comment]
Kurzer Hinweis: Das ist Standard-LaTeX. Demnach ist das hier eigentlich nicht der richtige Ort dafür, da ich gerade aber ohnehin hier bin:

Eigentlich löst man das mit der Dokumentenklassenoption:
`bibliography=totoc`

Anderenfalls kann es passieren, dass erstens die Seite vorher oder ggf. auch noch weiter Vorne eingetragen wird und nicht die richtige Seite. Für die Erklärung dafür aber bitte einen Anfängerkurs besuchen. Da geht mir jetzt die Zeit aus,
