### ISSUE TITLE
Ugly line after remove examheader tudaexcersice

### ISSUE THREAD

**Issue by long21wt** [tudace/tuda_latex_templates#113]
There is an unnecessary line after removing examheader block. I have tried to find a rule to disable it, but couldn't. 
![exam](https://user-images.githubusercontent.com/46249208/70239162-15a07c00-176b-11ea-9716-42310d06c423.png)

**Comment by TeXhackse** [comment]
Thanks for that report.

I wil change it the way, that the headsepline will automaticall set to 0pt, when the headline is empty.

As a workaroung, you can use:
```
\KOMAoptions{headsepline=0pt}
```

**Comment by long21wt** [comment]
Perfect, thanks for your help
