### ISSUE TITLE
German and English Abstract

### ISSUE THREAD

**Issue by Alfonso1991** [tudace/tuda_latex_templates#115]
Is it possible to place both, the german and the english abstract on one Page?

**Comment by juppees** [comment]
Since the abstract environment seems to use the ``\chapter{}`` command, you can redefine the command ``\clearpage`` and ``\cleardoublepage`` locally:
```LaTex
\begin{abstract}[ngerman]
	Abstract in German.
\end{abstract}

\begingroup
	\renewcommand{\cleardoublepage}{}
	\renewcommand{\clearpage}{}
	\begin{abstract}[english]
		Abstract in English.
	\end{abstract}
\endgroup
```

**Comment by TeXhackse** [comment]
Currently it is able by using KOMA-Scripts tocfeature leveldown. The disposition level of abstract is the same as the toc one. (Currently thinking about adding a specific option)

Anyway: the heading layout for `\chapter` is designed to not happen in the middle of a page. This might destroy the design idea. 

A better way would be to add a chapter called „Abstracts“ or „Zusammenfassung“ and change the level of the single abstracts. Either by using the leveldown or by 

```
\begingroup
\let\chapter\section
<abstract here>
\endgroup
```

**Comment by TeXhackse** [comment]
@Alfonso1991 did that help you? 

@marklaz  do you think this is a general issue, so we should change something about the implementation?

**Comment by Alfonso1991** [comment]
I uesed the code provieded by juppees and it works the way i wanted.

**Comment by TeXhackse** [comment]
Thank you, I'll close this and ask @marklaz to reopen if he recognizes a general requirement for that
