### ISSUE TITLE
Caption and Title

### ISSUE THREAD

**Issue by FlixXIV** [tudace/tuda_latex_templates#116]
Hello,

i've got two questions. First I'd like to know, whether there is a possibility to have no logo in the title of a document. There should be just grey space with the title. The second problem is, that if you want to title a picture or a table in a "figure-environment" with caption, this title isn't  centered even if you write \centering before.

Thanks for your help.

**Comment by schoeps** [comment]
Some general remarks (which hold for pretty much all projects on the internet): please read the documentation first. Only raise an issue if something is not working as expected. Please open a separate issue for each problem. Give minimal working examples for each issue.

Regarding your questions: you did not say what document type you are dealing with. Nonetheless, did you try the "logo=false" documentclass option? This is a documented feature. 

Second, you can modify the style of captions using standard koma-class commands (read its manual or just use google...). In this case "centering" applies only to the object inside of the environment (e.g the figure) and it does not work for the caption. Even of it would work it is a bad idea to enforce a general design of a document by "local" formatting commands. Also, try to not change the design, this is the whole point of corporate identity. Another suggestion: don't put tables inside a figure environment, use the table environment instead.

**Comment by schoeps** [comment]
Beispiel
```
\documentclass{tudapub}
\usepackage{graphicx}
\setcapindent{0em}
\begin{document}
\begin{figure}
	FIGURE
	\caption{Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.}
\end{figure}
\end{document}

```
