### ISSUE TITLE
tudapub: custommargins and marginpar options do not work as expected

### ISSUE THREAD

**Issue by marklaz** [tudace/tuda_latex_templates#117]
Class options
custommargins=true,
marginpar=true,

do not extend the header block above marginal column.

All other combinations of these options work fine.

**Comment by TeXhackse** [comment]
Thanks for the report. I am working on that. Will be included to the next release. Problem is, that all others calculations depend on the marginpar to be included in the typearea. 

(Anyway this will create weird layouts)
