### ISSUE TITLE
no author name in \affidavit

### ISSUE THREAD

**Issue by schrchr** [tudace/tuda_latex_templates#12]
When compiling the example file `DEMO-TUDaThesis.tex`, the upper name is missing. Maybe it is related to [this issue](https://github.com/tudace/tuda_latex_templates/issues/3).

![grafik](https://user-images.githubusercontent.com/50080123/63215795-1f569300-c12c-11e9-9ed4-acec42f99a82.png)

**Comment by marklaz** [comment]
This is already corrected in the development version on github (see  #9) and will be rolled out with the next official version.

**Comment by Thorgas1988** [comment]
Are you sure that it is fixed? I still get no valid name in there, although I set
\author[Shortname]{Name}

or

\affidavit{Name}

What is the correct way to pass the name in there?

**Comment by azrdev** [comment]
Indeed my intended fix f4096a1bcfa31591672b751bab8870c13fc8374e was none, since `#1` doesn't contain the author name but whether `\affidavit` or `\affidavit*` was called, instead `\TUDa@signature` has to be used and seems to work for me.

**Comment by marklaz** [comment]
![Screenshot_20190924_151546](https://user-images.githubusercontent.com/50663900/65514812-5adc3e00-dede-11e9-9648-7a9aaf6a20e6.png)
Der Autorenname bei DEMO_TUDaThesis wird in v1.10 nicht im Affidavit ergänzt (s.o.).

**Comment by marklaz** [comment]
Ok, ich dachte das wäre bereits in 1.10 erledigt, da das ursprüngliche Issue vom August war.

Bitte, sobald noch 2-3 weitere Änderungen umgesetzt wurden, ein neues Minor-Release machen, da das wirklich ein Punkt ist, über den einige stolpern werden. VD!

**Comment by TeXhackse** [comment]
ich hatte die zeitlichen Sachen nicht mehr im Kopf, aber ich kann auch direkt heute noch einen hinterherschießen, dann lass ich das mit den exercises aber erstmal noch raus, packe das aber mal als demo mit in die release info.

**Comment by marklaz** [comment]
Alles klar, dann bitte unmittelbar ein kleines Release-Update heute. VD!
