### ISSUE TITLE
Label and reference problem. 

### ISSUE THREAD

**Issue by SaschaStenger** [tudace/tuda_latex_templates#120]
Hi

sorry if this issue has already been described somewhere, but I can't find it, so I'll write one myself.
I'm using the TUDaThesis template and have problems concerning my labels and when referencing those labels. 

```
\begin{figure}[ht]
\centering
    \input{figures/2_Method/GCN.tex}
    \caption{The architecture of the neural network.}\label{fig:GCN}
\end{figure}
Text referencing the figure \ref{fig:GCN}.
```

Will result in the following warnings:
```
Package caption Warning: \label without proper reference on input line 156. See the caption package documentation for explanation.

You have referenced something which has not yet been labelled. If you have labelled it already, make sure that what is written inside \ref{...} is the same as what is written inside \label{...}.

 Learn more
```
As well as:
```
Reference `fig:GCN' on page 27 undefined on input line 148.

You have referenced something which has not yet been labelled. If you have labelled it already, make sure that what is written inside \ref{...} is the same as what is written inside \label{...}.

 Learn more
```
The figure is defined later in the script, then the reference, but this does not really make a difference. There are instances, where it is the other way around. 
Normally I wouldn't bother, but this leads to unresolved references when I try to reference a figure from another chapter.
My project is split into multiple files, that I all include in a `main.tex` , but this also happens, when I write in the main document.

Any help would be appreciated.

**Comment by schoeps** [comment]
You compiled several times, did you? What happens if you move `\label{fig:GCN}` inside `\caption{...}`?

**Comment by SaschaStenger** [comment]
I'm using Overleaf and i have compiled it multiple times, which still doesn't change the behavior. 

And the warning persists if the `\label` is put into the `\caption`.

Could this be a problem with package incompatibility?
The packages that I'm using additionally are:
```

\usepackage{blindtext}
\usepackage{subfig}
\usepackage[toc,page]{appendix}


% \usepackage{cleveref}
\usepackage{todonotes}
\usepackage{comment}
\usepackage{makecell}

\usepackage{import}
```

**Comment by schoeps** [comment]
I think the `subfig` package is superseded by `subcaption`. Maybe try the latter?

**Comment by SaschaStenger** [comment]
when trying out the `subcaption` package, i encounter the following error:

```
Package caption Error: The `subcaption' package does not work correctly

(caption)                in compatibility mode.

See the caption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.121 \begin{document}
                    
If you do not understand this error, please take a closer look
at the documentation of the `caption' package, especially the
section about errors.
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.
```

Also, maybe this is related: None of my figures or tables get a proper label. So in the text it will refere to some of the figure by number (e.g. 2.1.1) but there is no number under the figure.

**Comment by schoeps** [comment]
Please upload a complete (minimal) example, either here or at gist.github.com or at overleaf (e.g. share via link). I will have a look but not before tomorrow....

**Comment by SaschaStenger** [comment]
Thanks. 
I'm really grateful, that you have already stuck with me for this amount of time. 
Here is a working example:
https://www.overleaf.com/3827813865tjfsvrywtnxg

**Comment by TeXhackse** [comment]
@SaschaStenger if you change the caption layout, so that there is no number, you cannot reference any number …

So of course this does not work.

**Comment by SaschaStenger** [comment]
This helped me immensely though. Now I know what was causing it and it's fixable for me.

**Comment by dreamenwalker** [comment]
Main reason is because the order between lable and captaion,the label should under caption.
