### ISSUE TITLE
accentcolor and identbarcolor in tudaexercise ignore options

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#124]
Since the latest update I did via texlive [I updatetd on December 18 in the morning], the  `accentcolor` and `identbarcolor` options do not have any influence when creating a `tudaexercise` document (have not tested it for the other classes).
In the following example, everything is always colored in the ''default gray'', independent on the options I hand over to `accentcolor` resp. `identbarcolor`. In fact, it seems like the options are ignored completely, since even inserting incorrect options (like AAAAA) does not have any effect.

```
\documentclass[a4paper, accentcolor=1b, identbarcolor=AAAAA]{tudaexercise}

\usepackage[english]{babel}

\begin{document}

\title{Dummy}

\maketitle

\begin{task}{Dummy Task}
	Dummy task
\end{task}

\end{document}
```

**Comment by TeXhackse** [comment]
Thank you for the report. I will prepare a patch for that and re-release either today in the evening or tomorrow.

**Comment by TeXhackse** [comment]
released and uploaded. So we just gotta wait for the confirmation & mirror sync.
