### ISSUE TITLE
Mehr Platz auf tudabeamer-Folien

### ISSUE THREAD

**Issue by kerstenschmidt** [tudace/tuda_latex_templates#125]
Die tudabeamer-Klasse ist großartig. I get quite conformable with them. Ich benutze sie für Vorträge und Vorlesungen.

A bit similar to tudbeamer I found the space occoupied by the header with the TU Darmstadt logo too large and valuable space for slides, which I need at least for the lectures. Ich habe manuell an einigen Stellen in beamerouterthemeTUDa.sty etwas geändert, siehe den Diff-Output unten. Jetzt paßt das für mich mit Überschrift der Folie und zweite Überschrift (framesubtitle). Das Logo ist etwas kleiner.  Hier eine Seite einer Folie:

[11_VL_p5.pdf](https://github.com/tudace/tuda_latex_templates/files/4019864/11_VL_p5.pdf)

Das ist ja eine Entscheidung, wie groß die Abstände und Anteile von der Kopfzeile usw. auf den Folien ist. 

A. Wie fest ist die Entscheidung für diese Abstände?
B. Wäre zumindest eine Option möglich, mit der man die Kopfzeile etwas kleiner bekommt und mehr Platz auf einer Folie hat?

Vielen Dank! Thanks a lot for your answer.

Diff von beamerouterthemeTUDa.sty:

```68c68,69
<       \makebox[2.2\c_TUDa_logoheight_dim][l]{\includegraphics[height=\c_TUDa_logoheight_dim]{\g_TUDa_logofile_tl}}%
---
>       \makebox[1.76\c_TUDa_logoheight_dim][l]{\includegraphics[height=0.8\c_TUDa_logoheight_dim]{\g_TUDa_logofile_tl}}%
>       % changed by Kersten
118c119
<       rightskip=\TUDa@beamer@sep, ht=2.75mm,dp=2.75mm]{footline}
---
>       rightskip=\TUDa@beamer@sep, ht=1.75mm,dp=2.75mm]{footline}  % changed by Kersten
158c159
<       sep=\TUDa@beamer@logosep,%wd=\dimexpr\TUDa@beamer@linewidth\relax,
---
>       sep=0\TUDa@beamer@logosep,%wd=\dimexpr\TUDa@beamer@linewidth\relax, % changed by Kersten
162a164
>       \vspace{-0.5em}
173c175,176
<       \raisebox{\dimexpr-\height+\ht\strutbox\relax}{\usebox\TUDa@logobox}
---
>       \raisebox{\dimexpr-\height+\ht\strutbox\relax}{\usebox\TUDa@logobox} % changed by Kersten
>       %\vspace{-0.2em} % changed by Kersten

```

**Comment by TeXhackse** [comment]
Do you prefer an answer in English or German?

**Comment by kerstenschmidt** [comment]
Ich bevorzuge Deutsch. Danke.

**Comment by TeXhackse** [comment]
Okay, also die Folie oben sieht erst einmal so aus, als wäre da die Ausrichtung das Problem. Das ist in der Demo-Datei beschrieben. Oder ist das nur ein Beispiel, bei dem der obere Teil später gefüllt wird?

Die Abstände innerhalb der der Kopfzeile sind grundsätzlich fix und ich würde das ungerne pauschal ändern. Sie hängen von zu vielen Parametern ab. Insbesondere auch, da die Logogrößen auch durch das Design vorgegeben sind. Sofern es nicht ein allgemeiner Wunsch ist zusätzliche Varianten einzupflegen (diesbezüglich sind @marklaz und @schoeps derzeit meine Ansprechpartner). Dies ist derzeit jedoch nicht vorgesehen.

Es steht Ihnen jedoch frei, eine lokale Änderung zu machen und das entsprechende Template zu überschreiben. In diesem Fall würde ich Ihnen Empfehlen die Änderung als eine lokale Datei zu machen, die sie entweder über `\input` laden, oder aber in ein lokales Paket verwandeln. Dann würde Sie statt `tudabeamer.cls` beispielsweise `tudabeamer-mod.cls` laden. Dies würde dazu führen, dass Sie weiterhin updates zur Standardvariante erhalten, was durchaus sinnvoll ist.

Darüber hinaus besteht eventuell die Möglichkeit  ins Format 16:9 zu wechseln (?!). Dies würde allgemein mehr Platz ermöglichen, darüber hinaus jedoch iim Beispiel keinen Unterschied machen, da sämtliche Umbrüche dort manuell stattfinden.

Ich hoffe das hilft erst einmal weiter.

**Comment by kerstenschmidt** [comment]
Ja, oben ergänze ich handschriftlich in der Vorlesung. 

Danke für die Tipps!

**Comment by schoeps** [comment]
Ich habe es nicht im Detail geprüft, aber @kerstenschmidt's Vorschlag ist wohl wirklich nicht kompatibel mit dem TU-Designguide (bzw. der hoch-offiziellen Powerpoint-Vorlage). Ich würde auch abraten zu viele "offizielle" Latex-Varianten zu machen (der Maintenance-Aufwand explodiert - Fluch der Dimensionen).

@TeXhackse: aber wenn Kersten ein "addon" macht, würde es dann Sinn machen (nur im repository) ein Verzeichnis "unsupported" zu haben, wo wir solche "contributed" Lösungen sammeln? Es gab ja auch mal einen elaborierten Vorschlag zu Schriftarten, oder?! Den könnte man auch da aufnehmen.

@kerstenschmidt: in der Tat ist das Logo rechts nicht bündig. Ich finde das aber sowieso nur auf der ersten Seite wichtig, kann man mit der Klassenoption `logo=false` loswerden.

**Comment by kerstenschmidt** [comment]
Ich verstehe das Template nicht wirklich, habe nur an ein Zahlen etwas geändert, so daß es in die Richtung konvergiert. Das ist alles andere als sauber. Bei `logo=false` ist zwar das Logo weg, aber die Abstände stimmen schon nicht mehr.

Jedoch sehe ich einen Bedarf in der Mathematik, daß die Folien möglichst viel Platz haben. Das würde der Akzeptanz gut tun.

**Comment by schoeps** [comment]
@kerstenschmidt Templates werden von Designern gemacht, nicht von Anwendern. Ob das gut oder schlecht ist, das sei jetzt dahingestellt...  *Ich* finde Deinen Vorschlag optisch zu gedrungen und finde es auch ganz gut, wenn man nicht zu viel Platz auf einer Folie hat.

Wir können das Issue hier erst einmal offen lassen, vielleicht haben ja @TeXhackse (oder ich) mal Zeit etwas zu basteln. Ich würde aber für einen Status "unsupported" plädieren.

**Comment by TeXhackse** [comment]
> Ich verstehe das Template nicht wirklich, habe nur an ein Zahlen etwas geändert, so daß es in die Richtung konvergiert. Das ist alles andere als sauber. Bei logo=false ist zwar das Logo weg, aber die Abstände stimmen schon nicht mehr.

Entschuldigung, ich bin davon ausgegangen, dass die Funktionsweise von Beamer klar ist, wenn Zahlen verändert werden.

Also minimal wäre dann ungefähr so, inkl reduziertem logosep

### ohne logo
```
\makeatletter
\setbeamertemplate{frametitle}{%
\nointerlineskip%
\begin{beamercolorbox}[
  sep=.5\TUDa@beamer@logosep,
  wd=\dimexpr\TUDa@beamer@linewidth+2\TUDa@beamer@extraindent\relax,
  leftskip=\dimexpr-.5\TUDa@beamer@logosep+\TUDa@beamer@extraindent\relax,
	]{frametitle}%
		\usebeamerfont{frametitle}\strut\insertframetitle
		\ifx\insertframesubtitle\@empty
		\else
		\par
		\usebeamercolor[fg]{framesubtitle}%
		\usebeamerfont{framesubtitle}%
		\insertframesubtitle
		\fi
\end{beamercolorbox}%
\nointerlineskip
\TUDa@beamer@rule
}
\makeatother
```
### oder mit logo
```
\setbeamertemplate{frametitle}%
\nointerlineskip%
\begin{beamercolorbox}[
  sep=.5\TUDa@beamer@logosep,
  wd=\dimexpr\TUDa@beamer@linewidth+2\TUDa@beamer@extraindent\relax,
  rightskip=-.5\TUDa@beamer@logosep,
  leftskip=\dimexpr-.5\TUDa@beamer@logosep+\TUDa@beamer@extraindent\relax,
	]{frametitle}%
	\hbox_set:Nn \l_TUDa_frametitle_box {%
	\parbox[t]%
		{\dimexpr\linewidth- \wd\TUDa@logobox-1em\relax\relax}{%
		\usebeamerfont{frametitle}\strut\insertframetitle%
		\ifx\insertframesubtitle\@empty%
		\else%
		\par%
		\usebeamercolor[fg]{framesubtitle}%
		\usebeamerfont{framesubtitle}%
		\insertframesubtitle%
		\fi%
	}}%
	\leavevmode%
	\bool_if:NTF \g_TUDa_centerframetitle_bool%
		{\raisebox{\dimexpr-.5\height+.5\depth}}%
		{\use:n}%
			{\box_use:N \l_TUDa_frametitle_box}%
	\hfill%
	\bool_if:NTF \g_TUDa_centerframetitle_bool%
		{\raisebox{\dimexpr-.5\height+.5\depth}}%
		{\raisebox{\dimexpr-\height+\ht\strutbox}}%
		{\usebox\TUDa@logobox}%
\end{beamercolorbox}%
\nointerlineskip%
\leavevmode\color{black}\hspace*{-\TUDa@beamer@extraindent}\TUDa@beamer@rule%
}
```

**Comment by schoeps** [comment]
@TeXhackse was hälst Du vom Verzeichnis "unsupported"? Es wäre doch schade wenn immer wieder die gleichen Hacks neuentwickelt werden....

**Comment by TeXhackse** [comment]
@schoeps ich überlege noch, was die sinnvollste variante ist. Aber ja, wir sollten dazu was machen.

**Comment by TeXhackse** [comment]
Also mein Vorschlag nach aktuellem Stand wäre: Wir können den Modus erweitern. Als „nicht kompatibel“ zu den Richtlinien setzen und über Option aktivierbar machen, ähnlich wie das Logo. Allerdings würde ich dann zu einer Variante ohne Logo tendieren, da die Folien ja dann allgemein schon sehr voll werden. 

Darüber hinaus sind die Optionen zum quetschen von Beamerfolien vollständig unterstützt. Für den Notfall.

**Comment by schoeps** [comment]
Ich hatte eher daran gedacht, dass wir ins Verzeichnis "unsupported" ein sty oder tex-file legen, das  https://github.com/tudace/tuda_latex_templates/issues/125#issuecomment-570650939 implementiert. Das könnte dann jemand lokal einbinden oder eben auch nicht. Das müssten wir dann auch nicht in den PDF-Dateien dokumentieren. Was meinst Du?

**Comment by TeXhackse** [comment]
@schoeps  Puh, das wirft wahrscheinlich (aufgrund der Fragen, die wir hier bisher so hatten) eher noch mehr Fragen auf. + Es erhöht die Gefahr, dass $Menschen dann eine Version weitergeben, die dann bei anderen wieder nicht läuft. Das frustriert.

Wenn ihr das so wollt, mach ich das, aber ich glaube es macht mehr Ärger. Insbesondere weil dann ein Issue aufgeht und man dann immernoch extra drauf hinweisen muss.

**Comment by im-Kitsch** [comment]
To be honest, I would really recommend to reconsider the height of frame title.  The space of slides is really important.  

Iet's take a look at the example page, this is also mentioned in https://github.com/tudace/tuda_latex_templates/issues/420.  At least in my option, the gap of content is normal distance, this creates a strong contrast with title and that leaves the title region feeling empty.  Es pecially if we consider 16:10 case, the vertical space is very valuable and the contrast is very obvious.

Thanks a lot for the reading in advance.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/33943000/227059982-da4e4522-c4e2-4b56-9ee2-d82c63211344.png">

**Comment by TeXhackse** [comment]
The decision is sadly not up to me. It's a corporate design which doesn't take care of. I am not allowed to do that adjustment.

There is a redesign in progress which claimed to take care of that. But they have changed the time schedule several times and somehow want to do the PowerPoint first before I may start with updating the beamer themes. So actually I am currently just waiting for this to happen.
