### ISSUE TITLE
CC-Lizenz muss optional sein

### ISSUE THREAD

**Issue by flx-wlf** [tudace/tuda_latex_templates#126]
Die CC-Lizenz ist für TU-Prints zwar empfohlen, aber nicht zwingend erforderlich. Falls Inhalte der Dissertation schon anderweitig veröffentlicht wurden, muss oft eine andere Lizenz gewählt werden, sodass es eine entsprechende Option geben sollte.

**Comment by TeXhackse** [comment]
Das widerspricht meinen Infos als Externe, daher bitte @schoeps @marklaz? 

Grundsätzlich kein Problem. Das Feld wird über `\lowertitleback` (wie bei KOMA-Script üblich) gesetzt und kann auch beliebig überschrieben werden. Aber wenn die Info so stimmt, dann sollte das ggf. als Optional gesetzt werden, da stimme ich überein.

**Comment by schoeps** [comment]
Ja, stimmt. Felix hat gerade hier publiziert https://tuprints.ulb.tu-darmstadt.de/11317/. Vermutlich nehmen die meisten CC, aber muss eben nicht. Evtl reicht es zu dokumentieren, wie man es überschreibt?

**Comment by TeXhackse** [comment]
das steht auch schon irgendwo, weil das nur der Lowertitelback st, damit wird der aber als gesamtes ÜBerschrieben. Frage ist, ob das genügt, oder ob wie die Lizenz als einzelnes Tauschbar machen. Aufwandstechnisch ist beides gleich.

**Comment by TeXhackse** [comment]
ich hab für v2.07 einen schalter eingebaut und dokumentiert, das vereinfacht es vielleicht noch zusätzlich
