### ISSUE TITLE
Request for twoside option in tudathesis

### ISSUE THREAD

**Issue by Nerchimond** [tudace/tuda_latex_templates#127]
The twoside option would be a nice addition for the tudathesis template.
It reduces paper use and enhances readability.

**Comment by schoeps** [comment]
The option is `twoside` is available!? This is documented in [here](http://ctan.mirror.norbert-ruehl.de/macros/latex/contrib/tuda-ci/doc/DEMO-TUDaPhD.pdf). Maybe you misunderstood the table? The cross does not imply that this is not working, it just says that the demo file is not using this feature.

**Comment by Nerchimond** [comment]
Thanks for the hint. I really misunderstood the table and forgot to activate the option BCOR=15mm. Wihtout this the twoside option results in only minor changes. My bad.
