### ISSUE TITLE
Beamer: Compilation hangs at \ProcessOptions*

### ISSUE THREAD

**Issue by steven-lang** [tudace/tuda_latex_templates#128]
First off: thanks for your nice templates and the support you offer here!

Now to my issue:

I'm using your AUR packages and try to compile the demo beamer file.
This is my log: https://gist.github.com/steven-lang/787581da1684571049148d4b9c3e7994

The compilation process waits at 

```
...
l.104 \ProcessOptions*
? |
```

until I hit enter. It then continues and finishes the pdf. The result looks fine without any issues. 

Any idea why it stops at `l.104 \ProcessOptions*` everytime?

**Comment by schoeps** [comment]
I guess the error is a font issue: 
> ! Package fontenc Error: Encoding file `t2aenc.def' not found.
> (fontenc)                You might have misspelt the name of the encoding.

How did you install latex? I recommend a vanilla texlive installation (i.e. not using the one that ships with your linux), see https://www.tug.org/texlive/quickinstall.html. You could also try to compile with lualatex or xetex. They handle fonts differently (and have many other advantages).

**Comment by steven-lang** [comment]
I'm using the TeXLive distribution (`texlive-most` from the arch repo).

I've fixed the issued by installing the whole `texlive-lang` group from the arch repo -- thanks for the hint with the font!
