### ISSUE TITLE
Margins and missing blank page in title

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#13]
Hello,

I am wondering about two things:

1. Is it possible to bring the top and bottom margin to the values they had in the previous version of the coporate design? The space to write is currently very limited, we lose about half the page in margins and title.
I tried to comment the line `custommargins=true` which give me the top and bottom margin that I want, however it remove the "twoside" margins of the book class. Do you know how I could solve this problem?

2. I believe two blank pages are missing in the title.

- The first one between the title page and the page with the copyright: the copyright page is aligned to be on the right hand side of a book which is correct but as the title page is also on the right hand side of the book, there should be a blank page in between.
- The second one between the copyright page and the Erklarung. the Erklarung is currently on the left hand side of the book and I believe it would be much better on the right hand side of the book with a blank page before it. Adding this blank page would make all subsequent chapters starts on the right hand side of the book as it is usually done.

Thank you

**Comment by marklaz** [comment]
I guess you refer to a document based on "DEMO_TUDaPhD.tex"?

ad 1.
Have you tried "custommargins=false"?

ad 2.
- To my understanding, the copyright page should be located on the backside of the title page, i.e., it should be a left side page as the title page is right side normally. This is like DEMO_TUDaPhD looks out of the box.
- Affidavit is on the right hand side also in DEMO_TUDaPhD.
Do you have any unwanted page break somewhere (probably an oversized title page)?

**Comment by JuLateX** [comment]
Yes, i refer to a document based on "DEMO_TUDaPhD.tex".

ad 1.
Yes, unfortunately, `custommargins=false` removes the "twoside" margins of the book class.

ad 2.
I might be wrong but if you look at the "DEMO_TUDaPhD.pdf" given in example in the package:

- the copyright page got a margin larger on the left side than on the right, making it a page on the right
-  the affidavit got a margin larger on the right side than on the left, making it a page on the left

**Comment by TeXhackse** [comment]
I seem to know whats the problem, hope I am going to find some time to fix that today.

**Comment by open711** [comment]
I highly appreciate this ticket and I am looking forward to seeing a solution. 
The large top and bottom margins really mess up the document with floating figures, when figures are dimensioned with \textwidth.

**Comment by TeXhackse** [comment]
So, finally:
We now got a feature branch with #16.

There I added implementations in that way, that you can adjust the margins yourself using `cutommargins=true`. You cna  use the typearea package's features to change the calculation of the typearea.

If you want to do manual changes youcan use the option `custommargins=geometry` then the official Layout will be loaded, but you can change it yourself by using` \geometry{some geometry option}` I will add that info to the tudapub file for documentation.

**Comment by JuLateX** [comment]
Thank you for the work :)

I am rather new to LaTeX and I must be doing something wrong as I the book style two side margins still disappear if I use `custommargins=geometry`. Then I tried using `cutommargins=true` but whenever I try to use a typearea package, it does not compile.

**Comment by TeXhackse** [comment]
could you send me the document + logfiles? maybe via email. (you can find it inside the files)

**Comment by JuLateX** [comment]
Thanks for helping, it works perfectly!

**Comment by TeXhackse** [comment]
Problem was about loading typearea which already was loaded.
If you want to change the typearea using typearea, either use typeareas macro set or \KOMAoptions in the preamble.

So the thing is fixed, will be documented and placed in the next release.

**Comment by open711** [comment]
Thanks a lot. Is the next release data already known?
I am still wondering, why the bottom margin is so large for the default thesis settings with custommargins=true (like in the DEMO-TUDaPhD files). I couldn't find in the .cls file the entry that explains the default values. What are the desired values? Or is this based on typearea?

**Comment by TeXhackse** [comment]
> Is the next release data already known?
Not a fixed date, but since this is some kind of major issue I will try to plan it for next week. Would that be early enough?

The Default setting of custommargins=true is the default setting of typearea which is calculated from pagesize and fontsize. The Bottom margin is used to be quite large, due to some rules about typearea construction as a typographic concept. In the typearea documentation you can find more Information about that.

**Comment by open711** [comment]
Thanks a lot for the explanation. I found a way that works for me.  Excluding the footer and header in the typearea calculation "looks" good to me. Even it is not recommended in the KOMA script when the footer and header is separated from the text body by a line. Maybe still better than using geometry.
%included after the title
\KOMAoptions{footinclude=false, headinclude=false}
\recalctypearea

**Comment by TeXhackse** [comment]
Probably it would also have been a choice to simply increase the DIV value ;-) that would be the better variant when talking about harmonic typearea construction. But anyway. If you prefer that way feel free.
