### ISSUE TITLE
Fehler nach I3kernel Update MiKTeX vom 14.01.2020

### ISSUE THREAD

**Issue by open711** [tudace/tuda_latex_templates#131]
Hallo zusammen,

nach dem l3kernel oder l3packages Update vom 14.01. kommen bei mir Fehlermeldungen zu title/author/publisher/creator metadata entries.

\openout6 = DEMO-TUDaPhD.xmpdata
! Package TUDaPub Error: You used the title metadata entry.
(TUDaPub) I don't know how to handle that.
(TUDaPub) It will be ignored.

Ich vermute das Problem liegt an den l3kernel oder l3packages Paketen vom 14.01.2020 (booktabs wurde ebenfalls bei mir aktualisiert).  Updatet im Zweifel vorerst nicht bis ein Fix kommt. Minimalbeispiel ist das DEMO-TUDaPHd.tex

**Comment by schoeps** [comment]
Ich habe gerade texlive geupdated (expl vom 2020-01-12) und folgendes kompiliert bei mir durch
```
\documentclass[class=report,pdfa=false]{tudapub}
\begin{document}
test
\end{document}
```

**Comment by open711** [comment]
Vielen Dank für's Nachprüfen. Das genannte Beispiel läuft bei mir ebenfalls durch. 
Als Minimalbeispiel meinte ich die Beispielfiles auf ctan [http://mirrors.ctan.org/macros/latex/contrib/tuda-ci.zip](url)

**Comment by schoeps** [comment]
Ja, ich sehe das Problem, aber `pdfa=false` hilft, damit kompiliert bei mir auch `DEMO-TUDaPhD.tex` wieder durch (`\Metadata{...}` muss dann auch weg). Das ist insbesondere für Doktorarbeite kein Drama, weil das TUPrints-Team nicht (mehr?) auf PDF/A besteht.

**Comment by TeXhackse** [comment]
Ich kümmer mich drum.

**Comment by TeXhackse** [comment]
Also, mir ist mittlerweile klar wo das Problem liegt, und ich kläre ab, was die beste Lösung ist. Eine temporäre Lösung existiert, allerdings bin ich damit nicht ganz zufrieden, weil das auch längerfristig ein Problem werden könnte. Im Grunde geht es darum, dass ich die Optionen mit Kleinbuchstaben benannt habe, weil ich der Meinung war, das wäre einfacher, als es so zu machen, wie pdfx das möcht. Verarbeitet werden kann derzeit beides. 

Ich muss mir die Änderungen im Kernel nochmal genau angucken und dann wird entschieden, wie das langfristig wird.

**Comment by open711** [comment]
Info: I3kernel update from 01/24/20 on MiKTeX didn't solve the problem.

**Comment by TeXhackse** [comment]
@open711  i know, didnt expect that. fixed it now, will prepare a release tomorrow.

**Comment by TeXhackse** [comment]
ist jetzt mit kompatibilitätsfunktionen drin. Upload läuft.
