### ISSUE TITLE
Roboto und pdflatex

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#132]
Ich hatte länger nicht mehr pdflatex benutzt, daher kann ich nur vermuten, dass es mit dem Roboto-Update im Dezember zusammenhängt: die Datei "rbto_hsw3yt.enc" scheint im Paket Roboto zu fehlen (ist auch nicht [hier](http://mirrors.ibiblio.org/CTAN/fonts/roboto/enc/) aufgelistet). Das Dokument 
```
\documentclass[pdfa=false]{tudapub}
\begin{document}
test
\end{document}

```
führt daher zum Fehler
```
!pdfTeX error: pdflatex (file rbto_hsw3yt.enc): cannot open encoding file for reading

==> Fatal error occurred, no output PDF file produced!

A fatal error occurred, log file is in log.tex
```
Kann das jemand bestätigen?

**Comment by TeXhackse** [comment]
Das liegt nicht an der Installation als solches. Hier läuft alles. Ggf. bitte mal `\listfiles` eintragen und mir den Log schicken, dann kann ich einen Blick drauf werden.

**Comment by schoeps** [comment]
`\listfiles` war gut. Danke! Gelöst.

**Comment by AlexVHopp** [comment]
Bei mir tritt exakt das gleich Problem auf. Wie wurde das hier denn gelöst? Anbei mal mein .log-File für ein ähnliches MWE.
[MWE.log](https://github.com/tudace/tuda_latex_templates/files/4305882/MWE.log)

**Comment by hanyas** [comment]
@schoeps Ich hab gerade den selben Fehler. Woran lags denn?

**Comment by TeXhackse** [comment]
Wenn ich raten darf, dann Überbleibsel einer alten Installation. 

`\listfiles` zeigt am Ende des Logs an welche Dateien geladen wurden, und darüber kann man nachsehen, ob da noch was drin ist, was nicht drin sein sollte.

**Comment by schoeps** [comment]
Genau! Durch angucken der Pfade hatte ich eine "vergessene" Rest-Installation aufgespürt.
