### ISSUE TITLE
Sprache für Titel und Seite 2 getrennt vom Rest nicht auswählbar

### ISSUE THREAD

**Issue by geisenhofer** [tudace/tuda_latex_templates#133]
Hallo,

ich hätte gerne den Titel und die anschließende zweite Seite auf deutsch und die restliche Disseration auf Englisch. Aktuell entstehen Mischformen, wenn ich beispielsweise german als Option in \documentclass[german,...] setze und anschließend \usepackage[main=english]{babel} verwende.

Es wäre super, wenn die Sprache der ersten beiden Seiten getrennt vom Rest des Dokuments wählbar wäre. Gibt es außerdem die Möglichkeit Seite 2 komplett selbst zu setzen?

Danke vorab!

**Comment by ReinhardDominik** [comment]
Funktioniert das hier?

\usepackage[main=USenglish,ngerman]{babel}
\selectlanguage{english} 
\begin{abstract}
English abstract.
\end{abstract}
\selectlanguage{ngerman} 
\begin{abstract}
Deutsche Zusammenfassung.
\end{abstract}
\selectlanguage{english}

**Comment by geisenhofer** [comment]
Schaut gut aus! Danke!

Zu deinem edit: Funktioniert auch so, wenn english als main language gesetzt ist -->
\selectlanguage{ngerman}
\maketitle
\selectlanguage{USenglish}

Jetzt wäre nur noch gut zu wissen, wie Seite 2 im Fall der Fälle komplett editierbar wäre ;-)

**Comment by TeXhackse** [comment]
Seite 2 setzt die Attribute über '\uppertitleback{}' und '\lowertitleback{}` wie für KOMA-Script üblich. 

Ich werde das mit den Sprachen nochmal prüfen, weil ursprünglich war das so, dass die Titelseite immer deutsch sein muss.

**Comment by TeXhackse** [comment]
@geisenhofer 

Ich habs geprüft, also grundsätzlich sollte bei `\documentclass` auch nur die Hauptsprache geladen werden. Der Umschalter prüft tatsächlich auf den Wert der Hauptsprache nach Babel. Es wäre also für ein Dokument auf English mit deutschem Titel nichts weiter nötig als 
```
\usepackage[main=english]{babel}
```
TUDaPhd setzt sowieso für den Titel die Sprache auf Deutsch um. Da mich das Problem interessiert:
Wäre es möglich den Code des Status „Es geht nicht“ zu rekonstruieren? Mir ist unklar, was das Problem gewesen sein soll.

**Comment by geisenhofer** [comment]
@TeXhackse 

Wenn ich deine Einstellungen verwende, passt alles, bis auf die Sprache auf der zweiten Seite oben. Das ist in Englisch. Macht das Sinn, wenn die Titelseite komplett auf Deutsch ist (bis auf den Titel) und auf Seite 2 der untere Teil mit TUPrints und der Lizenz auf Deutsch ist?

Meiner Ansicht nach würde es Sinn machen, dass Seite 2 komplett auf Deutsch ist oder der Nutzer entscheiden kann, welche Sprache er möchte.

Hoffe, das war jetzt klar beschrieben, sonst frag gerne nochmal nach.

**Comment by TeXhackse** [comment]
@geisenhofer Jetzt verstehe ich. Danke.

Ähm, das hatten wir bei der Kostruktion besprochen, da die Info darüber welcher Dokumententyp es ist dann zweisprachig da ist und nicht nur einsprachig. Wie genau die Entscheidung zu Stande kam, kann ich gerade nicht mehr sagen, das ist schon eine ganze Weile her. Ich guck das bei Gelegenheit mal nach.

Ich nehm den Hinweis mal auf.

**Comment by marvinbernhardt** [comment]
Bei mir sieht es momentan in der Dissertation ähnlich aus:
`\usepackage[ngerman, main=english]{babel}` führt zu einer deutschen Titelseite und einer zweisprachigen zweiten Seite.
Dabei ist der obere Teil in Englisch und der untere Teil (tuprints, Lizenz) in Deutsch.
Für mich ist es so ok, aber es wäre wohl schöner, wenn die zweite Seite ganz Englisch oder ganz Deutsch sein könnte.

**Comment by TeXhackse** [comment]
Hmm Das ist etwas schwierig. Die Vorgabe von TUprints ist auf Deutsch. Es wäre höchstens möglich den `\uppertitleback` auch bei `main=english` auf deutsch zu erzwingen.

**Comment by marvinbernhardt** [comment]
Das ist Hilfreich, danke :)
