### ISSUE TITLE
glossary package wird scheinbar nicht unterstützt

### ISSUE THREAD

**Issue by MECLabTUDA** [tudace/tuda_latex_templates#135]
Die Verwendung von 
\usepackage[acronym]{glossaries}
scheint für das PhD Klasse nicht komplett unterstützt zu werden oder ich bekomm es einfach nicht zum laufen. Ich würde mich freuen, falls ihr da mal reinschauen und mir Feedback geben könntet!

Das Problem scheint zu sein, dass zwar die nötigen .glo und .acn files generiert werden, aber die nachfolgende Generation der .gls und .acr files funktioniert nicht.
Damit kann ich zwar wie gewohnt mit \gls{xxx} etwas referenzieren und es wird im Text auch korrekt dargestellt, das printing der glossaries (\printglossaries) schlägt aber fehlt bzw tut halt nichts. 

Ich verwende TexStudio 2.12.16 unter Windows 10. Miktex ist auf dem neuesten Stand.

Minimalbeispiel:

Ein einfacher arcticle funktioniert:
```
\documentclass{article}
\usepackage[utf8]{inputenc}

\usepackage[acronym]{glossaries}
\makeglossaries
\newglossaryentry{glos}
{
	name=Glossary,
	description={Glossaries are very useful.}
}
\newacronym{aaa}{AAA}{Abdominal Aortic Aneurysm}

\title{How to create a glossary}
\author{ }
\date{ }

\begin{document}
	\maketitle
		
	A \gls{glos} is very useful.
	
	A \gls{aaa} is bad.
	
	\clearpage
	
	\printglossaries
	
\end{document}
```

Das TUDA Template schlägt aber fehl.

Ergänzungen im TUDA Example für TUDaPhD:

- In der Preamble

```
%Literaturverzeichnis
%%%%%%%%%%%%%%%%%%%
\usepackage{biblatex}   % Literaturverzeichnis
\bibliography{DEMO-TUDaBibliography}

%%%%%%%%%%%%%%%%%%%
% Glossaries and Acronyms
%%%%%%%%%%%%%%%%%%%
\usepackage[acronym]{glossaries}
\makeglossaries

\newglossaryentry{glos}
{
	name=Glossary,
	description={Glossaries are very useful.}
}
\newacronym{aaa}{AAA}{Abdominal Aortic Aneurysm}
```

- Vor Chapter 1
```
\mainmatter

\chapter{Glossary Test}

A \gls{glos} is very useful.

A \gls{aaa} is bad.

\printglossaries

\chapter{Verwendung}
```

**Comment by TeXhackse** [comment]
Inwiefern es „tut es nichts“? Hier läuft es einwandfrei und ohne Schwierigkeiten durch. Könnte ich bitte ggf. den die Log Ausgabe bekommen? So ist es schwierig einzuschätzen, was passiert.

**Comment by TeXhackse** [comment]
@MECLabTUDA Eine Rückmeldung wäre hilfreich.

**Comment by TeXhackse** [comment]
Ich schließe das, als nicht reproduzierbar. Glossary funktioniert in den Tests ohne Probleme.
