### ISSUE TITLE
Captions in falscher Schriftart

### ISSUE THREAD

**Issue by akikker** [tudace/tuda_latex_templates#137]
Hallo!

Ich benutze das TUDaPHD-template und meine Abbildungsunterschriften erscheinen in einer anderen Schriftart oder Schriftgröße, zumindest sieht es nicht so aus wie in Abbildung und Fließtext. 
Außerdem würde ich gerne die komische Einrückung in den weiteren Zeilen unter "Figure" entfernen.

Danke!

![CaptionWrong](https://user-images.githubusercontent.com/29301136/72985895-4ace5f80-3de7-11ea-95ba-4d83366d17bc.PNG)

**Comment by schoeps** [comment]
Die Schriftart ist nicht "falsch", sie ist wie im Designguide vorgeschrieben (siehe auch https://github.com/tudace/tuda_latex_templates/issues/65). Das kann man aber leicht selber ändern, gleiches gilt auch für die Einrückung, siehe http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide.pdf.

**Comment by TeXhackse** [comment]
Für die Schriftart heir gilt das gleiche wie in #140. Modifikation ist über `\setkomafont` und `\addtokomafont` möglich (vgl KOMA-Script doku, wie oben verlinkt). Sofern es notwendig sein sollte, von den Vorgaben abzuweichen.
