### ISSUE TITLE
page number in roman and arabic  

### ISSUE THREAD

**Issue by SidMueller1337** [tudace/tuda_latex_templates#139]
Some professor want the page numbers the following way:

"Seitenzahlen: unten zentriert, Seiten vor dem Haupttext mit römischen Ziffern und ab dem Haupttext mit arabischen Ziffern nummeriert"

It doesn't have to be centered though.

**Comment by schoeps** [comment]
This can be achieved with standard ([koma class](http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide.pdf)) latex commands:
```
\documentclass{tudapub}
\begin{document}
\frontmatter 
Front
\mainmatter 
Main
\end{document}
```
This should be easy to figure out by googling!? By the way centering page numbers should also be easy (just look into the same manual)
