### ISSUE TITLE
Schriftgröße Titlepage

### ISSUE THREAD

**Issue by misfit2** [tudace/tuda_latex_templates#140]
Gibt es die Möglichkeit die Schriftgröße der Überschrift auf der Titelseite zu ändern? In der Dokumentation steht sie wurde extra verkleinert - nimmt bei mir aber immernoch sehr viel Platz ein.

**Comment by schoeps** [comment]
Über welche Vorlage reden wir? 

Nicht elegant, aber fast immer zielführend ist das lokale überschreiben, z.B. `\title{\footnotesize Mein Titel}}`.

**Comment by TeXhackse** [comment]
Da KOMA-Script verwendet wird, sind alle Titel über den komafont Mechanismus gesetzt. Es ist also möglich die Makros `\setkomafont` und `\addtokomafont` zu nutzen.

**Comment by schoeps** [comment]
@TeXhackse (nur bei Poster und Beamer geht das so nicht)

**Comment by TeXhackse** [comment]
@schoeps Poster greift auch den Mechanismus ab. 

Beamer stimmt, weil kein KOMA. Dort ist der Analoge Mechanismus den beamerfont über `\setbeamerfont` zu ändern. Danke für die Ergänzung.

**Comment by misfit2** [comment]
genau es war tudapub gemeint für eine masterthesis (also auch thesis class). Kann ich denn jetzt eine eigene Größe definieren? Weil \footnotesize ist ja dann wieder zu klein? Bzw. stehen die wählbaren Größenoptionen in der Koma doc drin?

**Comment by misfit2** [comment]
Ok nur falls das nochmal für jemanden relevant ist; die Schriftgrößenoptionen sind dann die standard Befehle von KOMA \Huge hat es für mich getan denke ich. Danke für die Antwort

**Comment by TeXhackse** [comment]
Das hat übrigens nichts mit KOMA-Script zu tun, sondern sind die LaTeX-Standardmakros. 

Ich schließe das hier dann als erledigt.
