### ISSUE TITLE
List of Figures – Abstand zwischen Nummer und Name zu klein

### ISSUE THREAD

**Issue by reg-is** [tudace/tuda_latex_templates#141]
Bei Abbbildungsverzeichnis, sobald die Nummerierung von Figures zweistellig wird, ist der Abstand zwischen Nummer und Name zu klein:

<img width="535" alt="grafik" src="https://user-images.githubusercontent.com/22980070/73181064-d103e200-4116-11ea-8de1-61e6806dc959.png">

Diesen Fehler gibt mir der Compiler:

`Package tocbasic Warning: number width of figure toc entries should be increased
!
(tocbasic)                Currently used number width = 25.26157pt,
(tocbasic)                Wanted number separation    = 4.37993pt,
(tocbasic)                Reserved number width       = 25.18501pt on input line
 124.`

**Comment by TeXhackse** [comment]
Die Nummer ist in diesem Fall ja mehr als Zweistellig, durch das vorangestellte „A“.

Der Abstand ist fix und wird dies in der Voreinstellung auch bleiben, da dies der üblichen Verwendung entspricht. Und die hierarchischen Inhaltsverzeichnisse üblicher sind. Alllerdings ist es möglich über den Wert `flat` der Verzeichnisoption ein tabellarisches Verzeichnis zu erzeugen. 

Sofern man dies nur für die Verzeichnisse mit Abbildungen und Tabellen will, heißt die Option dann `listof=flat`. 

Weitere Informationen hierzu finden sich in der KOMA-Script Dokumentation. Dort finden sich auch möglichkeiten die Einrückung für einspezifisches Verzeichnis anzupassen, sofern dies der gewünschte weg ist.

**Comment by reg-is** [comment]
> Die Nummer ist in diesem Fall ja mehr als Zweistellig, durch das vorangestellte „A“.

Anstelle des A (Appendix) könnte auch die Kapitelnummer stehen. zB 3.20.
Also sobald man 10 Abbilungen in einem Kapitel hat, werden sie im Abbildungsverzeichnis nicht mehr richtig angezeigt.


> Weitere Informationen hierzu finden sich in der KOMA-Script Dokumentation. Dort finden sich auch möglichkeiten die Einrückung für einspezifisches Verzeichnis anzupassen, sofern dies der gewünschte weg ist.

Ich habe es bei jetzt mit dem Befehl gelöst:
```
\DeclareTOCStyleEntry[numwidth=3em]{tocline}{figure} % Für Abbildungsverzeichnis
\DeclareTOCStyleEntry[numwidth=3em]{tocline}{table} % Für Tabellenverzeichnis
```

**Comment by TeXhackse** [comment]
> Anstelle des A (Appendix) könnte auch die Kapitelnummer stehen. zB 3.20.
Also sobald man 10 Abbilungen in einem Kapitel hat, werden sie im Abbildungsverzeichnis nicht mehr richtig angezeigt.

Wie gesagt, das entspricht den Standardeinstellungen und wir wollten, wenn möglich nicht davon abweichen, da das das ist, was am weitesten verbreitet ist. Ich hatte durchaus auch Dokumente, bei denen diese Anpassung nötig war. Die Aternatvie wären tabellarische Verzeichnisse, die allerdings bei weitem weniger übersichtlich sind.

Aber es freut mich, wenn das jetzt behoben ist.
