### ISSUE TITLE
Verwendung veralteter Befehle?

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#142]
Beim Kompilieren einer tudapubs Klasse erhalte ich die Warnung, dass der veraltete Befehl "\iftocfeature" verwendet wird. 
Ich habe bereits versucht die entsprechenden Stellen durch "\Iftocfeature" zu ersetzen, jedoch ohne Erfolg. Ich habe auch alle Pakete auf dem aktuellsten Stand, und das Problem tritt auf mehreren Rechnern auf, daher vermute ich dass es nicht nur ein Problem mit meiner Installation ist.

**Comment by TeXhackse** [comment]
Ich bin derzeit daran, das zu lösen. Es ist eine Warnung und die alten Makros werden noch eine Weile existieren. Das Problem bei einer zu frühen Umstellung ist, dass ältere Installationen gar nicht mehr funktionieren 

Grundsätzlich ist die Warnung lediglich ein Hinweis, dass dieses Makro mehr ewig existieren wird. Das betrifft überwiegend Paket Autoren. Es kann also auch indirekt durch andere Pakete ausgelöst werden, sollte aber zu keinen Problemen führen.

**Comment by markusbrandt** [comment]
Wie wäre es mit folgender Lösung?

```
%Rückwärtskompatiblität \iftocfeature -> \Iftocfeature
\providecommand{\Iftocfeature}{\iftocfeature}
```

**Comment by TeXhackse** [comment]
So ähnlich ist tatsächlich auch der aktuelle Plan, nur über let, wegen Expansion. Arbeite gerade am Release. Wollte nur vorher checken welche Versionen das betrifft, um de Überblick zu behalten.
