### ISSUE TITLE
Probleme mit Ligaturen in Kapitälchen

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#144]
Ich habe mehrere Probleme und Fragen bzgl. Schriftarten.

Zunächst verhält sich `\textsc{}` bei tudabeamer merkwürdig. Wenn man den Teilstring "fi" [ohne Anführungszeichen] in einem `\textsc{}` hat (wie etwa bei `\textsc{Coefficient}`) werden das f und das i sehr merkwürdig dargestellt. Wenn man jedoch zwei getrennte , direkt hintereinander kommende `\textsc{}`-Befehle dafür verwendet (also `\textsc{f}\textsc{i}`) tritt dieses Problem nicht auf.

Hier ein MWE:
```
\documentclass[accentcolor=1b,authorontitle=true,logo=true]{tudabeamer}

\begin{document}
\begin{frame}
\textsc{Coefficient}; \textsc{f};\textsc{i};\textsc{f}\textsc{i};\textsc{fi};
\end{frame}
\end{document}
```
Außerdem habe ich zusätzlich ein Problem mit der Schriftart "xcharter" bei Verwendung der tudapub Klasse. Nach meinem Verständins wurde die Schriftart nicht direkt mit installiert als ich "tuda-ci" per texlive/2019 installiert habe (was nach meinem Verständnis doch passieren sollte oder irre ich mich hier?). Ich habe dann versucht, die Schriftart nachträglich per Hand zu per texlive/2019 zu installieren, und obwohl das Paket laut texlive/2019 vorhanden und installiert ist scheint tudapub die Schriftart immer noch nicht zu finden.

**Comment by schoeps** [comment]
Es ist klar, dass es einen Unterhschied zwischen {f}{i} und {fi} geben kann: Latex nutzt [Ligaturen](https://de.wikipedia.org/wiki/Ligatur_(Typografie)). Allerdings sehe ich das weder mit ppdflatex noch lualatex, siehe Bild
<img width="398" alt="Bildschirmfoto 2020-01-30 um 10 09 33" src="https://user-images.githubusercontent.com/868081/73435410-dcd6ea80-4348-11ea-852d-3587197e16b1.png">

xcharter ist bei texlive (ggf. full install) automatisch dabei. Evtl hat die manuelle Installation etwas kaputt gemacht? (Unter Linux: am besten texlive aus der Originalquelle installieren, nicht über die Distribution)

**Comment by TeXhackse** [comment]
@AlexVHopp Danke fürs melden. Die Ligatur, die kaputt geht, kann ich rekonstruieren, ich glaube auch zu wissen, woran es liegt. Ich kümmere mich drum, 

wegen xcharter: Es gibt bei TeX Live kein dependency management. Es gibt möglichkeiten on the fly Pakete nachzuinstallieren, allerdings ist das auch nervig. Wenn die Schriftart also nicht mit installiert wurdem, dann müsste sie nachinstalliert werden. Manuelle Installation von Schriften ist bei LaTeX komplex. Wie wurde das versucht? Über den TeX Live Manager oder das Cockpit sollte es ohne Probleme funktionieren.

**Comment by schoeps** [comment]
@TeXhackse warum sehe ich das nicht? oder übersehe ich etwas?

**Comment by TeXhackse** [comment]
@schoeps kann spontan nicht sagen, aber ich kümmer mich drum, habs gerade in allen Varianten ins Testsystem geworfen, danach weiß ich mehr.

@AlexVHopp Als Workaround die Ligaturen für sc deaktiveren wäre wohl die einfachste Lösung:
```
\usepackage{microtype}
\DisableLigatures{encoding = *, shape = sc }
```

Um den Rest kümmere ich mich sobald wie möglich

**Comment by AlexVHopp** [comment]
@TeXhackse Vielen Dank für die Antwort und den Workaround! Ich werde das dann einfach in Zukunft einfügen bis das Problem behoben ist.

Bzgl. der manuellen Installation von xcharter habe ich versucht, mich an die folgende Anleitung zu halten: https://tug.org/fonts/fontinstall.html

Bei meinen Versuchen habe ich dann die folgenden Outputs bekommen:
```
hopp@fb04676:~/Promotion$ module load texlive/2019
Modules: loading texlive/2019

hopp@fb04676:~/Promotion$ tlmgr --usermode install xcharter
tlmgr: package repository http://mirror.informatik.hs-fulda.de/tex-archive/systems/texlive/tlnet (verified)
tlmgr install: package already present: xcharter

hopp@fb04676:~/Promotion$ texhash /home/hopp/texmf
texhash: Updating /home/hopp/texmf/ls-R... 
texhash: Done.

hopp@fb04676:~/Promotion$ updmap-user mode --force --enable Map=xcharter.map
updmap will read the following updmap.cfg files (in precedence order):
  /home/hopp/texmf/web2c/updmap.cfg
  /sw/fb04_texmf/v2018/texmf-local/web2c/updmap.cfg
  /sw/texlive/2019/texmf-dist/web2c/updmap.cfg
updmap may write changes to the following updmap.cfg file:
  /home/hopp/texmf/web2c/updmap.cfg
dvips output dir: "/home/hopp/.texlive2019/texmf-var/fonts/map/dvips/updmap"
pdftex output dir: "/home/hopp/.texlive2019/texmf-var/fonts/map/pdftex/updmap"
dvipdfmx output dir: "/home/hopp/.texlive2019/texmf-var/fonts/map/dvipdfmx/updmap"
updmap [ERROR]: The following map file(s) couldn't be found:
updmap [ERROR]: 	xcharter.map (in /home/hopp/texmf/web2c/updmap.cfg)
updmap [ERROR]: Did you run mktexlsr?

	You can disable non-existent map entries using the option
	  --syncwithtrees.
```
Nach meinem rudimentären Verständnis scheint irgendetwas mit den Map-Files nicht zu stimmen, obwohl xcharter lokal installiert ist und die Map-Files durch die Anwendung von `texhash` ja eigentlich richtig erzeugt wurden. Ich habe auch versucht `mktexlsr` zu benutzen, das ging jedoch wegen fehlender Berechtigungen nicht.

**Comment by TeXhackse** [comment]
äh naja 
> tlmgr install: package already present: xcharter

sagt, dass das Paket schon da ist und isntalliert es nicht. Deswegen fehlt später der Map file. Es ist also global installiert und nicht lokal da greift dann ein lokales texhash nicht. 
Also sollte die eigentlich schon da sein, und sie wird definitiv nicht gefunden?

Alternative mit lokalem texhash ginge die dateien direkt von https://ctan.org/pkg/xcharter laden und dann in den eigenen texmf entpacken. dann sollte der rest auch gehen.

Zur Erklärung:
> Nach meinem rudimentären Verständnis scheint irgendetwas mit den Map-Files nicht zu stimmen, obwohl xcharter lokal installiert ist und die Map-Files durch die Anwendung von texhash ja eigentlich richtig erzeugt wurden. 

texhash erzeugt den Map file nicht. texhash registriert die Datei nur in der FileNameDataBase (FNDB) mktexlsr tut übrigens genau das gleiche. Mittlerweile gibts auch beide Befehle auf allen Distributionen. 

Aber das Paket ist lokal nicht vorhanden, weil es schon global existiert, das ist eigentlich der einzige Fehler. Ich hoffe diese Info hilft.

**Comment by AlexVHopp** [comment]
Zuerst mal vielen Dank für die Hilfe! 
Das Problem bzgl. der fehlenden Schriftart sowie der Darstellung der Ligaturen tritt bei mir nach dem letzten Update (vor ca. 10 Minuten geladen) nicht mehr auf. Ich nehme daher an dass das Thema geschlossen werden kann?

**Comment by TeXhackse** [comment]
@AlexVHopp Dann sind zwei TeX installationen vorhanden un und der Pfad entsprechend falsch gesetzt.
`\listfiles` druckt die geladenen Dateien in den Log, das könnte beim auffinden ebendieser helfen.

**Comment by AlexVHopp** [comment]
@TeXhackse Vielen Dank für den Hinweis, ich werde mich mal mit meinem Systemadministrator in Verbindung setzen.
