### ISSUE TITLE
counter von subtasks wird nicht resetet

### ISSUE THREAD

**Issue by yfischler** [tudace/tuda_latex_templates#145]
Beim verwenden von subtasks in mehreren tasks ist der counter zum zählen der subtasks (a, b, c ...) über mehrere tasks hinweg durchgängig. D.h. folgende Struktur wird erzeugt:
A1
A1a
A1b
A2
A2c
A2d

Richtig wäre:
A1
A1a
A1b
A2
A2a
A2b

**Comment by schoeps** [comment]
Bitte ein MWE posten (und gerne auch direkt selber überprüfen, ob das an der TUDa-Klasse liegt, z.B. statt `tudapub` durch eine geeignete Koma-Klasse ersetzen)

**Comment by tugalus** [comment]
MWE siehe unten.
Im ersten Teil des MWE ist zu sehen, dass zumindest mit section und subsection ein ähnliches Verhalten nicht zu beobachten ist.
Wie im dritten Absatz zu sehen ist, ist ein möglicher Workaround: \setcounter{subtask}{0}

\documentclass[
	ngerman,
	color=2c,
	solution=true,
	]{tudaexercise}

\usepackage[english, main=ngerman]{babel}
\usepackage[babel]{csquotes}

\usepackage{biblatex}
%\bibliography{DEMO-TUDaBibliography}

%Formatierungen für Beispiele in diesem Dokument. Im Allgemeinen nicht notwendig!
\let\file\texttt
\let\code\texttt
\let\pck\textsf
\let\cls\textsf
\let\tbs\textbackslash

\ConfigureHeadline{
	%headline={title-name-id}
}

%compatbilitx
\let\unit\relax

\begin{document}

\title{}
\subtitle{}
\author{}
\term{}
%\date{03.02.2020}
\sheetnumber{6}

%\pagestyle{myheadings}

\maketitle

\begin{section}{}

\begin{subsection}{}

\end{subsection}

\begin{subsection}{}

\end{subsection}



\end{section}


\begin{section}{}

\begin{subsection}{}

\end{subsection}

\begin{subsection}{}

\end{subsection}



\end{section}




\begin{task}{}

\begin{subtask}
\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}
\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}
\begin{solution}
\end{solution}
\end{subtask}
\end{task}

\begin{task}{}


\begin{subtask}

\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}

\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}

\begin{solution}
\end{solution}
\end{subtask}
\end{task}

\begin{task}{}
\setcounter{subtask}{0}

\begin{subtask}
\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}
\begin{solution}
\end{solution}
\end{subtask}

\begin{subtask}

\begin{solution}
\end{solution}
\end{subtask}
\end{task}

\end{document}

**Comment by schoeps** [comment]
@TeXhackse das sieht nach einem Bug aus?!

**Comment by TeXhackse** [comment]
@schoeps äh ja. 
@yfischler: Danke fürs melden, anscheinend hat das vorher keiner benutzt :D Workaround ist folgendes in die Präambel (also vor '\begin{document}') packen:
```
	\makeatletter
	\@newctr{subtask}[task]
	\makeatother
```

Patch kommt sofort.
