### ISSUE TITLE
Speicherung des Logos tuda_logo.pdf

### ISSUE THREAD

**Issue by yfischler** [tudace/tuda_latex_templates#146]
Mir ist nicht klar, wo ich das Logo speichern muss.
Ich habe texlive unter Ubuntu installiert und möchte das Logo nicht in meinem working directory speichern. Auf der Webseite ist leider nur eine allgemeine Beschreibung "added somewhere with the local latex tree" gegeben. Ich habe nun schon mehrere Ordner ausprobiert, aber das Logo wird nicht gefunden. Wo genau muss ich das Logo ablegen oder muss ich danach ein index update ausführen, damit es gefunden wird? Ggf. ist eine Ergänzung der Anleitung hilfreich.

**Comment by schoeps** [comment]
Den lokalen texmf-Folder findet man mit `kpsewhich --var-value TEXMFHOME` heraus. Ich habe meine Bilder da unter `.../texmf/tex/latex/images` liegen und muss kein index Update durchführen. Wenn das nicht klappt --warum auch immer--, dann kann man den logo-pfad auch immer manuell als Klassenoption angeben (`logofile=/bla/blubb/images/tuda_logo.pdf`).

**Comment by yfischler** [comment]
Damit habe ich den richtigen Ordner gefunden. Vielen Dank.

**Comment by MSchilling7** [comment]
Hallo, hierzu nochmal ne Frage... Trat der Fehler bei nem Linux-System auf? 
Ich habe den gleichen Fehler, aber der Befehl("kpsewhich.exe --var-value TEXMFHOME") hat keinen Return in der PowerShell. Daher weis ich nicht genau welcher der richtige Ordner ist.
Wie geht das unter Windows? 
Danke schonmal im vorraus

**Comment by schoeps** [comment]
Unter Windows kann ich nicht helfen. Wenn Miktex, dann ist evtl. hier etwas dabei: [https://miktex.org/kb/texmf-roots](https://miktex.org/kb/texmf-roots)?

**Comment by TeXhackse** [comment]
@MSchilling7 Sofern das keine Rückgabe liefert ist TEXMFHOME nicht konfiguriert. Das kann unter MikTeX vorkommen. Ist aber kein Windows-Problem sondern gilt auf allen Betriebssystemen.

Der Ordner existiert also noch nicht, muss also angelegt werden und in den MikTeX-Optionen (über obigen Link) als Wurzelverzeichnis hinzugefügt werden.

Genügt das soweit, oder soll ich das genauer schildern? Dann kann ich später mal im Testsystem die einzelnen Schritte nachvollziehen.

**Comment by sln987** [comment]
Genauer schildern wäre toll. Habe sowohl unter Windows (Miktex) als auch macOS (Mactex 2021) Probleme,  die "obersten Ebene des lokalen LaTeX-Baums" zu finden und das ZIP-Archiv logo_bundle dort zu entpacken.

**Comment by schoeps** [comment]
> ... als auch macOS (Mactex 2021) 

Das kann man vielleicht besser dokumentieren (hat aber andererseits nichts mit TUDa-CI zu tun). Falls es um das akute Problem geht, bei mir liegt das Bild hier: `/Users/xxxx/Library/texmf/tex/latex/images/tuda_logo.pdf`

**Comment by TeXhackse** [comment]
Jein, das Problem ist, dass es tatsächlich von der Installation abhängt. MikTeX oder TeX Live (MacTeX ist auch nur TeX Live).

Ich würde übrigens empfehlen @sln987 auf beiden die gleiche TeX Distribution zu installieren. MacTeX ist das gleiche wie TeX Live nur eben für Mac. TeX Live gibts auch für Windows. 

Unter TeX Live will man eigentlich den `TEXMFLOCAL` Ordner nutzen, den Pfad bekommt man über 
```
kpsewhich --var-value TEXMFLOCAL
```

Unter MikTeX sieht das ganze anders aus: https://miktex.org/kb/texmf-roots User Install wäre daher per Default l: `%USERPROFILE%\Roaming\MiKTeX\2.9` oder Systemweit  `C:\Program Files\MiKTeX 2.9`

**Comment by schoeps** [comment]
> Unter TeX Live will man eigentlich den TEXMFLOCAL Ordner nutzen

Reine Neugierde: warum ist das besser als im home-folder (wenn es ein single-user system ist)?

**Comment by TeXhackse** [comment]
Bei Single-User Systemen ist fast egal, da hast du recht. 

Sonst wäre der Unterschied TEXMFLOCAL systemweit, TEXMFHOME nur für den Account.
Ich finds ordentlicher, weil dann in einem texlive-Ordner alles drin liegt, aber das ist rein persönliche Vorliebe.

**Comment by TeXhackse** [comment]
Oh warte, mir ist gerade noch ein Unterschied eingefallen...

TEXMFHOME wird nicht indiziert. D.h. dort wird immer gesucht, wenn der groß ist kann das dauern. Also dort werden keine ls-R Dateien erzeugt. Dafür kann man sich dort das `texhas` sparen.

Suchreihenfolge für diese drei Elemente stimmt.  

Das alles gilt natürlich nur, wenn du es nicht überschrieben hast. Die Infos stehen in texmf.cnf Überlichweise `$TEXMFDIST\web2c\texmf.cnf``
