### ISSUE TITLE
subtasks ohne Titel

### ISSUE THREAD

**Issue by yfischler** [tudace/tuda_latex_templates#147]
Hallo,
ist es gewollt, dass es nicht möglich ist bei subtasks einen Titel mit anzugeben, sowie es bei tasks möglich ist?

MWE:

```
\documentclass[
	ngerman,
	]{tudaexercise}

\begin{document}

\title{}
\subtitle{}
\author{}
\term{}
%\date{03.02.2020}
\sheetnumber{6}

%\pagestyle{myheadings}

\maketitle

\begin{task}{Taskname}
\begin{subtask}{Subtaskname}
\end{subtask}
\end{task}

\end{document}
```

**Comment by TeXhackse** [comment]
Ja, weil der Titel bei subtask optional ist. 

Ist auch in der Demo mit angegeben es müsste 

```
\begin{task}{Taskname}
\begin{subtask}[Subtaskname]
\end{subtask}
\end{task}
```
heißen. Die Länge von Unteraufgaben ist oft so kurz, dass ein Titel nicht sinnvoll wäre, aber die Möglichkeit besteht natürlich.
