### ISSUE TITLE
Nummerierung der Task-Umgebung

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#148]
Ich habe eine Frage zur `task`-Umgebung in der Klasse `tudaexercise`. Wenn man keine `sheetnumber` angibt werden die Aufgaben im Dokument mit 1 beginnend durchnummeriert. Gibt es eine Möglichkeit, die Aufgaben so zu nummerieren, als ob man verschiedene Sheets in einem Dokument hat (also 1.1, 1.2, 1.3, 2.1, 2.2 etc)?

**Comment by TeXhackse** [comment]
Klar geht das. So wie überall bei LaTeX.

Der Zähler der Aufgaben wird im Makro `\the<countername>` gespeichert. 
Der Zähler selbst heißt in diesem Fall, ebenfalls wie üblich `task` nach der Umgebung.
Damit ist es möglich die Ausgabe an beliebige Counter zu koppeln, z.B.
```
% neuen Zähler definieren
\newcounter{abschnitt}
% das definiert das MAkro \theabschnitt mit, welches für die Ausgabe benutzt werden kann

% Dafür sorgen, dass der task-counter beim erhöhen von abschnitt automatisch mit resettet wird:
\makeatletter
\@newctr{task}[abschnitt]
\makeatother

% Ausgabe des task-counters anpassen:
\renewcommand*{\thetask}{\theabschnitt.\arabic{task}}
```
Zum Erhöhen muss dann im Dokument nur 
```
\stepcounter{abschnitt}
``` 
ausgeführt werden. 

Anstatt einen eigenen Zähler zu definieren, kann man natürlich auch einen Nehmen, der schon da ist. Wie `section` dann geht statt `\stepcounter` der entsprechende Befehl für die Gliederungsebene.
