### ISSUE TITLE
Zentrieren von titlegraphic und unauffindbare Fußnoten

### ISSUE THREAD

**Issue by Ja-We** [tudace/tuda_latex_templates#149]
Hi!

Ich arbeite zur Zeit mit der TUDaBeamer und hänge mich leider gerade an einigen Kleinigkeiten auf.

Ich würde gern die Graphik auf der Titelfolie zentriert statt linksbündig darstellen. Welchen Befehl kann ich hierfür nutzen? 

Und mit \thanks erstellte Fußnoten werden nicht angezeigt.

**Comment by TeXhackse** [comment]
`\titlegraphic` zentriert  in den letzten Versionen das Bild horizontal. Wichtig ist dabei natürlich, dass die Breite geringer ist, als die verfügbare Breite.

`\thanks` wird nicht wirklich in Beamer Folien unterstützt. Es entspricht zwar \footnote, diese wird aber  im normalen Modus nur ausgeführt, wenn Sie auch Bestandteil der Kurzversion des Autors ist. Ggf. kann die Option `authorontitle` helfen, da in diesem Fall die lange Version ausgeführt wird.

Ich hoffe, das hiflt weiter.

**Comment by TeXhackse** [comment]
ich schließe das, da eigentlich alles geklärt sein sollte.
