### ISSUE TITLE
luatex vs pdftex

### ISSUE THREAD

**Issue by BenK3nobi** [tudace/tuda_latex_templates#15]
Heyho, 

I got a problem I do not understand. 
Using pdftex, the correct roboto fonts are used. 
Using lualatex it does not use it. 

Any ideas what the reason could be?

**Comment by marklaz** [comment]
What TeX distribution do you use?

**Comment by BenK3nobi** [comment]
TeXLive 19 on Ubuntu 18.

**Comment by TeXhackse** [comment]
This could rely on you font installations, can you please give us the log files?
Additional recorder files could also be helpful. Those are created when running the compiler using the --recorder option. You then get an `*.fls`-file including all file dependencies.

**Comment by TeXhackse** [comment]
I close this one since we did not get any further information.
