### ISSUE TITLE
Metadata falsch benutzt

### ISSUE THREAD

**Issue by aDramaQueen** [tudace/tuda_latex_templates#150]
Servus,
ich setz mich für mein ProSeminar gerade zum ersten mal mit der neuen Vorlage auseinander. Kleine Warnung: Ich bin ein LaTeX Anfänger.

Mein System: MikeTex 2.9.7338 mit TeXstudio 2.12.22 (sollte beides die aktuellste Version sein)

Ich hab mir eigentlich nur eure Templates von hier geholt und wollte die direkt Kompilieren & schon da scheitert es:

![latex](https://user-images.githubusercontent.com/52710085/74144263-b5abd300-4bfc-11ea-99c4-596b2230ce34.png)

Nun bin ich an dieser Stelle schon verwirrt. Die Errormessage:
`You used the X metadata entry`
ist doch aus meiner Sicht kein Fehler, sondern genau so soll es doch gemacht werde. Ich will doch, dass alle diese Infos in meine Titel auftauchen?

P.S.: Natürlich hab ich auch schon alle Packete auf Aktualität überprüft & die Filename-Database aktualisiert. Diese Fehler können also ausgeschlossen werden.

P.P.S.:
- Hier das komplette LOG von der Kompilation -> [DEMO-TUDaPhD.log](https://github.com/tudace/tuda_latex_templates/files/4180505/DEMO-TUDaPhD.log)

- Hier meine instalierten Packete -> [packages.txt](https://github.com/tudace/tuda_latex_templates/files/4180498/packages.txt)

**Comment by TeXhackse** [comment]
Das ist ein alter Bug der in Versionen, die älter als 2.07 ist mit dem neuen  expl3-kernel auftauchte. Das ist mittlerweile gefixt. 

Verwendet wurde laut log die Version 2.05. 

Als Workaround empfehle ich `pdfa=false` zu setzen, bis das paket geupdated ist. Sofern es akut zwingend notwendig ist, eine pdfa zu bauen, geht es auch das Paket lokal zu installieren.

Die MikTeX-Version hat nicht direkt etwas mit der Paketversion zu tun, es dauert oft einige Tage, bis das update, dass z.B. heute morgen (2.08) auf CTAN gegangen ist, über alle Systeme verteilt ist.

**Comment by aDramaQueen** [comment]
Ah sorry, hab die alten Issues garnicht durchforstet.

Ich danke artig.

**Comment by aDramaQueen** [comment]
**Nachtrag:**
Kleine Info für Leute die in ein ähnlich Problem rennen:
Wenn ihr die Packages in MikTex updated dann müsst ihr das 2 mal machen:
- Einmal im Administrator Mode
- Einmal im User Mode
Ich hatte das Update nur im Administrator Mode gemacht und hatte dort auch die 2.07 Version. Ich bin davon ausgegeangen, dass dann auch automatisch der User Mode geupdated wird. Das ist tatsächlich nicht der Fall. Wobei sich mir dann an dieser Stelle nicht ganz die Funktionalität des Administrator Mode erschließt, dass ist aber ein anderes Problem...
