### ISSUE TITLE
Submissiondate in different languages

### ISSUE THREAD

**Issue by amz16** [tudace/tuda_latex_templates#151]
Hi, 

I am using tuda thesis and would like to change the submission date from \today.
As I am using different languages in my document, English for the main part and German in the Thesis Statement (Erklärung zur Abschlussarbeit), I would like to specify my date in the \submissiondate{} so that it gets translated to the corresponding languages.
Is there any way to achieve this?

Thanks!

**Comment by TeXhackse** [comment]
Hey,
`\today` is automatically translated using the babel package. Since you might use babel anyway to change the languages (this is the way tuda-ci) supports you can simply use that mechanism. 

example: 
```
\documentclass{tudapub}

\usepackage[main=ngerman, english]{babel}
\begin{document}
	\today
	
	\selectlanguage{english}
	
	\today
\end{document}
```

I want to add that this has nothing to do with this template thats why I will close this issue.

**Comment by amz16** [comment]
Hello, 

it seems, I wasn't clear enough. 
I would like to put a different date than \today, say something like \submissiondate{01-01-2021}.
Then in the English version I would like something like 1 January 2021 and in the German version analogously.
I realize this doesn't work and I have found some options online to define a custom date, using packages like datetime though none of this worked for the tuda package. 

For example, I found this:

\documentclass{article}
\usepackage[ngerman]{datetime}
\usepackage[ngerman]{babel}
\newdate{date}{06}{02}{2012}
\date{\displaydate{date}}
\title{My Title}

\begin{document}
\selectlanguage{ngerman}
\maketitle
We discussed in the question session on \displaydate{date} unimportant stuff.
\end{document}

When I try to use this in my document and put \submissiondate{\displaydate{date}} it gives me numerous errors:

![image](https://user-images.githubusercontent.com/60963225/74353678-8f339680-4dba-11ea-8e86-d46731349eaa.png)

I don't really care about the specific package or solution, that does the job, that is why I didn't give this example in the previous message, but I hope this helps to understand my problem. Sorry for not being more clear in the first place.

Thanks!

**Comment by schoeps** [comment]
I may still not understand the problem. However, maybe this helps: you can set `submissiondate` to a string and you can even redefine it. So, just hardcode the strings as you like them to be:
```
\documentclass[thesis={type=bachelor},ngerman,pdfa=false]{tudapub}
\usepackage[english, main=ngerman]{babel}
\begin{document}

\author[V. Name]{Vorname Name}
\birthplace{Geburtsort}

\submissiondate{Whatever date you like}
\examdate{Some other date}
\affidavit

\submissiondate{Another date}
\examdate{Only today}
\affidavit

\end{document}
```

**Comment by amz16** [comment]
Yes, redefining helps, thanks!

**Comment by TeXhackse** [comment]
@amz16 @schoeps: The problem with this solution is, that you would have to change to twice in case of a change of the date. Usually thats a chance for mistakes to happen.

I'd either locally redefine `\day`, `\month`, `\year` as with 
```
\day=1
\month=3
\year=2019
<title material including \today>
``` 
which is a bit of a hack. 

Beside that one could use datetime2 (not datetime) or reconstruct a mechanism similar to `\today` as defining a language dependent macro using `\defcaptionname` (KOMA-Script) with different number macros than the upper ones.

**Comment by schoeps** [comment]
Thanks @TeXhackse: You have my emphatic sympathy for correcting such "mistakes". I would do the same if we would talk about octave, python or c-code but with Latex my coding moral is inferior :) 

I will not follow this issue any further. @amz16 can now choose between several working options.
