### ISSUE TITLE
microtype Error: Ignoring \DisableLigatures in XeLaTeX

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#152]
Als ich #51 lösen wollten, fiel mir auf, dass beim aktuellen Texlive (Mac), das Kompilieren mit pdflatex von
```
\documentclass[thesis={type=bachelor},ngerman]{tudapub}
\usepackage[english, main=ngerman]{babel}
\begin{document}
\affidavit
\end{document}
```
zum Fehler
```
/usr/local/texlive/2019/texmf-dist/tex/latex/tuda-ci/tudafonts.sty:62: Package 
microtype Error: Disabling ligatures of a font is only possible
(microtype)                with pdftex version 1.30 or newer.
(microtype)                Ignoring \DisableLigatures.
```
und noch einigen weiteren führt [example.log](https://github.com/tudace/tuda_latex_templates/files/4193752/example.log). lualatex hat keine Probleme.

**Comment by TeXhackse** [comment]
das ist aber mit texlatex kompiliert, nicht mit pdflatex. 

Aber ja, okay da wir auf type1 zurückfallen, macht das probleme, ich kümmer mich drum.

Grundsätzlich hilft hier auch pdfa ausschalten, aber ich bau einen fallback ein.

**Comment by schoeps** [comment]
Ja, stimmt: XeLaTeX, sorry (eilt nicht, ich schalte pdfa immer aus). Danke.

**Comment by marklaz** [comment]
Wie wichtig ist es, neben LuaLaTeX eine vollständige Unterstützung von XeLaTeX sicherzustellen?

Nach meinem Verständnis ist mit LuaLaTeX alles machbar, was auch mit XeLaTeX machbar ist. (Oder existieren bei LuaLaTeX deutlichere Einschränkungen bzgl. linksläufiger Schriften?)

Falls LuaLaTeX die meisten denkbaren Einsatzszenarien abdeckt, können wir die XeLaTeX-Unterstützung gerne als eher optional handhaben. Abschlussarbeiten und Dissertationen sind hinsichtlich der möglichen Sprachen ja ohnehin auf rechtsläufige Schriften festgelegt, wenn ich mich nicht täusche.

**Comment by TeXhackse** [comment]
Naja, das einzige was problematisch ist, ist ja PDF/A. Dazu haben wir schon geschrieben, dass das nicht voll unterstützt wird.

Es gibt grundsätzlich abseits von besonderen Schriftsystemen oder Sprachen keinen Grund für XeLaTeX, eher im Gegenteil, LuaLaTeX kann definitiv mehr abdecken.

**Comment by marklaz** [comment]
Das wäre für mich Grunds genug, XeTeX nicht als originär unterstützt darzustellen, sondern eher im Sinne von "kann funktionieren, wird aber nicht garantiert".

**Comment by TeXhackse** [comment]
Für mich war das schon immer ein „wird halt unterstützt soweit möglich“, entschuldigt, wenn das anders rüberkam.

Das microtype-Problem werde ich so oder so noch fixen, weil es keine große Sache ist. Formulieren könnt ihr das gerne auch so, wenn du denkst, dass das dann leichter nachvollziehbar ist.

**Comment by schoeps** [comment]
Ich hänge nicht an XeLaTex. Ich nutze LuaLaTeX und probiere den Rest nur hin und wieder aus, um ggfs. hier Bugs zu melden.
