### ISSUE TITLE
Author expansion not working for more than 2 authors with pdfa=true

### ISSUE THREAD

**Issue by ArashJavan** [tudace/tuda_latex_templates#153]
Hi, I have installed texlive 2019 manually on Kubunut 18.04, i use texstudio 2.12.22 (latest version). tuda-ci was also preinstalled, so there was no need to install it regarding to tlmgr. But every time I want to compile a TUDa document i get following error:
What ai am doing wrong?

Undefined control sequence. ...ertUTFtoBE{\pdfx@pdfAuthor}{\xmp@Author}
![Untitled](https://user-images.githubusercontent.com/5918827/74740177-aced7980-525a-11ea-8791-67c79ec3007d.png)

**Comment by TeXhackse** [comment]
You receive a warning about using pdfa-mode with xetex, you should have a look at that part of the log file. 

XeTeX doesn't completly support the pdfa-mode. Therefore you should either turn it off, or switch the compiler to lualatex.

This is all I can reply with only that screenshot. For more detailed information I'd require a log file.

**Comment by ArashJavan** [comment]
@TeXhackse Thanks a lot for your replay. Logfile is attached. As far as I can see, there is a problem with undefined control seq. used in pdfx.sty. This also can be found in the log file as: "! Undefined control sequence."
By the way, I have changed the compiler to lua, but still, get the same error as above.

[report.log](https://github.com/tudace/tuda_latex_templates/files/4219517/report.log)

**Comment by TeXhackse** [comment]
Cleanup the helper files, especially the `\jobname.xmpdata`-file that should help to compile with lualatex. I will have a closer look asap.

**Comment by ArashJavan** [comment]
@TeXhackse I just removed everything that was generated by latex, including *.xmpdata-file, but unfortunately the error with pdfx.sty is still there :(.

It would be great if you could inspect the report.log-file. Thanks

**Comment by TeXhackse** [comment]
well, you can disable pdfa-mode to workaround temporarily.

**Comment by ArashJavan** [comment]
@TeXhackse Disabling pdfa did the job! thanks!
