### ISSUE TITLE
Figure and Table Counting and lables aren´t working.

### ISSUE THREAD

**Issue by ZnLuBa** [tudace/tuda_latex_templates#156]
Dear Latex-Team,

I am not sure wether to write in English or german, but since most of the conversation in github is in English, I’ll just stick to that. 

So now as to what my problem is: I am currently writing my Bachelor thesis and of course I am using the Corporate Design. Unfortunately and I can´t find the problem, the number of my tables and figures are not  counting through the document as normal. They start with 0.1 and so on. I don´t now how I can change that in the document settings and I don´t want to mess around with the tudapub code. I can send you my main document but because of the research, I can´t send you anything else. Maybe you already know what mistake I have made. Please ignore my  second heading, I just wanted to test the two-side version.

A second problem that comes with the main numbering problem is that the references to the tables and figures don´t work.

I appreciate every help I can get. Thanks in advance!

Regards ZnLuBa
[TudaPub.txt](https://github.com/tudace/tuda_latex_templates/files/4230117/TudaPub.txt)
[Theorie.txt](https://github.com/tudace/tuda_latex_templates/files/4230153/Theorie.txt)

**Comment by schoeps** [comment]
You choose a document class that is based on koma report. This starts with `chapter` if I am not mistaken.

**Comment by TeXhackse** [comment]
> I am not sure wether to write in English or german, but since most of the conversation in github is in English, I’ll just stick to that.
thanks, actually we don't care, but English makes it easier for non German speakers to follow up, if necessary

## On the 0.1 Numbering
Easy answer: You use Report as a base class -> the 0 is the chapter Number. If you add a chapter, you will get the correct numbering. Actually you would have the same issue with the section numbers but are manually cheatin on that, by 

```
\renewcommand*{\thesection}{\arabic{section}}
\setcounter{section}{0} 
\pagenumbering{arabic} 
```

## References
These work fine for me. You know about compiling twice if you include references? 
Could help more with a log file.

## Preamble in general
Clean it up. You should not add any packages where you don't know what they are doing. Especially if they are not necessary (e.g. caption package). And You can use hyperrefs `\autoref` for an easier mechanism to replace your own ref macros.

**Comment by ZnLuBa** [comment]
Thank you so much ! So glad it was so easy*.*
