### ISSUE TITLE
tuda-Vorlagen lassen sich nicht kompilieren

### ISSUE THREAD

**Issue by tuda-dau** [tudace/tuda_latex_templates#157]
Guten Tag,

vor ca. einem Monat hat das Kompilieren der tuda-Vorlagen noch funktioniert, heute ging plötzlich gar nichts mehr und ich bekam unter TexStudio zunächst die Meldung

"Could not Start Build & View:PdfLaTeX: pdflatex.exe..."

und dasselbe auch mit lualatex. Ich nutze Miktex 2.9 mit Texstudio unter Windows 10. 

Ich habe nun stundenlang nach einer Lösung gesucht, die Name-Database und Package-Database aktualisiert, alle Updates installiert, pdflatex und lualatex in der Miktex-Konsole unter Settings -> Format neu gebaut. Als alles nicht half, habe ich Miktex komplett neu aufgesetzt, genauso wie Texstudio. Aber ich bekomme trotzdem jedes Mal eine ewig lange Liste an Fehlermeldungen, sowohl wenn ich meine Thesis (die schon einmal kompiliert werden konnte) als auch die Minimalbeispiele aus dem tuda-Package (DEMO-TUDaThesis, DEMO-TUDaReport, DEMO-TUDaPub,...) versuche zu kompilieren. Die Fehler sind immer die gleichen, unabhängig davon, ob ich pdflatex oder lualatex als Kompiler verwende:

Datei           Art     Zeile            Fehlertext
expl3.sty   Fehler    86    Missing \begin{document}. \_
expl3.sty   Fehler    86    Missing $ inserted. \_
expl3.sty   Fehler    87    You can't use `macro parameter character #' in math mode. ...r~request~inconsistent~with~engine:~using~'#
....

Das geht so noch eine Weile weiter. Ich habe nicht die geringste Ahnung, was es mit dieser expl3.sty auf sich hat. Da ich nicht weiter wusste, habe ich das zugehörige Paket l3kernel einmal deinstalliert und wieder neu installiert, es ändert sich aber nichts.

Für jede Hilfe wäre ich sehr dankbar.

**Comment by schoeps** [comment]
Es gab ein Update von expl3.sty, das für tuda-ci relevant ist. Das müsste aber im Miktex-Repository verfügbar und bei der Neuinstallation mitgekommen sein. Es kann aber noch irgendwo alte Pakete geben, zB unter %APPDATA% (C:\Documents and Settings\<user>\Application Data\MiKTeX\...), die Vorrang haben und Probleme verursachen. Ich kenne mich mich Miktex nicht gut aus, aber vielleicht hilft der Hinweis zur Selbsthilfe.
Wenn meine Vermutung stimmt, dann hat das mit dem Template nichts zu tun. Es ist ein reines Miktex-Problem.

**Comment by TeXhackse** [comment]
> "Could not Start Build & View:PdfLaTeX: pdflatex.exe..." 

Ist eine Meldung, die TeXstudio ausspuckt, wenn es die aktuelle Datei entweder für nicht kompilierbar hält (andere Dateiendung als `*.tex`) oder die Pfad Variablen nicht richtig gesetzt sind. Letzteres lässt sich über _Hilfe_ > _LaTeX-Installation prüfen_ testen. 

Es wirkt etwas so, als würde versucht werden `expl3.sty` zu kompilieren, statt der `*.tex`-Datei. Gibt es ein Log File? Sonst ist nämlich wirklich der Fall, dass die TeXStudio konfiguration nicht passt.

In diesem Fall einmal folgendes Testen:
1. Datei öffnen, die Kompiliert werden soll
2. _Tools_ > _Terminal öffnen_
3. `pdflatex <Dateiname>.tex` eingeben und ausführen.

**Comment by tuda-dau** [comment]
Vielen Dank schon einmal für die schnelle Rückmeldung!

Wenn ich unter Texstudio "Hilfe -> Latex-Installation prüfen" wähle, bekomme ich die angehängte Meldung. 
[Log_Latex_Installation.txt](https://github.com/tudace/tuda_latex_templates/files/4241718/Log_Latex_Installation.txt)

Ich habe weiterhin wie vorgeschlagen in Texstudio über das Terminal den Befehl pdflatex DEMO-TUDaPhD.tex sowie lualatex DEMO-TUDaPhD.tex eingeben. Hier die Ausgabe für die Ausführung mit pdflatex:

> C:\Users\MEIN_NUTZER\AppData\Local\Temp>pdflatex DEMO-TUDaPhD.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit)
Sorry, but pdflatex did not succeed.
The log file hopefully contains the information to get MiKTeX going again:

Hier der Inhalt der Log-File:

> 2020-02-23 17:20:18,828+0100 INFO  pdflatex - starting with command line: pdflatex --version
2020-02-23 17:20:18,852+0100 INFO  pdflatex - allowing known shell commands
2020-02-23 17:20:18,854+0100 INFO  pdflatex - enabling input (output) from (to) processes
2020-02-23 17:20:18,897+0100 INFO  pdflatex - finishing with exit code 0
2020-02-23 17:23:57,845+0100 INFO  pdflatex - starting with command line: pdflatex.exe -version
2020-02-23 17:23:57,855+0100 INFO  pdflatex - allowing known shell commands
2020-02-23 17:23:57,856+0100 INFO  pdflatex - enabling input (output) from (to) processes
2020-02-23 17:23:57,876+0100 INFO  pdflatex - finishing with exit code 0
2020-02-23 17:28:04,035+0100 INFO  pdflatex - starting with command line: pdflatex DEMO-TUDaPhD.tex
2020-02-23 17:28:04,045+0100 INFO  pdflatex - allowing known shell commands
2020-02-23 17:28:04,045+0100 INFO  pdflatex - enabling input (output) from (to) processes
2020-02-23 17:28:04,089+0100 INFO  pdflatex - going to create file: pdflatex.fmt
2020-02-23 17:28:07,921+0100 ERROR pdflatex - C:\Program Files\MiKTeX 2.9\miktex\bin\x64\initexmf.exe did not succeed; exitCode: 1
2020-02-23 17:28:07,922+0100 ERROR pdflatex - output:
2020-02-23 17:28:07,922+0100 ERROR pdflatex - 
Sorry, but "MiKTeX Configuration Utility" did not succeed.
The log file hopefully contains the information to get MiKTeX going again:
  C:\Users\MEIN_NUTZER\AppData\Local\MiKTeX\2.9\miktex\log\initexmf.log
2020-02-23 17:28:07,924+0100 FATAL pdflatex - The memory dump file could not be found.
2020-02-23 17:28:07,924+0100 FATAL pdflatex - Info: fileName="pdflatex.fmt"
2020-02-23 17:28:07,924+0100 FATAL pdflatex - Source: Libraries\MiKTeX\TeXAndFriends\texmfapp.cpp
2020-02-23 17:28:07,924+0100 FATAL pdflatex - Line: 689
2020-02-23 17:28:07,925+0100 INFO  pdflatex - finishing with exit code 1

Hier dann noch die Ausgabe mit lualatex:

> C:\MEIN_PFAD\...\tuda_templates\doc\latex\tuda-ci\example>lualatex DEMO-TUDaPhD.tex
This is LuaTeX, Version 1.12.0 (MiKTeX 2.9.7300 64-bit)
 restricted system commands enabled.
(./DEMO-TUDaPhD.tex
LaTeX2e <2020-02-02> patch level 3
 L3 programming layer <2020-02-14>
("C:/Program Files/MiKTeX 2.9/tex/latex/tuda-ci/tudapub.cls"
(C:/Users/MEIN_NUTZER/AppData/Roaming/MiKTeX/2.9/tex/latex/l3kernel/expl3.sty
(C:/Users/MEIN_NUTZER/AppData/Roaming/MiKTeX/2.9/tex/latex/l3kernel/expl3-code.
tex)
! LaTeX Error: Missing \begin{document}.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...
l.86 \_
     _msg_kernel_new:nnnn { expl } { wrong-driver }
?

Und final der Inhalt der lualatex.log:

> 2020-02-23 17:23:49,044+0100 INFO  lualatex - starting with command line: lualatex.exe -synctex=1 -interaction=nonstopmode DEMO-TUDaPhD.tex
2020-02-23 17:23:52,490+0100 INFO  lualatex - finishing with exit code 1
2020-02-23 17:30:31,127+0100 INFO  lualatex - starting with command line: lualatex DEMO-TUDaPhD.tex
2020-02-23 17:33:17,610+0100 INFO  lualatex - finishing with exit code 1
2020-02-23 17:37:39,543+0100 INFO  lualatex - starting with command line: lualatex DEMO-TUDaPhD.tex

Leider kann ich aus diesen Meldungen keine notwendige Handlung ableiten bzw. herauslesen, warum sich die tuda-Tex-Files nicht mehr mit pdflatex oder lualatex kompilieren lassen. Wie gesagt, andere tex-Files (ohne TUDA-Vorlage) lassen sich nach wie vor kompilieren. 

Vielen Dank im Voraus für Feedback und viele Grüße

**Comment by schoeps** [comment]
Die Zeile `C:/Users/MEIN_NUTZER/AppData/Roaming/MiKTeX/2.9/tex/latex/l3kernel/expl3.sty` deutet auf eine lokale Installation im Benutzerverzeichnis. Ich hatte vorgeschlagen nach so etwas zu suchen und es zu löschen. Wenn das nicht hilft, dann ggf. auch noch `C:/Program Files/MiKTeX 2.9` manuell löschen und Miktex neu installieren.

**Comment by tuda-dau** [comment]
Als ich die Neuinstallation vornahm, hatte ich den Ordner im Benutzerverzeichnis gelöscht, danach aber auch Miktex komplett neu aufgesetzt. Ich habe jetzt wie von schoeps vorgeschlagen nur den Miktex-Ordner in AppData\... gelöscht und danach versucht, die Demo-Vorlagen zu kompilieren. Zuerst wurde ich danach gefragt einige Pakete manuell nachzuinstallieren (der Ordner in AppData\... wurde dadurch neu erzeugt), danach hat es aber tatsächlich wieder funktioniert!

Vielen Dank also für die Hinweise! Vielleicht hat ja zukünftig jemand anderes das gleiche Problem und findet hier die Lösung.
