### ISSUE TITLE
Schriftgröße auf der Titelseite

### ISSUE THREAD

**Issue by Kexikus** [tudace/tuda_latex_templates#158]
Hallo,

mir ist die Schriftgröße auf der Titelseite in tudapub leider noch zu groß, obwohl sie laut Doku bereits verkleinert wurde. Laut [140](https://github.com/tudace/tuda_latex_templates/issues/140) sollte es möglich sein sie mit Standard-KOMA-Befehlen zu verkleinern, das funktioniert aber nicht.
Mit `\addtokomafont{title}{\tiny}` passiert gar nichts, mit `\setkomafont{title}{\tiny}` erreiche ich nur, dass die Schriftart zu Charter wechselt, die Größe bleibt aber wie sie war.

Laut [dieser Frage bei Stackexchange](https://tex.stackexchange.com/questions/82850/change-the-title-size-in-scrartcl) gibt es das Problem auch in der scrartcl Klasse, weil `\maketitle` die Schriftgröße dort selbst definiert und wenn ich die Definition von `\maketitle` in tudapub.cls richtig verstanden habe passiert dort etwas Ähnliches und ich kann die Schriftgröße nicht ändern.

Verstehe ich das falsch oder gibt es aktuell keine Möglichkeit die Schriftgröße zu ändern? Und gibt es in letzterem Fall einen Workaround? Die Schriftgröße einfach in die Definition von `\title` einzufügen ist leider auch keine Lösung weil sie dann auch auf der zweiten Seite verändert wird.

**Comment by TeXhackse** [comment]
Hallo @Kexikus,
Wurde versucht, die Option `title =small` zu setzen? 
Damit sollte sie eine Stufe kleiner werden.

**Comment by Kexikus** [comment]
Nein, wurde sie nicht. Das muss ich in der Dokumentation irgendwo überlesen haben.

Mit dieser Option passt dann zwar die Größe des Titels, allerdings wurden auch alle anderen Schriftgrößen auf der Titelseite verkleinert. Gibt es die Möglichkeit dort die ursprüngliche Größe beizubehalten und nur den Titel selbst zu verkleinern?

**Comment by TeXhackse** [comment]
Ist nicht vorgesehen, da das Design eigentlich ja diesbezüglich sehr strikte Vorgaben hat.

`title=small` setzt folgende Änderung für den Titel + ähnliche für die übrigen Schriftarten.
```
\ExplSyntaxOn
\cs_set:Nn \TUDa_title_fontsize: {{22pt}{28pt}}
\ExplSyntaxOff
```
