### ISSUE TITLE
\uppertitleback und \lowertitleback auf 3. Seite?

### ISSUE THREAD

**Issue by Kexikus** [tudace/tuda_latex_templates#159]
Mir ist klar, dass `\uppertitleback` und `\lowertitleback` dafür da sind die Rückseite der Titelseite zu beschreiben. Allerdings wird die dadurch erzeugte Seite von unserem Studienbüro bei Abschlussarbeiten immer genutzt, um diese bei der Einreichung zu stempeln, was auf der Rückseite der Titelseite eher schwierig ist.

Daher die Frage: Ist es irgendwie Möglich diese Informationen auf eine neue Seite zu verschieben? Oder alternativ dafür zu sorgen, dass sie trotz `twoside=true` nicht automatisch angezeigt werden, sodass ich sie selbst formatieren könnte?

**Comment by TeXhackse** [comment]
Beides kann natürlich manuell leer gesetzt werden. 
```
\uppertitleback{}
\lowertitleback{}
```
Wenn die Inhalte vorher gespeichert werden sollte, um sie zu verschieben, liegen diese in `\@uppertitleback` bzw. analog. Damit wäre Beispielsweise folgendes Möglich:
```
\let\saveUppertitleback{\@uppertitleback}
\uppertitleback{}
```
Damit könnte die Ausgabe verzögert und an beliebiger Stelle durch `\saveUppertitleback` benutzt werden.

**Comment by Kexikus** [comment]
Vielen Dank für die schnelle Antwort, das klingt genau nach der Lösung die ich suche.

Allerdings muss ich nochmal dumm nachfragen an welcher Stelle ich das jetzt in mein Dokument einfügen muss.

Ich habe bisher die ganzen Definitionen von `\title` etc ausgehend von der Vorlage nach `\begin{document}`, dann gefolgt von `\maketitle`. Nach meinem Verständnis müsste ich den obigen Code entsprechend nach den Definitionen, aber logischerweise vor `\maketitle` einfügen. Nach Letzterem folgt dann ein `\cleardoublepage` und `\saveUppertitleback`. Damit bekomme ich zwar einen Fehler über zu viele geschlossene Klammern }, aber kompiliert wird trotzdem. Nur landet mein Uppertitleback dann vor der Titelseite. Wenn ich den Code hinter das `\maketitle` verschiebe, bleibt allerdings wie zu erwarten das ursprüngliche Uppertitleback stehen.

Wenn ich den neuen Code und entsprechend auch die Titel-Definition etc vor `\begin{document}` ziehe, bekomme ich den Fehler, dass eben jenes fehlt.

Und mehr Platzierungen als das sind mir nicht eingefallen, daher wäre ich über jede Hilfe dankbar.

**Comment by TeXhackse** [comment]
wah sorry , ich editiere das oben

**Comment by Kexikus** [comment]
Perfekt, damit funktioniert es.

Vielen Dank!

**Comment by Kexikus** [comment]
Ich muss das Thema leider nochmal ansprechen, da mir heute doch ein Problem mit der obigen Lösung aufgefallen ist.

Und zwar sorgt sie dafür, dass das Dokument nicht mehr im Blocksatz formatiert wird. Grund dafür ist `\raggedright` am Anfang von `\uppertitleback`. Wieso das allerdings nur nach diesem Umbau passiert und nicht auch im normalen Design weiß ich nicht. Und was ich auch nicht weiß, ist was ich dagegen tun kann.

Ich musste, um sowohl upper- als auch lowertitleback richtig anzeigen zu können schon Folgende merkwürdige Konstruktion anwenden:

`\saveUppertitleback
\vspace{\fill}
\begin{minipage}[t][][b]{\textwidth}
\saveLowertitleback
\end{minipage}`

Alle anderen Möglichkeiten haben immer damit geendet, dass Lowertitleback nicht am unteren Seitenende gelandet ist.

Um jetzt wieder Blocksatz zu nutzen wollte ich das Paket ragged2e und den Befehlt `\justifying` verwenden. Das hat auch einigermaßen funktioniert, allerdings hat das wiederum die Position des Lowertitlebacks ruiniert. Und damit sind mir auch leider die Ideen ausgegangen. Über jede weitere Hilfe wäre ich entsprechend dankbar.

**Comment by TeXhackse** [comment]
Oh, Ich verstehe, die Gruppierung fällt dann weg. Tatsächlich wird bei KOMA-Script das ganze auch innerhalb einer Box ausgegeben, also der Aufruf ist dann
```
\begin{minipage}[t]{\textwidth}
\@uppertitleback% das dann halt durch \saveUppertitleback ersetzen
\end{minipage}\par
```
Könnte man dafür genauso machen.

Alternativ würde es hier aber auch genügen das ganze zu Gruppieren
```
\begingroup
\saveUppertitleback
\vfill
\saveLowertitleback
\par
\endgroup
\clearpage
```

### Allgemeiner Hinweis:
```
\begin{minipage}[t][][b]{\textwidth} 
``` 
ergibt nicht wirklich Sinn.
`[t]` richtet an der oberen Baseline aus. `[b]` den Text innerhalb der Box unten, allerdings macht das nur dann einen Unterschied, wenn der Mittlerere Parameter gesetzt ist. Dort wird die Höhe der Box übergeben. In diesem Fall würde `\begin{minipage}[t]{\textwidth}` wie oben den gleichen Effekt erzielen.

**Comment by Kexikus** [comment]
Danke für die Hilfe.

In der Minipage-Variante hat das Ganze jetzt funktioniert. In der rein gruppierten Version bekomme ich einen "No line to end here" Fehler wenn LowerTitleBack einen Inhalt hat. Aber die erste Version tut ja genau was ich möchte.

**Comment by TeXhackse** [comment]
Ah, Kleinkram Anpassungen. Ja. Aber dann mach ich das hier jetzt zu Ich nehm die zweite oben raus.
