### ISSUE TITLE
Title Page in English

### ISSUE THREAD

**Issue by PhilSuerte** [tudace/tuda_latex_templates#160]
Hello,

I have to write my master thesis in English, but I cant find a solution to customize the titlepage. Is there any way to switch to english or adjust it manually?

**Comment by schoeps** [comment]
Isn't it obvious? Just change `ngerman` to `english`, i.e.
```
\documentclass[english,...]{tudapub}
```
and
```
\usepackage[ngerman, main=english]{babel}
```
