### ISSUE TITLE
Index bei TUDa-Thesis

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#161]
Ich bin über einen kleineren Bug beim Erzeugen eines Index für Doktorarbeiten gestoßen. Wenn man die Option `custommargins=true` setzt wird die farbige Leiste in der Kopfleiste merkwürdig gesetzt (siehe angehängtes PDF/MWE). Wenn man die Option deaktiviert passiert das nicht.

Ich habe ein bisschen rumgetestet und das Ganze scheint unabhängig von der genauen Positionierung des Index zu sein oder ob man das in den Appendix schiebst, das als backmatter deklariert etc.

```
\documentclass[ruledheaders=chapter,
	class=book,
	thesis={
		type=dr,
		dr=rernat
	},
	custommargins=true,
	marginpar=false,
	fontsize=11pt,
	pdfa=false,
	IMRAD=false
]{tudapub}

\usepackage{makeidx}

\makeindex

\begin{document}

Das hier ist ein Test\index{Test} für Index.

\printindex

\end{document}
```
[MWE.pdf](https://github.com/tudace/tuda_latex_templates/files/4280206/MWE.pdf)

**Comment by TeXhackse** [comment]
Danke, ich kümmer mich drum.

**Comment by TeXhackse** [comment]
Ich muss noch ein paar Tests drauf werfen, aber wenn ich das gerade richtig sehe, sollte die angehängt Datei für alle Fälle, die mir gerade einfallen funktionieren. Nach den Tests, mach ich ein entsprechendes Release fertig.

Workaround folgendes (zur besseren übersicht vielleicht auch in eine extra datei und diese mit `\input` einbinden) vor `\begin{document}` einfügen:
```
\makeatletter
\ExplSyntaxOn
\renewpairofpagestyles{TUDa}{
	\KOMAoptions{plainfootsepline}	
	\bool_if:NTF \g_TUDa_marginpar_bool
	{
		\KOMAoptions {
			headwidth=textwithmarginpar,
			footwidth=textwithmarginpar
		}
	}{
		\KOMAoptions {
			headwidth=text,
			footwidth=text
		}
	}
	\setkomafont{pagehead}{\Large\bfseries}
	\RedeclareLayer[
	clone=scrheadings.head.above.line,
	background,
	contents={
		\dim_compare:nF {\box_wd:N \TUDa@headline_box=\layerwidth} {
			\TUDa@makeheadrule*[color=identbarcolor, width=\layerwidth]{TUDa@headline}
		}
		\smash{\TUDa@headline}
	}
	]{TUDa.head.above.line}
	\RedeclareLayer[
	clone=plain.scrheadings.head.above.line,
	background,
	contents={
		\dim_compare:nF {\box_wd:N \TUDa@headline_box=\layerwidth} {
			\TUDa@makeheadrule*[color=identbarcolor, width=\layerwidth]{TUDa@headline}
		}
		\smash{\TUDa@headline}
	}
	]{plain.TUDa.head.above.line}
	\bool_if:NT \g_TUDa_headline_bool {
		\clist_map_variable:nNn {oneside, even, odd} \l_tmpa_tl {
			\ModifyLayer[pretocontents={\rule[-6pt]{0pt}{\layerheight}}]{TUDa.head.\l_tmpa_tl}
		}
		\lehead{\headmark}
		\lohead{\headmark}
	}
	\ofoot[\pagemark]{\pagemark}
}
\ExplSyntaxOff
\makeatother
```
