### ISSUE TITLE
Adjusting page margins in tudapub?

### ISSUE THREAD

**Issue by pkonow** [tudace/tuda_latex_templates#163]
Hi,

we have been given a Word template for a seminar/term paper and are trying to re-create the requirements using Latex in the **tudapub** template. Unfortunately I haven't managed to adjust the page margins yet. We disabled the "Randnotizspalte" via `marginpar=false` in the `documentclass` options.

Now the Word template has margins of about 4cm on the left side, and 3cm on the right side. Our current tudapub document with `marginpar=false` has about 1cm on both sides. So we would like to increase the page margins on both sides and have the text centered in the middle.

Various online resources suggest to use the "geometry" package in some of the following ways:

* `\usepackage[margin=1in]{geometry}`
* `\usepackage[inner=4cm,outer=3cm]{geometry}`

However, when using this command I get the following error:

```
! LaTeX Error: Option clash for package geometry.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.25 
   
? 
```
I didn't find a reference regarding the change of page margins in the TuDaPub example document except for the `marginpar=auto/true/false` option. Help would be appreciated! :)

**Comment by schoeps** [comment]
The margins in the latex template are according to the TU style guide, so there should be no 'official' reason to change them (however, you can do surely do want you want). A minimal working example would be helpful to see which setting you are using. Did you read about `custommargins=geometry` in the manual?

```
%!TEX TS-program = lualatex
\documentclass[
	pdfa=false,
	class=report,
	custommargins=geometry,
]{tudapub}
\usepackage{blindtext}
\geometry{reset,left=5cm,right=5cm,nomarginpar}
\begin{document}
\blindtext
\end{document}

```

**Comment by schoeps** [comment]
@pkonow please report if `custommargins` is not working for you since otherwise I will close this issue soon.

**Comment by pkonow** [comment]
Hi, thanks for your help! Based on your response we have chosen to stick with the default layout based on the TU style guide. :+1:
