### ISSUE TITLE
Seitenränder TUDaPhD

### ISSUE THREAD

**Issue by ArtemKarev** [tudace/tuda_latex_templates#164]
Ich hätte eine Frage zu der aktuellen LaTeX-Vorlage für die Dissertationen "TUDaPhD". 

Ich bin mir nicht sicher, ob ich die Vorlage mit den voreingestellten Seitenrändern tatsächlich so für die Dissertation verwenden soll. Während die Titelseite noch ganz normal aussieht, haben die nachfolgenden Seiten alles recht großzügige Ränder, sodass die nutzbare Fläche äußerst gering ist. 

Empfiehlt es sich die Ränder anzupassen oder soll man tatsächlich die Vorlage so verwenden. Die aktuell veröffentlichten Dissertationen auf der ULB Webseite haben vorwiegend ganz normale Ränder und keine von denen scheint diese Vorlage zu benutzen.

Viele Grüße
Artem

**Comment by TeXhackse** [comment]
Die Ränder sind nach Satzspiegelkonstruktion gesetzt. Das hat typografische Ursachen. Wenn dich das genauer interessiert, ist dies z.B. in der KOMA-Script Dokumentation erläutert (http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide.pdf, Kapitel 2: Satzspiegelberechnung mitypearea.sty) 

Grunsätzlich ist es aber auch möglich das anzupassen, siehe z.B. `custommargins=usegeometry` bzw. `custommargins=false`.
Die meisten Ränder orientieren sich an dem Standard von Textverarbeitungsprogrammen, TeX ist jedoch als Satzsystem einem anderen Anspruch unterworfen und versucht so die typografisch beste Lösung zu finden. Leider ist dies den Erstellern von einem Großteil von Dokumenten egal.

**Comment by ArtemKarev** [comment]
Das leuchtet mir ein. Ich war nur etwas verunsichert, weil scheinbar niemand bisher die Vorlage für die Dissertationen benutzt hat. Aber wenn der Satzspiegel so typografisch richtig und von der TU gewollt ist, halte ich mich gerne daran.

**Comment by TeXhackse** [comment]
Die TU hat diesbezüglich keine feste Vorgabe gemacht, da diese von Fachbereich zu Fachbereich unterschiedlich sind. Deswegen existieren alle Mechanismen.

Wir haben uns nur während der Entwicklung und da die Vorgaben der TU (wie bei TUDaPub) sehr lange Zeilen haben, was die Lesbarkeit beeinträchtigt, dafür entschieden diese Variante als Voreinstellung zu nehmen, da sie den besten verfügbaren Automatismus nutzt.

**Comment by ArtemKarev** [comment]
Vielen Dank
