### ISSUE TITLE
Global Fontsize in LaTeX documents

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#166]
Hello,
I just installed the new LaTeX TU Corporate Design and try to setup a new template for interal reports.
In the DEMO-TUDaPub document it is shown, that you can change the globel fontsize of the document by define the documentclass:

\documentclass[
ngerman,
accentcolor=8b,
fontsize=12pt,
marginpar=false,
]{tudapub}

If I do this, the only thing thats changing is the fontsize of captions. The textsize remains at 11pt.
I am thankful for every hint you can provide!

**Comment by TeXhackse** [comment]
@BPollicino  is there a possibility of adding a log file? I cannot reconstruct that. 

Generally it's working fine. You can set `fontsize=11pt` and `fontsize=12pt` to see a change. The default fontsize of tudapub is 8pt anyway.

**Comment by BPollicino** [comment]
@TeXhackse Thanks for your reply, i tested some stuff yesterday and it worked fine!

But there are some other design questions: 

1) What is the default baselineskip in tudapub? because if i use \usepackage{setspace} with \onehalfspacing, nothing really changes. Is there a difference compared to the old latex-version?

2) There's a big space over a new chapter (\section{...}), how can i delete that?


Thank you for your help!

**Comment by TeXhackse** [comment]
> What is the default baselineskip in tudapub? because if i use \usepackage{setspace} with \onehalfspacing, nothing really changes. Is there a difference compared to the old latex-version?

Set the spacing after the title material. The title resets this. This has been mentioned somewhere. I will recheck that and make this information more visible.

> There's a big space over a new chapter (\section{...}), how can i delete that?

This could be done using the KOMA-Script mechanism. You find it in the explanation of `\RedeclareSectionCommand`
