### ISSUE TITLE
Change fontsize of Stafford in figure captions

### ISSUE THREAD

**Issue by jhabieker** [tudace/tuda_latex_templates#167]
Hello,

just a small question:
is there the possibility to simply change the (global) fontsize of the figure captions in the tudapub class?
E.g. to 9pt or else?

Thanks a lot and best regards

**Comment by TeXhackse** [comment]
Sure, you can change it the usual way as you can for all font elements of koma-script.
```
\addtokomafont{caption}{\small}
```
The size should be scaled with the text fontsize. 

But if really necessary, you ofc can add static fontsize changes using `\fontsize{<fontsize>}{<baselineskip>}\selectfont`

**Comment by jhabieker** [comment]
Thanks a lot! :)
