### ISSUE TITLE
adressing fonts for pgfplots, etc

### ISSUE THREAD

**Issue by jhabieker** [tudace/tuda_latex_templates#168]
Hello,

I use pgfplots for graphs in my thesis and I would like to use FrontPage/Roboto/... for the axis labels.
Is there a way to address the fonts for a global setting like

\pgfplotsset{
	tick label style = {font=...},
	every axis label = {font=...},
	legend style = {font=...},
	label style = {font=...}
}

Thanks a lot in advance!

**Comment by TeXhackse** [comment]
All fonts have been replaced by free variants, so frontpage is no Roboto Slab.

Generally the fonts can be used as 
* `\accentfont` roboto slab, as used for captions 
* charter has been mapped to \normalfont
* roboto is implemented as \sffamily font

I hope this helps.
