### ISSUE TITLE
dateseperator error

### ISSUE THREAD

**Issue by PNapi90** [tudace/tuda_latex_templates#17]
I can only compile my PhD thesis tex file if I comment out `\gdef\dateseparator{:~}` in `tudapub.cls`.
However, this yields to `Tag der Einreichung/ `instead of `Tag der Einreichung:` on the title page.

**Comment by TeXhackse** [comment]
Could you please give me the log file of a compilation without the commented out line?

**Comment by PNapi90** [comment]
[DEMO-TUDaPhD.log](https://github.com/tudace/tuda_latex_templates/files/3533049/DEMO-TUDaPhD.log)

**Comment by TeXhackse** [comment]
Thank you, this is an incompatibility with the datetime package. I will therefore rename the macro for the next release.
