### ISSUE TITLE
Tudabeamer: customize authorontitle

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#177]
Is it possible to customize authortitle so I can pick what to show on the title page?

Thanks in advance.

**Comment by TeXhackse** [comment]
I don't get the point. You can of course differ between shortauthor and shortinstitute, so if you use 
```
\author[shortauthor]{}
```
the author will not be displayed on the top of the titlepage, but shortauthor will be displayed in the footer. Same for the similar title macros like `\institute`.

Further customizations would require customization of the beamer template.

I hope this helps.

**Comment by TeXhackse** [comment]
@Zentox? Would be cool to get feedback on that issue.

**Comment by TeXhackse** [comment]
Closing this, as it seems to be solved. Please reopen if necessary.
