### ISSUE TITLE
ERROR - Cannot find 'DEMO-TUDaBeamer.bcf'!

### ISSUE THREAD

**Issue by martin284** [tudace/tuda_latex_templates#178]
I just downloaded the tuda-ci package from CTAN and open the template for the beamer presentation in the examples folder. If I try to compile the tex-file in TexMaker, I got 'ERROR - Cannot find 'DEMO-TUDaBeamer.bcf'!' and see that there is no file like this in my folder. But if I do the same with the template for the Bachelor Thesis it works and the bcf-file is generated with the compiling.
Has anyone an idea what the problem is?

**Comment by schoeps** [comment]
`bcf`-files are created by biber. Maybe TexMaker tries to compile a bibliography but the document does not have one?

**Comment by martin284** [comment]
Yes that was the problem. Thanks!
