### ISSUE TITLE
Suggest linking to your excellent Corporate Design Handbuch

### ISSUE THREAD

**Issue by hairykiwi** [tudace/tuda_latex_templates#179]
In README.md and DEMO-TUDaPub.pdf (linked below) - consider linking to your excellent [Corporate Design Handbuch](https://www.intern.tu-darmstadt.de/media/medien_stabsstelle_km/services/medien_cd/das_bild_der_tu_darmstadt.pdf).

I found it only via a web search, after reading of its existence in [TUDaPub – LATEX-Paper imCorporate Design der TUDarmstadt](http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/doc/DEMO-TUDaPub.pdf).

Even for non-German speaker's, with a little help of a translation tool, it is a useful reference in the production of an aethetically pleasing document.

**Comment by TeXhackse** [comment]
Thank you for the hint. The „Corporate Design Handbuch“ is not part of this project, since we tried to simplify the usage of the Guideline. But you are right, we should add this reference correctly.
