### ISSUE TITLE
A5 title page fontsize

### ISSUE THREAD

**Issue by PNapi90** [tudace/tuda_latex_templates#18]
If a5 is selected as paper size in the PhD template, the fontsize of the subtitles (title in german, Zur Erlangung des Grades eines Doktors ...) is too large. Would be nice if this could be edited in the template.

**Comment by TeXhackse** [comment]
We had some discussions on the font size and I was told to adjust it  that way.
If @marklaz agrees with you we can change that in the tempate.

But:
You can also choose it yourself by changing the corresponding komafont:
`\addtokomafont{subject}{\small}% or any other fontsize macro`

**Comment by PNapi90** [comment]
Thank you. It seems that `\normalsize` instead of `\small` is the right text size

**Comment by TeXhackse** [comment]
@marklaz @schoeps 
Should we change something about this?

**Comment by schoeps** [comment]
I am in favor of reducing the font size for A5 (since it looks more beautiful) but I was not part of any previous discussion, so I don't know if there is some obscure official regulation in the design guide.

**Comment by marklaz** [comment]
I cannot check the different font sizes at the moment. 

My vote would be, that everything should look harmonically within each paper size. If that leads to a reduced font for subtitles in A5, it may be fine.

**Comment by TeXhackse** [comment]
I've now reduced the calculation for 1pt. the fonts for the titlepage have beed directly defined depending on papersize according to the guidelines. Hope this is enough now.
