### ISSUE TITLE
Smaller title block for TUDaExercise (was TUDaExercise without logo)

### ISSUE THREAD

**Issue by g-jih** [tudace/tuda_latex_templates#180]
Hello,

I'd like to get rid of the logo from the exercise template. So I tried to put `logo=false` on the documentclass but it didn't work. Is there another way to do so?

**Comment by TeXhackse** [comment]
Currently not. You can replace the logo with another image (even an empty one) using the `logofile` option. 

I can add such a boolean easily, but it's not my job to decide about this.

**Comment by schoeps** [comment]
@TeXhackse this would be a rather natural extension and consistent with the other templates, no? I think it makes sense!

**Comment by TeXhackse** [comment]
@schoeps we don't have a mechanism to disable the logo for any template up to now. We can add this of course.  Currently it is consistent with the others. 

Thee other templates only have a mechanism to change the logo position.

**Comment by schoeps** [comment]
@TeXhackse dann habe ich das wohl verwechselt. Beim Brief (?) gibt es die Option, aber nur für die Folgeseiten!? Wir haben schon jetzt zu viele Optionen, man kommt durcheinander :)
Wenn es die Option noch nicht woanders gibt, dann ändere ich meine Meinung: der Workaround mit (transparenten) Bild ist ja auch machbar; ohne Logo ist es eben auch nicht mehr CI.

**Comment by TeXhackse** [comment]
> ohne Logo ist es eben auch nicht mehr CI.

@schoeps deswegen gibts die option woanders nicht. Hier gibt es bisher die Option die Hintergrundfarbe rauszunehmen, dann steht das Logo frei und frisst weniger Toner. 

Allerdings bleibt der Platz reserviert, auch wenn man ein weißes Bild einfügt. Von daher kann ich den wunsch schon nachvollziehen. Hatte aber genau deswegen gesagt, dass ich das nicht entscheiden werde.

**Comment by schoeps** [comment]
@marklaz Meinung?

**Comment by marklaz** [comment]
Ich kann das Problem sehen, dass bei zwei z.B. nur zwei Aufgabenseiten relativ viel Raum für den Header verlorengeht.
Wie aufwendig wäre es daher, eine Art “SmallHeader” als Option anzubieten, die nicht so hoch ausfällt?

Kleinere Header-Schriften, kleineres Logo, kleinere Abstände um Logo herum etc. Damit könnte man auf weniger als die halbe Höhe im Vergleich zu jetzt kommen, wo das Ganze tatsächlich relativ luftig ist. Diese Option sähe ich aktuell jedoch ausschließlich bei TUDaExercises.

Eine explizite Option zum Logo-Weglassen würde ich nicht einführen, da es im Rahmen des CD hierfür keine Rechtfertigung gibt. Mit der vorstehend genannten Option fiele die entsprechende Notwendigkeit ohnehin weg. Der Ersatz durch Leerraum funktioniert ja bereits.

Meinungen?

**Comment by TeXhackse** [comment]
> Wie aufwendig wäre es daher, eine Art “SmallHeader” als Option anzubieten, die nicht so hoch ausfällt?

`colorback=false` ist etwas kleiner. Aber wir haben auch den Mechanismus für die kleineren Titel bei TUDaPub, der passt analog da rein. Die Logogrößen passen wir da aber bisher nicht an. Wobei das eine Zeile mehr wäre ;-) Also hält sich der Aufwand sehr in Grenzen.

**Comment by schoeps** [comment]
> `colorback=false` ist etwas kleiner. Aber wir haben auch den Mechanismus für die kleineren Titel bei TUDaPub, der passt analog da rein. Die Logogrößen passen wir da aber bisher nicht an. Wobei das eine Zeile mehr wäre ;-) Also hält sich der Aufwand sehr in Grenzen.

Ich wäre dann dafür nur den Mechanismus für kleinere Header aus TUDaPub zu benutzen, aber das Logo nicht zu skalieren (ich finde wir sollten die Anzahl der Varianten begrenzen).

**Comment by marklaz** [comment]
Wenn da eine gewisse Platzersparnis im Headerbereich realisiert wird, passt das für mich. Eine neue Option muss eigens deswegen nicht geschaffen werden.

**Comment by TeXhackse** [comment]
Gut, dann mach ich das so.

**Comment by TeXhackse** [comment]
![image](https://user-images.githubusercontent.com/10723888/80414608-97877200-88d1-11ea-8d43-1f9a6d290771.png)

@schoeps @marklaz so vorschlag wäre dann für `title=small` folgedes größenverhältnis.

mit `colorback=true`:

![image](https://user-images.githubusercontent.com/10723888/80414761-d1587880-88d1-11ea-8e2a-bf027562d5cd.png)

wenn euch das so passt, dann merge ich das rüber.

**Comment by marklaz** [comment]
Passt für mich.
Welches Höhenverhältnis ergibt sich ungefähr im Vergleich zum normalen Header, 2:3?

**Comment by TeXhackse** [comment]
2:3 für die Mindesthöhe, da diese durch das Spacing um 1/2 Logohöhe reduziert wird. Der Rest hängt vom Titel ab.

**Comment by TeXhackse** [comment]
Ich bin gerade noch wegen #173 mit dem autor am diskutieren, warte daher den release upload noch ab, bis da absehbar ist, was raus kommt.
