### ISSUE TITLE
Class not found on Mac (tudexercise which is no longer supported)

### ISSUE THREAD

**Issue by marcos452** [tudace/tuda_latex_templates#181]
![image](https://user-images.githubusercontent.com/63551534/80377772-fc27da00-889b-11ea-8259-5c1da48940dd.png)
I have download the tuda_templates and try "tlmgr install tuda-ci"  Then I try to copy the file tuda_templates into /library/texfm.

**Comment by TeXhackse** [comment]
well, you are trying to load tudexercise. The class is called tudaexercise.

**Comment by marcos452** [comment]
@TeXhackse hallo, but I use the"tlmgr install tuda-ci" , it still have error.tlmgr: package repository http://ftp.uni-erlangen.de/ctan/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: tuda-ci

**Comment by marcos452** [comment]
@TeXhackse hallo, when I ''m trying to load tudexercise in Windows, must be download tuda_templates. But in macos I don't konw why Class not found

**Comment by TeXhackse** [comment]
@marcos452 
> tlmgr install: package already present: tuda-ci
says it's already installed. 

are you trying to load tudexercise or tudaexercise? Since in the upper message there was just tudexercise requested.

**Comment by marcos452** [comment]
@TeXhackse yes, I use the template from Professor, when l load the template with texshop , then error occurs "tederexcise.cls not found"
![image](https://user-images.githubusercontent.com/63551534/80403671-428f3000-88c0-11ea-9862-543c8302fdeb.png)
this is code

**Comment by TeXhackse** [comment]
@marcos452 the template is using `tudexercise` isntead of `tudaexercise` this is some outdated class which was not provided by us and is no longer maintained. 

There is an example file to show the compatibility mode of tudaexercise to make it easier to use the new class. But you should switch to tudaexercise. The current release of it can be found here: https://github.com/tudace/tuda_latex_templates/releases/download/v2.10/Examples-TUDexercise-compat.tex

I hope this helps.

Beside this you should update the preamble. latin9 as encoding should not be used anymore.
