### ISSUE TITLE
! Package xcolor Error: No driver specified.

### ISSUE THREAD

**Issue by jacarvalho** [tudace/tuda_latex_templates#182]
Hi, 
I have just installed the new texlive2020 distribution and I'm trying to make the basic example DEMO-TUDaExercise.tex to work, but I'm getting the following error after running `pdflatex DEMO-TUDaExercise.tex` (here just the last lines of the log)

```bash
(/usr/local/texlive/2020/texmf-dist/tex/latex/tuda-ci/tudarules.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/tuda-ci/tudacolors.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2020/texmf-dist/doc/generic/pgf/version-for-dvisvgm/en/colo
r.cfg)

! Package xcolor Error: No driver specified.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.223      eg: \protect\ExecuteOptions{dvips}}

? x
No pages of output.
Transcript written on DEMO-TUDaExercise.log.
```

The texlive installation works, as I get the expected result after `pdflatex small2e`. Also, in another computer everything worked as expected with texlive2019 (installed 2 months ago).

Any idea why this error is popping up?
Thanks!

**Comment by TeXhackse** [comment]
Usually the autodetection for the driver should work corrently. For my systems (TL2017 to TL2020) this works fine.

Could you add \listfiles to the first line of the document and give us a complete log file? Then I might be able to guess better.

**Comment by jacarvalho** [comment]
Here is the log file. I ran `pdflatex DEMO-TUDaExercise.tex` and everytime the compiler stopped I just pressed ENTER.

[DEMO-TUDaExercise.log](https://github.com/tudace/tuda_latex_templates/files/4541740/DEMO-TUDaExercise.log)

**Comment by TeXhackse** [comment]
@jacarvalho I can not reconstruct the error. But I found the following in your log file:
```
(/usr/local/texlive/2020/texmf-dist/tex/latex-dev/graphics/graphicx.sty
Package: graphicx 2019/11/30 v1.2a Enhanced LaTeX Graphics (DPC,SPQR)
(/usr/local/texlive/2020/texmf-dist/tex/latex-dev/graphics/graphics.sty
Package: graphics 2019/11/30 v1.4a Standard LaTeX Graphics (DPC,SPQR)
(/usr/local/texlive/2020/texmf-dist/tex/latex-dev/graphics/trig.sty
```
For some reason your graphics bundle is loaded from the latex-dev-tree, while the others are loaded from the latex-tree. Could it be that there has been some error during the installation?

Beside that the log seems to show that you run the compiler inside /usr/local/texlive/….
Please ensure that the directory you use is writeable.
I hope this helps.

**Comment by TeXhackse** [comment]
@jacarvalho Did that information help?

**Comment by jacarvalho** [comment]
Hi @TeXhackse it is working now. 
The solution was just to install it **not** under `/usr/local/texlive/`, but in ` $HOME/texlive/`.
Thanks a lot!
