### ISSUE TITLE
Where is the acknowledgement section for thesis template?

### ISSUE THREAD

**Issue by lucasribeiroufrj** [tudace/tuda_latex_templates#183]
Where is the acknowledgement section for thesis template?

**Comment by schoeps** [comment]
There is no official rule in the design guide on acknowledgements, so it's you choice (but you should probably ask your supervisor if appropriate). My group uses a non-numbered chapter `\chapter*{Acknowledgments}`.

**Comment by lucasribeiroufrj** [comment]
I have never seen a single thesis without an acknowledgments section, but dozens and dozens with it.
Anyway, thank you for your suggestion and response.

**Comment by schoeps** [comment]
Of course, most theses have such a section. However, it's your choice how you implement this (e.g. at the beginning or the end....). The design guide of TU Darmstadt does not make any statements about this and our latex templates aim to be minimal in the sense that they only implement the necessary features.
