### ISSUE TITLE
How to get rid of skips before new section/subsection

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#186]
In tudapub there's a big skip in before new sections. I tried the following to get rid of these, but it didn't work...

\usepackage{blindtext}	

\RedeclareSectionCommand[
beforeskip=-\baselineskip,
afterskip=.5\baselineskip]{section}

![tex](https://user-images.githubusercontent.com/62886054/81707215-c4f72280-9470-11ea-8df4-ccfe39807204.PNG)

Is there a way to get the headline closer to the identline?

**Comment by TeXhackse** [comment]
Are you sure it's the section command and you don't want to reduce the top margin?

**Comment by TeXhackse** [comment]
I close this, because I don't understand the issue and we did not receive an answer to the question.
