### ISSUE TITLE
Add advisor and on title page 

### ISSUE THREAD

**Issue by agutte** [tudace/tuda_latex_templates#187]
I'm writing an external master thesis at a company and have therefore not only 1st and 2nd reviewer at university, but also an advisor at the company who shall be named on the title page and the page after.

Is there a way to add my advisor without naming him as reviewer but simple advisor instead?
I tried it with \titleaddendum but this makes him not appear on the second page. 

Also, Is there a way to suppress the generation of the Eigenständigkeitserklärung? Instead, I want to inlcude the scanned Corona special version due to the current circumstances

**Comment by TeXhackse** [comment]
There is mechanism for different types of the `\reviewer` up to now. .The `\titleaddendum` + the title boxes should be used for this. If you want to place it directly below the reviewer and see it on the second page, it might be an option to abuse the `\publisher`. This field is predefined with `Darmstadt` so you might insert something like 
```
\publishers{Supervisor: XXXX\\Darmstadt}
```

The Affidavit („Eigenständigkeitserklärung“) is generated by `\affidavit`. So it won't be included, if you remove this. For including full PDF pages I'd recommend the pdfpages package. (http://mirrors.ctan.org/macros/latex/contrib/pdfpages/pdfpages.pdf)

**Comment by agutte** [comment]
Great, problem solved. Thanks!
