### ISSUE TITLE
Italics in figure caption

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#192]
Hello,

I need to use italics in a figure caption (I am referring to a physical quantity and this must be in italics, independently of the document design) but it does not seem to work.

This is how I introduced my figure with its caption:

```
\begin{figure}[tb]
	\begin{center}
		\input{My_figure}
	\end{center}
	\caption{\textit{P}-\textit{E} hysteresis loop}
\end{figure}
```

It should give: "Figure 2.4: _P_-_E_ hysteresis loop" but gives: "Figure 2.4: P-E hysteresis loop".
Is there a solution for this?

Thank you!
![Sans titre](https://user-images.githubusercontent.com/54108560/83498690-862b1a00-a4bc-11ea-8e45-5a4e43ecc0f2.png)

**Comment by schoeps** [comment]
Duplicate https://github.com/tudace/tuda_latex_templates/issues/143. However, in your case `$P-E$` would be the more consistent option, right? That should work because you switch to the math font.

**Comment by JuLateX** [comment]
Thank you, I missed this when looking for an answer.
I am not so sure the math font is the logical choice here, but it should do the job.

**Comment by schoeps** [comment]
I guess that you use the same "P" and "E" in formulas, right? Then I would surely use the same style for labeling axes and eventually also in the caption.
