### ISSUE TITLE
Titelpage, 2nd Titelpage, & Creative Commons License Page: Conformity with coporate design

### ISSUE THREAD

**Issue by MillieIS** [tudace/tuda_latex_templates#193]
I have a few questions about the titlepages in this new LaTeX format. I am referencing the TUDaPhD LaTeX Dissertation Template. 

1. The new title page includes a lot more information than before. Originally, it was just title (english/german), author, Dissertation D17, and Darmstadt 20XX. Now, it includes the written text "Zur Erlangug des akademischen.... von Name aus Geburtsort", dates of submission and exam, reviewers/examiners, and Darmstadt -D17. Is this correct? Seems to be when I look at the template, but looks much busier than the old template. If this is corporate design, however, I concede to the design masters.

2. The second title page (is there a proper name for this? Not the cover, with the colored square depending on department, this second page, where, for type=dr, it gives you "vorgelegte Dissertation" and with type=drfinal it gives you "eingreichte Dissertation") used to be formatted a little bit nicer in the old template (see attached image: 2ndtitlepage_old). It was centered, the title was larger font than the authors, and the creative commons license was on a separate page. In this new, official template, this second title page is left-justified, all the same font size, and the creative commons license seems to be combined on this page (without the CC logo, see attached image: 2ndtitelpage_new). Is this an error on my end or is this the way it is supposed to be? 

3. In addition, I have my main babel language set to english with ngerman as an additional package. When using main=english, regardless of what I set the type to in the \documentclass (i.e. type=dr or type=drfinal) the output on this 2nd title page is just "doctoral thesis" rather than "eingreichte" or "vorgelegte" Dissertation. Should I just set my main babel language to ngerman to correct for this? 

Thanks for all of your help!

![2ndtitlepage_old](https://user-images.githubusercontent.com/25899279/83656888-6846dd80-a5c0-11ea-89ab-344efccdf55f.jpg)

![2ndtitlepage_new](https://user-images.githubusercontent.com/25899279/83659277-9da0fa80-a5c3-11ea-88e1-b9bc4b3baa53.jpg)

**Comment by schoeps** [comment]
**Questions 1&2**: If you are unsure about your pdf, the latex package ships with examples, e.g. http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/doc/DEMO-TUDaPhD.pdf for the PhD thesis. You can also check how other thesis look like, e.g. http://tubiblio.ulb.tu-darmstadt.de/view/type/thesis.date.html#group_2020. This gives you an idea what is possible nad what not.

We have consulted the ULB regarding the latex template of the PhD thesis, so this this design will be surely accepted for online publication at tubiblio. I am sure that this is not the only possible implementation, so feel free to modify the current one (or even use the old one). However, we cannot guarantee acceptance by ULB in this case. Please understand that we cannot discuss particular design choices here.

If you agree, then please close this issue and open a new one for your **question 3**. Ideally with a minimal working example that demonstrates the problem (Indeed, there might be something fishy here, also in German it should be "eingereichte" and "genehmigte" if I am not mistaken).

**Comment by MillieIS** [comment]
Yes, I had seen the examples, and those submitted to ULB are quite diverse, so I just wanted to be on the safe side. I will use the standard formatting and open a new issue for the 3rd item as suggested. Thanks!
