### ISSUE TITLE
Exercise: credit/point position in task/subtask

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#195]
Is it possible to change the position of credit/point in the task/subtask environment for example, on the right side of the environment? 
#176

**Comment by TeXhackse** [comment]
Just to understand if correctly:
You want the credit to be displayed raggedright?

**Comment by TeXhackse** [comment]
@Zentox I'd be glad if you could answer my question. Otherwise I will close this at the end of the week.

**Comment by Zentox** [comment]
Yes thanks. I am sorry I was busy.

**Comment by schoeps** [comment]
@TeXhackse @marklaz I think that we should create a FAQ page with question/answers like this, e.g. using the wiki functionality. However, let's discuss this after the famous 3.0 release....
