### ISSUE TITLE
BCOR for titlefront page

### ISSUE THREAD

**Issue by tcd2** [tudace/tuda_latex_templates#196]
Hello =)
I changed the margin for the document replacing
`		%\dim_gset:Nn \g_TUDa_bottomMargin_dim {20mm}`
		`%\dim_gset:Nn \g_TUDa_outerMargin_dim {15mm}`
		`%\dim_gset_eq:NN \g_TUDa_innerMargin_dim \g_TUDa_outerMargin_dim`
		`%\dim_gset_eq:NN \g_TUDa_topMargin_dim \g_TUDa_outerMargin_dim`

by
`		% Änderung von Muetschard 20200609 für GLR Vorlage`
`		\dim_gset:Nn \g_TUDa_bottomMargin_dim {20mm}`
	`	\dim_gset:Nn \g_TUDa_outerMargin_dim {15mm}`
		`\dim_gset:Nn \g_TUDa_innerMargin_dim {20mm}`
		`\dim_gset:Nn \g_TUDa_topMargin_dim {15mm}`
in the tudapub.cls-document.

I also managed to set the additional margin for the whole document with BCOR with the following settings. 
 `\documentclass[`
	`ngerman,`
	`ruledheaders	=all,		`
	`class			=report,		`	
	`thesis			={type=Masterthesis},	`
	`accentcolor		=1c,				`
	`custommargins	=false,			`
	`marginpar		=false,	`
	`BCOR			=15mm, 	`
	`parskip			=half-,	`
	`fontsize		=11pt,	`
`%	twocolumn 		=true, 	`
	`logo			=body,  `
	`twoside 		=false,	`
`]{tudapub}`

However, the margin on the front page doesn't adapt to BCOR value. Is there a possibility to apply the BCOR setting for the front page?

Thank you in advance for your help! =)

**Comment by TeXhackse** [comment]
I am sorry for the late reply. I thought I'd have already answered and just realized, that I didn't :/

We are using the KOMA-Script option `titlepage=firstiscover` This is why we differ from the other margins. Currently this doesn't adapt te BCOR. Which is not really intended. I will try to find time to fix this asap. It it's urgent please let me know, and I will try to build a workaround.

**Comment by TeXhackse** [comment]
I have to excuse once again :/ I had a look at the KOMA-Script documentationa and KOMA-Script is intending this. But you can workaround using this redefinition of the leftmargin.

I decided not to change this in general (because this would be incompatible to KOMA) but add an Option to achieve this.
Workaround by adding this before \maketitle

```
\makeatletter
\xdef\coverpageleftmargin{\the\dimexpr\coverpageleftmargin+\the\ta@bcor}
\makeatother
```
