### ISSUE TITLE
PDF/A compatibility

### ISSUE THREAD

**Issue by BlackbirdB51** [tudace/tuda_latex_templates#199]
Validating the output of the tudapub class (for example the DEMO-TUDaPhD.tex example) for pdf/a compatibility an [online tool of the pdf association](https://bfo.com/blog/2017/11/08/verify_pdfa_online/) returns that it does not comply to the standard of pdf/A-2b, because:
"FontWidthsNotConsistent is set, but shouldn't be". An additional tip indicates, that the width of the fonts doesn't match the width specified in the pdf.

**Comment by TeXhackse** [comment]
@BlackbirdB51  Is it possible to add a log file? Because y tests on all my systems now create a valid pdf/A-2b. It seems like there was a bug which has been fixed in the meantime. So I currently cannot reconstruct this, but will pay attention.

The files for the next release will be valid again.
