### ISSUE TITLE
improve documentation on usage of department option

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#2]
`DEMO-TUDaThesis.pdf` tells me i can use a classoption `department=<department shortcut>`, and I understand that this will replace `\institution` in the topmatter (or its deprecated alternative `\department`), however it seems like only when including `\department` the document builds.

Document is `thesis={type=master}` built on archlinux with `pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux)`

**Comment by TeXhackse** [comment]
oh the `department `option currently only works as thesis option, so it would work to write

`thesis={type=master,department=...}`

I will think about either adding a passing mechanism or improve the documentation

**Comment by TeXhackse** [comment]
I improved the passing mechanism. Think this makes the option handling easier
