### ISSUE TITLE
in  tuda-ci_ctan_v1.01.zip ist das TUDA Logo enthalten

### ISSUE THREAD

**Issue by iibPScheich** [tudace/tuda_latex_templates#20]
Hallo,
in der Datei  tuda-ci_ctan_v1.01.zip aus dem Release TUDa-CI Version 1.01 liegt unter /tuda-ci/tex/ die Datei tuda_logo.pdf.

Passt das mit "Die verwendeten Logos sind nicht Bestandteil dieses Bundles und können von Mitgliedern der TU Darmstadt über das interne Netzwerk heruntergeladen werden." zusammen?

**Comment by TeXhackse** [comment]
Nein, danke für den Hinweis, das sollte nicht der Fall sein. Da ist was schief gelaufen. das Wird umgehend korrigiert. 

Entsprechende Anfragen sind raus.
