### ISSUE TITLE
White line on title-page with `tudapub` class

### ISSUE THREAD

**Issue by davidgengenbach** [tudace/tuda_latex_templates#201]
See https://www.overleaf.com/read/vbfzsfzkrvwq

When zooming in, there is a white line (above the title and logo):
![Screenshot_2020-06-24_14-19-18](https://user-images.githubusercontent.com/2621491/85555060-cdbd4580-b625-11ea-8e8c-247ad27a893d.png)

The same problem can be seen in `docs/DEMO-TUDaReport.pdf` bundled with the release zip.

I do not think it's an artifact of the PDF viewer as I have tried multiple programs.

## Context

Template version: [v2.11](https://github.com/tudace/tuda_latex_templates/releases/tag/v2.11)

**Comment by TeXhackse** [comment]
Sorry for the late answer. I checked this. And I cannot receive this artifact in any viewer. Can you please add a log file? It's true, that there are two boxes but they should not add a margin in between. It might be an antialiasing artifact but as I told I cannot reconstruct.

**Comment by davidgengenbach** [comment]
Very strange. I checked again with more document viewers:
**Working**: Chrome, Okular
**Not working**: Evince, Firefox, GIMP, Xournal

Maybe they use the same rendering engine?

**Comment by TeXhackse** [comment]
Well, it might also depend on the display driver and your display resolution.  But there is no white line ;-) This actually happens sometimes if you have two colored boxes without a overlap. We could add an overlap but this might lead to different issues.

**Comment by davidgengenbach** [comment]
> Well, it might also depend on the display driver and your display resolution. But there is no white line ;-) This actually happens sometimes if you have two colored boxes without a overlap. We could add an overlap but this might lead to different issues.

It works in Chrome and Okular - consistently.
And it does not work in the other viewers - also consistently.

So I do not think the display driver, resolution or zoom level or something like that are the culprit?

Strange...

**Comment by TeXhackse** [comment]
Since I don't get it in Evince, Firefox, GIMP, Adobe Acrobat (Windows & Wine), Inkscape, Okular, Chrome, MasterPDFeditor It seems to be a system issue (Xournal I didn't test). There is no white pixel, but the Poppler library sometimes has version dependent artefacts.
