### ISSUE TITLE
Using TUDaExercise for exams?

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#203]
I would like to use the TUDa exercise class for creating an exam. I thus need to build a title page with general announcements, a table for the points and so on. Is this possible with TUDaExercise or is there another class of the package that is suited better for this?

**Comment by TeXhackse** [comment]
Of course this is possible. You can simply add custom material right after \maketitle and before the first task. 

If this does not suit your needs I can also help out to adapt that.

What's not included up to now is a reference of the credit mechanism. But I have build a similar mechanism for some other university which we could adapt (so it's a 10 minute task). I can try to find time to look this up in the evening. This might be a useful enhancement.

**Comment by AlexVHopp** [comment]
Ok, I thought that there might be some macros for creating a table for the credits, inserting the formal things like duration and so on. I will probably just design something myself, but thank you for offering your help.

Regarding the credits: I always just included the credits in the name of the task (so I used `\begin{task}{The best task\hfill 42 points}`. That always gave a warning but worked nevertheless and I will also use this for the exam as I want to have it in the same style. But again thank you for your offer!
