### ISSUE TITLE
Titlepage: Cooperation with another university

### ISSUE THREAD

**Issue by JuliusAurelius** [tudace/tuda_latex_templates#207]
Hey, I am currently writing my master thesis in cooperation with the TU Delft, therefore their Logo should be included as well on the Titlepage. Is there an easy way to include the logo underneath the TU Darmstadt Logo?
I tried replacing `tuda_logo.pdf` with an altered version, but compiling did not change the title page.

Also, is there a way to change "1. Review:__, 2. Review: ____" to "1. Supervisor:_____" etc.?

**Comment by schoeps** [comment]
1. You can easily add extra logos. This is explained in the tudathesis manual an page 8 (`\titleimage`). Please read the manual before asking.

2. I am not sure if there is an easier way to do this but this code  (to be put in the preamble) should do what you want
```
\makeatletter
\ExplSyntaxOn
\TUDa_declare_caption:Nnn \TUDa@reviewname {Supervisor}{Supervisor}
\ExplSyntaxOff
\makeatother
```

**Comment by JuliusAurelius** [comment]
First of all, thanks for the help!
The Logo is inserted but not fitting to the size of the other two boxes (See pictures).
I have tried \addTitleBoxLogo[width=0.4\textwidth]{picture.pdf} but that gives me errors ($ missing)
![Bildschirmfoto 2020-07-26 um 17 47 50](https://user-images.githubusercontent.com/26138628/88483475-7bdf4680-cf68-11ea-89f6-01d6d2518ecf.png)
![Bildschirmfoto 2020-07-26 um 17 49 28](https://user-images.githubusercontent.com/26138628/88483477-7e41a080-cf68-11ea-8c0a-df2512299586.png)

**Comment by schoeps** [comment]
See here: https://github.com/tudace/tuda_latex_templates/blob/fb031257c850fcbc5d036385d49e26c4a64c523a/example/DEMO-TUDaPub.tex#L45
