### ISSUE TITLE
File 'URspecialopts.sty' not found

### ISSUE THREAD

**Issue by CarstenWandschura** [tudace/tuda_latex_templates#21]
Hi,

I have some troubles with compiling the TUDaThesis file on Linux. The .zip file is extracted to every folder possible in /usr/share/...
The error comes from tudapub.cls file which is contained in texmf/tex (or Tex?)/latex/tuda-ci

Errortext:
"File 'URspecialopts.sty' not found. \Define@specialopt@Module"

Works perfectly on Windows 10.
Thanks for your help.

**Comment by CarstenWandschura** [comment]
FYI: The TU Design from the FKP page worked perfectly on all systems.

**Comment by marklaz** [comment]
LaTeX package URcls is required. 

Using (minimal) LaTeX which comes with Linux distributions does not resolve that dependency automatically. You may need to install additional Linux-LaTeX-packages from your Linux distro which contain URcls.
For (complete) TeXlive in Linux it should work out of the box.

I will try to add a list of package dependencies on our website.

**Comment by TeXhackse** [comment]
I added an extra not on that to the README. Though it might be helpfull it's not typical to publish dependency lists as long as all packages are part of TeX Live and MikTeX. Whenever you get such a message in any other circumstances again, you could lookup the file on [CTANs filesearch](https://ctan.org/search?ext=false&FILES=on).
