### ISSUE TITLE
How to change the license in "tudapub"?

### ISSUE THREAD

**Issue by geisenhofer** [tudace/tuda_latex_templates#210]
Hi all,

how do you edit the license on the second page, e.g., the Creative Commons license?

Thanks for your replies!

Best regards,
Markus

**Comment by schoeps** [comment]
I don't want to be too direct but I have to ask... did you read the documentation? https://github.com/tudace/tuda_latex_templates/blob/fb031257c850fcbc5d036385d49e26c4a64c523a/example/DEMO-TUDaPhD.tex#L207

for older releases, see also #87. I hope that helps.

**Comment by TeXhackse** [comment]
Since we did not receive any further information I guess this is solved.
