### ISSUE TITLE
Farbbalken im PMV Stil

### ISSUE THREAD

**Issue by RosOth** [tudace/tuda_latex_templates#211]
Ist es möglich den zweifarbigen Balken des PMVs in das Template einzupflegen?
Als Beispiel habe ich ihn mal eingefügt.
![image](https://user-images.githubusercontent.com/49841472/90236945-c21b1d80-de23-11ea-990e-7cde48a51cf2.png)

**Comment by schoeps** [comment]
@RosOth habt ihr schon Latexcode dafür, den ihr nur einbringen wollt, oder muss das noch entwickelt werden. Das klingt ja nicht so schwierig... an welcher Stelle änder änder sich die Farbe? goldener Schnitt?

Man müsste aber (a) klären, ob das dem TU-Styleguide entspricht und (b) ob das offizielle TU-Template fachgebietsspezifische Modifikationen berücksichtigen soll. Ich sehe das bei >200 Fachgebieten (FGs) skeptisch.

Ich würde empfehlen, dass wir (@TeXhackse?) FGs unterstützen, dass sie eigene Vorlagen anbieten.

**Comment by RosOth** [comment]
Bisher habe ich in der "alten" "Vorlage" der Physiker folgendes im Header ergänzt und dann sah es gut aus (funktioniert jetzt nicht mehr):

\usepackage{fancyhdr}
\usepackage{color} %um PMV-Blau und PMV-Rot für die Identitätsleiste zu definieren
\definecolor{pmvblau}{RGB}{38,53,114}
\definecolor{pmvrot}{RGB}{156,28,38}
\fancypagestyle{plain}{%dieser ganze folgende Teil sorgt dafür, dass der TU-Balken durch den PMV-Balken ersetzt wird
	\fancyhf{}
	\if@reversemargin
	\fancyhfoffset[LO]{\marginparwidth + \marginparsep}
	\fancyhfoffset[RO]{0pt}
	\else
	\fancyhfoffset[LO]{0pt}
	\fancyhfoffset[RO]{\marginparwidth + \marginparsep}
	\fi
	\if@twoside
	\if@reversemargin
	\fancyhfoffset[LE]{0pt}
	\fancyhfoffset[RE]{\marginparwidth + \marginparsep}
	\else
	\fancyhfoffset[LE]{\marginparwidth + \marginparsep}
	\fancyhfoffset[RE]{0pt}
	\fi
	\fi
	\fancyhead[C]{\color{pmvblau}\rule{0.666\headwidth}{4mm}\color{pmvrot}\rule{0.333\headwidth}{4mm}\\\vspace*{-3.2mm}\color{black}\rule{\headwidth}{1.2pt}}
	\fancyfoot[C]{\tudrule[\headwidth]\footerfont\strut\\\nouppercase\mycentermark}
	\fancyfoot[LE,RO]{\footerfont\strut\\\thepage}
	\fancyfoot[RE]{\footerfont\strut\\\myleftmark}
	\fancyfoot[LO]{\footerfont\strut\\\myrightmark}
}
\fancypagestyle{empty}{%
	\fancyhf{}
	\if@reversemargin
	\fancyhfoffset[LO]{\marginparwidth + \marginparsep}%
	\fancyhfoffset[RO]{0pt}%
	\else
	\fancyhfoffset[LO]{0pt}%
	\fancyhfoffset[RO]{\marginparwidth + \marginparsep}%
	\fi
	\if@twoside
	\if@reversemargin
	\fancyhfoffset[LE]{0pt}%
	\fancyhfoffset[RE]{\marginparwidth + \marginparsep}%
	\else
	\fancyhfoffset[LE]{\marginparwidth + \marginparsep}%
	\fancyhfoffset[RE]{0pt}%
	\fi
	\fi
	\fancyhead[C]{\color{pmvblau}\rule{0.666\headwidth}{4mm}\color{pmvrot}\rule{0.333\headwidth}{4mm}\\\vspace*{-3.2mm}\color{black}\rule{\headwidth}{1.2pt}}
	\fancyfoot[C]{\tudrule[\headwidth]} 
}


Farbteilung ist 2/3, 1/3. Farbcodes sind aus obigem Code ersichtlich.
Gerne nehme ich die Unterstützung an, ein entsprechendes Template für das FG zu erstellen!

**Comment by TeXhackse** [comment]
@RosOth Ich hab mir mal erlaubt, das als Code einzubauen.

Also grundsätzlich geht das natürlich, man kann „einfach“ die entsprechende Box tauschen, um das lokal zu ändern.

(Kleine Anmerkung 1/3 zu 2/3 sind aber nicht .666 und .333 ;-)  - SCNR)

Aber unabhängig davon: Ich arbeite derzeit noch an den letzten Dingen des Maschinenbau CDs. Um dann version 3.0 vorzubereiten. Das ist aber ein extra Auftrag. Dabei ging es aber um eine Umarbeitung aller Templates. Grundsätzlich ist sowas also möglich, aber wie @schoeps  schon sagte muss dann von entschieden werden, ob das als Option in das template einfließt, wie `mecheng` oder eben nicht. Und falls ich diesbezüglich etwas tun soll benötige ich eine entsprechnenden Auftrag, da ich nicht Teil der TUDa bin, sondern eben als Externe damit beauftragt. Mehr Details gerne per Email.

**Comment by RosOth** [comment]
Bei der Vorlage würde es sich ja nicht direkt um eine FG-spezifische, sondern mehr um eine Studiengang-spezifische (Paper Science and Technology) handeln. 
Wem muss ich Bescheid geben den Auftrag zu geben? Dem Prof. selbst?

**Comment by TeXhackse** [comment]
@schoeps @RosOth hat mir jetzt ne mail geschickt, und ich hab kurz dort erklärt, weil diese Diskussion ja nicht wirklich was mit dem eigentlichen Thema zu hat. Wenn ich weiß was genau möglich ist, dann können wir gucken, ob das sinnvoll ist das reinzunehmen.
