### ISSUE TITLE
content overlaps with titlehead in twocolumn

### ISSUE THREAD

**Issue by towadroid** [tudace/tuda_latex_templates#212]
When using the tudapub class with the options `type=intern` and `twocolumn` the content overlaps with the titlehead. I am not sure if this is a bug or I missed something.

MWE:
```
\documentclass[
	type=intern,
	marginpar=false,
	twocolumn,
]{tudapub}

\usepackage{lipsum}

\begin{document}

\title{MWE}

\maketitle
\lipsum[1-7]

\end{document}
```

**Comment by TeXhackse** [comment]
IC.

The workaround would be to not use the twocolumn option but 
```
\twocolumn[\maketitle]
```

This should help. I will add this on the Todo list and hopefully maage bevor 3.0.
