### ISSUE TITLE
Marginpar und TU-Design

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#215]
Ich würde gerne den Inhalt von `marginpar` ausserhalb des Bereichs, der durch die horizontalen TUDa-Linien beschrieben wird anzeigen. Ich hätte erwartet, dass das mit einer Kombination von `includemp` und/oder `ignoremp`gehen müsste, aber ich war nicht erfolgreich. Kann jemand helfen? Danke.
  
```
\documentclass[
	pdfa=false,
	class=report,
	custommargins=geometry,
	fontsize=11pt,
]{tudapub}
\geometry{top=2cm, right=2.5cm, bottom=2cm, left=2.5cm, marginparwidth=2cm,marginparsep=0.5cm}
\begin{document}
text\marginpar{margin}
\end{document}
```

**Comment by TeXhackse** [comment]
Wenn ich das richtig verstehe, möchtest du nur den Farbbalken verkürzen? 

Dann müsste das mit 
```
\KOMAoptions{headwidth=text}
``` 
zu lösen sein. Wichtig ist das nach \maketitle zu machen, da das auf die Standardeinstellung zurücksetzt.

**Comment by schoeps** [comment]
Ja, genau das Kommando fehlte mir (und man braucht natürlich auch `footwidth`). Danke!

Hier das komplette Beispiel für die Nachwelt:
```
\documentclass[
	pdfa=false,
	class=report,
	custommargins=geometry,
	fontsize=11pt,
]{tudapub}
\geometry{top=2cm, right=0.5cm, bottom=2cm, left=2.5cm, marginparwidth=1.75cm,marginparsep=0.25cm}
\begin{document}
\KOMAoptions{headwidth=text,footwidth=text}
\noindent text \marginpar{x}
\end{document}
```

**Comment by schoeps** [comment]
@TeXhackse  Leider Kommando zurück... das klappt nicht, wenn man `\chapter` benutzt. Noch eine Idee?

```
\documentclass[pdfa=false,class=report,custommargins=geometry,fontsize=11pt]{tudapub}
\geometry{top=2cm,right=0.5cm,bottom=2cm,left=2.5cm,marginparwidth=1.75cm,marginparsep=0.25cm}
\begin{document}
\KOMAoptions{headwidth=text,footwidth=text}
\chapter{x}
\noindent text \marginpar{x}
\end{document}
``` 

![Bildschirmfoto 2020-08-24 um 15 35 02](https://user-images.githubusercontent.com/868081/91050736-63258780-e61f-11ea-8755-1de1b0831197.png)

**Comment by TeXhackse** [comment]
Muss ich mir angucken, hatte nicht mit der Kombination aus Geometry gerechnet, das verändert dann quasi alles. 

Allgemein: Ich weiß nicht inwieweit es sinnvoll ist, solche Abweichungsbeispiele hier mit zu sammeln … Weil das dann genau dem Grundgedanken eines Corporate Design wiederspricht und eure Regeln da ja eigentlich strikt wären. (Die Word-Tempaltes halten sich auch nicht dran … )aber ich hab da immer ein komisches Gefühl
