### ISSUE TITLE
Missing translation IST

### ISSUE THREAD

**Issue by fprott** [tudace/tuda_latex_templates#216]
Hello,

Apparently there is a translation error in tudathesis.cfg, line 149 (and possible others that I do not know). 
The department IST should have a German name called  "Informationssystemtechnik". For details see [their website](https://www.tu-darmstadt.de/studieren/studieninteressierte/studienangebot_studiengaenge/studiengang_178880.de.jsp).

**Comment by TeXhackse** [comment]
Looks like you are right. Although it's not an error, but I simply was not provided with a translation. See the similar ones. Will add this.

**Comment by fprott** [comment]
Sorry  ^^
Didn't want to offend you. Let's just call it a bug.

**Comment by TeXhackse** [comment]
:D Didn't feel offended. Just wanted to tell you, that there might be others missing.
