### ISSUE TITLE
Change font for dedication only

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#22]
Hello,

Is it possible to change the font used in the dedication (to a handwritten font)?

I tried varous methods, including: `\newenvironment{myfont}{\qzc}{\par}` in the declaration and `\begin{myfont}
	Blablabla
\end{myfont}
` where I want to change font locally.

I got the following message 

> Undefined control sequence. \begin{myfont}

I am wondering if there is not some restrictions encoded in the template due to the corporate design.

Thank you

**Comment by TeXhackse** [comment]
This is a general LaTeX question and rather relies below the template.
Anyway:
You can change the font for dedication using the komafont element dedication
```
\setkomafont{dedication}{set all settings for the element here}
\addtokomafon{dedication}{add some settings for the font element}
```
More information on this can be found in the documentation for KOMA-Script.

The Error message might be created to the fact, there is no `\qzc` macro at all. Maybe you wanted to load some font which requires a package?

**Comment by marklaz** [comment]
The font qzcmi is from the TeX-Gyre package, its otf name should be "texgyrechorus".

**Comment by JuLateX** [comment]
Thank you, it worked
