### ISSUE TITLE
Missing Whitespace in Affidavit

### ISSUE THREAD

**Issue by luth1um** [tudace/tuda_latex_templates#220]
Hi,

I just found a typo that was probably introduced in the last update. In `DEMO-TUDaThesis` (and other documents that have an affidavit), there is a whitespace missing at the end of the affidavit between "Darmstadt" and the date. If I understand this correctly, the bug is in line 581 of `tudathesis.cfg` (the whitespace after `#1,` should be replaced by `~`).

**Comment by TeXhackse** [comment]
Thank you. Will be fixed with the update planned for Friday.
