### ISSUE TITLE
Fehlermeldung in v3.01: \ptxcd_setup_solution: already defined.

### ISSUE THREAD

**Issue by miterion** [tudace/tuda_latex_templates#221]
Ich bekomme seit der version 3.01 einen Fehler beim Kompilieren von Dokumenten der `tudaexercise` Klasse:
```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux)
 restricted system commands enabled.
(./abgabe.tex
LaTeX2e <2020-02-02> patch level 5
 L3 programming layer <2020-06-03>
(/usr/share/texmf/tex/latex/tuda-ci/tudaexercise.cls
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def))
Document Class: tudaexercise 2020/09/12 v3.01 Exercise sheets and exams using T
U Darmstadt's Corporate Desing (TUDa-CI)
(/usr/share/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/usr/share/texmf-dist/tex/latex/environ/environ.sty
(/usr/share/texmf-dist/tex/latex/trimspaces/trimspaces.sty))

! LaTeX3 Error: Control sequence \ptxcd_setup_solution: already defined.

For immediate help type H <return>.
 ...

l.212 }
```
Vermutlich wurde das das im Commit 59d8cd30263bfd3efe5dd58e3f93722c97d6af7c passiert ist, da hier `ptxcd_setup_solution` nochmals definiert wird.

**Comment by TeXhackse** [comment]
Jap, das passiert, wenn man nur die halbe Änderung hinzufügt :D 
Anscheinend dachte mein Hirn, dass die Umstellung zu 3.0 zu gut lief. 

Fixe ich sofort und kriegt jetzt dann extra die 3.02.

**Comment by TeXhackse** [comment]
Upload ist erledigt, damit es über die Distributionen kommt dauert es ungefähr einen Tag je nachdem welcher Mirror eingestellt ist. Aber ggf. lässt sich das ja, wie oben schon erwähnt auch lokal umgehen.

**Comment by miterion** [comment]
Vielen Dank und kein Problem, solche Fehler passieren halt mal :). Die neue Version behebt das Problem für mich.

**Comment by TeXhackse** [comment]
Danke.

Mich ärgert es einfach, wenn es so unnötig ist ;-) Aber war ja keine große Sache.
