### ISSUE TITLE
MikTeX still offering 2.11

### ISSUE THREAD

**Issue by geisenhofer** [tudace/tuda_latex_templates#222]
Hi all,

I guess, a lot of you use MiKTeX. I wanted to updated the packages, in order to get the new version of tuda-ci (which should be 3.02). Unfortunately, I did not receive an update for it, so my latest version is still 2.11 (see screenshot). Do you have any idea, how to fix this or what I have to do differently?

Thank you!

Best regards,
Markus

![Unbenannt](https://user-images.githubusercontent.com/29272185/93315498-68838580-f80b-11ea-8c41-fe61bebcf17e.png)

**Comment by TeXhackse** [comment]
Hi Markus,
MikTeX is a bit slower with the updates than TeX Live. (This is one of the reasons, I always prefered TeX Live on every OS.)
As you can see here https://miktex.org/packages it's still only offering the 2.11.

### in case you can't wait

If you rely on the new features I can offer you to install it in the local texmf tree or replace the files manually so it will be overwritten bei miktex as soon as they offer a new version.

You can find out where your files are located by running 
```
kpsewhich tudapub.cls
```

Download the ctan-zip-file of the release (https://github.com/tudace/tuda_latex_templates/releases/tag/v3.02) 
Simply replace the files in the directory and then run a refresh for the fndb in the miktex console to be able to use the additional files.

If you install it to the local texmf tree (as described in the stackexchange-answer) this will not be automatically replaced by the miktex variant as soon as they offer the new version.

**Comment by open711** [comment]
For everyones information: MikTeX now offers v3.03. Thus this issue can be closed.

**Comment by TeXhackse** [comment]
@open711 thank you
