### ISSUE TITLE
Option to enable footsepline in tudaexercise

### ISSUE THREAD

**Issue by long21wt** [tudace/tuda_latex_templates#224]
I noticed that in the `tudaexercise` template. If we compile with the default setting, it lacks a horizontal line above of the page number in comparison to other templates (`tudapub`, word, etc), which already have. Is there a way to enable it in `tex` file or it have to be modified in the `cls` hard code?

**Comment by TeXhackse** [comment]
This one is not missing. The Exercise template never was meant to have one. (Exception is the mecheng mode, which has a special footline).

You can enable it using the KOMA-Script option `footsepline=true` in this case you might want to increase the spacing between the pagenumber & the rule. This can be archieved by 
```
\addtokomafont{pagenumber}{\rule{0pt}{\baselineskip}}
```

I will mark this as a feature request.
