### ISSUE TITLE
Font question: Merging of "f" and "i"

### ISSUE THREAD

**Issue by martin-fzd** [tudace/tuda_latex_templates#226]
I noticed a strange behavior of the font selected for headlines. It causes certain letters to merge into each other. In my case it is "f" and "i" in veri**fi**kation. The dot on the i disappears.
I wonder if this is this acceptable from a typographic point of view?

Can you please take a look at the following heading:
![image](https://user-images.githubusercontent.com/26324188/94029693-5d0cfd00-fdbd-11ea-8522-caa7a7f3807e.png)

I have created a public sharelatex document for verification ;-) of the problem: (see line 186)
https://sharelatex01.ca.hrz.tu-darmstadt.de/9661911811vqfthkhbxqbg

**Comment by schoeps** [comment]
>I wonder if this is this acceptable from a typographic point of view?

Please have a look here https://de.wikipedia.org/wiki/Ligatur_(Typografie) or https://en.wikipedia.org/wiki/Orthographic_ligature and then revisit your question :)

**Comment by TeXhackse** [comment]
I'd like to add a note anyway, because this might be interesting, in case you want to disable them. 

In case you want to adjust the Ligatures globally, have a look at the microtype package (pdflatex) or fontspec (lualatex/xelatex). 

Locally they can be split using babel.
