### ISSUE TITLE
Check for solution=true / Provide solution environment without header

### ISSUE THREAD

**Issue by eknoes** [tudace/tuda_latex_templates#227]
We are afraid of accidentally uploading the solution sheets of our exercises and like to implement something in the sheet header or similar that makes it more obvious, that the document was built with `solution=true` argument.

As far as I know [we cannot check in the document if the option](https://tex.stackexchange.com/questions/3089/how-do-i-conditionally-execute-something-based-on-a-documentclass-option) `solution=true` is set. It would be nice if you could provide some conditional or maybe a `solution*` environment which simply does not print the solution header.

**Comment by TeXhackse** [comment]
Of course you can check the option, but the mechanism is different from the plain TeX one. 
The Boolean saving the value is the expl3-variable `\l_ptxcd_ex_solution_bool`. In  Expl3-Syntax you could be able to check this without any difficulty. 

### current possibilites

If you want to define a classical TeX Boolean to be mapping this, you chould do 
```
\ExplSyntaxOn		
\def\ifsolution{
	\if_bool:N \l_ptxcd_ex_solution_bool
}
\ExplSyntaxOff
```
Then you could use
```
\ifsolution
solution is true
\else
solution is false
\fi
```
### Feature request
I am not sure which variant is easier. So a boolean or an environment. Probably an enviroment will fit more usecases, 

I will think about this and add that for a future release. If you have any preferences, let me know.

**Comment by eknoes** [comment]
Perfect, I'll try it. Thanks! 

I think a solution environment without a header would work for more use cases, maybe someone would like to have several inline-solutions or so where the header might be not fitting.
