### ISSUE TITLE
Cannot cite webpage with url

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#229]
Hello,

I need to cite a webpage in my thesis but the url or the access date are not printed in the references. This is my BibTeX file, created using the "WebPage" type on Mendeley:

`@misc{EuropeanClimateLawProposal2020,`
`address = {Brussels, Belgium},`
`author = {{European Comission} and {Directorate-General for Climate Action}},`
`booktitle = {\url{https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52020PC0080&from=EN}},`
`title = {{Proposal for a regulation of the European Parliament and of the Council establishing the framework for achieving climate neutrality and amending Regulation (EU) 2018/1999 (European Climate Law) - COM/2020/80 final - 2020/0036 (COD)}},`
`url = {https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52020PC0080&from=EN},`
`urldate = {2020-09-30}`
`}`

And this is the result printing in the references:

![image](https://user-images.githubusercontent.com/54108560/94896273-6406d000-048d-11eb-829d-06248febae64.png)

Does someone know how to solve the problem?

Thank you!

**Comment by TeXhackse** [comment]
This depends on the style you are using. It could be possible to activate the url with setting the style-specific option `url=true`.

If you are using the setup I provided with the demo files, you should change `@misc` to `@online`.
This looks like Mendeley is using the bibtex variants for default, but you should be using biblatex. If I remember correctly there was a possibility to change the settings. `@misc` was the type provided before BibLaTeX introduces `@online` which is more flexible.

**Comment by JuLateX** [comment]
Thanks for your answer! I used the `ieeetr` style. A friend has the same problem with the `unsrt` style.

I tried to change `@misc` to `@online` manually in my `.bib` file but it does not solve the problem.

I had a look at the demo, you used `\printbibliography` which never printed anything for me (whether with this template or with another). I never managed to figure out what was wrong in my setup so I am currently using:

`\bibliographystyle{ieeetr}`
`\renewcommand{\bibname}{References}`
`\bibliography{PhD_thesis}`

**Comment by TeXhackse** [comment]
I See. You are using bibtex and not BibLaTeX. This makes it more complicated. I strongly recommend the usage of BibLaTeX with biber. If I remember correctly (could look up later) you can use the ieee style of BibLaTeX as a replacement. 

Your style simply does not support this. You can modify the style itself but i think the more sustainable way to solve this would be using BibLaTeX which is a lot more configurable.

I can send you an example, as soon as I am back at the office.

**Comment by TeXhackse** [comment]
@JuLateX Since there was no further reaction I will close this. If you need further help, feel free to reopen.
