### ISSUE TITLE
How to remove the dot in chapters/sections/figures/etc.? (4.1.1 instead of 4.1.1.)

### ISSUE THREAD

**Issue by geisenhofer** [tudace/tuda_latex_templates#231]
Hi all,

I noticed that when referring to a section or chapter, I get: In Section 1.1, the mathematical model...
**(no dot at end)**

However, the section itself is labeled with:
1.1. The Mathematical Model
**(dot at the end)**

I tried the classical commands
\renewcommand*{\thechapter}{\arabic{chapter}}
\renewcommand*{\thesection}{\thechapter.\arabic{section}}
which did not change anything.

The solutions on the web did not solve the problem, so I am posting this issue here.

Thank you!

Best regards,
Markus

**Comment by TeXhackse** [comment]
Hi,
this is a KOMA-Script Feature. The enddot is only added in the headline directly. And is set using `\autodot` it is included in the `\sectionformat`/`\chapterformat` macros. (e.g. `\sectionformat` normally expands to `\thesection\autodot\enskip`).

You can disable this by using the `numbers=noenddot` option. tuda-ci will pass this one to the KOMA-Script class.

For more information on that behaviour and the changes when adding an appendix, you might have a look at the KOMA documentation: (option numbers EN: http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguien.pdf#page=99 DE:http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide.pdf#page=104)
I hope this helps.

Marei

**Comment by geisenhofer** [comment]
Thanks, Marei! This worked perfectly!

**Comment by shinomathews** [comment]
How to remove the dotted lines in Listoffigures and Listoftables in Latex?
