### ISSUE TITLE
Referent/Berichterstatter in PhD Thesis

### ISSUE THREAD

**Issue by martin-fzd** [tudace/tuda_latex_templates#232]
https://github.com/tudace/tuda_latex_templates/blob/87facc5f569060988cfd5655c8b634ccbf267ffb/tex/tudathesis.cfg#L83

This issue concerns the designation of the "Reviewer". Currently, this is designated as 1st reviewer / 2nd reviewer etc (i.e. "Gutachten" in German).

There is no central default but for FB 16 (mechanical engineering) the use of "Referent" is very common. (see e.g. in Announcements of doctoral examinations, https://www.maschinenbau.tu-darmstadt.de/fachbereich/aktuelles_fb/neuigkeiten/news_details_396160.de.jsp) 

Sometimes the term "Berichterstatter" is also used, which is actually only the German translation of the Latin "Referent".

The TU dictionary also suggests examiners for "Referent". (see: https://www.intern.tu-darmstadt.de/arbeitsmittel/uebersetzungen_deutsch_englisch/index.de.jsp#R)

Because of the enumeration it is not straight forward to change this in the cfg file. I suggest to change the name to "Referent" (for the first reviewer, "examiner" in english ) and "Koreferent" (for the second reviewer, "second examiner" in english).

However, I would like to discuss this here first.

**Comment by TeXhackse** [comment]
I will mark this as a „enhancement“ and „discussion“ because it would also be a possibility to provide multiple variants if there is no „right“ way of solving this or add a simpler mechanism to change that. (Since I am not directly involved into TUDa my opinion on this is not relevant.)

**Comment by TeXhackse** [comment]
@schoeps @marklaz are there any opinions on this? If I shall add a mechanism to change this without expl3, I could do this together with the other adjustments for v3.06

**Comment by schoeps** [comment]
Ich stimme zu. Auch die Begriffe in der Promotionsordnung (https://www.intern.tu-darmstadt.de/dez_ii/hochschulrecht/gesetze_und_ordnungen/index.de.jsp) sind "Erstreferent_in" und "Koreferent_in" und auf english "first referee" und "co-referee". Mir scheint es sinnvoll den default so zu setzen, aber überschreibbar zu machen, denn die allgemeine Form mit "_" ist ja typographisch nicht schön und auch nicht mehr nötig, wenn man weiss wer begutachtet.

@marklaz gibt es mit der ULB andere Vereinbarungen?

**Comment by marklaz** [comment]
Keine anderen Vereinbarungen mit der ULB.

Erstreferent_in, Korreferent_in [mit zwei "r" vor dem "ef"]
first referee, co-referee

Wie von Sebastian vorgeschlagen, als Default mit Änderungsmöglichkeit.

**Comment by TeXhackse** [comment]
okay. [Der Unterstrich ist zwar echt schrecklich, aber wenn ihr das so wollte … ;-) ]
Dann dokumentier ich das heute.

**Comment by marklaz** [comment]
Aus meiner Sicht können wir hier auch ganz klassisch mit Schrägstrich arbeiten. Insbesondere, da dann in der finalen Version ja jeweils ohnehin nur die relevante Form stehenbleiben soll.

**Comment by TeXhackse** [comment]
Doppelpunkt wäre auch okay 

Aber dann fände ich tatsächlich den neutralen Default, wie er jetzt ist sinnvoll, sonst würde ich das als ntowendige Angabe machen. Einen Default so zu setzen, dass er geändert werden sollte, ist irgendwie doof.

**Comment by schoeps** [comment]
Unsere Promotionsordnung selbst nutzt den Unterstrich, daher würde ich das beibehalten.

**Comment by TeXhackse** [comment]
Wie gesagt, ich finds okay, wenn man es daran anlehnt, nur grundsätzlich schrecklich. Aber das ist irrelevant.

Soll ich das dann als Default für alle oder nur für Dissertationen ändern?

**Comment by marklaz** [comment]
Aus meiner Sicht nur für Dissertationen (Habilitationen haben wir ja bislang nicht explizit vorgesehen).

Bei den BSc/MSc-Arbeiten taucht wahrscheinlich in den meisten Fällen nur jeweils ein_e Betreuer_in auf. Referenten werden dort in der Regel nicht benannt. Insofern wäre hier eine andere Terminologie vorzuziehen.

**Comment by schoeps** [comment]
Ich habe gerade nachgeguckt: die APB spricht im [deutschen](https://www.intern.tu-darmstadt.de/media/dezernat_ii/satzungsbeilagen/Sb-2020-V.pdf#%5B%7B%22num%22%3A1993%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C841.92%2C0.75%5D) von "Prüferinnen" und "Prüfer", im [englischen](https://www.intern.tu-darmstadt.de/media/dezernat_ii/ordnungen/apb_english.pdf) von "examiner", siehe § 23. Später gibt es auch noch "Betreuerin oder Betreuer" und "advisor", aber das würde ich ignorieren. 

Interessante Beobachtung: der "_" (z.B. Prüfer_in) findet in der APB keine Verwendung. Es gibt hin und wieder die Variante mit "/".

**Comment by TeXhackse** [comment]
Also eigentlich wäre es egal, wenn wir darauf hinweisen und die Möglichkeit geben, es einfach zu ändern, oder?

Ich frag mich einfach, ob es das nicht unnötig kompliziert macht, wenn wir uns ewig überlegen welche Formulierung sinnvoll wäre, aber wenn es eigentlich keine 100%ig richtige Lösung gibt. Bei der Promotionsordnung verstehe ich die Referenz aber aber ansonsten kann es auch Fachbereichsspezifisch sind, wie die Position benannt werden soll. (Zumindest hatte ich da schon sehr sehr sehr viele Diskussionen zu.)

**Comment by schoeps** [comment]
> Also eigentlich wäre es egal, wenn wir darauf hinweisen und die Möglichkeit geben, es einfach zu ändern, oder?

Ja! aber einen Default sollten wir trotzdem setzen, oder?

**Comment by TeXhackse** [comment]
Jap, aktuell ist es 1. Gutachten / 1. review und wird durchnummeriert. Wenn ihr den default anders wollt, dann muss ich nur wissen wie. 

Dissertationen würden dann nach Promotionsordnung
> Erstreferent_in, Korreferent_in [mit zwei "r" vor dem "ef"]
first referee, co-referee

bekommen und für kleinere Arbeiten gingen Varianten von Betreuer_in. Da ist dann die Frage vom man Erstbetreuer_in und Zweitbetreuer_in schriebt oder numerisch.

Sollten wir in dem Fall auch die Anzahl limitieren? Aktuell gibt es keine Grenze, wenn wir aber solche Unterscheidungen machen, brauche ich entweder einen „Ausweichtitel“ oder das bleibt für alle leer, bei denen es nicht definiert wurde.

**Comment by TeXhackse** [comment]
Ich würde, falls wir da bis morgen Abend keine fixe Entscheidung erstmal nur den Änderungsmechanismus einbauen, Die Doku dazu usw. würde ich dann ergänzen, wenn hier was festesteht, Ich möchte eigentlich vermeiden wieder zwei Releases in kurer Folge zu haben, aber es ist dann auch kein Drama, wenn es eben so läuft.

**Comment by marklaz** [comment]
Mein Vorschlag:
Wir haben mit "1. Gutachten" etc. eine schöne und neutrale Default-Formulierung, die letztlich keiner Promotionsordnung widersprechen dürfte. Daher sollten wir nur dafür sorgen, dass die Begrifflichkeiten leicht (d.h. möglichst granular) an spezifische Wünsche angepasst werden können, und dies geeignet in den DEMO-Files dokumentieren.

Eine harte Begrenzung der Gutachten auf 4 erscheint mir zudem mit Blick auf die Promotionsverfahren an der TUDa vollkommen ausreichend. Wenn mehr angebracht sein sollte, dann gerne auch 5 oder 6. Wenn keine Begrenzung sinnvoll erscheint, dann gerne auch weiterhin keine.

Bei BSc/MSc-Arbeiten könnte wahrscheinlich sogar eine Begrenzung auf 2 Betreuer_innen erfolgen.

**Comment by schoeps** [comment]
Wenn der Begriff leicht überschrieben werden kann, dann sehe ich auch kein Problem und wir können für alle (Ba,Ma, PhD) einen generischen Default setzen. Ich würde die Anzahl, wenn nötig, nur sehr großzügig begrenzen (zB 10), wer weiß welche Spezialfälle es gibt. Ich habe schon (Cotutelle-)PhD Thesen mit recht vielen Namen gesehen (z.B. 3 Betreuer und 3 Gutachter = 6 Namen), sogar in meiner Arbeitsgruppe :) https://tuprints.ulb.tu-darmstadt.de/11687/1/ulb_phd_simona.pdf.

**Comment by TeXhackse** [comment]
Okay, dann machen wir das so. Danke für dich Rückmeldung

**Comment by TeXhackse** [comment]
Es ist jetzt dann so, dass man entweder den Begriff für die Nummerierung ändern, oder einzelne Begriffe überschreiben kann.  

Damit führt dann z.B.
```
\setupReviewName{Erstreferent,Zweireferent}
```
oder 
```
\setupReviewName[1]{Erstferent}
\setupReviewName[2][Zweitrefent}
```
zu
![image](https://user-images.githubusercontent.com/10723888/96588317-ce1fd180-12e3-11eb-9661-d5f42669d138.png)
```
\setupReviewName*{Ersatzwort für „Gutachter“}
```
überschreibt dann den Begriff mit Nummerierung

**Comment by schoeps** [comment]
:thumbsup:
