### ISSUE TITLE
tudaexercise: Check if \@author is empty

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#233]
**Version 3.03**
File: tudaexercise.cls
Command: `\renewcommand*{\@maketitle}`
Line 544

```tex
{\ifx\@author\@empty\else\usekomafont{author}\@author\par\fi}%
```

In any case, the above code is always executed in the else block for me.

So I created a minimal example to test this behavior:

```tex
\documentclass[ngerman]{tudaexercise}

\title{Test}
%\author{\LaTeX}

\begin{document}
	\maketitle
	\ExplSyntaxOn
	\makeatletter
 	{\ifx\@author\@empty Empty\else Author:~\@author\par\fi}%
	\makeatother
	\ExplSyntaxOff
\end{document}
````
The output of the above code is: 

> Author:

From this I conclude that the if statement has no effect.  Is there another way to check if `\@author` is empty?

**Comment by TeXhackse** [comment]
oh, you are right, this is indeed not wanted, but created by the reimplementation of authors. 
It's now implemented in a sequence, called `\g_ptxcd_author_seq`.

I will change this (hopefully I'll manage today).

What exactly is your intention? There is a bunch of possibilities to check that, but I am wondering which syntax would be the easiest for your usecase.

**Comment by Zentox** [comment]
I wanted to write a prefix in front of the author. That's how I noticed that behavior.

Example:
Author: Name
