### ISSUE TITLE
"Fachbereich Architektur" is hard-coded in the german affidavit (Erklärung zur Abschlussarbeit)

### ISSUE THREAD

**Issue by koehler-f** [tudace/tuda_latex_templates#235]
The german affidavit (Erklärung zur Abschlussarbeit) includes always:
" ... Bei einer Thesis des **Fachbereichs Architektur** entspricht...",  since "Architektur" is hard-coded to the tudathesis.cfg. 

Correct me if I am wrong, but this seems to be a mistake.

**Comment by TeXhackse** [comment]
Nope this is not a msistake, because that sentence is specific about the Department. 

It could be added only if this is really the case, but this was the official Text I received to add it there.

**Comment by koehler-f** [comment]
@TeXhackse thank you for your quick responds. 

Ok, I understand. However, then this last sentence should be excluded for all remaining departments, I guess?

**Comment by TeXhackse** [comment]
Since it was the official version I am not sure if this is allowed. (bureaucracy ftw)

It might be, that the exam board has to decide about that, this is why I will not change anything before I got it approved.
(During my own studies we had a bunch of issues like that.)

**Comment by koehler-f** [comment]
Ah ok. I did not understand that this sentence is included independent of the department where the thesis was written.

Sorry, for the confusion.

**Comment by schoeps** [comment]
There is one text for all departments and it includes a specific paragraph for architecture, see https://www.tu-darmstadt.de/studieren/studierende_tu/studienorganisation_und_tucan/hilfe_und_faq/artikel_details_de_en_37824.de.jsp

We should not change it!

**Comment by TeXhackse** [comment]
@schoeps thanks that's what I thought. But wanted to ensure. I'll close this now.
