### ISSUE TITLE
TUDaPub - Title Picture

### ISSUE THREAD

**Issue by Lithimlin** [tudace/tuda_latex_templates#236]
I'm trying to set a title picture on the `tudapub` class.
In the old design, this was apparently possible using `\settitlepicture[]{image.png}`. However, this does not work with the new design. Is there a command that replaces it? I've been trying to look for a documentation on the various commands and options for the different classes but wasn't able to find anything besides this repository.
Some relevant options to this issue may be
```latex
\documentclass[
    class=article,
    type=intern,
    [...]
]{tudapub}
```

**Comment by schoeps** [comment]
Doesn't page 4 in http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/doc/DEMO-TUDaPub.pdf address this question?

**Comment by TeXhackse** [comment]
Generally there's `\titleimage` as you can find in the documentation and demo files.

The option `type=intern` is changing the titlepage mode to `titlepage=false` so there is only a titlehead used. You could change this back either by removing that option or add a `titlepage=true` after `type=intern`.

**Comment by Lithimlin** [comment]
Thanks for the quick replies! I had missed that document it seems.
