### ISSUE TITLE
Show total number of slides / frames in tudabeamer footer

### ISSUE THREAD

**Issue by rindPHI** [tudace/tuda_latex_templates#237]
Hi,

is it possible to show the total number of frames in the footline of tudabeamer slides, like "2 / 23"? In the old TeX templates, I managed to somehow hack this in by a "\setbeamertemplate{footline}" in my code, but in the new template, I don't succeed with this (big number of compilation errors). Could you consider making this a standard option in the layout? When being part of an audience, I personally like to know how far in a talk the speaker already proceeded, so I'd like to also offer this to my audience ;)

Thanks & Best Regards,
Dominic

**Comment by schoeps** [comment]
I tend to favor the opposite. I think people will focus too much on the number and this has no meaning since the presenter may have created separate slides instead of overlays for an animation, there may by backup slides,  etc. 

However,  I am not with the style police... so you can just use `\insertframenumber` and `\inserttotalframenumber` anywhere in the footer, e.g. put this before `\begin{document}`:
 
```
\department{TU Darmstadt | Fachbereich xx | Slide \insertframenumber/\inserttotalframenumber}
```

or in `\institute` or wherever.

**Comment by rindPHI** [comment]
Thanks, that's an option to change the footline, but it also affects elements of the title slide in an unintended way (frame number should not be part of the institute description on the title slide). I could of course construct the title slide manually, but I'd prefer a cleaner way, best by passing an option "showtotalframenum" or the like to the class. The metropolis theme, for instance, has an option "numbering" to which you can pass "none", "counter", or "fraction", where "counter" is the standard of tuda-beamer and "fraction" what I'd like. If nobody else has a need for this feature, I can try to find a workaround like the one proposed above.

**Comment by schoeps** [comment]
> but it also affects elements of the title slide in an unintended way

You can distinguish between the title and the footline using the optional argument in square brackets: `\department[Slide \insertframenumber/\inserttotalframenumber]{TU Darmstadt | Fachbereich xx}`. By the way: this works almost all documenttypes in Latex analogously, e.g. author names, or section titles. 

> If nobody else has a need for this feature, I can try to find a workaround like the one proposed above.

No, we won't add this. Sorry. We try to add only stuff that the TU guide requires. The rest are design decisions of the user... we may have a FAQ in the future and it could be put there.

**Comment by rindPHI** [comment]
OK, I understand. Thanks for the hints!

**Comment by TeXhackse** [comment]
@rindPHI just let me add the following hint. Easiest way to change ist
```
\renewcommand*{\insertframenumber}{\arabic{framenumber}/\inserttotalframenumber}
```
this is conform to all other uses of the framenumber inside the theme.

This is exactly the reason, why themes shall use `\inserframenumber` or `\pagemark` instead of calling the pagenumber directly ;-)

**Comment by rindPHI** [comment]
> @rindPHI just let me add the following hint. Easiest way to change ist
> 
> ```
> \renewcommand*{\insertframenumber}{\arabic{framenumber}/\inserttotalframenumber}
> ```
> 
> this is conform to all other uses of the framenumber inside the theme.
> 
> This is exactly the reason, why themes shall use `\inserframenumber` or `\pagemark` instead of calling the pagenumber directly ;-)

Thanks a lot! That's perfect!
