### ISSUE TITLE
Titelrückseite bei PhD Thesis

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#238]
Ich plane, meine PhD-Thesis im Verlag zu veröffentlichen. Dazu muss ich die Angaben auf der Rückseite des Titelblattes anpassen und würde dies idealerweise komplett selbst gestalten wollen. Dort befinden sich jedoch die automatisch generierten Angaben (Autor, Reviewer etc) und bis auf das Verweisen auf TUPrints (was für meine Zwecke nicht passt) sehe ich keine Möglichkeit, diese Seite selbst anzupassen. Ist dies auf einfache Weise möglich?

**Comment by TeXhackse** [comment]
Ja. 

Die Titelrückseite setzt sich aus aus den Mechanismen `\uppertitleback` und `\lowertitleback` zusammen. Beide können wie andere Werte besetzt werden. Siehe auch KOMA-Script Doku.

**Comment by AlexVHopp** [comment]
Hat wunderbar funktioniert, vielen Dank!
