### ISSUE TITLE
Title page department/institute/group lack of spacing

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#239]
Hello,

On the title page when entering the fields department, institute and group, the three are together without any spacing. It looks strange, especially if each field is taking two lines:

![Picture](https://user-images.githubusercontent.com/54108560/96351311-cfba8100-10ba-11eb-8e65-c8f1bb6553ec.png)

Would it be possible to leave half a line or so between each field?

Thank you!

**Comment by TeXhackse** [comment]
You are right, that combination looks quite crappy.

I am not the one decide about the general requirements. But if remember correctly this addendum was something which is not described in the official guideline. So @marklaz /  @schoeps, I'll leave this one open until I get a decision.

@JuLateX You can disable the auto generated box by using the thesis option `noinstbox` and then setup a own layout unsing `\addTitleBox`

**Comment by schoeps** [comment]
I had a quick look into the style guide. I did not find a specific rule but an image on page 33 has (quite some) vertical space between "department" and "institute". So I would be in favor adding this by default
<img width="554" alt="Bildschirmfoto 2020-10-18 um 14 11 19" src="https://user-images.githubusercontent.com/868081/96367076-f70d5e80-114b-11eb-9564-d23751f47d55.png">

**Comment by TeXhackse** [comment]
okay

**Comment by JuLateX** [comment]
Thanks!
