### ISSUE TITLE
D17 on title page

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#24]
One of my reviewers made me aware that the title page contains D 17 which according to [this](https://www.etit.tu-darmstadt.de/media/etit/01_etit/forschen/promotion/Merkblatt_Einleitung_Promotionsverfahren_dt.pdf) marks it as a PhD thesis which it is not.
I'm not sure if D 17 should be written on the title page for anything other than a PhD thesis.
If not, any quick fixes, how it can be removed?

It's also in the example thesis but for reference my document class setup:
```
\documentclass[
	english,
	fontsize=12pt,
	ruledheaders=section,
	class=report,
	thesis={type=master},
	accentcolor=1b,
	marginpar=false,
	parskip=half-,
	colorback,
	twoside]{tudapub}
```

**Comment by marklaz** [comment]
You could add, e.g.,
\publishers{Darmstadt}
to the preamble of your tex file.

**Comment by StefanFabian** [comment]
Thank you, that works for me.
I'll leave the issue open because it might make sense to check if this has to be fixed for everyone or not.

**Comment by marklaz** [comment]
An update of DEMO_TUDaThesis.tex, to which this line is added, should be sufficient.
Additionally, the documentation in the same file might be expanded by "\publishers" on page 7.

**Comment by StefanFabian** [comment]
Sure but since the type can be explicitly specified it wouldn't make sense that it has to be overridden if the type is already specified as bachelor or master thesis.

**Comment by TeXhackse** [comment]
After having a look at the linked document, I agree with @StefanFabian concerning the D17 Info. Would then remove it from the title definitions for any other type of thesis besides phd ones.
