### ISSUE TITLE
New affidavit wording since paper submissions are not longer required for thesis

### ISSUE THREAD

**Issue by PE-AR** [tudace/tuda_latex_templates#240]
There is a new wording for the "Thesis Statement pursuant to § 22 paragraph 7 of APB TU Darmstadt" since paper submissions are no longer required ([source]). It should be included into the thesis template, ideally as an configurable feature, because the regulation may change in the future.

[source]: https://www.tu-darmstadt.de/studieren/studierende_tu/studienorganisation_und_tucan/hilfe_und_faq/artikel_details_de_en_37824.de.jsp

**Comment by TeXhackse** [comment]
Thanks for the information.

@marklaz / @schoeps: since there are two variants we would have to add a switch to select between both. Since we should not change the default (might lead to issues with people updating during writing). I'd recommend to add an option for the digital submission's affidavit and the default would stay as it is.  I'd implement that as soon as you tell me to.

**Comment by schoeps** [comment]
It's true that currently no physical copies are required but I am not ware that there is a new affidavit. 

@PE-AR The website that you provide refers to a word document that uses the same "old" wording (see also the date in the footline: "Stand: 20.09.2017") that we are using. Did you compare it? Am I missing another document?

**Comment by PE-AR** [comment]
@schoeps For whatever reason, the new wording is only mentioned in the German website version.

**Comment by TeXhackse** [comment]
and they translate Vorname -> Prename (SCNR :D)

**Comment by schoeps** [comment]
@PE-AR: Thanks, found it!

@TeXhackse can we allow `\affidavit` to accept options? e.g. 'digital'?

**Comment by TeXhackse** [comment]
@schoeps We can do everything =P 
And yes, we could do it that way or add a thesis-option. I'd prefer a global option, but only because I think it's a really fundamental setting. But the decision is not mine. As I said I'd leave the default to print.

**Comment by schoeps** [comment]
@TeXhackse I guess this is to some extend a matter of taste.... I'd say it should be no "global" thesis option  since the usage of `\affidavit` is optional. If (in the future) there would be even style differences that I would surely agree. Nonetheless, I have no strong opinion.

**Comment by TeXhackse** [comment]
That's why I'd say it's a thesis option. That option would only exist if the thesis mode is activated. Similar to the other options which only exists in thesis. But we could also ask Markus about his opinion.

**Comment by schoeps** [comment]
@marklaz we need a third opinion :)

**Comment by PE-AR** [comment]
Not that you asked for it, but here is my opinion anyway:) Intuitively, I would expect such an options to a parameter to the `\affidavit`-command.

**Comment by marklaz** [comment]
I would vote for a command related affidavit-option, i.e., an optional argument which defaults to "print" but may be changed to "digital".

Reason is, that I cannot see any other differences between the two versions of a thesis apart from the affidavit.

Is it possible to offer this optional argument only for [BSc/MSc] theses? I guess that the affidavit of PhD theses is not affected (at least so far).

**Comment by TeXhackse** [comment]
@marklaz Everything is possible ;-) Will do it that way
