### ISSUE TITLE
Overfull hbox in `affidavit[digital]` 

### ISSUE THREAD

**Issue by Alby407** [tudace/tuda_latex_templates#241]
With the new option `digital`, I get the following overfull box in the affidavit:

![affidavit](https://user-images.githubusercontent.com/8408093/96638191-0c3ae680-1320-11eb-949b-4e9b90bcd5ef.png)
Of course, this depends on the name (and font size), since I have a rather long name :D
I solved the problem temporarily by removing the `~` after the `7`. This gives also an overfull hbox, but it is barely noticeable and looks better than removing `~` after `Abs.`. I'm not sure if this is typographically correct. Might not be a smart solution, but works for now :)

Also, the documentation `DEMO-TUDaThesis.tex` says the optional parameter is `online`, but only `digital` works.
 https://github.com/tudace/tuda_latex_templates/blob/d1b378e424d19f6a44fa388f6800df8a93f45803/example/DEMO-TUDaThesis.tex#L196

**Comment by TeXhackse** [comment]
Thanks for reporting, you are right, I messed that up. Will fix that tomorrow.

**Comment by TeXhackse** [comment]
Alright after some tests -> the only general working solution is to switch that paragraph to sloppy (increase tolerance, emercencystrech and hfuzz). Since this is only a variant of affidavit and I don't want to change the general layout due to the others, I will implemented it that way.

**Comment by schoeps** [comment]
Out of curiosity: where does the problem come from? Nonbreaking spaces between "Abs", "7" and "ABP"?

**Comment by TeXhackse** [comment]
Yes, because you must not have a linebreak in there. And after thinking about this even setting the paragraph to a high tolerance is the less evil. The print version of the affidavit does not use a reference in there.

**Comment by schoeps** [comment]
I checked, even within the APB they do line breaks between "§ 7" and "Abs. 3" (page 21):

![Bildschirmfoto 2020-10-21 um 12 34 48](https://user-images.githubusercontent.com/868081/96708667-d6d2df00-1399-11eb-9712-7c94b3f2514f.png)

So I'd say we can remove the non-breaking spaces, too.

**Comment by TeXhackse** [comment]
Ofc you can allow that. But as I said it's worse than the current setup. 

If you really want me to do this I'd do this of course. But still this would not be enough for length of the `\@author`. So I'd have to increase tolerance and emergencystretch anyway. 

Beside that I don't think that the author of the APB did pay any attention to the linebreaks and it is typeset raggedright, which would also be an alternative if you don't like the sloppy paragaph.
