### ISSUE TITLE
“Datum” is still not translated with type=pp

### ISSUE THREAD

**Issue by JohannaTU** [tudace/tuda_latex_templates#242]
I am still having problems with the date not being translated.
I know that there already exists an issue for a past version of the TU Design, but it is still does not work for me, even though I updated the tuda-ci package. I also compiled the file in overleaf, where the same problem occured.
In addition the work around, proposed in the other issue, does not work for me.

I added a modified version of DEMO-TUDaThesis.tex, where I changed the type to pp, added a \date{\today} and changed the language to english.
[DEMO.zip](https://github.com/tudace/tuda_latex_templates/files/5414524/DEMO.zip)

For this file the problem does occur for me

**Comment by TeXhackse** [comment]
You are currently loading 
```
\usepackage[english, main=english]{babel}
```
You would have to load 
```
\usepackage[ngerman, main=english]{babel}
```
Otherwise a translation will not be possible.
I will recheck the documentation maybe it's not stated clear enough, while preparing 3.07

**Comment by JohannaTU** [comment]
Thank you, but even with this changes "datum" is still not translated to "date".

**Comment by TeXhackse** [comment]
Oh, sorry I got that wrong, will have a look and also fix that with todays release.
