### ISSUE TITLE
Very long title font size

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#243]
Hello,

If I understood the demo file of TUDaThesis (my German is not very good), the font size should be automatically reduced for very long titles. I think it is not working properly (see image below).

![Title_page](https://user-images.githubusercontent.com/54108560/96699855-0af4d280-138f-11eb-85c6-d5ed1ee21204.png)

While my real title is not as long as in my example, it still looks disproportionally large. How can I write it with a smaller font?

Thank you

**Comment by TeXhackse** [comment]
Nope, there is no automatic reduction of the fontsize. 

You can try the class option `title=small` this will probably help.

**Comment by JuLateX** [comment]
It is much better and solves my problem. Thank you!
