### ISSUE TITLE
Alternativtitel für Reviewer

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#244]
Ich kann bei Verwendung von TUDaThesis nicht die Bezeichnung für Reviewer ändern. Weder über die Option, alternative Titel mit`\reviewer*[Titel]{Gutachter}` noch über das Kommande `\setupReviewName*{...}`. Im ersten Fall erhalte ich ein merkwürdiges Ergebnis (s. angehängtes MWE), im zweiten erhalte ich die Nachricht dass der Befehl nicht gefunden wurde.

```
\documentclass[ruledheaders=chapter,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=book,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		type=drfinal,
		dr=rernat
	},
	accentcolor=1b,% Auswahl der Akzentfarbe
	custommargins=geometry,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	ruledheaders=true,
	bibliography=totoc,
	index=totoc,
	fontsize=11pt,
	pdfa=false,
	IMRAD=false
]{tudapub}

\geometry{top=2 cm, bottom=3.5cm, left=3cm, right=3.5cm}

\usepackage{iftex}
\ifPDFTeX
	\usepackage[utf8]{inputenc}%kompatibilität mit TeX Versionen vor April 2018
\fi

\usepackage[english]{babel}

\begin{document}

\pagestyle{TUDa.headings}
\frontmatter

\title{The Complexity of Zadeh's Pivot Rule}
\author[Alexander V. Hopp]{Alexander Vincent Hopp}%optionales Argument ist die Signatur,

\reviewer*[Test]{Some Reviewer}%Gutachter

\department{math} %Kürzel werden entsprechend der Liste in diesem Dokument ersetzt.

\maketitle

This is just a MWE

\end{document}

```
[MWE.pdf](https://github.com/tudace/tuda_latex_templates/files/5415112/MWE.pdf)

**Comment by TeXhackse** [comment]
Das sieht so aus, als wäre das noch die alte Version.

Mit dem gestrigen Update läuft das und in der Version, die ich gerade Upload-fertig mache, auch.

**Comment by AlexVHopp** [comment]
Laut Miktex habe ich die Version vom 21.10.2020 installiert, auch alle anderen Pakete habe ich heute aktualisieren lassen.

Es wäre für mich schon praktisch wenn es einen einfachen Workaround gibt mit dem ich das Problem bei mir beheben kann, wann wäre die nächste Version denn verfügbar?

**Comment by TeXhackse** [comment]
MikTeX hat nach seiner Info momentan noch die Version vom Juli (vgl. https://miktex.org/packages) Das angezeigte Datum ist wahrscheinlich das Installationsdatum.. Es kann noch ne Weile dauern. Da die Projekte von freiwilligen betrieben werden und MikTeX macht das nicht automatisch, wie TeX Live. Kann also etwas dauern, ich rate genau deswegen meistens zu TeX Live, weil ich dann schneller fixen kann.

Workaround wäre, die Datei tudathesis.cfg der Version 3.06 zu nehmen und im aktuellen Verzeichnis abzulegen:
Direktlink: https://raw.githubusercontent.com/tudace/tuda_latex_templates/d05c16aee78ed1501e755c60ce0a0d8461065320/tex/tudathesis.cfg

Die sollte zu den anderen Dateien der Version 3.05 kompatibel sein. Und bei Installation von 3.06 oder neuer würde das einen Fehler werfen, um daran zu erinnern die lokale Datei zu entfernen. 

Ich kann es gerade nicht testen, kann das aber tun, sobald ich später wieder im Büro bin. Falls es Probleme gibt, gerne melden, das vereinfacht es für mich. Danke.

**Comment by AlexVHopp** [comment]
Das hat funktioniert, vielen Dank! Ich schließe dann hier da sich mein Problem ja gelöst hat und es in Zukunft nicht mehr dazu kommen dürfte.
