### ISSUE TITLE
Teilweises Anpassen der Seitenränder in TUDaPhD

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#246]
Ich würde gerne den oberen und unteren Seitenrand in meiner Dissertation anpassen, die seitlichen Seitenränder jedoch beibehalten. Ich habe bereits manuell versucht, über `custommargins=geometry` undexplizites Setzen der Seitenränder möglichst nah an die durch `custommargins=true` linken und rechten Ränder heranzukommen, schaffe das aber nicht exakt was mir die Formatierung einiger Formeln zerstört.
Ist es daher möglich lediglich zwei der Seitenränder manuell anzupassen und die anderen beiden so zu belassen?

**Comment by TeXhackse** [comment]
Also ja, das geht, allerdings ist die Anforderung etwas speziell weil sich damit zwei mechanismen überlargern, dementsprechend wäre der übliche weg geometry zu nehmen und einfach alle Ränder einzustellen, die Größen der berechneten Ränder lassen sich aus der log-Datei entnehmen. Das Paket typearea, dass für die Berechnung verwendet wird, schreibt diese raus, das sieht dann z.B. so aus, da kann man die Werte dann entnehmen und bei geometry als Option einfügen.
```
Package typearea Info: These are the values describing the layout:
(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -6%
(typearea)              \evensidemargin = 17.3562pt
...
```
Generisch geht das auch, ist allerdings etwas tricky, weil man damit den Automatismus von tuda-ci umgehen muss.

1.  Einstellung der Option ist `custommargins=true`. Es wird also die berechnung aktiviert

2.  Innerhalb der Präambel wird geometry mit der Option `pass` geladen

    ```
    \usepackage[pass]{geometry}
    ```
    Das führt dazu, dass das Paket direkt keine Änderungen vornimmt, aber seine Mechanismen später zur Verfügung stehen.

3.  Nach `\maketitle` kann dann über `\newgeometry` eine Anpassung gemacht werden, z.B. 
    ```
    \newgeometry{top=2cm,bottom=2cm}
    ```
    Kopf- und Fußzeile werden dabei nicht zum Rand gerechnet, das kann ebenfalls über geometry-Optionen angepasst werden.

(Theoretisch wäre es auch möglich den Mechanismus von tuda-ci für die Rekonstruktion der Ränder nach der Titelseite umzudefinieren, aber da gibts ein paar Dinge zu beachten, deswegen wäre das wahrscheinlich so einfacher.)

**Comment by AlexVHopp** [comment]
Die zweite Variante hat funktioniert, bei der ersten hat er nicht alles genommen (oder ich habe es falsch übergeben) vielen Dank!
