### ISSUE TITLE
Can not set up label of reviewers

### ISSUE THREAD

**Issue by chrstmnn** [tudace/tuda_latex_templates#247]
Hi,

I currently try to adapt the naming of my reviewers in TUDaThesis with
`\reviewer[1. Review,2. Review,Supervisor]{Name 1 \and Name 2 \and Name 3}`

When i compile, I get a compile error. Without the modification of the naming everything is fine, but I need to rename the third person.

PS: I use the tool under sharelatex01.ca.hrz.tu-darmstadt.de

**Comment by schoeps** [comment]
Sharelatex is not using the latest version of the package which allows renaming of reviewers (you can see it here: "log and output files" -> "view raw logs"): `tudapub 2020/03/13 v2.09 Publications using TU Darmstadt's Coporate Design (TUDa-CI)`. You can install the package locally in your overleaf project or try to motivate HRZ to update the global installation.

**Comment by chrstmnn** [comment]
Thanks for your quick reply! Will do!

**Comment by schoeps** [comment]
Maybe there is a better solution but uploading everything from `tex/` of the [released zip file](https://github.com/tudace/tuda_latex_templates/releases/tag/v3.07) into sharelatex seems to work.

**Comment by TeXhackse** [comment]
Duplicate of #244. 

It's enough to use the 3,06 version of tudathesis.cfg instead of all files. (https://raw.githubusercontent.com/tudace/tuda_latex_templates/d05c16aee78ed1501e755c60ce0a0d8461065320/tex/tudathesis.cfg)
