### ISSUE TITLE
Add another TOC (was: Loading titletoc package)

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#249]
Hello,

I need to load the`titletoc` package to create a table of contents for the appendices outside of the main toc (I want the main toc to read only "List of appendices" and the second toc to give the detailled list).

The package `titletoc` must be loaded before the package `hyperref` but I think the `hyperref` package is already loaded by default. Is there a solution to load titletoc before?

Thank you!

**Comment by TeXhackse** [comment]
Hi,
no you don't need to load the titletoc, see solution below. 
In case you ever want to load a package before an automatically loaded one.
Either use scrlfile to manipulate the file loading mechanism itselg, or use `\RequirePackage` before `\documentclass`. This is the same as `\usepackage` but could be used before. Anyway you should be careful with that and know what the package is doing before using this. 

#### Answer to the problem itself
You can simply solve this using tocbasic which is part of the komascript bundle and define a mini toc.

The following code is to simplify the usage:

```
%Define another toc file for the appendix
\DeclareNewTOC[%
	listname={\contentsname~(\appendixname)},% You can add any text as a headline here.
	setup=totoc
]{atoc}

\makeatletter
\newcommand*{\appendixwithtoc}{%
	\listofatocs% Print the atoc toc
	\hypersetup{bookmarkstype=atoc}%
	\def\toclevel@chapter{1}% These redefinition are the easiest way to change the level of  the bookmarks inside appendix
	\def\toclevel@section{2}%
	\def\toclevel@subsection{3}%
	\def\toclevel@subsubsection{4}%
        \def\toclevel@paragraph{4}%
        \def\toclevel@subparagraph{5}%
	\renewcommand*{\ext@toc}{atoc}% Write all following toc entries to atoc instead of toc
}
\makeatother
```
After this definition you can simply replace `\appendix` by `\appendixwithtoc`

If you have any further questions, feel free to ask.

**Comment by JuLateX** [comment]
This is wonderful! Thank you!
