### ISSUE TITLE
Anpassen der Seitenränder PhD Titlepage

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#250]
Ich versuche momentan, die Seitenränder der Titlepage anzupassen. Ich habe `custommargins=geometry` und in der Präambel den Befehl `\geometry{reset, margin=9cm}` (zu Testzwecken) verwendet. Dabei ändern sich jedoch nur die Seitenränder aller Seiten nach der Titelseite, nicht jedoch die der Titelseite und deren Rückseite. 

Passend zu meinem letzten Issue habe ich es auch über `\usepackage[pass]{geometry}` und `\newgeometry{...}` versucht, jedoch ohne Erfolg.

Gibt es eine einfache Methode die Seitenränder dort zu ändern?

**Comment by AlexVHopp** [comment]
Ich habe eine Möglichkeit durch Anpassen von `\dim_gset:Nn \g_ptxcd_outerMargin_dim {15mm}` in der Datei `tudapub.cls` gefunden. Das ist zwar wahrscheinlich komplett widersprüchlich dazu wie man es machen sollte aber mein Problem ist damit gelöst worden, ich lösche das hier aber nicht falls jemand in Zukunft noch einmal das Problem hat.

**Comment by TeXhackse** [comment]
Okay. Ähm.

Die Titelseite ist im Modus `titlepage=firstiscover` (vgl. KOMA-Doku) das müsste auch irgendwo in den Demos stehen, ich prüfe das nochmal.
Das bedeutet, dass die Ränder der Titelseite über die Makros

```
\coverpagetopmargin
\coverpageleftmargin
\coverpagerightmargin
\coverpagebottommargin
```
festgelegt sind. Diese lassen sich umdefinieren.

Und ja, Wertemäßig ist das gleich zur outer margin, aber naja …

**Comment by geisenhofer** [comment]
Leider wirken sich die Befehle nicht auf die zweite Seite aus @TeXhackse... Hast du hierfür auch eine Lösung? Danke!
