### ISSUE TITLE
TUprints now using CC BY 4.0

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#251]
_Originally posted by @martin-fzd in https://github.com/tudace/tuda_latex_templates/issues/87#issuecomment-721006750_

I am afraid I have to repost into this old issue. The current publisher agreement for tuprints by the ULB provides for Creative Commons version 4, alternatively a separate license.

![image](https://user-images.githubusercontent.com/26324188/97969176-f6b5ca00-1dbf-11eb-8bfd-be212b9f91d6.png)

In my experience, the issue of license selection for a work is not given the attention it deserves. It cannot be assumed that the default license (in this case it would be CC 4.0 BY) is always the best choice. Would it be an idea to highlight the license paragraph in the template in a different color to force "active" editing by the user?

**Comment by TeXhackse** [comment]
@marklaz, @schoeps : Since they seemed to have changed their version, we should update as well. 

I remember myself asking you about the outdated version, and this is why we sticked to 2.0 to use theirs.

**Comment by schoeps** [comment]
1. I agree to update the default license according to the recommendation of ULB (2->4 if I understood correctly).
2. I think that we should have an easy mechanism to put something else. I can confirm that this is important in practice, i.e., my recent PhD graduates also used different licenses (due to an additional publication as a printed book). They managed to put their license into the template but I am not sure how convenient the current mechanism is.

**Comment by TeXhackse** [comment]
We already have a mechanism to change the license.

**Comment by schoeps** [comment]
@TeXhackse sorry, too many issues, too less time and not enough (brain) memory.

**Comment by TeXhackse** [comment]
alright. and @schoeps no need to excuse. That's exactly what's my job, not yours. So I'll prepare this and upload it with the bugfix of the other open issue.

**Comment by TeXhackse** [comment]
@schoeps let me correct this and I'd like to get this confirmed before I upload 4.08. 
The old default license was “CC BY-NC-ND 2.0 DE” the new variant as described above would only be “CC BY 4.0 International”. 

This allows to share derivatives and commercial use. This makes it a bigger change than expected.

**Comment by schoeps** [comment]
@TeXhackse shall I double check and ask our publishing service (ULB) if this was intended?

**Comment by TeXhackse** [comment]
To me it seems to be not intended. So probably that's a good idea. (I could do that as well, but probably you'll be faster.)

In case they really mean it, I'd suggest we add some information on that change to the documentation. Because otherwise it seems like a small change, but it's definetely not.

**Comment by schoeps** [comment]
CC-BY 4.0 ist in der Tat der neue Standard an der TU Darmstadt, dazu kann man jetzt stehen wie man möchte, aber wir sollten nachziehen. Ich schlage daher vor: 
1. wie ändern den default zu CC-BY 4.0
2. wir fügen zu der Dokumentation einen Link zu mehr Hintergrundinformationen zu den Lizenzen hinzu  (z.B. https://creativecommons.org/licenses/)
3. wir fügen im Quellcode von 'DEMO-TUDaPhD.tex' so etwas  hinzu:
```
% The recommended license at TU Darmstadt is the most liberal CC BY which
% allows third parties to modify and commercially use the thesis. If you want to restrict
% the use by third parties then you may change the license here, e.g., to the less
% liberal CC BY-NC-ND or the minimal UrhG which are both accepted by TUPrints
%\license... 
```

Ich glaube, dass gerade der Quelltextkommentar im besten Interesse der Dokrand:innen ist. 
Die Doku wird ja nachweislich nicht von allen gelesen. Einverstanden?

**Comment by TeXhackse** [comment]
Mostly yes, but atm I am also wondering, if we should add a Warning.
I know, there are people ignoring these. But it would be the only option to notify users, who already work with the template. 

Otherwise they'll update and this update will change the license of their thesis without any feedback.

**Comment by schoeps** [comment]
You are right. We should do it the other way around... we keep the old license for now and add a warning that the next major version bump will also change the default license. We document this now in the source code and manual.

What do you think?

**Comment by TeXhackse** [comment]
Yes but then, I'd prefer  implement both licenses as well as CC BY-ND-NC 4.0 international. We leave 2.0 as default adding the warning and people can simply change it without copying the complete text?

This would probably simplify it for the user and users can choose they key-val variant. And easier downgrad in case they want to stick to 2.0

**Comment by schoeps** [comment]
yes and please add something like this to the example file:
```
% The current Latex template uses CC BY-NC-ND 2.0 DE as the default license.  
% However, TU Darmstadt currently recommends the most liberal CC BY 
% which allows third parties to modify and commercially use the thesis.
% The Latex templates will change the default with the next major release. 
\license{CC BY 4.0} 
```
where `CC BY 4.0` should be replaced by the correct syntax. This should ensure that people who start writing now based on the template are not surprised by a change. However, people that have started already will be neither affected since we keep the old default + warning.

**Comment by TeXhackse** [comment]
Alright.

**Comment by TeXhackse** [comment]
@schoeps The text inside the code was added in German -> because we have all of it in German but has an English hint to the warning message. The warning message is english and I extended the help text there to directly point on the predefined license options.

**Comment by schoeps** [comment]
@TeXhackse sounds very good to me. I will have look to commit ac53eebc7644983b6b5c256f53348e95b9f7717b! Thanks!

**Comment by TeXhackse** [comment]
@schoeps um, nope not that commit, you should grab it in total.

I removed the licensedemo afterwards and replaced it by a link to http://creativecommons.org/choose/ which will be the better explained variant.

**Comment by schoeps** [comment]
@TeXhackse ok, I will checkout the latest build later this evening. I have anyway (unfortunately) some other stuff to do :)

**Comment by TeXhackse** [comment]
You're always faster than I'd expect anyway =P

I'll wait with the upload. Rest is finished I think, so I'll work on some other project now as well.
