### ISSUE TITLE
tudapub: Ränder der Titelrückseite passen sich nicht wie erwartet an

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#252]
_Originally posted by @geisenhofer in https://github.com/tudace/tuda_latex_templates/issues/250#issuecomment-720601996_

> Leider wirken sich die Befehle nicht auf die zweite Seite aus @TeXhackse... Hast du hierfür auch eine Lösung? Danke!

------------------------------------
Das scheint ein Bug zu sein, ich versuche mich im Laufe des Tages darum zu kümmern. 

@geisenhofer Anmerkung: Allgemein ist es hilfreich, ggf. ein neues Issue anzulegen, auch wenn ein ähnliches Issue schon existiert hat, aber das Problem ist ein neues. Ggf. kann ich dann zuordnen, ein Bazug auf ein anderes Issue ist ebenfalls möglich, aber Kommentare unter geschlossene Issues haben eine niedrigere Priorität als neue Issues.

**Comment by geisenhofer** [comment]
Alles klar und danke! Mache ich beim nächsten Mal 👍

**Comment by TeXhackse** [comment]
Um Missverständnisse zu vermeiden, dass Verhalten ist mit 1d350237b7ce0e2a42844d2ca33b0d546b070e6f genauso wie bei Standard-KOMA-Script.

Also die Ränder werden für die Titelrückseite vom Fließtext übernommen.
Einzige anpassung ist, dass für diese Seite immer `marginpar=false` gilt.


@geisenhofer ich würde gerne mit der Veröffentlichung warten, bis das Lizenproblem im anderen Issue gelöst ist. Falls das super eilig ist, bitte nochmal melden, dann lade ich die Dateien nochmal einzeln hoch, damit die Änderung lokal schonmal funktioniert

**Comment by geisenhofer** [comment]
@TeXhackse Danke dir! Wäre tatsächlich dringend, da ich meine Arbeit Anfang nächster Woche einreichen möchte 🤓

**Comment by TeXhackse** [comment]
@geisenhofer => siehe Email
