### ISSUE TITLE
tudapub: Footnote in section

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#254]
I'm currently trying to add a footnote in section, but it doesn't appear at the bottom of the page. I am wondering how I can achieve this.

```tex
\documentclass{tudapub}

\begin{document}
\section[Test]{Test\footnote{Test}}
Text
\end{document}
```

**Comment by TeXhackse** [comment]
tuda-ci requires the section headers to be typeset inside a box to achieve the layout including the rules.

So it's similar to 
```
\mbox{\footnote{test}}
```
You can use footnotes there by splitting it up into `\footnotemark` and `\footnotetext`.

So using you example this would be like:
```
\section[Test]{Test\footnotemark}
\footnotetext{text}
```
If you need multiple footnotes you can use the optional argument to ensure the correct reference between them.
