### ISSUE TITLE
How to removed white space in a Figure's caption?

### ISSUE THREAD

**Issue by SamuelePolimi** [tudace/tuda_latex_templates#256]
I want to remove the white space under "Figure 4.1", so to save more space. This is particularly useful in the case of small figures, where the space for the caption is already small.
![robo-fig](https://user-images.githubusercontent.com/17749114/98467400-5273bf00-21d5-11eb-9bfe-89d468919250.png)

**Comment by TeXhackse** [comment]
Adding `\setcapindent{0em}` to your preamble would resolve that. This is a feature of KOMA-Script. You can find that information in the KOMA-Script documentation.

**Comment by SamuelePolimi** [comment]
Thanks @TeXhackse for the very very quick reply!

**Comment by TeXhackse** [comment]
Thank yourself for the good timing ;-) 

Anyway. If this is all you wanted to know please close this issue. If you need any further information feel free to ask.

**Comment by TeXhackse** [comment]
I'll close this myself, because it seems to be solved.
