### ISSUE TITLE
Remove white space on the left of figures' captions.

### ISSUE THREAD

**Issue by SamuelePolimi** [tudace/tuda_latex_templates#257]
I want to remove the white space under "Figure 4.1", so to save more space. This is particularly useful in the case of small figures, where the space for the caption is already small.
![robo-fig](https://user-images.githubusercontent.com/17749114/98467400-5273bf00-21d5-11eb-9bfe-89d468919250.png)

**Comment by TeXhackse** [comment]
closed as cuplicated of #256
