### ISSUE TITLE
TUDaSciPoster - Custom Poster Resizing Beyond A0, A1, A2, A3

### ISSUE THREAD

**Issue by salsayed86** [tudace/tuda_latex_templates#258]
I'm required to design a vertical poster of dimensions 36 in x 48 in for upload to a conference website. The current design allows me to select only among A0, A1, A2 and A3. I did nevertheless try adding the lines:

\usepackage{geometry}
\geometry{paperwidth=36in,paperheight=48in}

while maintaining the default A0 poster size. This indeed resized the poster, but as far as I can see there is at least one problem with this approach: The header (colored background with title and TUDa logo) does not stretch to cover the span of the increased width. Is there any workaround?

**Comment by TeXhackse** [comment]
The header is initialized inside the document class. (This was done, because we wanted to ensure people stick to the papersizes we are maintaining.)

But, you can simply do another init of the titleblock after changing the geometry. Please pay attention to the fact, that geometry has already been loaded by the tudasciposter class, so I won't load it again:

```
\geometry{paperwidth=36in,paperheight=48in}

\ExplSyntaxOn
\dim_set:Nn \contentwidth {\paperwidth-2\g_ptxcd_margin_dim}
\ptxcd_makeheadrule[
   width=\contentwidth,
   color=identbarcolor
]{ptxcd_headrule}
\ExplSyntaxOff
```

Disclaimer: This is a workaround and I cannot promise this will work for all future releases.

**Comment by TeXhackse** [comment]
@salsayed86 it would be nice if you either could leave additional feedback or close the issue.

**Comment by salsayed86** [comment]
Thanks - satisfactory workaround!

**Comment by salsayed86** [comment]
Thanks, Marei! I just commented and closed the issue. I’m sorry, I’m not familiar with GitHub etiquette. For starters, I thought I shouldn’t clutter a post with confirmation that the suggested workaround was successful. All good now… Sorry again for the delay =)

 

Sara

**Comment by TeXhackse** [comment]
Thank you, no need to be sorry. I usually decided to not close these issues before I know that everything worked fine. There is no general etiquette for this. this is why I ask.

Just to inform you, if you reply to an email whcih was sent to you by github, this will be placed below the issue as a comment as well. If – for some reason – you need to get in contact via email. You can find my email address in the files: tuda-ci@peitex.de

Happy TeXing ;-)

Marei
