### ISSUE TITLE
Creating chapter without a number but with a toc entry

### ISSUE THREAD

**Issue by martin-fzd** [tudace/tuda_latex_templates#259]
I use the setting "ruledheaders=section". 

In the appendix of my thesis (i.e. after the bibliography) there are some additional chapters (e.g. list of supervised works).
How can I prevent that an "old" section is used in the header of the current chapter?

I have created an MWE:

![image](https://user-images.githubusercontent.com/26324188/98517726-a979a280-226e-11eb-81eb-2f5f3f037475.png)

(Note the "First Chapter" in the Header below, although we are in the "Second Chapter after Bibliography")

Sharelatex Link: https://sharelatex01.ca.hrz.tu-darmstadt.de/8161698576fvxtymwnjcxs

**Comment by TeXhackse** [comment]
This has nothing to do with tuda-ci but with the fact, that you use `\chapter*` + a manual toc entry.

KOMA-Script is facing this issue and therefore providing the `\addchap` command. 

This will also resolve the issue you try to fix using `\phantomsection`.

**Comment by martin-fzd** [comment]
Indeed, that does the job!
If someon else will find this issue:
Do not use 

```Latex
\chapter*{chapter heading}
\phantomsection
\addcontentsline{toc}{chapter}{chapter heading}
```

instead, use `\addchap[toc entry]{chapter heading}`

**Comment by TeXhackse** [comment]
@martin-fzd It's not that easy … But. Probably in most cases you will be right. But it's almost never a good a idea to manually add toc entries. So there's nearly always a better solution. tl;dr; Use the scrguien/scrguide ;-)
