### ISSUE TITLE
Frage: Hintergrundfarbe für Titel und Logo auf der Seite (logo=body)?

### ISSUE THREAD

**Issue by m7a** [tudace/tuda_latex_templates#260]
Ich versuche, die 1. der Farbvariationen aus dem Corporate Design Handbuch (vgl. hellblaue Abbildung) einzustellen, erhalte aber je nach Wahl der Optionen in `documentclass` nur die gezeigten Ergebnisse (Variante A, B1, B2, dunkelblaue Abbildungen).

![zulaessig](https://user-images.githubusercontent.com/18630636/98833552-74bc4580-243e-11eb-87cd-f667601d9bcd.png)
Darstellung im Corporate Design Handuch. Die 1. Variante soll realisiert werden.

![variantea](https://user-images.githubusercontent.com/18630636/98833548-738b1880-243e-11eb-9be1-7b046d7b6f84.png)
Ergebnis für Variante A

![varianteb1](https://user-images.githubusercontent.com/18630636/98833549-7423af00-243e-11eb-8c8a-3e0a5e4887ad.png)
Ergebnis für Variante B1

![varianteb2](https://user-images.githubusercontent.com/18630636/98833551-74bc4580-243e-11eb-8a29-07ce0a0cd5e3.png)
Ergebnis für Variante B2

**Wie müssen die Parameter gewählt werden, um die 1. Farbvariation aus dem Coroporate Design Handbuch einzustellen?**

Die Varianten B1 und B2 unterscheiden sich nur in der Reihenfolge der Parameter `logo=body` und `colortitleback=true`. Jeweils die letzte Option scheint die vorherige zu überschreiben.

Beispieldokumentquelltext:
```
% Variante A
%\documentclass[ngerman,class=article,fontsize=11pt,accentcolor=1d,type=intern,marginpar=false,titlepage=false,title=default,logo=body]{tudapub}

% Variante B1
%\documentclass[ngerman,class=article,fontsize=11pt,accentcolor=1d,type=publication,pdfa=false,IMRAD=false,marginpar=false,title=default,logo=body,colortitleback=true]{tudapub}

% Variante B2
\documentclass[ngerman,class=article,fontsize=11pt,accentcolor=1d,type=publication,pdfa=false,IMRAD=false,marginpar=false,title=default,colortitleback=true,logo=body]{tudapub}

\usepackage[english,main=ngerman]{babel}
\usepackage[babel]{csquotes}

\begin{document}
\title{Vorlage}
\author{Autoren}
\addTitleBox{Institut}
\date{}
\maketitle
\clearpage
\tableofcontents
\clearpage
\listoffigures
\clearpage
\section{Kapitel}
Text
\end{document}
```

Ich verwende TUDa-CI v3.07.

Danke im Voraus

**Comment by TeXhackse** [comment]
Ersteinmal tut es mir leid, weil das wohl ein historischer Punkt ist. Da bei der Erstellung von tuda-ci darauf geachtet wurde, kompatibel zu den älteren Templates zu bleiben wurde diese Option gleichbedeutend dazu implementiert. In den alten Templates war das genau so.

Ehrlich gesagt glaube ich, ich habee darüber die Variante vergessen/übersehen. Es wäre kein Problem das entsprechend zu erweitern, allerdings wäre dann die Frage, ob die compatibility-Option, die seit version 1.0 genau das als Warnung ausgibt, mittlerweile wegfallen kann. Weil das wäre logischerweise der sinnvolle Name dafür.

@marklaz @schoeps: Wäre das okay?  Da ich noch auf Rückmeldung wegen des bezüglich der TUprints ware, könnte ich das in den glecihen Release mit einbauen.

@m7a Da das wohl auf meine Kappe geht: Wenn es eilt, kann ich heute noch eine Entsprechende Ergänzung als Workaround liefern.

**Comment by marklaz** [comment]
Wegen mir kann der Warnhinweis wegen der alten Templates inzwischen wegfallen.

**Comment by TeXhackse** [comment]
Es würde dann aber auch die Kopplung der Optionen wegfallen. Ich würde dann einen Warnhinweis ergänzen, dass wir das geändert haben, wobei die Ausgabe wahrscheinlich ofensichtlich genug ist.

**Comment by m7a** [comment]
Danke für die schnelle Rückmeldung!

Von meiner Seite ist es auf jeden Fall nicht so eilig, dass es heute noch gemacht werden müsste :) Ich würde das gerne für eine Übungsabgabe verwenden, die in etwa einer Woche fällig ist. Wenn es bis dahin schon funktioniert, wäre das klasse!

**Comment by TeXhackse** [comment]
@marklaz Okay, den edit hab ich nicht gesehen, daher hier die Erklärung:

Das alte Template hatte eben die `colortitleback` option als Schalter um das Logo und die Farbe zu ersetzen. Da die Option nur aus Kompatibilitätsgründen existiert, würde ich jetzt dazu übergehen die neue Option hinzufügen und zu dokumentieren.

Und um verwechslgung zu vermeiden nenne ich sie einfach `colorbacktitle` dann nehm ich die alte Option raus, die schon lange als compat getagged war und gebe einen Fehler aus, wie die neue Bennennung lautet. Dann fangen wir einfach alles ab. 
Dann sind alle zufrieden. Sobald die Info bezüglich der Lizenzänderung da ist, mach ich den Upload.

**Comment by schoeps** [comment]
>Sobald die Info bezüglich der Lizenzänderung da ist, mach ich den Upload.

@TeXhackse das bezog sich auf mich bzw. auf #251, oder? Ich bin mit der aktuellen Lösung einverstanden und haben sie lokal ausprobiert und für gut befunden.

**Comment by TeXhackse** [comment]
@schoeps jup, okay, dann mach ich das alles heute fertig.

**Comment by TeXhackse** [comment]
@m7a Der Release ist raus, und wird wahrscheinlich heute noch auf CTAN eingespielt, falls du TeX Live benutzt, sollte das dann am morgen irgendwann verfügbar sein. 

Das ganze ist jetzt über 
```
colorback=title,
colorback=head,
colorback=body
``` 

zusätzlich zu den true/false werten ergänzt worden. Beschreibung findet sich wie üblich in der DEMO-TUDaPub.pdf

**Comment by m7a** [comment]
Danke vielmals für die schnelle Implementierung!
Ich kann bestätigen, dass die neuen Optionen in der Version 3.08 funktionieren.

Als Hinweis, falls nochmal jemand das selbe Problem haben sollte: Die Reihenfolge der Optionen ist zu beachten. Bei mir funktioniert `logo=body,colorback=head` nicht aber `colorback=head,logo=body`.

**Comment by TeXhackse** [comment]
Das steht auch in der Demo Datei mit drin.
Also dass die Einstellung von colorback nach der Auswahl der Logoposition passieren soll. Ich kann das aber bei Gelegenheit vielleicht noch deutlicher machen. 

Liegt einfach daran, dass `logo=head` eigentlich immer farbig hinterlegt sein soll und um die Vorherigen Einstellungen nicht zu beeinflussen.
