### ISSUE TITLE
How to change/remove "date" on titlepage?

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#261]
On the title page of "tudapub" there's the current date written within the subtitle-box. Its printed in american format and my professor wants it in german format. Is there any way to change the format of this date or even remove it from the title?

Best regards!

![Capture](https://user-images.githubusercontent.com/62886054/98918692-39695780-24ce-11eb-8f9e-982b55b233cb.JPG)

**Comment by TeXhackse** [comment]
As for all standard LaTeX classes the date is initialized as `\date{\today}` so ofc you can replace it by setting `\date{<custom date>}` or remove it setting it empty `\date{}`.
