### ISSUE TITLE
Undefined control sequence in tudarules.sty at line 139 

### ISSUE THREAD

**Issue by m0m0khan** [tudace/tuda_latex_templates#262]
Hello,

When I try to compile TUDaThesis.tex, I get the following error:

"
ERROR: Undefined control sequence.

--- TeX said ---
l.139 \str_case:Vn
                   \g_ptxcd_department_str {
--- HELP ---
TeX encountered an unknown command name. You probably misspelled the
name. If this message occurs when a LaTeX command is being processed,
the command is probably in the wrong place---for example, the error
can be produced by an \item command that's not inside a list-making
environment. The error can also be caused by a missing \documentclass
command.
"

Could anyone please help me to solve this?

**Comment by TeXhackse** [comment]
Hi there,
at that moment I am only able to have a guess.

Your LaTeX distribution might be outdated. 

The output excerpt you showed is not one tex would give you, so probably your Editor also has an impact on this. 

If you need further help, I'd need more information or a log file.

**Comment by m0m0khan** [comment]
My tex distribution was old. I updated it and it worked. Thanks
