### ISSUE TITLE
How to change margin after top bar?

### ISSUE THREAD

**Issue by unconsciou5** [tudace/tuda_latex_templates#263]
I would like to get more space for my pages in my document of [class=article]
ive tried using `custommargins=geometry` but it gives me the same margin as without custommargins
please let me know how i can modify this margin to reach it
![grafik](https://user-images.githubusercontent.com/46046233/99200563-622b6e80-27a6-11eb-895b-1ae9afffd9bf.png)

**Comment by TeXhackse** [comment]
`custommarins=geometry` allows you to modify it using `\geometry`. But this loads the default margins and you can add aditional settings before `\begin{document}`

The distance between both is called `headsep` so you can change it using 
```
\geometry{headsep= 2cm}%choose any length you'd like to
```
For more details on the geomety options, please have a look at the geometry documentation.


Pay attention to the fact, that the section heading also includes the `sectionbeforeskip` if you want to change this one, it would be done by using KOMA-Scripts `\RedeclareSectionCommand`

**Comment by unconsciou5** [comment]
Thank you very much, works like a charm
