### ISSUE TITLE
tudapub kompiliert nicht mehr (bereits gefixter Bug in XCharter)

### ISSUE THREAD

**Issue by Krokodil005** [tudace/tuda_latex_templates#266]
Hallo, gestern habe ich mal wieder die Packages in der MikTex-Konsole geupdatet. Hier war laut MikTex auch ein Update für tuda-ci vom 24.11.2020 dabei. Heute werden alle Dokumente, die "tudapub" nutzen, nicht mehr erstellt. Der Kompiler gibt aus: "Der Prozess endete mit Fehler(n)", aber im Log in Texstudio sind keine Fehler gelistet (nur einige Warnungen, die aber auch schon vorher vorhanden waren (ob das gut ist, sei mal so dahin gestellt)). In den Arbeitsordnern entstehen weder .pdf noch .log Dateien, alte .pdf Dateien verschwinden nach einem erneuten Kompilierversuch. "tudabeamer" und allgemeine Klassen wie "article" funktionieren nach wie vor. Zweimaliges De- und wieder Installieren von TexStudio und MikTex haben nichts geändert, auch TexWorks hatte das gleiche Problem. Hier ein Beispiel, dass vorher kompiliert hat, es jetzt aber nicht mehr tut:

\documentclass[
ngerman,
ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub\label{key}
class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
accentcolor=9c,% Auswahl der Akzentfarbe
custommargins=false,% Ränder werden mithilfe von typearea automatisch berechnet
marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
%BCOR=5mm,%Bindekorrektur, falls notwendig
parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Sript
fontsize=12pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%logofile=tuda_logo, %Falls die Logo Dateien nicht vorliegen
pdfa=false,
]{tudapub}
\begin{document}
	May the force be with you!
\end{document}

Ersetzt man hier das "tudapub" durch "tudabeamer", kompiliert die Datei ganz normal (nur eben als Folien). Ist es möglich, die alte Version des Packages wieder hochzuladen bzw. das neue schnellstmöglich zu fixen? Und ist der Fehler noch bei anderen aufgetreten?

Danke im Voraus!

Viele Grüße und einen gute Start in die Adventszeit!

**Comment by TeXhackse** [comment]
Hallo,
ich hab versucht das zu rekonstruieren, prinzipiell ist ein Log da hilfreich.
Ich glaube, dass es nicht an uns liegt also kann ich das wahrscheinlich nicht direkt fixen.

pdfLaTeX spuckt im aktuellen Updatestatus von MikTeX folgende Fehlermeldung 
> !pdfTeX error: pdflatex.exe (file xch_rydp4l.enc): cannot open encoding file for reading
==> Fatal error occured, no output PDF file produced!


Und ja, anscheinend filtern Editoren diese Nachricht heraus. Das verwundert mich ebenso, aber ich kann dem gerade nicht nachgehen. 
Insgesamt genügt für die Rekonstruktion die das folgende Minimalbeispiel
```
\documentclass{article}
\usepackage{XCharter}
\begin{document}
	test
\end{document}
```
Es hat demnach nicht wirklich was mit tuda-ci zu tun, aber ich versuch drum zu kümmern.

Dieser Bug betrifft anscheinend nur die T1 Version der Schriftart. Es würde daher helfen auf lualatex zu wechseln. Ansonsten kann ich auch einen temporären Workaround auf eine andere Schriftart zeigen. 
Das geht in den meisten Editoren auch einfach über einfügen des folgenden Kommentars in die erste Zeile des Dokuments.
```
% !TeX program=lualatex 
```
tudabeamer ist nicht betroffen, weil dort die Serifenlose als Standardschrift eingestellt ist. 

Ich hoffe das hilft erstmal weiter.

**Comment by Krokodil005** [comment]
Guten Abend,
super, vielen Dank für die schnelle Rückmeldung und Hilfe! Der Hinweis mit lualatex hat erstmal geholfen. Dann heißt es wohl Warten auf das Update.
VG
