### ISSUE TITLE
tudapub and index

### ISSUE THREAD

**Issue by Zentox** [tudace/tuda_latex_templates#267]
I want to use `imakeidx` in tudapub but the hyperlinks are not working. It seems like that I need load the package before `hyperref`. Therefore I  tried the solution below but I receive an error. Is there a way to make the hyperlinks working? (

Error: `! LaTeX Error: Missing \begin{document}.`

```tex
%\RequirePackage{scrlfile}
%\AfterClass{scrartcl}{
 %   % Needs to be  loaded before hyperref or else  the hyperlinks for the index are not working
%    \RequirePackage{imakeidx}
%}
\documentclass[
    class = report
    ]{tudapub}

\usepackage{imakeidx}
\makeindex[
    columns = 3,
    title = Custom index title
]
\begin{document}
\chapter{Chapter}
\index{Chapter}
Test
\printindex
\end{document}
```

**Comment by TeXhackse** [comment]
Could you please attach a log file? I cannot reconstruct that. For me the hyperlinks are working fine with the setup you posted.

**Comment by Zentox** [comment]
I forgot to mention that the hyperlinks on the page numbers are not working
```tex
\documentclass[
    class = report
    ]{tudapub}

\usepackage{imakeidx}
\makeindex[
    columns = 3,
    title = Custom index title
]
\begin{document}
\chapter{Chapter}
\index{Chapter}
Test
\printindex
\end{document}
```
This code snippet compiles but the hyperlinks on the page numbers in index are not working.

```tex
\RequirePackage{scrlfile}
\AfterClass{scrartcl}{
    % Needs to be  loaded before hyperref or else  the hyperlinks for the index are not working
    \RequirePackage{imakeidx}
}
\documentclass[
    class = report
    ]{tudapub}

\makeindex[
    columns = 3,
    title = Custom index title
]
\begin{document}
\chapter{Chapter}
\index{Chapter}
Test
\printindex
\end{document}
```
This snippet only works only without the option `class = report`.
[main.log](https://github.com/tudace/tuda_latex_templates/files/5618755/main.log)

**Comment by TeXhackse** [comment]
Strange, with MikTeX I received the hyperlink working without any adjustment. Anyway with TeX Live I did not.

Anyway scrlfile is no longer needed since the kernel now provides methods for this. So what you want is probably the following:
```
\AddToHook{package/before/hyperref}{\RequirePackage{imakeidx}}
\documentclass[
    class = report
    ]{tudapub}

\makeindex[
    columns = 3,
    title = Custom index title
]
\begin{document}
\chapter{Chapter}
\index{Chapter}
Test
\printindex
\end{document}
```
`\RequirePackage` is doing the same as `\usepackage` but could internally also be loaded before the documentclass command, that's why one would usually prefer this, in that case.

**Comment by Zentox** [comment]
Thanks a lot! I did not know that and will read more about that.
