### ISSUE TITLE
tuda-pub, department=mecheng: Position Seitenzahl

### ISSUE THREAD

**Issue by rough-robster** [tudace/tuda_latex_templates#268]
Hallo,

erstmal vielen Dank für die Arbeit an dem Paket.

Mit der tuda-pub klasse mit der mecheng-Option werden die Seitenzahlen sehr eng an der Linie des Pfeils positioniert. Das sieht sehr unschön aus. Optisch wäre es besser, wenn die Seitenzahl vertikal zentriert mit dem Maschinenbau-Logo platziert werden würde.

Hier in der Skizze sieht man ungefähr, wie ich es mir vorstelle: ![skizze](https://user-images.githubusercontent.com/75376084/100886545-44534e80-34b4-11eb-83c2-ad14601a59e8.PNG)

Hier ist als Beispiel eine pdf-Datei, welche mit dem unteren Code generiert wurde: [tudapub_minimal.pdf](https://github.com/tudace/tuda_latex_templates/files/5629927/tudapub_minimal.pdf)

```
% !TeX program = lualatex

\documentclass[
    type=intern,
    marginpar=false,
    ruledheaders=section,
    department=mecheng,
    fontsize=11pt,
    ]{tudapub}

\usepackage{lipsum}

\begin{document}

\title{Minimalbeispiel}

\maketitle

\lipsum

\end{document}
```

**Comment by TeXhackse** [comment]
Ich muss das prüfen und die entsprechen Absprachen nochmal raussuchen, dass ich ncihts übersehe. Eine Zentrierung wäre sehr tief, ich glaube mich zu erinnern, dass die eigentlich oben bündig sein sollten. Ich prüfe das nach und gebe dann Bescheid.

**Comment by TeXhackse** [comment]
Das ist leider untergegangen, da ist tatsächlcih was beim update falsch gelaufen, das war mal richtig implementiert, die Seitenzahl soll allerdings mit dem logo oben bündig platziert werden. 

Die richtige Version der tudamecheng.cfg liegt ab jetzt im Repo (https://github.com/tudace/tuda_latex_templates/blob/master/tex/tudamecheng.cfg) und kann ggf. im lokalen Arbeitsverzeichnis eingebunden werden, um die installierte Version zu überschreiben. Der Release wartet noch auf Rückmeldung betreffend #269
