### ISSUE TITLE
Randnotizen entfernen

### ISSUE THREAD

**Issue by buchhorn** [tudace/tuda_latex_templates#27]
Hallo,
die Dokumentation zur Benutzung der einzelnen Optionen ist leider etwas knapp. Was sind die Einstellungsmöglichkeiten zu marginpar? Wie kann ich die Randnotizspalte in tudapub entfernen?

**Comment by TeXhackse** [comment]
`marginpar=false`
deaktiviert den Platz, der sonst für die Randnotizspalte reserviert ist. Der Mechanismus für die Randnotizen wird nicht deaktiviert. Falls also `\marginpar` genutzt wird, werden diese auch verarbeitet. (Sofern die Standard-Definition gilt.)

Den Hinweis bezüglich false sollte ich noch ergänzen. Danke für den Hinweis. 

Ich hoffe das hilft weiter.

**Comment by buchhorn** [comment]
Ja, vielen Dank!

Ich fände es generell nicht schlecht, wenn die Optionen in der Doku mit allen Einstellungsmöglichkeiten gelistet werden.

**Comment by TeXhackse** [comment]
Ja *ertappt* war alles etwas chaotisch, aber wir arbeiten dran.
