### ISSUE TITLE
Undefined control sequence. in tudapub.cls Zeile 98

### ISSUE THREAD

**Issue by the-powl** [tudace/tuda_latex_templates#272]
Ich habe über MikTex das tuda-ci Package installiert und in TeXstudio die DEMO-TUDaThesis.tex kompiliert. Dabei erhalte ich eine pdf-Ausgabe aber es erscheint noch die Fehlermeldung Undefined control sequence. } in Zeile 98. Leider weiß ich nicht, wie ich das beheben kann und warum das auftritt. Kann jemand helfen?

![fehler](https://user-images.githubusercontent.com/23441799/103463723-becef280-4d2e-11eb-8d22-498b63a90614.png)

**Comment by TeXhackse** [comment]
Der Screenshot zeigt leider nicht die wirkliche Fehlermeldung, sondern lediglich die gefilterte Variante. Die volle Fehlermeldung ist über den Reiter „Fehler und Warnungen“ oder direkt in der zugehörigen log-datei zu sehen. Vielleicht hilft das ja schon weiter. Ohne mehr Infos kann ich das leider nicht rekonstruieren.

**Comment by the-powl** [comment]
Ah pardon, der Fehler im Log lautet:
! Undefined control sequence.
<argument> \LaTeX3 error: 
                Misplaced equals sign in key-value input on line 98
l.98 }

**Comment by TeXhackse** [comment]
Da die Demo-Dateien in einer aktuellen MikTeX Installation fehlerfrei durchlaufen, würde ich davon ausgehen, dass eine Änderung an den Klassenoptionen vorgenommen wurde.

Der Fehler sagt, dass in einer Liste von Key-Value Einträgen die Syntax falsch ist. 
Ohne den Code gesehen zu haben, würde ich vermuten, dass bei der Anpassung von Dokumentenklassenoptionen wahrscheinlich ein Komma vergessen wurde. Diese findet man in der eigenen MikTeX-Installation unter  `C:\Program Files\MiKTeX\doc\latex\tuda-ci\example` (`C:\Program Files\MikTeX` ist der Installationsordner bei Standardeinstellungen)

Eine andere Möglichkeit wäre, dass zuvor mit einer veralteten Version kompiliert wurde und noch alte Hillfsdateien da sind. Um das auszuschließen kann man unter TeXstudio im Menü > Tools > Hilfsdateien aufräumen ausführen. Das ist für diese Fehler zwar unüblich, allerdings allgemein ein Hinweis zum Debugging.

Falls das hilft, bitte ich darum das Issue zu schließen.

**Comment by TeXhackse** [comment]
@the-powl 

Hat sich das Problem gelöst? Falls nicht bitte ich um eine Log-Datei bzw. ein Minimalbeispiel.

**Comment by TeXhackse** [comment]
Ich schließe das dann mal, da ich davon ausgehe, dass sich das erledigt hat.

**Comment by the-powl** [comment]
Hallo, der Fehler besteht weiterhin. Wollte mich heute wieder damit befassen.
Was ich getan habe:
- MiKTeX installiert
- TeXstudio installiert
- das tuda-ci package über den Paketmanager von MiKTex installiert
- Die datei C:\Program Files\MiKTeX\doc\latex\tuda-ci\example\DEMO-TUDaThesis.tex in einen neuen Ordner kopiert und von dort aus über TeXstudio kompiliert.

Darüber hinaus wurde nichts verändert. Auf einem anderen Rechner habe ich die Prozedur gerade wiederholt, hier ist der Fehler allerdings nicht reproduziertbar. Was kann ich noch tun?

**Comment by TeXhackse** [comment]
Eine komplette Log Datei würde helfen. Falls der LaTeX-Lauf über den roten Stop-Knopf beendet wird, wird diese trotzdem bis zum Abbruch geschrieben. 
Dann kann ich das mit meiner Version abgleichen.

**Comment by the-powl** [comment]
Ich habe den Fehler ausfindig machen können. 

`\Metadata{
	title=Titel der Arbeit,
	author=Vorname Nachname
}`

ich habe beim title das Komma am Ende der Zeile vergessen, dadurch entstand der Fehler. Danke für die Hilfestellung soweit!
