### ISSUE TITLE
tudaexercise: points parameter does not support half points

### ISSUE THREAD

**Issue by danielrutz** [tudace/tuda_latex_templates#273]
Consider following MWE:
```latex
\documentclass{tudaexercise}
\begin{document}
\begin{task}[points=2.5]{Test Exercise}
\begin{subtask}[title=Test Subtask,points=2.5]
Bla
\end{subtask}
\end{task}
\end{document}
```
Expected behaviour: The titles should contain "2.5 Points"
Actual behaviour: The titles say "2 Points". There is a ".5" randomly floating above the title.
![Screenshot_20210111_211527](https://user-images.githubusercontent.com/2223467/104233462-34833e80-5452-11eb-88fe-f1e84975d946.png)

Tested with tudaexercise 2020/11/12 v3.08 on LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux). The TeX distribution is patched to the newest version offered by the Arch Linux package repository.

**Comment by TeXhackse** [comment]
You are right, because points are saved to an integer.

That's why we also added credit. 
you can use `credit=2.5` for a custom setup and replace the `\creditformat`
Based on your example, this would be
```
\documentclass{tudaexercise}
\renewcommand*{\creditformat}[1]{\space(#1\space\PointName)}
\begin{document}
	\begin{task}[credit={2.5}]{Test Exercise}
		\begin{subtask}[title=Test Subtask,credit=2.5]
			Bla
		\end{subtask}
	\end{task}
\end{document}
```

**Comment by danielrutz** [comment]
Hi,
thank you a lot for your help! I guess I should read the documentation a little more precisely next time...

**Comment by TeXhackse** [comment]
@danielrutz In case you are interested from 3.13 on points is a floating point value.  I changed this because we had to change some internals for the reference mechanism to create automatic tables of credits.
