### ISSUE TITLE
Literaturverzeichnis nicht sichtbar

### ISSUE THREAD

**Issue by ramona3300** [tudace/tuda_latex_templates#274]
Ich habe ein Problem mit dem Literaturverzeichnis, es wird nicht im Dokument angezeigt und Referenzen mit /cite haben keine Wirkung. Problem tritt bei den Beispieldokumenten auf. Dabei macht es keinen Unterschied, ob ich die .bib Datei in der Präambel oder im Dokument einbinde.

MikTex Version 2.9 und neustes tuda-ci Package Version 3.09

**Comment by TeXhackse** [comment]
Ich rate jetzt mal. 

Das Literaturverzeichnis wird bei der Voreinstellung mit Biber erzeugt. Kann es sein, dass der Editor auf BibTeX eingestellt ist?

Grundsätzlich muss für die Erzeugung des Literaturverzeichnisses erst der LaTeX-Compiler laufen, dann das Literaturverzeichnisprogramm (meistens BibTeX oder Biber). Und dann nochmal LaTeX. 

Viele Editoren machen die Schritte von selbst hintereinander. Und deswegen muss das eingestellt werden.

Falls TeXstudio verwendet kann dies auch über einen Kommentar 
```
%!TeX TXS-program:bibliography = txs:///biber
```
für das einzelne Dokument abweichend gesetzt werden. Ansonsten geht das über die Einstellungen unter Erzeugen.

**Comment by ramona3300** [comment]
Danke, das hat funktioniert. Ich war nur überrascht, dass es ohne Anpassung vorher bei einer Fachgebietsvorlage funktionierte und den Vorlagen nicht.

**Comment by TeXhackse** [comment]
Schön zu hören, dann schließe ich dieses Issue. 

Einfach zur Info: Alte Vorlagen verwenden oft noch BibTeX. Das kann leider einiges nicht, also zum Beispiel sind Umlaute und Sonderzeichen da etwas kompliziert. Ich würde daher – wenn möglich – allgemein den Umstieg auf Biber empfehlen, das macht vieles deutlich einfacher :)
