### ISSUE TITLE
title page, titleimage addTitleBoxLogo not working

### ISSUE THREAD

**Issue by ramona3300** [tudace/tuda_latex_templates#275]
Hi, 
wenn ich ein Fachbereichslogo unter das TU Logo setzten möchte mit \titleimage oder \addTitleBoxLogo* und \includegraphics kompiliert das Dokument nicht. Getestet mit dem Thesis-Beispieldokument. Habe die Befehle unter \department positioniert.

Habe ich etwas falsch gemacht bei der Implementation?

Danke

**Comment by schoeps** [comment]
Bitte ein Minimalbeispiel posten und die Fehlermeldung nennen, sonst können wir wenig machen. 
Wenn ich raten muss: Bild evtl. nicht im Pfad?

**Comment by TeXhackse** [comment]
```
\addTitleBoxLogo{example-image}
\addTitleBoxLogo*{\includegraphics[width=.3\linewidth]{example-image}}
``` 
Sollte auch als Ersatz zum Testen gehen, um auszuschließen, dass es am Bild liegt. 

Ansonsten gilt das was @schoeps sagt. „Kompiliert nicht“ kann leider 1000 Ursachen haben, Der Compiler gibt da normalerweise mehr Informationen.

**Comment by ramona3300** [comment]
Mit einer Fehlermeldung kann ich leider nicht dienen, da durch Druck auf Kompilieren der Prozess `lualatex.exe` gestartet wird und sich aufhängt. 
Habe MikTex Version 2.9 und die neusten Package Updates geladen. 

Im Log ist folgendes das letzte was angezeigt wird:
```
Package tudapub/thesis Info: You submitted examdate data for title
(tudapub/thesis)             information. 
(tudapub/thesis)             This fiel
```

Minimalbeispiel: Änderung von \addTitleBoxLogo zu \titleimage bringen keine Änderung. Die Datei logo.pdf liegt im gleichen Verzeichnis wir die .tex Datei.
```latex
%!TEX program = lualatex
\documentclass[
	ngerman,
	ruledheaders=section,
	class=report,
	thesis={type=bachelor},
	accentcolor=9c,
	custommargins=true,
	marginpar=false,
	parskip=half-,
	fontsize=11pt,
]{tudapub}
\usepackage[english, main=ngerman]{babel}
\begin{document}

\title{TUDaThesis -- Abschlussarbeiten im CD der TU Darmstadt}
\subtitle{\LaTeX{} using TU Darmstadt's Corporate Design}
\author[M. Peischl]{Marei Peischl}
\birthplace{Geburtsort}
\reviewer{Gutachter 1}
\department{ce} 
\institute{Institut}
\group{Arbeitsgruppe}
%
\addTitleBoxLogo*{\includegraphics[]{logo.pdf}}
%
\submissiondate{\today}
\examdate{\today}
\maketitle

\affidavit

\tableofcontents
\end{document}
```

**Comment by TeXhackse** [comment]
Der Unterstrich muss in diesem Fall nicht escaped werden. Unterstiche müssen nur dann escaped werden, wenn sie Ausgegeben werden sollen. Das Erklärt das Problem. Wieso es sich dann allerdings aufhängt.

Die Warnung besagt nur, dass das Feld examdate nicht verarbeitet wird weil der Ausgabemodus für den Gewählten Thesistyp das nicht automatisch im Titel verwendet.

**Comment by ramona3300** [comment]
Ok, Dankeschön für die schnellen Antworten. Dann hat sich mein 'Problem' geklärt.
