### ISSUE TITLE
Displaying title of current chapter in every page's footer

### ISSUE THREAD

**Issue by zhtaihao** [tudace/tuda_latex_templates#276]
Many departments require having the title of the current chapter (section, subsection, ...) in every page's footer.  
The package `fancyhdr` provides this functionality to some extent, but using it manually seems to lead to conflicts with the tudapub document class.  
How could something similar to this be achieved in the tudapub class?  

Below screenshots shows the MS Word template from the Chair of Corporate Finance.
![image](https://user-images.githubusercontent.com/46465678/105641673-ac575d00-5e85-11eb-8247-fe4546124b83.png)

**Comment by schoeps** [comment]
The TUDa templates are based on the Koma class. It supports commands like `\ofoot`. Chapter 5 of the manual discusses headers and footers, e.g. https://ftp.mpi-inf.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/macros/latex/contrib/koma-script/doc/scrguien.pdf#page253. I guess this should do the trick.

**Comment by zhtaihao** [comment]
This does indeed help. Thank you very much for your quick response.  
For future reference, I will include a MWE here:

```latex
\documentclass[fontsize=12pt]{tudapub}
\usepackage{lipsum}
    
\automark{section}
\lofoot{\rightmark}

\begin{document}
    \section{Introduction}
        \lipsum[1-7]
    \section{Conclusion}
        \lipsum[1-7]
\end{document}
```

**Comment by TeXhackse** [comment]
The `\lofoot` command is only working that way, because you are in a onesided document. Generally speaking this would require the `\ifoot` macro. I adjusted your example to use that one instead.

**Comment by nicolasj92** [comment]
It would be nice if this could be added as a standard option
