### ISSUE TITLE
Margins above chapter and section

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#277]
Is it possible to make the margins over \chapter and \section a little smaller?
I tried \geometry{reset, headsep=5mm} but it didn't work. I searched as well for their definition in the class files, which should not be the correct choice.

Thats my header (if this changes anything)

\documentclass[
	ngerman,
	accentcolor=8b,% Farbe für Hervorhebungen auf Basis der Deklarationen in den Corporate Design Richtlinien
	fontsize=12pt,
	marginpar=false,
%	ruledheaders=all,
	thesis={type=master},
	class=report,
]{tudapub}

![image](https://user-images.githubusercontent.com/62886054/106140822-8ecd1080-616f-11eb-9589-acb681439996.png)

![image](https://user-images.githubusercontent.com/62886054/106140919-b0c69300-616f-11eb-9111-5c3822ae4a8b.png)

**Comment by TeXhackse** [comment]
This is the `beforeskip` attribute which can be adjusted using KOMA-Scripts `\RedeclareSectionCommand`., for example:
```
\RedeclareSectioncommand[beforeskip=0pt]{section}
```

Please pay attention, that this doesn't affect the distance between  typearea and identbar. In case you want to change that one, you could use geometry with `custommargins=geometry`.

**Comment by BPollicino** [comment]
Thank you very much! It worked just fine!
