### ISSUE TITLE
Lizenz für Doktorarbeiten ändern

### ISSUE THREAD

**Issue by DrMarkEy** [tudace/tuda_latex_templates#278]
Im Template für Doktorarbeiten ist als Lizenz by-nc-nd 2.0 voreingestellt.
Bei Veröffentlichung über TUprints empfiehlt die ULB aber die CC BY-SA 4.0 Lizenz (siehe https://www.tu-darmstadt.de/media/dezernat_ii/promotionen_dokumente/Dissertation_Erklaerung_Rechte.de.pdf).

Da die by-nc-nd 2.0 zudem veraltet ist, werden Dissertationsschriften mit dieser Lizenz von der ULB nicht mehr angenommen, was zu unnötigen Rückfragen und zusätzlicher Arbeit führt.

**Comment by schoeps** [comment]
Danke für den Hinweis, aber das ist ist uns bekannt, siehe https://github.com/tudace/tuda_latex_templates/issues/251 und 
https://github.com/tudace/tuda_latex_templates/blob/a1fabe1e20ab3bd82ee3ec15dcdaa7c72e857144/example/DEMO-TUDaPhD.tex#L102-L108
Wir haben die Lizenz nicht einfach umstellen können, denn sonst würden wir im schlimmsten Fall eine bewusste Entscheidung eine/r Autor/in nachträglich ändern.

Übrigens: ich glaube nicht, dass die ULB das Recht hat eine Lizenz zu verweigern, denn die Entscheidung liegt ja bei der/m Autor/in.

**Comment by marklaz** [comment]
Beim Bereitstellen auf TUprints kann man im entsprechenden Vertrag manuell auch eine andere Lizenz angeben (§1 (2)). Man muss nicht die vorausgewählte akzeptieren:

https://www.ulb.tu-darmstadt.de/service/elektronisches_publizieren/tuprints_vertrag.de.jsp

**Comment by DrMarkEy** [comment]
Danke für die schnelle Antwort. Dass man den default schlecht ändern kann, klingt absolut logisch. Ich habe jetzt versucht, die Lizenz via \tuprints{urn=12345,printid=12345,license=cc-by-sa-4.0} selbst anzupassen. Leider wird aber nur cc-by-4.0 und nicht cc-by-sa-4.0 unterstützt. Vielleicht könnte man zumindest diese Option noch hinzufügen?

**Comment by schoeps** [comment]
Man kann auch jetzt schon eigene Lizenztexten nutzen, ist auch in der Doku beschrieben. Ich nehme den Vorschlag auch cc-by-sa-4.0 als Schlüssel zu hinterlegen aber für das nächste Release mit.

**Comment by TeXhackse** [comment]
Dann würde ich dazu tendieren alle Varianten zu nehmen. Wir wollten ursprünglich nicht zu viele und hatten es daher auf die defaults cc-by-4.0 und cc-by-nc-nd-4.0 reduziert. Dann mach ich da eine generische Anpassung rein, wie ich es ursprünglich mal vor hatte.
