### ISSUE TITLE
Duplicated thanks/footnote on first page if "titlepage=false"

### ISSUE THREAD

**Issue by towadroid** [tudace/tuda_latex_templates#279]
When using the tudapub class with option `titlepage=false`, the command `\thanks` creates two entries on the first page. One in the titlehead and one as a regular footnote at the bottom of the page. The command `\footnote` behaves in  the same way.
 
I am not sure if this is intended behavior but I think this is not what one would expect.

MWE:
```
\documentclass[
titlepage=false,
]{tudapub}

\begin{document}
	\title{Title}
	\author{Author\thanks{Text}}
	\maketitle
\end{document}
```

**Comment by TeXhackse** [comment]
I will hopefully manage to upload a new release including the fix tomorrow. Anyway if it's urgent you can use this as a temporary workaround:
```
\makeatletter
\let\orig@maketitle\@maketitle
\def\@maketitle{\orig@maketitle\let\@thanks\@empty}
\makeatother
```
This would not affect the functionalityafter the fix has been applied published.
