### ISSUE TITLE
Abstand zwischen Kopfzeile und Text anpassen

### ISSUE THREAD

**Issue by brandt1234** [tudace/tuda_latex_templates#28]
Der Abstand zwischen der Kopfzeile und dem Textkörper ist mit persönlich viel zu groß. Wie kann ich das ändern?

**Comment by brandt1234** [comment]
Mir ist bewusst, wie man den Abstand in eigenen Vorlagen anpasst. Allerdings funktioniert keine Lösung, die ich sonst gefunden habe.  Anbei ist ein Bild angehängt, das verdeutlicht, was ich meine. Ich wäre über Hilfe sehr dankbar, da ich die Vorlage ansonsten nicht verwenden kann.
![LAtex](https://user-images.githubusercontent.com/55052280/64633092-c8766d80-d3fa-11e9-8121-740a3634bb6b.PNG)

**Comment by brandt1234** [comment]
Das Packet geometry funktioniert. Allerdings nicht in der Präambel, sondern erst als \newgeometry Befehl im Textkörper. Für die Lösung muss das ganze Seitenlayout neu eingestellt werden. Das kann aber doch nicht die Lösung sein. Zum jetzigen Zeitpunkt, wäre die zur Verfügung gestellte Vorlage für Latex nicht verwendbar. Kann doch nicht sein, dass ich wieder zu Word wechseln muss, wegen so ner Kleinigkeit.

**Comment by schoeps** [comment]
Widerspricht der Abstand dem Design-Guide der TU? Wenn ja, dann wäre es tatsächlich ein Fehler ("Issue"), sonst ist es eben eher eine allgemeine Latexfrage (so wie es derzeit getaggt ist). 

Konkrete Fehler werden wir versuchen schnell zu reproduzieren und zu fixen, aber allgemeinere Themen bleiben ggf. erst einmal liegen (die Meldung ist gerade 3 Tage alt), wenn andere Issues wichtiger erscheinen. Wir hoffen darauf, dass zukünftig erfahrenere Benutzer*innen hier Hilfe anbieten.

> Zum jetzigen Zeitpunkt, wäre die zur Verfügung gestellte Vorlage für Latex nicht verwendbar. 

Die Vorlage ist nicht verwendbar weil Ihnen der Abstand nicht gefällt?

**Comment by brandt1234** [comment]
Ich kenne die Guidelines für das TU Design nicht, der Abstand unterscheidet sich allerdings stark von der Word-Vorlage (und der alten Latex-Vorlage).  Mein Betreuer wird mein Protokoll in dieser Form nicht annehmen und verweist auf Word. Ein Schritt, den ich gerne vermeiden will, weil ich absolut von Latex überzeugt bin. 

Eine normale, schnelle Änderung habe ich nicht gefunden, das ganze Layout über \newgeometry neu zu definieren, erscheint mir sehr umständlich. Die Abstände sind über Variablen definiert, darauf muss ich doch irgendwie Zugriff bekommen können.

Ich weiß, der Beitrag ist erst drei Tage als, danke für die Hilfe. Meine Abgabe ist leider bald, Probleme mit der Vorlage sind nicht eingeplant.

**Comment by marklaz** [comment]
Nur nochmal kurz zur Erläuterung:
Die Idee eines Design-Guide/Corporate Design der TU Darmstadt ist, dass eben möglichst konsistente Dokumente erzeugt werden. Die bereitgestellten LaTeX-Vorlagen zielen auf eine entsprechend standardisierte und damit vereinfachte Erstellung von Dokumenten, die diesem CD entsprechen.
Dass der Betreuer diesen Standardabstand ablehnt, ist natürlich bedauerlich, dessen freie Modifikation liegt jedoch nicht im primären Fokus der Templates (zumindest nicht in den aktuellen Versionen 1.x) - streng genommen eigentlich auch nicht in späteren (s.o.).

Das heißt zum aktuellen Zeitpunkt:
Die Templates basieren auf Koma-Script, das eine (hier angepasste) eigene Layoutkonfiguration verwendet. Somit wird nur teilweise auf geometry zurückgegriffen. Sind \geometry{}-Befehle in der Präambel komplett ohne sichtbare Wirkung?
Leider kann ich es hier gerade nicht selbst testen und kann daher keine unmittelbaren Vorschläge machen. Vielleicht springt ein anderer TUDa-LaTeX-User ein...

Für die Zukunft:
Es kann ein Feature Request für die Bereitstellung einer Klassenoption zur Randanpassung formuliert werden. Dessen Umsetzung ist jedoch nicht kurzfristig zu erwarten.

**Comment by marklaz** [comment]
Schon mal so etwas in der Präambel ausprobiert?
In Anlehnung an [https://texwelt.de/fragen/15050/abstand-zwischen-kopfzeile-und-textkorper](url)

\AfterCalculatingTypearea{%
  \addtolength{\headsep}{-.5\baselineskip}%
  \addtolength{\textheight}{.5\baselineskip}%
}

**Comment by TeXhackse** [comment]
@brandt1234 
Da nichts mehr kam: Ist das akute Problem behoben, oder können wir da noch etwas tun? Das Hauptproblem ist, dass wir mit den Vorgaben übereinstimmen aber die Word-Vorlagen auch von Version zu Version leicht unterschiedlich sind. Ich kann ggf. dabei helfen die Werte zu erzwingen, allerdings müssten wir dafür Werte haben.

**Comment by brandt1234** [comment]
Ich bin im Moment nicht an meinem Arbeitsrechner auf dem auch die aktuelle Version das TU-Designs installiert ist. Vielen Dank für eure Vorschläge, ich werde sie am Montag direkt ausprobieren.

Das Bild zeigt den Abstand in der aktuellen Word Vorlage, ziemlich genau so sah das auch in der letzten Latex Vorlage aus. Die Abstände sind 1,25cm vom Rand zur Kopfzeile und 2,5cm  "oben", was wohl der Absand des Textkörpers zum Seitenrand darstellt.
Ich werde die Vorschläge wie gesagt direkt am Montag ausprobieren! Danke!
![Word](https://user-images.githubusercontent.com/55052280/64908433-93bb2c80-d700-11e9-9eda-80de75ea76fc.PNG)
)

**Comment by open711** [comment]
In einem geschlossenen Issue kam schon einmal die Frage wegen den Rändern auf und \newgeometry wurde als Lösung eingeführt. Damit muss man dann allerdings alles einzeln definieren.

TeXhackse gab den Tipp, dass man auch den DIV-Wert erhöhen könnte.  Ich habe allerdings keinen vernünftigen Wert gefunden, der ein Layout ähnlich der Word-Vorlage erzeugt (am ehesten div=13).

Ich kam auf ein ein Layout ähnlich der Word-Vorlage, wenn ich den foot und head aus der Berechnung nehme. Damit habe ich halt nicht mehr das  Randbreiten Verhältnis 5:5:5:8.
\KOMAoptions{footinclude=false, headinclude=false}
 \recalctypearea

**Comment by brandt1234** [comment]
> Schon mal so etwas in der Präambel ausprobiert (dies wäre im wesentlichen eine schnelle Lösung, sofern es funktioniert)?
> In Anlehnung an https://texwelt.de/fragen/15050/abstand-zwischen-kopfzeile-und-textkorper
> 
> \AfterCalculatingTypearea{%
> \addtolength{\headsep}{-.5\baselineskip}%
> \addtolength{\textheight}{.5\baselineskip}%
> }
Dieser Befehl hat leider keine Wirkung.
Der \KOMAoptions{footinclude=false, headinclude=false} Befehl funktioniert, leider sieht es dann so aus: 
![Koma](https://user-images.githubusercontent.com/55052280/64967037-28a85c00-d8a0-11e9-89bb-a5354286bd7e.PNG)

Mit \newgeometry geht es, ich werd sobald ich die Zeit finde die entsprechenden Werte hochladen.

**Comment by marklaz** [comment]
Dieser Befehl hat eine Wirkung, man muss nur den Faktor entsprechend heraufsetzen:
\AfterCalculatingTypearea{%
	\addtolength{\headsep}{-4.\baselineskip}%
	\addtolength{\textheight}{4.\baselineskip}%
}
vgl. vorher 
[DEMO-TUDaPhD.pdf](https://github.com/tudace/tuda_latex_templates/files/3619348/DEMO-TUDaPhD.pdf)
mit Modifikation
[DEMO-TUDaPhD_mod.pdf](https://github.com/tudace/tuda_latex_templates/files/3619353/DEMO-TUDaPhD_mod.pdf)

Leider funktioniert der Befehl zu gut, da dann natürlich alle Seitenspiegel verschoben werden (vgl. Seite 3 der modifizierten Version).

**Comment by marklaz** [comment]
Mein Lösungsvorschlag ist folgender:
- Im Frontmatter sollte bzgl. Formatierung generell für alle Überschriften nicht die Chapter-Variante aus dem Haupttext gewählt werden, die mit vergrößertem oberen Abstand zur Titelzeile versehen ist, sondern die Section-Variante, die weiter oben auf der Seite platziert ist. Im Vorspann erscheint dieser große Abstand nicht wirklich adäquat. (Natürlich aknn auch die Chapter-Variante weiter verwendet werden, allerdings sollte dann der Satzspiegel der jeweils ersten Seite eines Abschnitts entsprechend nach oben verschoben werden.)
- Im Mainmatter sollte eine Option bereitgestellt werden (@TeXhackse: existiert diese nicht sogar bereits?), wie die Überschriften auf oberster Gliederungsebene formatiert werden sollen:
(i) so wie es aktuell umgesetzt ist, d.h. mit großem Abstand zur Titelzeile (Chapter-Formatierung)
(ii) analog zum (zukünftigen) Vorspann, d.h. mit kleinerem Abstand zur Titelzeile (Section-Formatierung)
- Im Backmatter würde ich wieder wie im Frontmatter verfahren.

@TeXhackse 
Wenn dies bereits alles grundsätzlich so angelegt ist (insbesondere im Mainmatter), wäre eine kurze Ergänzung der Doku sicher ausreichend.

**Comment by TeXhackse** [comment]
Also, ich antworte erstmal auf das Problem, dann auf den Vorschlag von @marklaz  separat, sonst komme ich selbst durcheinander:

Grundsätzlich geht bezüglich Anpassung alles, was sonst auch geht. Allerdings wird der Satzspiegel momentan sowohl bei `\begin{document}` als auch bei `\maketitl` zurückgesetzt.
Das werde ich leichter ergänzbar machen. Das sollte heute abgeschlossen werden.

Grundsätzlich ist -- und ich habe das extra nochmal geprüft der Abstand mit den Corporate Design Richtlinien konform. Ich hab keine Ahnung auf welche Version der Word Vorlage sich dieses Issue bezieht, aber auch die mit vorliegenden Versionen haben einen Abstand in dieser Größe.

Die schnelle -- jedoch unschöne -- Lösung wäre die Länge einfach direkt zu setzen, damit ist es möglich alle anderen Werte identisch zu lassen.

```
\setlength{\headsep}{0pt}
```
Wenn der Bedarf besteht die Abstände nur teilweise zu übernehmen, finden sich in der Tabelle auf Seite 9 der Designrichtlinien  (3. Auflage, von 2011) die verwendeten Werte. Diese werden intern über expl3 Variablen gespeichert.
 Damit ist es möglich die Einstellungen für a4 wie folgt zu wählen:

```
\geometry{
	twoside,
	top=15mm,
	inner=20mm,
	outer=15mm, 
	bottom=20mm,
	includehead,
	includefoot,
	nomarginpar,
	headsep=0pt
}
```

Aufgrund der oben beschriebenen Implementierung muss das derzeit mit `\newgeometry` innerhalb des Dokuments und nach `\maketitle` erneut geladen werden. Das wird heute noch behoben.

**Comment by TeXhackse** [comment]
So, jetzt zu @marklaz 

> Im Frontmatter sollte bzgl. Formatierung generell für alle Überschriften nicht die Chapter-Variante aus dem Haupttext gewählt werden, die mit vergrößertem oberen Abstand zur Titelzeile versehen ist, sondern die Section-Variante, die weiter oben auf der Seite platziert ist. Im Vorspann erscheint dieser große Abstand nicht wirklich adäquat. (Natürlich kann auch die Chapter-Variante weiterhin verwendet werden, allerdings sollte dann der Satzspiegel der jeweils ersten Seite eines Abschnitts entsprechend nach oben verschoben werden.)

Das halte ich für Problematisch, da ein `\chapter` damit im Frontmatter eine vollkommen andere Optik bekommt als im Hauptteil. Die Inhaltsverzeichnisstruktur müsste ja gleich bleiben....

Also ich beuge mich da euren Wünschen, merke nur an, dass das wahrscheinlich zu Verwirrung führt. Aber kann ich schon machen.


>     Im Mainmatter sollte eine Option bereitgestellt werden (@TeXhackse: existiert diese nicht sogar bereits?), wie die Überschriften auf oberster Gliederungsebene formatiert werden sollen:

Es existiert eine Option um die Linien außennrum zu steuern. Die Abstände der Überschriften sind den vorliegenden Dokumenten entnommen. Viele davon haben jedoch kein \chapter im eigentlichen Sinne, sondern lediglich \sections, dadurch ist der Unterschied in der Wahrnehmung entstanden. 

>     (i) so wie es aktuell umgesetzt ist, d.h. mit großem Abstand zur Titelzeile (Chapter-Formatierung)
>     (ii) analog zum (zukünftigen) Vorspann, d.h. mit kleinerem Abstand zur Titelzeile (Section-Formatierung)

Das geht wie gesat, nur verstehe ich nicht ganz, wieso das Sinnvoll ist, wenn man dann doch einfach auf eine Dokumentenklasse ohne chapter wechseln kann. Das gesamte LAyout der book-Basis ist darauf ausgelegt, dass Abstände das ganze gliedern. Um viel Text unterzukriegen, würde ich dann eine article-basierte Variante nehmen.

>     Im Backmatter würde ich wieder wie im Frontmatter verfahren.

Selbige Bedenken.

**Comment by TeXhackse** [comment]
@marklaz Ich fixe nur den Bug, der die Möglichkeit von custommargins=geometry momentan nur schwer verwendbar macht. Bei allem andere warte ich ab.

**Comment by marklaz** [comment]
Ja, wir warten am besten mal ab.

Noch eine kurze Anmerkung zu @TeXhackse:
Ich teile die Bedenken hinsichtlich struktureller Konsistenz des Dokuments, sehe jedoch keinen unüberbrückbaren typographischen Widerspruch darin, die Abschnittsüberschriften im Vorspann anders zu formatieren als die Kapitelüberschriften im Dokument. (Gehört das Affidavit formatierungstechnisch zum Vorspann oder ist es ein Zusatz der unabhängig vom restlichen Dokument steht?) 
Dies natürlich nur derart, dass die durch preface, toc, lof etc. getriggerten \chapter-Befehle im frontmatter einfach eine andere Formatierung erzeugen, als die realen \chapter-Befehle im mainmatter, d.h., die Struktur der LaTeX-Source bliebe unverändert, und auch eine Umdefinition der Vorspann-Befehle zur Verzeichniserzeugung wäre nicht notwendig. 
Damit bin ich aber auch schon fertig mit meinem Einwurf :-)

Da eine Implementierung aber wahrscheinlich eher aufwendig ist im Verhältnis zum Nutzen, nehme ich meinen obigen Vorschlag gerne wieder zurück. D.h., die Klassenzuordnung von PhD- und BSc-/MSc-Thesis kann so bleiben wie gehabt, und TUDaPub kann für (tendenziell kürzere) Reports oder Artikel verwendet werden, bei denen die Platzproblematik ggf. eine größere Relevanz besitzt.

**Comment by TeXhackse** [comment]
Die Implementierung wäre dank KOMA-Script relativ easy. Das ist gar nicht das Problem.

Es geht eher darum, dass es sehr komisch wikt mit einen `\cleardoublepage` einen Bereich einzuleiten, der dann vielleicht eine Seite lang ist und wie eine `\section` wirkt. Dann kann es passieren, dass über eine Vakatseite platziert wird und dann ist der Text danach ziemlich wenig.
Dann beschweren sich wieder $Menschen, dass zu viel Platz verschwendet wird. Und die Seitenumbrüche rausnehmen macht im Doppelseitigen Modus allerdings noch weniger Sinn.

**Comment by brandt1234** [comment]
Mit \setlength{\headsep}{0pt} ergibt sich auf den ersten Blick das passende Layout. Vielen Dank! Diesen Befehl hatte ich davor schon ausprobiert, allerdings vor \maketitle. Das war vermutlich das Problem, ich wusste nicht, dass dieser Befehl alles andere zurücksetzt.

@marklaz ich schreibe ein Protokoll, daher nutze ich die article Klasse. Als Demo-File habe ich TudaPup verwendet. Ich arbeite also bereits mit der von dir vorgeschlagenen Umgebung.
