### ISSUE TITLE
titleback margins & geometry reset option – Ränder der Titel Rückseite vom tudathesis 

### ISSUE THREAD

**Issue by JessicaMarino** [tudace/tuda_latex_templates#280]
The margins on the back page of the title do not conform to the geometry definitions.

If the document margins are customized (custommargins=geometry), this page is generated outside the paper area (see the figure).
![Titel Rückseite](https://user-images.githubusercontent.com/79210738/108223364-07edd100-713a-11eb-9066-a362b93bd327.JPG)

Only if the default margins are chosen (custommargins=true), this page is generated within the dimensions of the A4 sheet but does not maintain the margins of the document either.
How can you fix these margins?

**Comment by TeXhackse** [comment]
@JessicaMarino I am sorry, but I cannot confirm.

Can you me more information on your geometry configuration and maybe a log file?

**Comment by JessicaMarino** [comment]
this is my main preamble
[mainfile.zip](https://github.com/tudace/tuda_latex_templates/files/5996979/mainfile.zip)


%% ============================================================================
%%
% !TeX program = lualatex
%%
\PassOptionsToPackage{dvipsnames}{xcolor}
\documentclass[
	ngerman,
	ruledheaders=chapter,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=book,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=ing
	},
	accentcolor=2c,% Auswahl der Akzentfarbe
%          custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	custommargins=geometry,% personal marges
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
%	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}

\geometry{
	reset,
	top=2.5cm,
	bottom=2.3cm,
	left=3cm,
	right=2cm,
	includemp=false,
	includehead=true,
	includefoot=true
}


% Der folgende Block ist nur bei pdfTeX auf Versionen vor April 2018 notwendig
\DeclareRobustCommand{\tbs}{\textbackslash}
\usepackage{iftex}
\ifPDFTeX
	\usepackage[utf8]{inputenc}%kompatibilität mit TeX Versionen vor April 2018
\fi

%%%%%%%%%%%%%%%%%%%
%Sprachanpassung & Verbesserte Trennregeln
%%%%%%%%%%%%%%%%%%%
\usepackage{setspace}
%\linespread{1.15}
\setlength{\parskip}{6pt}

\usepackage[ngerman, spanish, main=english]{babel}
\usepackage[autostyle]{csquotes}% Anführungszeichen vereinfacht

% Falls mit pdflatex kompiliert wird, wird microtype automatisch geladen, in diesem Fall muss diese Zeile entfernt werden, und falls weiter Optionen hinzugefügt werden sollen, muss dies über
% \PassOptionsToPackage{Optionen}{microtype}
% vor \documentclass hinzugefügt werden.
\usepackage{microtype}


%%%%%%%%%%%%%%%%%%%
%Literaturverzeichnis
%%%%%%%%%%%%%%%%%%%
%%\usepackage{biblatex}   % Literaturverzeichnis
\usepackage[style=numeric-comp,natbib=true]{biblatex}
\AtEveryBibitem{%
  \clearfield{issn} % Remove issn
  \clearfield{doi} % Remove doi
   \clearfield{isbn} % Remove isbn
   
  \ifentrytype{online}{}{% Remove url except for @online
    \clearfield{url}
  }
}
\bibliography{library}

%%%%%%%%%%%%%%%%%%%
%Paketvorschläge Tabellen
%%%%%%%%%%%%%%%%%%%
\usepackage{array}     % Basispaket für Tabellenkonfiguration, wird von den folgenden automatisch geladen
\usepackage{tabularx}   % Tabellen, die sich automatisch der Breite anpassen
\usepackage{longtable} % Mehrseitige Tabellen
\usepackage{xltabular} % Mehrseitige Tabellen mit anpassarer Breite
\usepackage{booktabs}   % Verbesserte Möglichkeiten für Tabellenlayout über horizontale Linien
\usepackage{multirow}

%%%%%%%%%%%%%%%%%%%
%Paketvorschläge Mathematik
%%%%%%%%%%%%%%%%%%%
\usepackage{mathtools} % erweiterte Fassung von amsmath
\usepackage{amssymb}   % erweiterter Zeichensatz
\usepackage{siunitx}   % Einheiten
\usepackage{amsmath,amsfonts}
\newcommand*{\rttensor}[1]{\overline{\overline{#1}}}
\newcommand{\equal}{=}

%Formatierungen für Beispiele in diesem Dokument. Im Allgemeinen nicht notwendig!
\let\file\texttt
\let\code\texttt
\let\tbs\textbackslash

\usepackage{pifont}% Zapf-Dingbats Symbole
\newcommand*{\FeatureTrue}{\ding{52}}
\newcommand*{\FeatureFalse}{\ding{56}}

% additional packages Jessica!
\usepackage{graphicx}
\graphicspath{{./figures/}}
\usepackage{subfigure}
\usepackage{caption}
\usepackage{enumitem}
\usepackage{float}
\usepackage{hyperref}
\usepackage{listings}
\usepackage{rotating, lscape, threeparttable}
\usepackage{blindtext}
% ref Artem
\usepackage{adjustbox} % more graphic adjusts
\usepackage{varioref} % reference pages in doc
\usepackage{cleveref} % reference style
\usepackage{nicefrac} % a/b in nice way

%\usepackage{tikz} % create graphics in latex
%\usetikzlibrary{external}
%\tikzexternalize[prefix=tikz/]
%\usepackage{pgf} 
%\usepackage{pgfplots}
%\pgfplotsset{compat=newest}
%\pgfplotsset{plot coordinates/math parser=false}
%\usepgfplotslibrary{groupplots}
%\usepgfplotslibrary{fillbetween}
%\usetikzlibrary{patterns}

**Comment by TeXhackse** [comment]
Remove the `reset` option from geometry, and it works and does not change the page setup for the other pages. I will have a look at the cause, because this is indeed a not intended effect, but might take a bit until I find time.

Typographic hint: You are currently mixing up two different types of paragraph breaks. Usually paragraphs either start with an indent or have a skip (usually a half or one baselineskip). You are using indents + a skip of a bit less than a baselineskip and set it to a fixed value. This might lead to issues with the page filling mechanism, because TeX is used to have so called glue in the parskips. This means, the skip is a bit flexible.

E.g. the `parskip=half` option would lead to a 6.8 plus 6.8 pt parskip which means it can vary between 6.8 and 13.6 pt, depending on the rest of the page.

**Comment by JessicaMarino** [comment]
Thank you very much for your help. Now it is work!

**Comment by TeXhackse** [comment]
Issue was caused because the marginpar adjustment which is required for the title material was activated even if the marginpar mechanism was not used.
