### ISSUE TITLE
RGB colors with pdfa=true

### ISSUE THREAD

**Issue by martin-fzd** [tudace/tuda_latex_templates#283]
I am trying to create plots with PFGplots and the TUDa colors.
However, these look very strange with the TUDa template, somehow shinier than it should be:

**this is how the colors should look like**:
![image](https://user-images.githubusercontent.com/26324188/108637575-a99f5600-748b-11eb-8cdd-a088ae5e85d7.png)

Sharelatex Project: https://sharelatex01.ca.hrz.tu-darmstadt.de/4861396118wqtbtnpxbspj

**This is how they do in the tuda_latex_template**:
![image](https://user-images.githubusercontent.com/26324188/108637659-dd7a7b80-748b-11eb-8504-07416a79ae2c.png)
Sharelatex project: https://sharelatex01.ca.hrz.tu-darmstadt.de/4167154365wsvxdbgcybdc

The difference is particularly clear with purple and green.
I tested it on 2 monitors. So either I see it wrong or there really is an issue?

**Comment by TeXhackse** [comment]
Thanks for reporting. 
The PDF/A-mode converts colors to RGB. It was a necessary requirement back then to create valid PDF/A.
I was sure we mentioned this in the docs but I currently can't find it. So I will have a look.

`pdfa=false` will  disable the conversion.

**Comment by TeXhackse** [comment]
Just tested, and it's possible to remove the conversion now, I will prepare the update tomorrow.

**Comment by martin-fzd** [comment]
Thank you for the information. To the best of my knowledge, PDF/A is no longer a ULB requirement, is it? (Maybe @schoeps knows this?)
Regarding the color: Why is the RGB value not used in PDF/A mode? This is already provided in the `TUDacolors.def`.
And a general question, which I am wondering about: Why does it come at all to the distortion of the colors? I thought, the conversion from CMYK -> RGB is unambiguous?

**Comment by schoeps** [comment]
>To the best of my knowledge, PDF/A is no longer a ULB requirement, is it?

I think so too but I will send an email an ask to know this for sure.

**Comment by TeXhackse** [comment]
The RGB value is used. If you check the color in both pdfs you will see that, this the difference between both.

And no color conversion is not unambiguous. Easy explanation on this: CMYK has 10e8 colors, RGB can only show 1.7 ×  10e7. You can get close to the other value but will never exactly reach it.

Beside this the most displays are not calibrated on colors. So the internal conversion is really crappy. But you can see a similar result when printing RGB on a cheap printer.

**Comment by TeXhackse** [comment]
@schoeps I just checked, the only Feature not supported by DVI is PDF/A. Disabling this allows the usage anyway So I added information on this similar to the note about XeLaTeX. In the README I mention the fact that one need to use PDF-output. Are you fine with that?

**Comment by schoeps** [comment]
> Are you fine with that?

Sounds good to me!

By the way: if I recall correctly `pdfa=true` is our default, right? If indeed our OA-platform does not care about this anymore then we may change that seeting anyway, right? - I think that you didn't like from the start :) However, I will open a new issue if I get official confirmation.

**Comment by TeXhackse** [comment]
OT: @schoeps Pfffft. Now that we can create PDF/A in CMYK mode I don't care anymore =P.

**Comment by schoeps** [comment]
Nachtrag: die ULB bestätigt noch einmal, dass PDF/A weiterhin das bevorzugte Dateiformat ist.
