### ISSUE TITLE
Literaturverzeichnis und Zitation

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#284]
Hallo, ich habe ein Problem mit BibLaTeX:
Ich verwende schon länger biblatex mit folgenden Funktionen:

\usepackage[backend=biber,style=chem-angew,sorting=none,language=english,url=false,natbib=true]{biblatex}

Hinzu kommt noch eine Erweiterung, die mir den Zitierstil anpasst (findet man so beim googlen) -> superscript bei der Verwendung von \autocite und eckige Klammern um die Zahlen.

\DeclareCiteCommand{\supercite}[\mkbibsuperscript]%
{\usebibmacro{cite:init}%
	\let\multicitedelim\supercitedelim%
	\iffieldundef{prenote}%
	{}%
	{\BibliographyWarning{Ignoring prenote argument}}%
	\iffieldundef{postnote}%
	{}%
	{\BibliographyWarning{Ignoring postnote argument}}%
	\bibleftbracket%  HIER DIE OEFFNENDE KLAMMER
}%
{\usebibmacro{citeindex}%
	\usebibmacro{cite:comp}}
{}%
{\usebibmacro{cite:dump}%
	\bibrightbracket%   HIER DIE SCHLIESSENDE KLAMMER
}%

In einem neuen Dokument verwende ich nun die exakt gleichen Befehle und das Dokument kompiliert auch ohne weitere Fehler. Heraus kommt allerdings folgendes:

![image](https://user-images.githubusercontent.com/62886054/108861906-0287ff00-75f0-11eb-90de-4a975f15c34b.png)

Trotz dem durchiterieren sämtlicher biblatex-Optionen, Verwendung anderer style-Optionen doppelt und dreifach kompilieren, Zwischenspeichern etc. ändert sich nichts. Die Fehlfunktion kommt zudem nicht durch das Einbinden mehrerer Dokumente zustande, da das Kompilieren im Hauptdokument zum selben Ergebnis führt. Habe ich hier ein kritisches Update bei einem der Pakete verpasst oder ist hier grundlegend etwas falsch?

**Comment by schoeps** [comment]
Können wir ein komplettes MWE haben?

**Comment by BPollicino** [comment]
Ich gehe mal davon aus, dass Du mir MWE ein Minimalbeispiel meinst? 

\documentclass[
	ngerman,
	accentcolor=8b,% Farbe für Hervorhebungen auf Basis der Deklarationen in den Corporate Design Richtlinien
	fontsize=12pt,
	marginpar=false,
	ruledheaders=section,
%	type=thesis,
	thesis={type=master},
	class=report,
	custommargins=geometry,
]{tudapub}

\bibliography{literatur}

\usepackage[backend=biber,style=chem-angew,sorting=none,language=english,url=false,natbib=true]{biblatex}

\DeclareCiteCommand{\supercite}[\mkbibsuperscript]%
{\usebibmacro{cite:init}%
	\let\multicitedelim\supercitedelim%
	\iffieldundef{prenote}%
	{}%
	{\BibliographyWarning{Ignoring prenote argument}}%
	\iffieldundef{postnote}%
	{}%
	{\BibliographyWarning{Ignoring postnote argument}}%
	\bibleftbracket%  HIER DIE OEFFNENDE KLAMMER
}%
{\usebibmacro{citeindex}%
	\usebibmacro{cite:comp}}
{}%
{\usebibmacro{cite:dump}%
	\bibrightbracket%   HIER DIE SCHLIESSENDE KLAMMER
}%

\begin{document}

Alkohole: Ethanol -> Acetaldehyd/Essigsäure\autocite{Sobolev2011}

\end{document}

Hier noch das zugehörige Zitat:

@Article{Sobolev2011,
  author       = {Vladimir I. Sobolev and Konstantin Y. Koltunov},
  date         = {2011-05},
  journaltitle = {{ChemCatChem}},
  title        = {{MoVNbTe} Mixed Oxides as Efficient Catalyst for Selective Oxidation of Ethanol to Acetic Acid},
  doi          = {10.1002/cctc.201000450},
  number       = {7},
  pages        = {1143--1145},
  volume       = {3},
  file         = {:D\:/Nextcloud/01 - Studium Chemie TUD/Master/4. WS Nov. '20 - Apr. '21 - Master-Thesis/Paper/cctc.201000450.pdf:PDF},
  publisher    = {Wiley},
}

**Comment by TeXhackse** [comment]
@BPollicino Ich würde mal `\bibliography` und `\usepackage{biblatex}` in der Reihenfolge vertauschen ;-)

**Comment by schoeps** [comment]
@TeXhackse das hatte ich auch gerade heruasgefunden. Ungerecht!

**Comment by TeXhackse** [comment]
@schoeps Musstest du dafür kompilieren? Dann ist das nicht ungerecht, sondern einfach nur die Tatsache, dass mir das Problem schon öfter begenet ist. Erfahrung nennt sich das ;-)

**Comment by schoeps** [comment]
@TeXhackse ja, klar muss ich kompilieren. Ich bin doch auch nur der Einäugige unter Blinden :) [sorry @BPollicino]

**Comment by schoeps** [comment]
@BPollicino ich nutze ja (auch deswegen) `\addbibresource`

**Comment by BPollicino** [comment]
@TeXhackse das war zu logisch, als dass ich selbst drauf gekommen wäre... sowas passiert wenn man einmal Ordnung in seine Präambel bringt...
Funktioniert wieder einwandfrei!
Danke euch beiden!
