### ISSUE TITLE
Exercise/Exam solution spacing

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#287]
It would be great if the solution environment could evaluate to blank space that the students can use if solution is false.
Ideally, you could specify with an optional argument how much space it should reserve.

**Comment by TeXhackse** [comment]
Sounds like a nice idea. Only issue with an option to add an amount of space would be, how to handle pagebreaks. 
I will think about this.

Anyway you can use `\IfSolutionF` to add space right now, which will only appear if the boolean expands to false.

```
\IfSolutionF{\par\vspace{5cm}}
```
Or as a makro
```
\newcommand{\addSolutionSpace}[1]{\IfSolutionF{\par\vspace{#1}}
```
to be used as `\addSolutionSpace{5cm}`

**Comment by StefanFabian** [comment]
I have used `tcolorbox` to achieve this by specifying a `height from=#1mm to 20cm]` where the 20cm is just to make it a minimum height, not sure if there is a better way, the documentation is quite heavy ^^
I've created our own solution environment to wrap this.
Is there an option for the original solution environment to only output the content without the "Lösungsvorschlag" heading?

**Comment by TeXhackse** [comment]
Hmmm if you don't want the boxes Breakable you could simply use `\vspace` this can be used flexible as well `\vspace{1cm plus 5cm }` tcolorbox might be a solution if you want a frame around the space + allow pagebreaks in betweek. 

And there is `solution*` providing the same functionality than Solution without the heading.

**Comment by StefanFabian** [comment]
We want a vertical line next to the answer space anyway so tcolorbox is a good fit.
Ah, thank you for the suggestion.
After a little bit of trouble, I've even managed to wrap it in our solution environment.
Thanks to the update in this answer [here](https://tex.stackexchange.com/a/78712/107370).

**Comment by TeXhackse** [comment]
You could have found the definition in the tudaexercise.cls as well ;-)

**Comment by TeXhackse** [comment]
@schoeps @marklaz Since we already have macros to use code relying on the value of Solution I don't think we need this as a supported feature. Do you think different on this?

**Comment by schoeps** [comment]
I agree. I think we should support users to build their ("local") customized solutions but we cannot include all variants in the main code base. I am afraid that maintenance and documentation will explode otherwise. If this is a heavily requested feature than we may add it in the future?

**Comment by TeXhackse** [comment]
Yup. this one would be easy.

**Comment by TeXhackse** [comment]
I will close it, because we have a working variant in here.
