### ISSUE TITLE
Sponsor-option--logo-at-frontpage 

### ISSUE THREAD

**Issue by studi1882** [tudace/tuda_latex_templates#29]
An earlier version from the department "Festkörperphysik" offered the possibility to include a \sponsor on the titly page. This is esspecially useful for external thesises. I hope this option will be included in future Releases.

**Comment by TeXhackse** [comment]
This is still possible, we just set this as basic Feature of TUDaPub. I will add a specific example to TUDaThesis as well.

```
\addTitleBoxLogo{example-image}
\addTitleBoxLogo*{\includegraphics[width=.3\linewidth]{example-image}}
```
The variant without asterisk takes a filename and autoscales it. The second one allows custom scaling.

**Comment by studi1882** [comment]
Thank you very much for your help!
