### ISSUE TITLE
using texstudio under linux only works from the command line

### ISSUE THREAD

**Issue by Foly93** [tudace/tuda_latex_templates#290]
Hi guys, I am working from linux ubuntu 20.04. (hence texlive is my dist) and was very baffled when I compiled the DEMO tex files and everything worked and then the next days without turning off my computer it just wouldnt work. It took me quite a while to figure out the error. The day before I started the texstudio from command line whereas later I started by clicking the corresponding icon that starts the program.
I am not sure what causes this strange behaviour, however I would guess that it has something to do with how I set $PATH. In my case I added 
`export MANPATH=$MANPATH:/usr/local/texlive/2020/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/usr/local/texlive/2020/texmf-dist/doc/info
export PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH
`
to my bashrc. So from what I understand, the bashrc is getting sourced when the shell opens. Therefore I would guess the $PATH is not exported when I open texstudio by clicking the icon. What do you think?

**Comment by TeXhackse** [comment]
Which message does TeXstudio show when you try to compile?

To check it's related to the path variables you can use the function “check LaTeX installation” which can be found under “help“.

Did you restart TeXstudio after hanging your bash variables? one would have to reinit the environment variables before the change gets applied.

**Comment by Foly93** [comment]
File `tudapub.cls' not found.

Okay I have compared the output that shows if 'check Latex installations' is prompted and the two different opening methods result in two different outputs.
How do I reinit the environmental variables ? I have shut down my PC several times since I installed texstudio and set the $PATH in ~/.bashrc.

**Comment by TeXhackse** [comment]
Well logout should do that. But it seems like on your system the bashrc does not have any effect on the 

So you are not loading your bashrc when using texstudio. You could directly add it to the path via /etc/profile (or something differenc, I don't know this for every Linux Distribution)

You could also direct add the PATH under texstudio settings. You find these when activating the advanced settings under “build.”

**Comment by TeXhackse** [comment]
@Foly93 did you make any progress with this?

**Comment by Foly93** [comment]
Since starting it from the shell works fine I didn't do anything about it.

**Comment by TeXhackse** [comment]
Shall we do anything about it? If not I'd like you to close the issue.
