### ISSUE TITLE
\affidavit not compatible with \usepackage{titlesec}

### ISSUE THREAD

**Issue by Foly93** [tudace/tuda_latex_templates#291]
When using \affidavit with \usepackage{titlesec} I get the following error:

"Missing number, treated as zero. \tableofcontents"

I do not really need titlesec, therefore my solve was to kick out that package, nonetheless it would be interesting to know why those two clash.
A minimal example that works (if the logo file is present) is given below:

```
% !TeX program = lualatex
\documentclass[
	ngerman,
	ruledheaders=section,
	class=report,
	thesis={type=master},
	accentcolor=1c,
	custommargins=true,
	marginpar=false,
	parskip=half-,
	fontsize=11pt,
]{tudapub}

\usepackage{geometry}
\geometry{a4paper,left=30mm,right=20mm,top=20mm,bottom=20mm}
\usepackage[english,plain]{fancyref}
%\usepackage{titlesec} % nicht kompatibel mit affidavit
\usepackage[english]{babel}

\begin{document}
	\Metadata{
		title=Useful Thesis Project Number 1,
		author=Seneca
	}
	
	\title{Useful Thesis Project Number 1}
	\subtitle{It might even be very useful}
	\author[S. Seneca]{S. Seneca}
	\birthplace{Rom}
	\reviewer{Reviewer 1\and Reviewer 2}
	
	\department{department}
	\institute{institute}
	\group{group}
	
	\submissiondate{\today}
	\examdate{\today}
	
	\maketitle
	
	\affidavit
	\tableofcontents
	
	
	\chapter{Introduction}
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
	
\end{document}
```

Is that a solvable problem?

**Comment by TeXhackse** [comment]
titlesec is redefining the section commands. TUDa-CI is based on KOMA-Script which itself adds all functionalitly provided by titlesec, so there is no need for the package anyway + titlesec is already throwing a bunch of warnings when being loaded that this won't work.

So yes it is a solveable problem, but only if you use the KOMA-Script functions and not titlesec.

Beside this using geometry without the corresponding option for the `cutsommargins` might lead to weird results.

**Comment by Foly93** [comment]
Ah i see, very helpful, thank you very much! I also deleted geometry, it had no effect on the document;
