### ISSUE TITLE
Provide better guidance on local installation

### ISSUE THREAD

**Issue by habernal** [tudace/tuda_latex_templates#292]
Thanks for making this template fully open-source!

However, for all the years, installing this template has always been a struggle.

Suggestions:

* Write exact steps how to install this template on major OS (Win / Ubuntu / MacOS)
* Including dependencies, such as `lualatex`, so on Ubuntu with TexLive `sudo apt-get install texlive-luatex`

**Comment by TeXhackse** [comment]
Would you be fine with adding information on tlmgr? Because this would be the way which would work on all OSes. 

I would not like to support all packaged because we would have to track the distributions version as well beside staying compatible to the latest TeX Live Release.

**Comment by schoeps** [comment]
@TeXhackse: I have the feeling that the questionis more basic. Shall we add something to [README.md](https://github.com/tudace/tuda_latex_templates/blob/master/README.md) under `Installation`? For example

> Do a full install of all tex packages. We recommend 
>- Windows: https://miktex.org/howto/install-miktex
>- Linux: https://tug.org/texlive/acquire-netinstall.html
>- Mac: http://www.tug.org/mactex/mactex-download.html

**Comment by habernal** [comment]
Thanks for your replies.

Take a perspective of a bachelor or master student who needs to write a thesis using this template. So he/she needs to install an environment (say texlive) which is super-straightforward on major OS. On major linux distributions, such as Ubuntu, most packages are also bundled in the repository, so it's again super-easy to install. But then comes this template, and for example, pointing here ( Linux: https://tug.org/texlive/acquire-netinstall.html ) scares me off, despite decent experience with LaTeX. So you have to go down the rabbit hole of messing up with installing fonts and this package, but mostly figuring out what does not work.

If you provide a clear steps for, say, three major systems, then everyone is happy. Just in the Readme.md. At the end of the day, it's simply downloading this zip into somewhere, unpacking, and running a command or two, provided you have the required latex binaries, such as luatex or whatever.

**Comment by schoeps** [comment]
@habernal 
> install an environment (say texlive) which is super-straightforward on major OS

This is all you have to do. All recent versions come with the template preinstalled. Nothing needs to be done, no font installation etc. However, many distributions are not shipping the latest tex version, therefore we recommend a manual install (e.g. from https://tug.org/texlive/acquire-netinstall.html). This requires only to execute an installer. This should be doable?

@TeXhackse 
> Well, it's more complicated anyway

My point is that people may think that they have to install the package from this repository. However, users shall just do proper full installation of a tex distribution. This may not be clear from the README.

> (beside the fact I'd never recommend MikTeX, TeX Live works fine on all three – MacTeX is just bundled.)

I have no opinion here. I just observe that most windows users seem to install MikTeX

**Comment by TeXhackse** [comment]
Yup, got that point, I will add this to the README.md and extend the INSTALL.md. 

OT: @schoeps Yup, most Windows users install MikTeX because somehow people still think it's the only option. But it makes things more complicated because there are small differences.  Just use TeX Live wherever possible ;)

**Comment by habernal** [comment]
> This is all you have to do. All recent versions come with the template preinstalled. Nothing needs to be done, no font installation etc.

That would be great :)

I just tested that on a vanilla Ubuntu 20.04.2.0 LTS in docker with

```text
apt-get install texlive-full -y
```

and this simple MWE:

```text
% !TeX program = lualatex
\documentclass[accentcolor=9c,type=intern,marginpar=false]{tudapub}
\usepackage[english]{babel}
\usepackage[autostyle]{csquotes}
\begin{document}
\title{Test}
\author{Author}
\maketitle
\tableofcontents
\section{Introduction}
Lorem ipsum
\end{document}
```
which fails on

```text
root@de2882a547e4:/tmp# luatex test.tex 
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian) 
 restricted system commands enabled.
(./test.tex
! Undefined control sequence.
l.2 \documentclass
                [accentcolor=9c,type=intern,marginpar=false]{tudapub}
? 
```

So what are the "recent" versions and are that recent versions of OS or texlive dist?

**Comment by TeXhackse** [comment]
ähm, you run `luatex` not `lualatex` Tex Live 2019 should be new enough for all features. 

Try `lualatex test.tex`

**Comment by habernal** [comment]
yeah, the devil lies in the details... :/

**Comment by TeXhackse** [comment]
you will probably run an outdated version, but you should be able to run it. 

Logo files are missing ofc, because we are not allowed to publish these together with the bundle.

**Comment by habernal** [comment]
OK, I can confirm that, it works (but fails on the logo), thanks!

So to wrap up:

1) The readme.md in this repo should explicitly state that there is no need to install this package manully, as it is part of the texlive 2019 distribution onwards

2) It should say that the logo has to be installed manually anyway. By the way:

> Logo files are missing ofc, because we are not allowed to publish these together with the bundle.

Where's the problem? I guess it only needs someone to give it a green light and the proper license. It makes no sense, as it is, it is a public logo anyway.

3) It could say which package exactly contains this design, as `texlive-full` is an X-GB overkill for a single X-kB template. I couldn't figure it out, there are way too many packages to try out:

```text
root@a6f4d0825425:/tmp# apt-cache search texlive
context - powerful TeX format
texlive - TeX Live: A decent selection of the TeX Live packages
texlive-base - TeX Live: Essential programs and files
texlive-bibtex-extra - TeX Live: BibTeX additional styles
texlive-binaries - Binaries for TeX Live
texlive-extra-utils - TeX Live: TeX auxiliary programs
texlive-font-utils - TeX Live: Graphics and font utilities
texlive-fonts-extra - TeX Live: Additional fonts
texlive-fonts-extra-doc - TeX Live: Documentation files for texlive-fonts-extra
texlive-fonts-extra-links - TeX Live:
texlive-fonts-recommended - TeX Live: Recommended fonts
texlive-fonts-recommended-doc - TeX Live: Documentation files for texlive-fonts-recommended
texlive-formats-extra - TeX Live: Additional formats
texlive-full - TeX Live: metapackage pulling in all components of TeX Live
texlive-games - TeX Live: Games typesetting
texlive-humanities - TeX Live: Humanities packages
texlive-humanities-doc - TeX Live: Documentation files for texlive-humanities
texlive-lang-all - TeX Live: metapackage depending on all TeX Live language packages
texlive-lang-arabic - TeX Live: Arabic
texlive-lang-chinese - TeX Live: Chinese
texlive-lang-cjk - TeX Live: Chinese/Japanese/Korean (base)
texlive-lang-cyrillic - TeX Live: Cyrillic
texlive-lang-czechslovak - TeX Live: Czech/Slovak
texlive-lang-english - TeX Live: US and UK English
texlive-lang-european - TeX Live: Other European languages
texlive-lang-french - TeX Live: French
texlive-lang-german - TeX Live: German
texlive-lang-greek - TeX Live: Greek
texlive-lang-italian - TeX Live: Italian
texlive-lang-japanese - TeX Live: Japanese
texlive-lang-korean - TeX Live: Korean
texlive-lang-other - TeX Live: Other languages
texlive-lang-polish - TeX Live: Polish
texlive-lang-portuguese - TeX Live: Portuguese
texlive-lang-spanish - TeX Live: Spanish
texlive-latex-base - TeX Live: LaTeX fundamental packages
texlive-latex-base-doc - TeX Live: Documentation files for texlive-latex-base
texlive-latex-extra - TeX Live: LaTeX additional packages
texlive-latex-extra-doc - TeX Live: Documentation files for texlive-latex-extra
texlive-latex-recommended - TeX Live: LaTeX recommended packages
texlive-latex-recommended-doc - TeX Live: Documentation files for texlive-latex-recommended
texlive-luatex - TeX Live: LuaTeX packages
texlive-metapost - TeX Live: MetaPost and Metafont packages
texlive-metapost-doc - TeX Live: Documentation files for texlive-metapost
texlive-music - TeX Live: Music packages
texlive-pictures - TeX Live: Graphics, pictures, diagrams
texlive-pictures-doc - TeX Live: Documentation files for texlive-pictures
texlive-plain-generic - TeX Live: Plain (La)TeX packages
texlive-pstricks - TeX Live: PSTricks
texlive-pstricks-doc - TeX Live: Documentation files for texlive-pstricks
texlive-publishers - TeX Live: Publisher styles, theses, etc.
texlive-publishers-doc - TeX Live: Documentation files for texlive-publishers
texlive-science - TeX Live: Mathematics, natural sciences, computer science packages
texlive-science-doc - TeX Live: Documentation files for texlive-science
texlive-xetex - TeX Live: XeTeX and packages
```

**Comment by TeXhackse** [comment]
1. As I said I will improve the text there. 
2. We are not allowed to. They don't understand that one could easily extract it from a pdf anyway. Sadly that's a quite common decision and we can't change anything about it.
3. Yes it would be possible, but the texlive-xx packages differ for each Linux distribution. So to to list some explicitly which are decent in one distribution but not for another this might make it even worse. Using tlmgr one could filter this and there are plans for a dependency management, but since there are so many new features in LaTeX atm this might take some time.

**Comment by schoeps** [comment]
> it is a public logo anyway.

No, not in the sense of public domain. TU Darmstadt has surely some copyright. 

>> one could easily extract it from a pdf anyway

This is true, e.g., one could just take the vectorized logo from Wikipedia ('fair use') but this does not mean that one is allowed to use it in a letter head.

**Comment by TeXhackse** [comment]
@schoeps You are partly  right. But including it into the bundle would not change the fact that one is not allowed to write TUDa-letters without permission. Because it's a trademark that's different from copyright. The file might be available but one would not be allowed to use it anyway. But it's not our decision anyway so we stick to it. 

What do you think about a general „Get started Guide“  with screenshot instructions for those who really don't know anything about the LaTeX installation process? 

I did this for [Uni Regensburg](http://www.physik.uni-regensburg.de/studium/edverg/latex/anleitung_texlive_texstudio/anleitung.phtml) back in 2013 and am planning to do a update. I could host this via my webserver, because it could be generic for all similar templates. We could link this as external help from the README or create a PDF copy to be downloadable from the TUDa-LaTeX website and link it there.

**Comment by habernal** [comment]
My five cents: KISS. Add a section into the main README.md with Installation instructions. It can contain images (for Win) or bash commands (for Ubuntu/other linux/MacOS). Advantages: Single source of information, everyone can update through PR, visible on first sight, typical for small-scale Github hosted projects. No need for extenal PDF (sync problems), Wikis, videos, whatsoever.

**Comment by schoeps** [comment]
I'd agree with @habernal. We could just do a bullet list with common cases in the readme (and make clear that the code here in this repo is for developers, not users)

**Comment by TeXhackse** [comment]
The problem with this is, that we also use the README on CTAN. And the markdown parser there works really different from this one. 

So I can split it up and create the short variant of the README for CTAN. We discussed this before, this is why we added the INSTALL.md to note the script adding the license infos to the files.

**Comment by TeXhackse** [comment]
I tried to resolve it. Since I don't want to wait any longer with the release of fixing the two bugs, I will merge and upload right now. If you have further additions, let me know. Information on installation is also provided in English to prevent further confusion.
