### ISSUE TITLE
Fehlermeldung im TeXstudio

### ISSUE THREAD

**Issue by lengocduc2401** [tudace/tuda_latex_templates#293]
Hallo,

ich habe MacTeX und TeXstudio auf meinem Mac (macOS Big Sur, M1 Chip) installiert und haben versucht, eine Datei zu kompilieren. Leider hat es nicht geklappt, da die tudapub.cls nicht gefunden werden kann... Über TeX Live Utility habe ich alle Pakete installiert und aktualisiert. Könnte jemand mir bei diesem Problem weiterhelfen? :(

Vielen Dank im Voraus!

<img width="1416" alt="Screen Shot 2021-03-04 at 10 48 31 PM" src="https://user-images.githubusercontent.com/68738654/110035300-c49b8100-7d3b-11eb-867f-9efd412c7cdf.png">

**Comment by schoeps** [comment]
Ich nutze eine ähnliche Konfiguration, allerdings textmate statt texstudio, daher muss das hinzukriegen sein. Was ist denn die Ausgabe von `sudo /Library/TeX/texbin/tlmgr install tuda-ci` im Terminal?

**Comment by lengocduc2401** [comment]
Ich habe es eingegeben und so sieht es dann im Terminal aus:

<img width="562" alt="Screen Shot 2021-03-05 at 2 38 23 PM" src="https://user-images.githubusercontent.com/68738654/110123549-513c5280-7dc1-11eb-8c32-a2474a9ca34e.png">

Ich habe TeXStudio gelöscht und stattdessen Texmaker verwendet und jetzt hats geklappt :)

<img width="1432" alt="Screen Shot 2021-03-05 at 2 45 56 PM" src="https://user-images.githubusercontent.com/68738654/110123701-85177800-7dc1-11eb-82a8-e2f4bbb8443a.png">

Soweit sieht es ganz in Ordnung aus oder? (da ich noch nie mit LaTeX gearbeitet habe, habe ich leider keine Ahnung...). Ich habe außerdem aus Neugier noch TextMate heruntergeladen. Da konnte ich auch die Datei kompilieren. Scheinbar liegt es echt an TexStudio...

**Comment by TeXhackse** [comment]
An TeXstudio selbst kann es in dem Zusammenhang nicht liegen. Ich vermute, dass wohl zwei Varianten von LaTeX oder zumindest dem alias auf lualatex installiert sind und TeXstudio die andere genommen hat. Das hängt ggf. mit der Installationsreihenfolge zusammen. Kann aber auch andere Ursachen haben.

Aber die Wahl des Editors ist jedem selbst überlassen. Wenn der jetzt so passt, dann bitte ich darum das Issue zu schließen. Falls wir dem auf den Grund gehen sollen, müsstest du TeXstudio allerdings nochmal installieren ;-)

**Comment by lengocduc2401** [comment]
Ich würde erstmal weiter mit Texmaker arbeiten :D. Die Datei ganz oben ist von einem Workshop an der Uni, also nicht aus den TU-Templates. 

Nochmal Danke für Eure Hilfe!

**Comment by TeXhackse** [comment]
Dann viele Grüße an den Menschen, von dem die Datei kommt. Das gilt sonst, dass die Kombination, wie sie da steht keinen Sinn ergibt.

**Comment by schoeps** [comment]
> aus Neugier noch TextMate heruntergeladen

Ich nutze TextMate für alle Textdateien (Python, Matlab, C++, CSV-Dateien, HTML, Latex....), dann muss man sich nicht ständig an neue Tastenkürzel gewöhnen. Textmate ist eine Allzweckwaffe wie vi oder emacs. Wenn man aber einen Editor nur für Latex sucht, dann gibt es sichere bessere (z.B. Texmaker).
