### ISSUE TITLE
(Urgent) Appendix destroys the numbering format of chapters, figures...

### ISSUE THREAD

**Issue by anxin8r593t** [tudace/tuda_latex_templates#295]
I use the template TUDaThesis -- Abschlussarbeiten im CD der TU Darmstadt
After adding the appendix code as follows, the number of all the chapters and figures changing from "2.1" to "2.1."
`\usepackage[toc,page]{appendix}`
`\begin{appendices} `
`\chapter{dhal}`
`\section{mm}`
`\end{appendices}`

When not adding `\chapter{dhal}`  , the numbering of chapters and figures is correct. But the generated format of the appendix is not correct  ".1".
I also tried \appendix, same issue.

**Comment by TeXhackse** [comment]
It does not destroy it. 

`\appendix` even without the package will change the chapter number to alphanumeric.

So a \chapter after \appendix will be numbered A and the figures will be numberes A.1

If you don't add a chapter in the appendix this will change. 

The appendix changes something about it, I may need to have a look at what part of it. 

So what do you want to achieve?

**Comment by anxin8r593t** [comment]
Thank you for the answer in time.
I tried in the original template without my own code. After add the appendix
![image](https://user-images.githubusercontent.com/59647383/110766475-7f081800-8255-11eb-8e8e-c9d306bd6442.png)

The number changes from "2.6" to "2.6."

**Comment by TeXhackse** [comment]
Oh sorry, I missunderstoff. 


That's a feature of KOMA-Script you can deactivate that one with changing the behaviour with `numbers=noenddot`.
The automatism has typographic reasons, because usually if numbers consists of other elements than digits, one would add and enddot. Because an appendix adds letters to the numeration this is changed with `numbers=auto` which is the default setting for all KOMA-Script classes.

**Comment by TeXhackse** [comment]
If you want to level Down the appendix without a chapter in advance this can be done as well but you would have to redefine the number format for the appendix. This is not recommended, because usually you use the same section levels as you do in the main matter of the document.

**Comment by anxin8r593t** [comment]
Perfect. It works after adding the `numbers=noenddot`. I will keep chapter. Thank you so much.
