### ISSUE TITLE
Farbiger Titelhintergrund und Logos im body

### ISSUE THREAD

**Issue by cbergmann** [tudace/tuda_latex_templates#296]
Hallo,

ist es möglich die tudapub Klasse so zu konfigurieren, dass auf der Titelseite der Titel und Untertitel farbig hinterlegt und der body weiß ist? Die Logos sollen im unteren Bereich sein.

Endgültig soll es folgendermaßen aussehen: [request.pdf](https://github.com/tudace/tuda_latex_templates/files/6149338/request.pdf)

**Comment by TeXhackse** [comment]
Ja.

**Comment by cbergmann** [comment]
Hi @TeXhackse,

bin ja selbst Schuld wenn ich geschlossene Fragen stelle :)

Leider bekomme ich den Fehler "LaTeX3: Key 'colorback' accepts boolean values only.". 
Ich vermute das hängt an dieser Zeile https://github.com/tudace/tuda_latex_templates/blob/master/tex/tudapub.cls#L82.

**Comment by TeXhackse** [comment]
In der aktuellen Version?
Dann bräuchte ich einen Log.

**Comment by TeXhackse** [comment]
@cbergmann Da ich gerade mit dem Upload der neuen Version warte, bis wir geklärt haben, ob es sich nicht doch um einen Bug handelt (wenn auch unwahrscheinlich) wäre ich für eine rasche Rückmeldung sehr dankbar.

**Comment by cbergmann** [comment]
@TeXhackse Es handelt sich um die Version v3.07 welche mit dem texlive auf meinem Host mitgekommen ist.

**Comment by TeXhackse** [comment]
@cbergmann Danke, dann ist das nicht mein Fehler. Die Option wurde im November mit 3.08 hinzugefügt. Davor ist es möglich das umzusetzen, allerdings deutlich komplizierter, ich empfehle ein Update. 

Falls das über TeX Live nicht möglich ist (warum auch immer) geht es ja immernoch die aktuelle Version zusätzlich zu installieren. Falls es da Probleme gibt, kann ich gerne helfen.

**Comment by cbergmann** [comment]
@TeXhackse danke erstmal. Sorry für den Aufwand und danke fürs Hilfsangebot. Ich melde mich sollte es Probleme geben. Und Danke für das Projekt als solches.

**Comment by TeXhackse** [comment]
War kein Aufwand, das Sorry ist also unnötig. Und das ganze hier ist Teil meines Jobs. Danke fürs benutzen und gerne weiter verbreiten ;-)

**Comment by TeXhackse** [comment]
Da wir hier keinen weiteren Prozess hatten, mach ich das jetztz mal zu. @cbergmann falls da noch was auftaucht, gerne wieder öffnen oder eben falls andere Probleme auftauchen ein neues Issue öffnen.
