### ISSUE TITLE
using \chapterfont{\color{red}} results in missing space between Chapter number and titel

### ISSUE THREAD

**Issue by Rashow** [tudace/tuda_latex_templates#297]
Hi everyone,
im working on a Document and want to change the color of the chapter.

> \documentclass[
> 	ngerman,
> 	ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
> 	class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
> 	thesis={type=bachelor},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
> 	accentcolor=9c,% Auswahl der Akzentfarbe
> 	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
> 	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
> 	%BCOR=5mm,%Bindekorrektur, falls notwendig
> 	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Sript
> 	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
> ]{tudapub}
> ....
> \usepackage{sectsty}
> ...
> chapterfont{\color{red}}  % sets colour of chapters
> \chapter{\textcolor{red}{Titel}}

results in 
**5Titel**

This was already discussed here https://tex.stackexchange.com/questions/519801/no-space-anymore-between-section-heading-and-numbering

Is there a different way to change to color?

**Comment by TeXhackse** [comment]
Yes, you should not load `sectsty` but use `\addtokomafont{chapter}{\color{red}`
