### ISSUE TITLE
Der Bezug zu Bildern funktionier in einem Kapitel nicht richtig

### ISSUE THREAD

**Issue by Gu5tav** [tudace/tuda_latex_templates#299]
In einem Kapitel werden zwei Fragezeichen anstelle der Nummer des Bildes im Bezug angezeigt. 
Der Bezug ist aber hergestellt (wenn man auf die ?? klickt)

In den Kapiteln davor und danach funktioniert alles normal.

Mein Code:

`\subsection{Gaußstrahl} \label{K:Theorie_Gaussstrahl}
Erster Test \ref{A:gaussstrahl} 
\begin{figure} [h]
	\centering
	\includegraphics[width=0.6\textwidth]{2_Theorie/Bilder/Gaussstrahl.eps}
	\caption{Gaußstrahl und dessen wichtigste Kenngrößen \cite{Meschede.2005}}
	\label{A:gaussstrahl}  
\end{figure}

\section{Laserhaerten}
Zweiter Test \ref{A:Laserhaerten}
\begin{figure}
	\centering
	\input{2_Theorie/Bilder/Laserhaerten}
	\label{A:Laserhaerten}
	\caption{Schematische Darstellung des Laserhärtens nach \cite{Buchfink.2008}}
\end{figure}

\section{Laserabtrag} \label{K:Laserabtrag}
\begin{figure} [h]
	\centering
	\includegraphics[width=0.6\textwidth]{2_Theorie/Bilder/Gaussstrahl.eps}
	\caption{Gaußstrahl und dessen wichtigste Kenngrößen \cite{Meschede.2005}}
	\label{Test2}  
\end{figure}
Dritter Test \ref{Test2}`

Danke im Voraus für euere Hilfe!

**Comment by schoeps** [comment]
Hilft es `label` in `caption` zu packen, z.B.`\caption{Gaußstrahl und dessen wichtigste Kenngrößen \cite{Meschede.2005}.\label{Test2}}`?

**Comment by TeXhackse** [comment]
@schoeps ja.

Das Problem ist, dass das obige `\label` vor der `\caption` steht.

Allerdings sollte das `\label` nach der `\caption` stehen.

**Comment by Gu5tav** [comment]
@TeXhackse das hilft danke.

wenn ich `\caption` und `\label` vertausche funktioniiert es.

Danke für die schnelle Hilfe

**Comment by schoeps** [comment]
@TeXhackse off-topic: ich habe manchmal Probleme mit `\caption{x}\label{y}` während `\ caption{x\label{y}}` immer geht. Leider kein Beispiel zur Hand. Hast Du zufällig eine Erklärung dafür?

**Comment by TeXhackse** [comment]
@schoeps Wenn du komische Dinge mit `\caption` machst ja, sonst nicht wirklich. Wobei es mittlerweile auch okay ist, das in der caption zu machen, weil es innerhalb der Verzeichniseinträge entfällt. Von daher ist beides okay.
