### ISSUE TITLE
no author name on titlepage without \author[Signature]

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#3]
I specify `\author{My Name}` on a thesis and get on my title page 
~~~
Master thesis in Computer Science by
Datum: July 25, 2019, Date of submission: July 25, 2019
~~~

i.e. my name is missing. `DEMO-TUDaThesis.pdf` doesn't have that problem and specifies the optional signature in `\author`. Adding `\Metadata` like that document doesn't help, so I suspect the missing signature is the culprit.

**Comment by TeXhackse** [comment]
Thank you got reporting, it was a bug in argument parsing. 

The Signature argument was added later and somehow I forgot to adjust the enumeration.
It's fixed and going to included into 1.1
