### ISSUE TITLE
How to make chapter headings to look like sections

### ISSUE THREAD

**Issue by climberger** [tudace/tuda_latex_templates#303]
I created a document for my master thesis as follows:
```
\documentclass[
	ngerman,
	ruledheaders=chapter,
	class=report,
	thesis={
		type=master,
		department=wi
	},
	accentcolor=9c,
	custommargins=false,
	marginpar=false,
	parskip=half-,
	fontsize=11pt
]{tudapub}
```

I expect it to have ruled headers for chapters and looking like in Corporate design as follows:

![image](https://user-images.githubusercontent.com/9077746/113844648-fd90a080-9794-11eb-8265-7aa650851492.png)

Instead it looks like this:

![image](https://user-images.githubusercontent.com/9077746/113844253-9377fb80-9794-11eb-9c44-ffcc9ebfe1a2.png)

I tried "report" and "book" as classes.

Is this intended behavior or am I doing anything wrong?
Is there a way to customize this? 

Tanks for your help!

**Comment by TeXhackse** [comment]
This is intended behaviour, the Guideline does - if I remeber correctly - not use chapters, just sections.

You could either switch to a class without chapters or change this by switching the style of headers from chapter to section.

```
\RedeclareSectionCommand[style=section]{chapter}
```

Due to typographic reasons this difference between chapters as sections is important though I'd not recommend if you are not forced to.

**Comment by climberger** [comment]
Ok, thanks. That's nice to know. Then the Word Template of my department ist wrong.
I was already surprised.

**Comment by schoeps** [comment]
> Then the Word Template of my department ist wrong.

The department may not be following the Corporate Design Guidelines but your supervisor may still _suggest_ to follow his/her rules... so I'd ask if he/she has an opinion on this.

**Comment by climberger** [comment]
My document needs to look like the file Vorlage_Bericht_mit_Fusszeile.docx in this zip-file:
https://download.hrz.tu-darmstadt.de/protected/DezIF/Corporate_Design/gr.%20Berichte,%20Dissertationen/Word2016_Bericht.zip

From the TU Darmstadt Corporate Design Page:
https://www.intern.tu-darmstadt.de/arbeitsmittel/corporate_design_vorlagen/index.de.jsp

**Comment by TeXhackse** [comment]
The pdf in there is using `\section` as highest level. (No pagebreaks … )
So maybe you would like to switch to the article base class.

**Comment by schoeps** [comment]
`class=article`  and `ruledheaders=section`.... full example:
```
%!TEX TS-program = lualatex
\documentclass[
	class=article,
	marginpar=false,
	ruledheaders=section,
]
{tudapub}
\usepackage{lipsum}
\begin{document}
\section{Section}
\lipsum
\subsection{Subsection}
\lipsum
\end{document}

```
