### ISSUE TITLE
Undefined control sequence thesistype

### ISSUE THREAD

**Issue by Airtuda** [tudace/tuda_latex_templates#306]
Hallo, ich bekomme beim Kompilieren die Fehlermeldung "Undefined control sequence.\thesistype -->\TUDa@thesisTyp Vorgelegte \thesistype". Ich habe viel probiert, aber leider weiß ich nicht genau, was das Problem genau ist. Wahrscheinlich wird nicht richtig auf die Variable thesistype referenziert?! Ich habe mal das Logfile angehängt. Für jede Hilfestellung bin ich dankbar.

Gruß
[main.log](https://github.com/tudace/tuda_latex_templates/files/6337999/main.log)

**Comment by TeXhackse** [comment]
Hallo @Airtuda,
der Fehler hat nichts mit dem TUDa-CI Template zu tun, sondern mit der FSR-Vorlage.

Ich hatte bereits Kontakt zu den Verantwortlichen udn Sie sind wohl dabei da was anzupassen, aber gerne nochmal dort nachhaken, damit dort auch realisiert wird, dass dieses Template in Verwendung ist und Probleme macht.

Ich kann einen Workaround liefern halte das jedoch nicht für sinnvoll, da sonst nur modifizierte Varianten des Templates existieren. Das Weglassen von `\maketitle` führt dazu, dass ohne Fehler kompiliert werden kann, bis das Tempalte gefixt ist.

**Comment by Airtuda** [comment]
@TeXhackse, vielen Dank für die schnelle Antwort. Dann werde ich am besten nochmals Rücksprache mit meinem Betreuer halten und nachhaken, ob sich was getan hat:) 

Einen schönen Abend!
