### ISSUE TITLE
Cannot select text in created PDF

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#307]
When opening the PDF/A created by LaTeX, I can select text and copy/paste it. However, if I re-print a single page of this document in a PDF file to send it by email, it is not possible to select the text in the new document.

Is there something to enable/disable in LaTeX for this to be possible? Or does it has nothing to do with LaTeX properties?

**Comment by TeXhackse** [comment]
Most PDF printers don't allow this. This has nothing to do with LaTeX but with out PDF-printer.

You can use the pdfpages (https://ctan.org/pkg/pdfpages) package or pdfjam script (https://ctan.org/pkg/pdfjam) to extract pages from your pdf.

**Comment by JuLateX** [comment]
Thanks, that's good to know!
