### ISSUE TITLE
Zeilenabstand

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#308]
Moin, eine allgemeine Frage:
Wie ist die Standardeinstellung/Definition des Zeilenabstand in tudapub bzw. tudathesis ?
Beim Vergleich mit MS Word entspricht die dortige Einstellung von 1,5 der option "doublespacing" des Pakets setspace, was dem doppelten Zeilenabstand entsprechen würde.

**Comment by TeXhackse** [comment]
Das ist etwas komplizierter. Schriftgrößen sind keine absolute Größenangabe. Wie groß 10pt also tatsächlich in der Ausgabe sind, hängt von der Schriftart ab. Bei Word schwankt das erfahrungsgemäß sogar mit der Versionsnummer. Es ist somit nicht möglich diesbezüglich eine allgemein gültige Aussage zu machen. Ich versuche das zu erklären.

Für die Diskrepanz gibt es zwei Ursachen.

-------------------------

### pt vs. bp

die Angabe 1 pt unterscheidet sich bei TeX und bei Word. 1 pt in TeX sind 1''/72,27, Word vereinfacht die Rechnung auf 1/72pt.  1 Word-pt heißt bei TeX 1bp (big point).

### Worauf wird der Faktor 1,5 angewandt?

#### TeX/LaTeX
Meistens entspricht der Zeilenabstand der Nominellen Schriftgröße (bei 10 pt eben 10 pt) multipliziert mit dem Faktor 1,2. Bei Schriftgröße 10 pt also 12 pt. 

`\onehalfspacing` erhöht den Faktor auf 1,5 (15 pt). `\doublespacing` auf 2 (20 pt)

#### Word
Word rechnet dies anders. Dort wird 1,5 fach als Faktor für den schon existierenden Abstand gemessen. Demnach ist das aber nicht 1,5 facher Zeilenabstand sondern eben 1,2 * 1,5 = 1,8 (alles ungefähre angaben, dazu kommt die Unterscheidung der pt/bp) also ja, das entspricht dann eher aber nicht exakt `\doublespacing`.  Teilweise (ich weiß nicht, ob das immernoch so ist) gab es auch Word Versionen die dann noch rundungen vorgenommen haben, was ggf. noch größere Abstände als diese Berechnung ergibt erzeugt haben. 

----------------------------

Ich hoffe das hilft etwas weiter das Problem zu verstehen. Missverständlich bleibt bei einer Vorgabe von eineinhalbfachem Zeilenabstand also immer wie diese Angabe gemeint ist. Daher kann ich leider keine allgemeine Handlungsempfehlung geben.

**Comment by BPollicino** [comment]
Super, das erklärt meine Beobachtung, vielen Dank für die detaillierte Anwort!
