### ISSUE TITLE
Remove a spacing after the title

### ISSUE THREAD

**Issue by RostyslavUA** [tudace/tuda_latex_templates#309]
I would like to ask the question regarding the template. So I am writing a report and I want to remove the large spacing after the title (highlighted by yellow line) 

![image](https://user-images.githubusercontent.com/49762976/117487834-e5669980-af6b-11eb-9cd0-ef85e7e12420.png)

I have tried to use the package `setspace` as mentioned [here](https://download.hrz.tu-darmstadt.de/protected/CE/TUDa_LaTeX/How_to_LaTeX_-_Ergaenzungen_zur_TUDa-Vorlage.pdf), but it does not remove the spacing.

So how could I solve my problem?

Thanks!

**Comment by TeXhackse** [comment]
The title block is automatically placing a vspace of `.5\c_ptxcd_logoheight_dim` at it's bottom. 

The intention is to separate the title from the Text. This is reuqested by the guidelines as well. 

If you want to get rid of this for a single document you can simple add `\unskip`. 

Full example:

```
\documentclass[
	ngerman,
	accentcolor=9c,% Farbe für Hervorhebungen auf Basis der Deklarationen in den
	type=intern,
	marginpar=false
	]{tudapub}

\begin{document}

\title{TUDaReport -- Minimales Template für TUDa-CI}
\author{Marei Peischl}


\maketitle
\unskip% removes that last skip
test
\end{document}
```
In case you are creating multiple documents and want to change this for a complete type of documents I'd suggest to redefine `\@maketitle` (that's the internal command called by `\maketitle` if `titlepage=false`.

``` 
\makeatletter
\let\orig@maketitle\@maketitle
\renewcommand*{\maketitle}{%
	\@maketitle
	\unskip
}
\makeatother
```

**Comment by RostyslavUA** [comment]
Thank you very much! This answers my question!
