### ISSUE TITLE
Affidavit + Titelseite

### ISSUE THREAD

**Issue by EIKI212** [tudace/tuda_latex_templates#31]
Hallo,

ich nutze die Latex Vorlage TuDaThesis.
Das mit dem Affidavit wurde schon einmal in einer anderen Issue behandelt, scheint aber noch nicht final geklärt zu sein.
Also noch mal das Problem mit dem nicht korrekt ausgefüllten Affidavit.
Dies ist das Feld zwischen den Kommas in der ersten Zeile die "..." Stelle in "Hiermit versichere ich, ..., die vorliegende". Es ist auch nicht möglich dies über eckige oder geschweifte Klammern zu übergeben.
Dieses Problem ist auch genauso auch in der Beispiel PDF enthalten.

Ansonsten hätte ich noch eine Anmerkung zu der Bibliographie.
Da für diese ja im Dokument das Package BIBLATEX eingebunden wird und dieses anscheinend auf BIBER zurückgreift, muss man beispielsweise bei TexMaker sicher stellen, dass bei der Befehle unter Bib(la)tex auch biber und weder biblatex noch bibtex eingetragen ist, da sonst das Zitieren nicht ordnungsgemäß funktioniert.
Dies könnte vielleicht in die Anleitungen aufgenommen werden um etwaige Unklarheiten zu vermeiden.

Noch ein allgemeiner Hinweise.
Auf der CE Website ist zu Latex eine Kontaktemail ("latex@tu-darmstadt.de") angegeben.
Als Antwort auf eine E-Mail erhält man vom HRZ Server direkt: <latex@tu-darmstadt.de>... Requested action not taken: recipient not allowed by policy

Vielen Dank schon einmal für die Antwort.

Mit freundlichen Grüßen
EIKI

**Comment by TeXhackse** [comment]
@EIKI212 danke für den Hinweis. Der Bug ist in der online Version behoben und wird in den nächsten release eingepflegt. Die Datei findet sich hier:

 https://raw.githubusercontent.com/tudace/tuda_latex_templates/master/tex/tudathesis.cfg

Für die Emailadresse is @marklaz zuständig.

Der Hinweis bezüglich bibtex und biber betrifft LaTeX allgemein. daher ist die Konfiguration davon abhängig welches System benutzt wird, was die allgemeine Güntigkeit eines solchen Hinweises nicht möglich macht. Wir überlegen, wie wir das am besten lösen.

**Comment by EIKI212** [comment]
@TeXhackse vielen Dank für die ausführliche Antwort.

Vielleicht würde auch schon ein allgemeiner Hinweis dazu reichen, weil sowie ich es verstanden habe gibt es ja mit dem Biblatex Package die Möglichkeit sowohl Biber als auch Biblatex zum kompilieren zu nutzen.
Vielen Dank für den schnellen Support und noch viel Erfolg.

**Comment by TeXhackse** [comment]
@EIKI212 Ah. Das mit dem dateseparator ist eine Korrektur, die im 1.10 enthalten ist, davor aber nicht.  Es wäre also, da die neue .cfg nur eine Übergangslösung ist, bis der Release raus ist, das dort ohne das Prefix anzuwenden. Alternativ ist es auch möglich, die 1.10 der Klassendatei zu verwenden, das behebt das Problem auch.

Diese findet sich unter
http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/tex/tudapub.cls

Das ist kein allgemeines Problem sondern liegt eben an der noch installierten Version 1.01
