### ISSUE TITLE
mistake in doku for tudaexercise

### ISSUE THREAD

**Issue by AFelix5** [tudace/tuda_latex_templates#310]
I have tried to use tudaexercise and have found a mistake in the doku.

It says the option for the studnetiformation on the frontpage is "headtotitle".
By searching in the source code I found out it is "headontitle".(DEMO-TUDaExercise.tex Z.131)

Maby add a sentece too that it is used as atribute for the documentclass and not in "\ConfigureHeadline".

Thank you very much Felix Amann.

**Comment by TeXhackse** [comment]
Thanks for the report. Sorry about the issue, this is indeed a mistake. I will patch that today.

Concerning your hint: The documentation states “Klassenoption” this means exactly what you requested. So it's an option for the documnt class. But I will think about your feedback and therefore might change the description.
