### ISSUE TITLE
tuda=mecheng, compilation error on pagestyle switch, departmentlogo_box already been defined.

### ISSUE THREAD

**Issue by Stormyend** [tudace/tuda_latex_templates#311]
Hallo,

beim Kompilieren mit dem Zusatz `department=mecheng` kommt es zu der Fehlermeldung `LaTeX has been asked to create a new control sequence '\g_ptxcd_departmentlogo_box' but this name has already been used elsewhere.`.
Das vollständige Log habe ich mal angehängt.

Der Fehler taucht bei mir mit TUDa-ci Version 3.13a auf und ein Output-File wird gar nicht generiert.
Mit Version 3.12 bekomme ich dieselbe Fehlermeldung, aber eine PDF wird generiert.
[output.log](https://github.com/tudace/tuda_latex_templates/files/6477982/output.log)

**Comment by TeXhackse** [comment]
Hallo,
ich gehe davon aus, dass das aus dem TUDa-ShareLaTeX kommt?

Dort habe ich eben ausprobiert und die dort isntallierte Version läuft ohne Probleme. Dort ist 3.12 installiert. Einzig die Logodateien liegen dort nicht, ich schicke eine Supportanfrage an den Sharelatex-Support damit die mit eingeplegt werden. 
Ich kann anbieten mir das im konkreten Projekt mal anzusehen, mein Account dort heißt marei@peitex.de.

**Comment by Stormyend** [comment]
Hallo,
danke für die schnelle Antwort!
Genau, 3.12 habe ich über das TUDa-ShareLaTeX versucht, lokal mit MikTeX habe ich die neuste Version 3.13a probiert.
Ich habe dich mal in das Projekt eingeladen.

**Comment by TeXhackse** [comment]
Ah, ist in der Tat ein Bug, der beim zugriff auf die pagestyles auftritt. ich fix das kurz und lade dir die angepasste tudamecheng.cfg in dein sharelatex projekt hoch, damit sollte es dann gehen. Ansonsten bereite ich eh gerade die neue Version vor.

**Comment by Stormyend** [comment]
Alles klar, ich danke dir vielmals! :)

**Comment by TeXhackse** [comment]
Ich lass das gerne offen, falls bis zum release noch jemand drüber stolpert.
