### ISSUE TITLE
Add support for \institute affiliations and multiple institutes in tudasciposter

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#313]
A request of todays office hour, `tudasciposter` is currently supporting the use of multiple contact addresses but not the use of multiple entries in `\institute`. I'd suggest to add the use of `\and`and `\inst` in `\institute`.

**Comment by MattGroenewald** [comment]
Hi, 
it should also be possible to add multiple affiliations to one author, perhaps comparable to the `authblk` package:
` \author[1, 2]{Someone} \author[3, 5]{SomeoneElse}    
    \affil[1]{Institute A} \affil[2]{institute B}`
  
but perhaps in the form
`\author{Someone\inst{1}, Someone2nd\inst{2} \and SomeoneElse\inst{1,2}}
\institute{\inst{1} Institute of A,
                \inst{2} Institute of B}`

Thank you.

**Comment by TeXhackse** [comment]
This was ofc included into my intention. 

The second variant is the one I intended to add. The first I'd not recommend because it would not be able to use it the same way with all classes. e.g. beamer uses the optional argument for the shortauthor, and usually a second call auf `\author` is overwriting the previous setting.

**Comment by TeXhackse** [comment]
I added this, but am facing a conflict with the numbers of thanks. Since `\inst` ist mostly used to manually add the affiliations and might contain more than one number this is nothing too serious, but I added a comment to make the user be aware of.
