### ISSUE TITLE
PDF/A Konformität mit pdfLaTeX

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#314]
Hallo,
mal eine vielleicht blöde Frage: Wie kann es denn sein, dass die TeX Variante des CD eine Datei erstellt, die aussieht, wie ein PDF/A inkl. Metadatendatei, aber nicht von TUbama als solche akzeptiert wird? 
Gibt es eine Option, die ich nicht kenne, die dafür eingefügt werden muss, oder geht das mit pdfLaTex einfach nicht ?

LG

**Comment by BPollicino** [comment]
Hi, hat sich mittlerweile erledigt, da ich bereits am Dienstag einreichen musste.

Ich verleibe daher mit der Anmerkung, dass die Hilfestellung in den FAQ von TUbama aktualisiert werden müssen! Dort findet sich Folgendes:

\usepackage{hyperref}
\usepackage[<option>]{pdfx}

Das Laden beider Pakete beißt sich, da laut div. Foren hyperref von pdfx mitgeladen wird und die Paketoptionen sich gegenseitig blockieren.
Hilfreich wäre auch Folgendes, was ich erst nachträglich rausgefunden habe und allen hilft, die nach mir dasselbe Problem haben:

Da nicht jeder eine Acrobat Lizenz hat, wären auch Vorschläge seitens der TU für TeX-User förderlich, welche Online-Konverter benutzt werden können/sollen. Das nur am Rande.

Wer allerdings im Besitz einer Adobe Acrobat **PRO** (Standard reicht nicht) ist, die ich für den Zeitraum einer Abschlussarbeit sehr empfehlen kann, wenn mit TeX gearbeitet wird, muss zur non-destruktiven Konvertierung des TeX-PDFs zu PDF/A zuerst die **Farben konvertieren**!!! Hierzu folgendes auswählen:

Tools -> Print Production -> Convert Colors

Dort bei "Conversion Profile" **Output Intent: sRGB IEC61966-2.1** auswählen  -> OK.
Danach:

Tools -> PDF Standards -> Save as PDF/A.


LG!

**Comment by TeXhackse** [comment]
@BPollicino Ich hab keine Ahnung welche FAQ und wie TUbama funktioniert. (@schoeps @marklaz ist das für mich relevant?)
Ich würde darum bitten, da es dort sicherlich eine Kontaktadresse gibt das dort zu melden, weil das mit TUDa-CI nichts zu tun hat. 

Ich habe nirgends empfohlen Pakete zu laden, hyperref vor pdfx zu laden is doof, das ist korrekt. Steht auch in der pdfx-Doku. 

tudapub macht das bei `pdfa=true` selbstständig. Bei einer Kompilierung mit LuaLaTeX ist das ganze valide, extern eingebettete Inhalte natürlich ausgeschlossen, weil TeX daran keine Bearbeitung vornimmt. D.h. die eingebunden Bilder müssen dem Farbmodus entsprechen (sollten sie unabhänig von PDF/A ohnehin.)

Ich verstehe daher den Hinweis auf Online-Converter nicht und weiß gerade nicht, wie ich damit umgehen soll.  Ich hoffe mein Problem mit der Anfrage ist verständlich… Es tut mir leid, falls da etwas komisch kommuniziert wird.

**Comment by schoeps** [comment]
@TeXhackse  Das hier ist vermutlich gemeint: https://www.tu-darmstadt.de/studieren/studierende_tu/studienorganisation_und_tucan/hilfe_und_faq/artikel_details_de_en_26885.de.jsp

Kannst Du dafür einen Textvorschlag für den Abschnitt "Latex" machen? @marklaz und ich versuchen derweil herauszufinden an wen man das schicken muss. Die Kontaktadresse scheint mir da nicht hilfreich.

**Comment by TeXhackse** [comment]
Oh, ja der Hinweis dort ist doof. Mach ich heute nach dem stressigen Teil fertig und schick ihn euch per Mail, oder falls ihr vorher einen Ansprechpartner hat, kann ich das dann acuh direkt mit denen klären.

**Comment by BPollicino** [comment]
@schoeps Genau das meinte ich.

@TeXhackse Ich wusste nicht, dass das TeX-Paket unabhängig erstellt ist. Sorry dafür. 
Kann sein, dass ich nur für mich spreche, aber das GitHub ist die erste Adresse, an die ich mich wende, wenn ich Probleme mit TeX habe. Daher habe ich den Kommentar für Andere hiergelassen :)
Bzgl. der Farbmodi: das steht auch nirgends, dass darauf geachtet werden muss. Das ist (vermute ich) auch einer der Gründe für die vielen Probleme bei der Konvertierung von Abschlussarbeiten ins richtige Format... 

Wenn Ihr wegen dem Text noch Input oder Unterstützung braucht, sagt einfach Bescheid!

**Comment by schoeps** [comment]
@TeXhackse gerne direkt per Mail an tucan@tu... und cc an mich und ggf. @marklaz. Das muss nicht heute sein :)

**Comment by TeXhackse** [comment]
@BPollicino danke für das Angebot. Ist schon okay, das hier gefragt wird. Wir versuchen  – wie man sieht ;-) –  allen dabei zu helfen ihr Zeug sinnvoll hinzubekommen. 

@schoeps mach ich.

**Comment by TeXhackse** [comment]
@BPollicino Vielleicht eine etwas blöde Frage… aber ich finde nirgends exakte Vorgaben dazu und ich hab jetzt zum testen mal alle möglichen PDF-Dateien hochgeladen und das akzeptiert so ziemlich alles, was behauptet es wäre PDF/A, auch wenn es nicht valide ist. Da ich nicht sicher bin, ob das vielleicht erst später im Prozess käme, hat es das direkt beim Upload gemeldet?

Ich werde die Hinweise trotzdem jetzt auf valides PDF/A-2b anpassen, aber bin einfach neugierig.

**Comment by BPollicino** [comment]
@TeXhackse Das Hochladen in TUbama erfolgt vor der Dateiformatüberprüfung. Der Upload ist ein mehrschrittiger Prozess. DIe Datei selbst hochzuladen war noch nie ein Problem, allerdings tauchen die Fehler im Anschluss auf, da das Dateiformat nochmal separat überprüft wird. 
Details dazu kenne ich leider nicht, da müsstet ihr euch an jemand anderen wenden.

Danke fürs überarbeiten schonmal!

**Comment by TeXhackse** [comment]
Danke, dann wird das wohl später erst geprüft. Ich schreib den Hinweis jetzt Mal auf PDF/A-2b um und versuche das rauszufinden.

**Comment by TeXhackse** [comment]
Oh, die haben meinen Vorschlag übernommen aber nicht nochmal geantwortet. Ich mach das hier dann mal zu.
