### ISSUE TITLE
Unknown option `paper=section' for package `typearea'.

### ISSUE THREAD

**Issue by maxwebbi** [tudace/tuda_latex_templates#317]
Ich erhalte immer folgende Fehlermeldung, wenn ich das tud thesis Template nutze: 

```
LaTeX Error: Unknown option `paper=section' for package `typearea'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.996 \KOMAProcessOptions
                       \relax
The option `paper=section' was not declared in package `typearea', perhaps you
misspelled its name. Try typing  <return>  to proceed.

\ta@hblk=\skip49
\ta@vblk=\skip50
\ta@temp=\skip51
\footheight=\skip52
Package typearea Info: These are the values describing the layout:
(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -6%
(typearea)              \evensidemargin = 17.3562pt
(typearea)              \oddsidemargin  = 17.3562pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 595.80026pt
(typearea)              \topmargin      = -25.16531pt
(typearea)              \headheight     = 17.0pt
(typearea)              \headsep        = 20.40001pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 47.6pt
(typearea)              \baselineskip   = 13.6pt
(typearea)              on input line 1741.
)
\c@part=\count183
\c@chapter=\count184
\c@section=\count185
\c@subsection=\count186
\c@subsubsection=\count187
\c@paragraph=\count188
\c@subparagraph=\count189
\scr@dte@chapter@maxnumwidth=\skip53
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\chapter on input line 5678.
\scr@dte@section@maxnumwidth=\skip54
Class scrreprt Info: using compatibility default `runin=bysign'
(scrreprt)           for `\section on input line 5689.
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\section on input line 5689.
\scr@dte@part@maxnumwidth=\skip55
Class scrreprt Info: using compatibility default `afterindent=true'
(scrreprt)           for `\part on input line 5698.
\scr@dte@subsection@maxnumwidth=\skip56
Class scrreprt Info: using compatibility default `runin=bysign'
(scrreprt)           for `\subsection on input line 5708.
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\subsection on input line 5708.
\scr@dte@subsubsection@maxnumwidth=\skip57
Class scrreprt Info: using compatibility default `runin=bysign'
(scrreprt)           for `\subsubsection on input line 5718.
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\subsubsection on input line 5718.
\scr@dte@paragraph@maxnumwidth=\skip58
Class scrreprt Info: using compatibility default `runin=bysign'
(scrreprt)           for `\paragraph on input line 5729.
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\paragraph on input line 5729.
\scr@dte@subparagraph@maxnumwidth=\skip59
Class scrreprt Info: using compatibility default `runin=bysign'
(scrreprt)           for `\subparagraph on input line 5739.
Class scrreprt Info: using compatibility default `afterindent=bysign'
(scrreprt)           for `\subparagraph on input line 5739.
\abovecaptionskip=\skip60
\belowcaptionskip=\skip61
\c@pti@nb@sid@b@x=\box52
Package tocbasic Info: babel extension for `lof' omitted
(tocbasic)             because of missing \bbl@set@language on input line 6976.
\scr@dte@figure@maxnumwidth=\skip62
\c@figure=\count190
Package tocbasic Info: babel extension for `lot' omitted
(tocbasic)             because of missing \bbl@set@language on input line 6993.
\scr@dte@table@maxnumwidth=\skip63
\c@table=\count191
Class scrreprt Info: Redefining `\numberline' on input line 7162.
\bibindent=\dimen138
) (/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudarules.sty
Package: tudarules 2021/05/26 v3.15 Creation of colored bars for tuda-ci bundle
\g_ptxcd_titlerule_dim=\dimen139
\c_ptxcd_largerule_dim=\dimen140
\c_ptxcd_rulesep_dim=\dimen141
\c_ptxcd_smallrule_dim=\dimen142
\c_ptxcd_logoheight_dim=\dimen143
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudacolors.sty
Package: tudacolors 2021/05/26 v3.15 Color definition for TU Darmstadt's tuda-ci bundle
(/usr/local/texlive/2021/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: luatex.def on input line 225.
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-def/luatex.def
File: luatex.def 2021/05/26 v1.2b Graphics/color driver for luatex
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1352.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
) (/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudacolors.def
File: tudacolors.def 2021/05/26 3.15 Color definitions for tuda-ci
))
\l_ptxcd_headrule_width_dim=\dimen144
) (/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudafonts.sty
Package: tudafonts 2021/05/26 3.15 font loading for TUDa-CI, TU Darmstadt's Corporate Design
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
) (/usr/local/texlive/2021/texmf-dist/tex/latex/anyfontsize/anyfontsize.sty
Package: anyfontsize 2007/11/22 anyfontsize.sty by pts
) (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.sty
Package: fontspec 2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
Lua module: fontspec 2020/02/21 2.7i Font selection for XeLaTeX and LuaLaTeX (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
Package: fontspec-luatex 2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
\l__fontspec_script_int=\count192
\l__fontspec_language_int=\count193
\l__fontspec_strnum_int=\count194
\l__fontspec_tmp_int=\count195
\l__fontspec_tmpa_int=\count196
\l__fontspec_tmpb_int=\count197
\l__fontspec_tmpc_int=\count198
\l__fontspec_em_int=\count199
\l__fontspec_emdef_int=\count266
\l__fontspec_strong_int=\count267
\l__fontspec_strongdef_int=\count268
\l__fontspec_tmpa_dim=\dimen145
\l__fontspec_tmpb_dim=\dimen146
\l__fontspec_tmpc_dim=\dimen147
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty
Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
) (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.cfg))) (/usr/local/texlive/2021/texmf-dist/tex/latex/xcharter/XCharter.fontspec)
```

**Comment by TeXhackse** [comment]
Halllo @maxwebbi,
kann es sein, das im Dokument irgendwo `paper=section` gesetzt wird? Vermutlich bei `\documentclass`? 


Leider schreibt der Log nicht mit welche Optionen gesetzt sind, d.h. ich müsste dazu mehr wissen, um detaillierter zu antworten.
Da tuda-ci direkt keinen solchen Optionswert verwendet, ist es etwas schwer nachvollziehbar. Ein vollständiger Log oder – noch besser – die Einstellungen der Dokumentenklasse bzw. die gesamte Präambel würde helfen.

**Comment by maxwebbi** [comment]
Hi @TeXhackse,

nein, `paper=section` ist nicht konkret gesetzt. Hier mal die Einstellung der `\documentclass`:
`\documentclass[
	ngerman,
	ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={type=bachelor},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=false,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}`

**Comment by TeXhackse** [comment]
Ich habs gerade mal auf das TUDa-Sharelatex geworfen, das scheint ein dort auftretender Fehler zu sein, war das der Versuch?

Auf einer normalen TeX Live Installation läuft es ohne Probleme durch. Ich kümmer mich drum, muss mir das aber mal im Detail angucken.

**Comment by maxwebbi** [comment]
Ja genau, hab's auf Sharelatex getestet. Danke!

**Comment by TeXhackse** [comment]
Der Fehler hat – auf den ersten Blick – keine weiteren Auswirkungen, weil er keinen Folgefehler erzeugt. d.h. es müsste möglich sein weiter zu Arbeiten wenn man ihn ignoriert. Ich würde ihn ignorieren, und andere Fehler aber trotzdem beachten, da diese Folgefehler erzeugen könnten. Ich kann gerade nicht sagen, wie schnell das gefixt wird, aber wir informieren hier.

**Comment by TeXhackse** [comment]
Ich korrigiere, das ist nicht nur ShareLaTeX, sondern jede TeX Live auf aktuellem Stand, der Bug scheint auf den ersten Blick nicht mit TUDa-CI direkt zusammenzuhängen, aber ganz sicher kann ich das noch nicht sagen.

**Comment by TeXhackse** [comment]
Workaround: platzierung der angehängten Datei  als tudapu.cls (txt war notwendig, um das hier anhängen zu können) im Arbeitsverzeichnis. 

Vor einem neuen Release möchte ich gerne dem Ursprung auf den Grund gehen, d.h. ich kann nicht garantieren, dass das alle Probleme löst, aber momentan sieht es nach einer Änderung in der Verarbeitung von Optionen aus. Das sollte also kein großes Problem werden.

[tudapub.cls.txt](https://github.com/tudace/tuda_latex_templates/files/6591968/tudapub.cls.txt)

**Comment by schoeps** [comment]
FYI: ich habe jetzt auch texlive (konkret: mactex 2021) aktualisiert und werde dafür mit dem gleichen Fehler bestraft.

**Comment by TeXhackse** [comment]
@schoeps jup, hab ich ja oben gesagt (mactex=tex live ;-) aber ich denke es gillt auch für MikTeX) Ich glaube ich hab eine änderung im Kernel übersehen. Aber workaround funktioniert ja. Ich will nur kein schnelles Release raushauen, sondern erst prüfen, weil es soll ja auch bis TL2019 abwärtskompatibel bleiben

**Comment by TeXhackse** [comment]
Fix is vorbereitet, gerade laufen noch ein paar Tests, da hatte ich eine Neuerung im Kernel übersehen, also mein Fehler. Ich kümmer mich drum, dass  das so schnell wie möglich dann auch auf dem TUDa-Server läuft.

**Comment by schoeps** [comment]
Danke! Aus Neugierde:  der Fehler war ja nicht von Anfang an mit texlive 2021 da. Ich dachte dass es bei Latex keine Kernelupdates unterjährig gibt?

**Comment by TeXhackse** [comment]
Falsch gedacht, und nein, war er nicht, die haben Angekündigt, dass sich mit dem Formal anfang Juni noch was ändert. Das war geplant. Die Standardformate umfassen mittlerweile ja viel mehr, insbesondere ist expl3 ja automatisch mit drin. War also tatsächlich ganz frisch aber ich hätte es vorher wissen müssen. Hab auf diesem weg festgestellt, dass mein dev-Format-Testsystem gerade komische Dinge tut … beziehungsweise getan hat. Jetzt passt wieder alles.

**Comment by TeXhackse** [comment]
Das Update ist auf CTAN installiert, wird also jetzt auf die Mirror verteilt, ich gehe davon aus, dass das Sharelatex sich das update selbst holt, ansonsten habe ich dort auch eine Mail hingeschickt. Ich lasse das issue hier offen, bis es auch dem Sharelatex richtig läuft.

**Comment by TeXhackse** [comment]
Läuft jetzt auch wieder unter dem TUDa-Overleaf-Server.
