### ISSUE TITLE
tudaposter für kleine Aushänge

### ISSUE THREAD

**Issue by buchhorn** [tudace/tuda_latex_templates#32]
Ich würde gerne einen kleinen (A4), zweiseitigen Aushang mit der Klasse tudaposter machen. Dabei machen mir momentan zwei Dinge Probleme:
1. Ich würde gerne den qrcode loswerden. Gibt es eine Option dafür?
2. Die Balken an Kopf und Fuß der Seiten werden offenbar nur auf der ersten Seite erzeugt. Kann man diese auf den nächsten Seiten auch auftauchen lassen?
Die Klasse tudapub kommt leider nicht infrage, da sie ein ganzseitiges Titelblatt erzwingt und die anderen scheinen mir wie ein Overkill für mein Anliegen.

**Comment by schoeps** [comment]
>Ich würde gerne den qrcode loswerden. Gibt es eine Option dafür?

Das scheint in der Tat bei `tudaposter` nicht möglich, bei `tudasciposter` geht es (einfach `\footerqrcode `nicht definieren). Das ist meiner Meinung nach ein Bug. Als workaround könnten Sie `tudasciposter` ausprobieren, die Boxen muss man ja nicht benutzen (aber das löst das zweite Problem leider nicht).

> Die Balken an Kopf und Fuß der Seiten werden offenbar nur auf der ersten Seite erzeugt.
 
Ja, das war eben als "typische" Posterklasse angelegt, daher hatten wir den Use Case "zwei Seiten" nicht auf dem Schirm. @TeXhackse  kann man das nachrüsten für `tudaposter`? Bei `tudasciposter` braucht man das wohl eher nicht.

**Comment by marklaz** [comment]
Nur als ergänzende Information hierzu: 
Gegenwärtig ist noch ein weiteres Template “TUDaAnnounce” in der Vorbereitung, das ebenfalls diese Thematik (A4/A3 Aushänge) adressiert. Hier wird etwa auch eine Marginalspalte mit Kontaktinformationen o.Ä. verfügbar sein.

**Comment by TeXhackse** [comment]
## QRcode
Ist in der Repository-Version gefixt, kommt dann in den nächsten Release. Als kurzer Workaround bitte in die Datei vor `\begin{document}` folgendes einfügen:
```
\ModifyLayer[contents={}]{TUDa.poster.qrcode}
```

**Comment by buchhorn** [comment]
Super, danke!

**Comment by TeXhackse** [comment]
So, endlich steht die Demo, es gibt jetzt ein DEMO-TUDaAccouncement:

[DEMO-TUDaAnnouncement.pdf](https://github.com/tudace/tuda_latex_templates/files/3755250/DEMO-TUDaAnnouncement.pdf)

Es hat einige kleinere Änderungen an der tudaposter Klasse erforderlich gemacht, aber mit der Version hier im Repo läuft alles.
