### ISSUE TITLE
Section Frame in TUDaBeamer

### ISSUE THREAD

**Issue by stangier** [tudace/tuda_latex_templates#322]
Hello,

I was wondering if there is the option to (automatically or manually) create "Section Frames" using the beamer template. I am thinking about something like this: 

![](https://i.stack.imgur.com/sLbN9.png)

A slide that appears before every new section and contains the name of the upcoming section. Please excuse me, if this option already exists, but I was not able to find it.

Kind regards

**Comment by TeXhackse** [comment]
The CI Guideline does not have any regulations concerning this. Therefore it's not implemented as a base funktionality but you can use beamers function for this. (See the beamer documentation for further unstrictions).

Quick example taken from the beamer userguide (https://texdoc.org/serve/beamer/0#page=98) would be
```
\AtBeginSection[] % Do nothing for \section*
{
  \begin{frame}<beamer>
    \frametitle{Outline}
    \tableofcontents[currentsection]
  \end{frame}
}

```

**Comment by schoeps** [comment]
Are you aware of Beamer's "\AtBeginSection[]{}" mechanism? With this it should be fairly easy to do that with a couple of lines.
Personally, I use it for long talks to include the tableofcontents at the beginning of each section.

**Comment by stangier** [comment]
Thank you! I knew about the `\AtBeginSection` option, however I saw a presentation a couple of weeks ago where the presenter used some kind of section frame in the TUDa design (at least I thought so back then) but this means that this was probably also a custom function :) Thank you very much for the quick response, it's all clear now!

**Comment by TeXhackse** [comment]
You can use the blocks for the intro but there is no official rule about this. Maybe one would prefer the frametitle but since there are too many differences I did not want to enforce some default.
