### ISSUE TITLE
Page number shifted when a new chapter begins (TUDaThesis)

### ISSUE THREAD

**Issue by moritzmathes** [tudace/tuda_latex_templates#324]
Hi, I noticed that the page numbers in TUDaThesis are not at a constant position. On all new-chapter pages the numbers are shifted downwards. For instance, this can be seen in the official compiled documents (https://ctan.space-pro.be/tex-archive/macros/latex/contrib/tuda-ci/doc/). I'd appreciate a fix. Best regards, Moritz

**Comment by TeXhackse** [comment]
Thanks, this seems to be caused by some packages changes because we didnt have that die older versions of TUDa-CI. 

I will prepare an update, which is planned to be released until monday.

**Comment by moritzmathes** [comment]
Thanks, it works!
