### ISSUE TITLE
Fußzeile 

### ISSUE THREAD

**Issue by jrosolino** [tudace/tuda_latex_templates#325]
Liebes Team,
vielen Dank für die Bereitstellung der LaTex-Vorlage für Abschlussarbeiten. Ich habe eine Frage zum Thema Fußzeilen. Wie im angehängten Bild zu erkennen, fügt LaTex über \footnote die Fußzeile über der Linie mit der Seitenzahl ein. Ist das so vorgesehen? Da unter der Trennlinie mit der Seitenzahl noch sehr viel Platz ist, hätte ich die Fußzeile eher dort erwartet. Oder liege ich da falsch? LG Jan
![Beispiel](https://user-images.githubusercontent.com/87950274/126913176-7853b2af-4592-4584-af00-ae20d2636272.png)

**Comment by TeXhackse** [comment]
Hallo Jan,
erst einmal ja, du liegst damit falsch. Das ist exakt so vorgesehen, die untere Trennlinie soll ja den Rand begrenzen und Fußnoten werden unten im Textblock platziert. Allerdings ist – in der Tag – das Layout nicht auf viele Fußnoten optimiert. 

Die Linie unten hat mit den Fußnoten absolut gar nichts zu tun. Es wäre eine Überlegung wert diese Trennlinie abzuschalten, wenn du viele Fußnoten benutzt. Allerdings ist exakt diese Position so wie sie ist vorgesehen. 

Die allgemeine Trennlinie kannst du über 
```
\KOMAoptions{footsepline=false}
```
nachdem die Dokzumentenklasse geladen ist, abschalten.

**Comment by TeXhackse** [comment]
Ich schließe das mal, falls noch weitere Rückfragen da sind, kann das natürlich wieder geöffnet werden.
