### ISSUE TITLE
Too Wide Section Numbers Breaks Table of Contents

### ISSUE THREAD

**Issue by fdamken** [tudace/tuda_latex_templates#326]
When using very wide section numbers, e.g., when the document has more than 100 chapters, the section numbers are moved into the section title.

![Example](https://user-images.githubusercontent.com/13728817/127372889-d5a7028b-ea3c-4408-82e9-6cff3fc7fc4a.png)

**Comment by schoeps** [comment]
The TUDa template is based on KOMA, so you can use all the options and tricks known to the internet, e.g. https://tex.stackexchange.com/a/314021. Applied to our template:

```
\documentclass[class=book,pdfa=false]{tudapub}
\RedeclareSectionCommands[tocdynnumwidth]{chapter,section}
\RedeclareSectionCommands[tocpagenumberwidth=6ex]% adjust the space for the page number
  {part,chapter,section,subsection,subsubsection,paragraph,subparagraph}

\begin{document}
\tableofcontents
\setcounter{chapter}{100}% just for the example
\setcounter{page}{998}% just for the example
\chapter{Title of chapter}
\setcounter{section}{10}% just for the example
\section{Title of a Section}
\section{Title of a Section}
\chapter{Title of chapter}
\setcounter{section}{20}% just for the example
\section{Title of a Section}
\section{Title of a Section}
\end{document}
```

**Comment by TeXhackse** [comment]
Additionally one can use KOMA's `toc=flat` option. This will switch to a tabular-like toc layout which also can be used in case one want's to not use the fixed number widths.
