### ISSUE TITLE
Sollen wir "Github Discussions" erlauben?

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#331]
Ich habe gerade gelesen, dass Github hat heute Discussions ausgerollt hat. Vielleicht sollten wir das nutzen, um zukünftig Fragen und Bugs ("Issues") auseinander zu halten? Man kann notfalls auch Issues zu Discussions konvertieren. Von mir aus können wir es aber auch alles so lassen.

@TeXhackse @marklaz  Was meint ihr?

**Comment by TeXhackse** [comment]
Bleibt das Repo jetzt langfristig hier? Dann ist es mir relativ egal. Ich würde dann den discussions link unter support bei CTAN eintragen lassen. Grundsätzlich ist es mir relativ egal, weil die Zuordnung wahrscheinlich weiterhin bei uns bleibt.

**Comment by TeXhackse** [comment]
Die Frage stellte sich geraede in Kombination mit dem PR bezüglich der Zitatbeispiele wieder. Mir ist das relativ nach wie vor egal, aber wir hatten mal noch was in Richtung Beispiele sammeln und Wiki. Ich kann hier sowas nicht ändern, von daher müsst das ggf. wirklich ihr machen ;-)

**Comment by TeXhackse** [comment]
Ich hab das übrigens mal angeschaltet. Daher kann das hier auch mal zu,
