### ISSUE TITLE
setstretch affects footer (TUDaThesis)

### ISSUE THREAD

**Issue by moritzmathes** [tudace/tuda_latex_templates#332]
Hello,
I noticed that the vertical spacing in the footer changes after I use `\setstretch{1.5}`. Is there a way to avoid this?
Best regards,
Moritz

**Comment by TeXhackse** [comment]
It's not directly caused by TUDa-CI but by scrlayer-scrpage. I will have a look at it and think about a fix/workaround.

**Comment by TeXhackse** [comment]
Workaround until I discussed this:
```
% Insert this block  into your preamble 
 \newlength\footercorrection
 
 \newcommand*{\modifiedsetstretch}[1]{
 	\setlength\footercorrection{\baselineskip}
 	\setstretch{#1}
 	\addtolength\footercorrection{-\baselineskip}
 	\ModifyLayer[addvoffset=\footercorrection]{TUDa.pub.foot.even}
 	\ModifyLayer[addvoffset=\footercorrection]{TUDa.pub.foot.odd}
 	\ModifyLayer[addvoffset=\footercorrection]{TUDa.pub.foot.oneside}
 	\ModifyLayer[addvoffset=\footercorrection]{plain.TUDa.pub.foot.even}
 	\ModifyLayer[addvoffset=\footercorrection]{plain.TUDa.pub.foot.odd}
 	\ModifyLayer[addvoffset=\footercorrection]{plain.TUDa.pub.foot.oneside}
 }
```
Then you can use `\modifiedsetstretch{1.5}` instead of `\setstretch`.

I will care for this and keep this issue open until I have further information if that's intended.

**Comment by TeXhackse** [comment]
shame on me (i thougth it to be more complicated -> removed the workaround to avoid confusion). https://sourceforge.net/p/koma-script/tickets/14/

Alright, you can use the `singlespacing=true` option. I will enable it by default for the next release, because this might be a common issue.

**Comment by komascript** [comment]
Alternative workaround:
```latex
\PassOptionsToPackage{singlespacing}{scrlayer}
```
before `\documentclass`.

**Comment by TeXhackse** [comment]
@komascript That's what I will take care of, when it's handled internally. But you're right, maybe I should take care of  to the details.  Thank you.

**Comment by moritzmathes** [comment]
Thank you!
