### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Maxianer** [tudace/tuda_latex_templates#333]
Hi,
since yesterday I cannot complie my thesis anymore. I always get "**Server Error** Sorry, something went wrong and your project could not be compiled. Please try again in a few moments." I only changed something in one chapter but even if I do not include it, it doesn't work. I don't get any further error messages. What can I do ?

Best regards,
Max

**Comment by TeXhackse** [comment]
Hi, 
I'd need some additional information to help you.

TUDa's sharelatex or Overleaf?
You can try to delete all temporary files at the bottom of the log view.  And recompile afterwards?

**Comment by Maxianer** [comment]
Hi,
it's TUDa's sharelatex. I've created a Test project only with the main.tex and still it's not working. I shared the project with you.

**Comment by TeXhackse** [comment]
It's a server issue, the Code itself is okay.  I will close this as unrelated to TUDa-CI and as you read in the chat, contact the ShareLaTeX support.
