### ISSUE TITLE
tudaposter change orientation from vertical to horizontal

### ISSUE THREAD

**Issue by ChristophReich1996** [tudace/tuda_latex_templates#336]
Hi, is there a way to generate a poster with a horizontal orientation (landscape)?

**Comment by TeXhackse** [comment]
You can simply use the `landscape` option. It's based on KOMA-Script so it should work.

**Comment by ChristophReich1996** [comment]
Thanks for the very quick response! `landscape` works well :)

**Comment by timbmg** [comment]
Where would I need to specify `landscape`?

**Comment by TeXhackse** [comment]
As it's a global option one has to set it when loading the class.

**Comment by schoeps** [comment]
```
\documentclass[landscape]{tudasciposter}
\begin{document}
\title{Hallo}
\author{ich}
\begin{tcbposter}
Inhalt
\end{tcbposter}
\end{document}	
```

**Comment by TeXhackse** [comment]
edited the code example. Please always add a value if possible. The default values only exist for backwards compatibility.

**Comment by TeXhackse** [comment]
Oh, that's a bug… Somehow it's not working with a value. I will fix that today.

**Comment by schoeps** [comment]
> Oh, that's a bug… Somehow it's not working with a value. I will fix that today.

Lucky me, who is still using old school syntax :)

**Comment by TeXhackse** [comment]
I just realized we don't mention it in the demo poster anyway, so there will be some additions.
