### ISSUE TITLE
Undefined control sequence in tudathesis.cfg (very outdated TeX Live)

### ISSUE THREAD

**Issue by Stysch** [tudace/tuda_latex_templates#337]
Hi all,

I have a problem that is probably closely related to [issue 209](https://github.com/tudace/tuda_latex_templates/issues/209), but still don't seem to be able to figure out what's going wrong.

Trying to compile the official PhD thesis demo file DEMO-TUDaPhD.tex, I get the error
```
! Undefined control sequence.
\@subject ->\text_titlecase_first:n 
                                    {\tl_if_empty:NF \ptxcd_thesisStatus {\p...
l.186 
```
I'm on a Windows machine and I downloaded the tuda-ci package (version 3.18) via Miktex from CTAN. 

Small disclaimer: I am an external PhD student at TU Darmstadt and therefore have to use a corporate computer to work, on which packages are not automatically updated. However, I could update packages manually if I knew what causes the problem.

Thank you for your help!

**Comment by TeXhackse** [comment]
Hi,
you downloaded the package via MikTeX or installed it manually into MikTeX?

You have a version clash between the TUDa-CI package and your kernel. So I'd recommend to update the TeX distribution itself or downgrad TUDa-CI. Here the package causing the issue is expl3, but this is directly connected to the underlying LaTeX installation.

**Comment by Stysch** [comment]
Hi Texhackse, thank you for your reply!

I searched for the tuda-ci package in the Miktex package manager and installed it there (oddly enough installing new packages this way is allowed on my corporate machine but updating existing ones does not work).

Thanks for pointing towards expl3. The four related packages l3build, l3kernel, l3packages, and l3experimental are installed with a version from 07/2017. I'll see if there is any way for me to update my distribution but I'm afraid that is probably not the case and I'll have to resort to downgrading tuda-ci. Do you have an idea with version of tuda-ci could work here?

**Comment by TeXhackse** [comment]
Hmmm… 
I'd give the version 2.00 a try … But actually I'd have to test it. If you have a TUDa-Account you should probably try to use the sharelatex-instance which might be easier. sharelatex01.ca.hrz.tu-darmstadt.de/

If that's the only error you get it's possible easier to make a workaround, so `\text_titlecase_first:n` is a macro which set's the first letter in uppercase and the following lowercase. One could adjust it manually.
I can offer we fix it together in case you attend the office hour today at 2 p.m. or if you send me a full log via email.

**Comment by Stysch** [comment]
Thank you for the info and for the offer to look at it together. Fortunately, I have in the meantime found a way to use an up-to-date Miktex installation until my thesis is finished. You may close this issue.
