### ISSUE TITLE
Text on the cover page

### ISSUE THREAD

**Issue by benbredt** [tudace/tuda_latex_templates#339]
I would like to write on the space below the headers on the cover page, since it is required by the department. Is there a way to write on the white space, as in the Word-template shown below?

<img width="483" alt="Screenshot 2021-09-13 at 10 00 47" src="https://user-images.githubusercontent.com/90499497/133046280-56c1505f-1554-40c3-9d7b-693f81e5660d.png">

**Comment by TeXhackse** [comment]
You can add a text box instead of an image to the `\titleimage` variable.

**Comment by benbredt** [comment]
Thanks for your prompt reply! That worked well. 
Now as a follow up question: Can I remove the string "Master thesis by" that is automatically generated in the Latex document?

**Comment by TeXhackse** [comment]
Please have a look at the configuration parameters of `thesis={}` 

You can adjust single elements or replace it using `\subject`.

**Comment by benbredt** [comment]
> Please have a look at the configuration parameters of `thesis={}`
> 
> You can adjust single elements or replace it using `\subject`.

Can you explain this in a bit more detail? If I change the thesis type in the documentclass, it'll change the affidavit (where I'd like master thesis to remain). But if I keep `thesis={type=master}`, it set's "Master thesis by" on the cover under the title as well as a line "Darmstadt", where I cannot remove the extra line by keeping `\publishers{}` empty. My simple goal is to have three lines under the topic like in the picture above, saying Master thesis, my name and matriculation number as well as my course of study.
