### ISSUE TITLE
Empty page TuDThesis

### ISSUE THREAD

**Issue by PNapi90** [tudace/tuda_latex_templates#34]
In the old Latex template of TuDThesis, empty pages (e.g. empty page before a new chapter) still had the colored bars and page number etc. on them. Is it possible to add these? It looked much nicer compared to a completely empty page as it is the case now.

**Comment by TeXhackse** [comment]
Generally empty pages due to typesetting are set as completly empty. 

But KOMA-Script offers an Option for that if you like to change. 
`cleardoublepage=current`
Usage information for that can be founds in the KOMA-Script documentation.
