### ISSUE TITLE
Zeilennummerierung außerhalb Algorithmus (bei parskip= als globale Option)

### ISSUE THREAD

**Issue by julianb3** [tudace/tuda_latex_templates#343]
Hallo zusammen,

ich nutze die Latex Vorlage der TU zum Schreiben meiner Masterarbeit. Dort schreibe ich Pseudocode mit dem Package  algorithm2e. Bei der Erstellung des Pseudocodes habe ich allerdings das Problem, dass die Zeilennummerierung außerhalb des Algorithmus Blocks und somit außerhalb der \textwidth ist (siehe Bild). 
![algorithmus_falsch](https://user-images.githubusercontent.com/57254850/137769198-e3a55022-ea39-40eb-8848-42b6dd5efe20.PNG)

Dies ist ein Problem, was mit der Vorlage zusammenhängt, denn wenn ich mit dem identischen Code ein leeres File mit folgendem Code erstelle: `\documentclass{Article}
\usepackage[ruled,vlined,linesnumbered]{algorithm2e}
\begin{document}
	\begin{algorithm}
		\DontPrintSemicolon
		\caption{Test Algorithmus}
		Text in Algorithmus \;
		noch \;
		mehr \;
		text \;
	\end{algorithm}
\end{document}`

sind die Zeilennummerierungen innerhalb des Code Blocks und wären in meinem File später nicht mehr außerhalb der \textwidth.
![algorithmus_richtig](https://user-images.githubusercontent.com/57254850/137769040-1ff1e199-a7b7-4b7c-8448-b809123e38a2.PNG).

Kann mir jemand sagen, wie ich das vermeiden kann?

Vielen Dank schonmal im Voraus!

**Comment by TeXhackse** [comment]
Ähm, das ist interessant. Aber tatsächlich mehr, weil ich einen Moment gebraucht habe um das zu rekonstruieren. Ich muss nochmal genauer hingucken, woher das kommt, aber anscheinend verarbeitet da irgendwas die parskip Option anders als gedacht. 

Vermieden werden kann das, wenn `parskip` nicht als globale Option gesetzt wird. 

```
\documentclass[fontsize=11pt]{tudapub}
\KOMAoptions{parskip=half-}%oder eben ein anderer beliebigr Wert.
\usepackage[ruled,vlined,linesnumbered]{algorithm2e}
\begin{document}
	\begin{algorithm} \DontPrintSemicolon \caption{Test Algorithmus} Text in Algorithmus \; noch \; mehr \; text \; \end{algorithm}
\end{document}
```
Ich geh dem Ganzen nochmal genauer auf den Grund, wollte aber erstmal diese Erkenntnis teilen.
