### ISSUE TITLE
TUDaLetter creates undefined control sequence error

### ISSUE THREAD

**Issue by volkerbetz** [tudace/tuda_latex_templates#344]
Hi, 

when trying to compile the demo of TUDaLetter, I get the error undefined control sequence (see below).
It seems to find all the packages but produces that error all the same. Can you help me? 

Best wishes
Volker Betz

This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2022/dev) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./DEMO-TUDaLetter.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-10-18> (./tudaletter.cls
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))
Document Class: tudaletter 2019/08/05 v1.01 Letters for TUDa-CI, Corporate Desi
gn of TU Darmstadt
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
 (/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlttr2.cls
Document Class: scrlttr2 2021/06/25 v3.34 KOMA-Script document class (letter)
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrkbase.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrbase.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlogo.sty)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/keyval.sty)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudalettersize10pt.clo)
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/typearea.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/DIN.lco)
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudacolors.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-def/pdftex.def))
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudacolors.def))
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudafonts.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/anyfontsize/anyfontsize.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/xcharter/XCharter.sty
`XCharter' v1.222, 2021/09/01 Text macros for XCharter, an extension of Charter
 (msharpe) (/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/cyrillic/t2aenc.def
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/t2aenc.dfu))
(/usr/local/texlive/2021/texmf-dist/tex/latex/ly1/ly1enc.def
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/ly1enc.dfu)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/textcomp.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/carlisle/scalefnt.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/fontaxes/fontaxes.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2021/texmf-dist/tex/generic/xkeyval/xkvutils.tex))))
(/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/microtype.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/microtype-pdftex.def)
(/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/microtype.cfg))
(/usr/local/texlive/2021/texmf-dist/tex/latex/roboto/roboto.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/ifxetex.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/ifluatex.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/xcharter/T1XCharter-TLF.fd)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/roboto/roboto-mono.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/tools/afterpage.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/ragged2e/ragged2e.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/ifvtex.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/tuda-ci/tudarules.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse.sty))
./tudaletter.cls:145: Undefined control sequence.
<recently read> \TUDa@makeheadrule 
                                   
l.145 \TUDa@makeheadrule
                        [width=\useplength{firstheadwidth}, color=\TUDa@prem...
./tudaletter.cls:145: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.145 \TUDa@makeheadrule[
                         width=\useplength{firstheadwidth}, color=\TUDa@prem...

**Comment by TeXhackse** [comment]
Please use the latest release of TUDa-CI. That should help ;-)

Seems like you are mixing up some versions.

**Comment by volkerbetz** [comment]
Actually, I just installed (and updated) the package from https://ctan.net/systems/texlive/tlnet/ <https://ctan.net/systems/texlive/tlnet/> via the 
TeX Live utility. Is this not the most recent version?

**Comment by TeXhackse** [comment]
Your log says
```
Document Class: tudaletter 2019/08/05 v1.01 Letters for TUDa-CI, Corporate Desi
gn of TU Darmstadt
```
this file seems to be in your working directory. So this one is loaded instead of the installed variant. 

You have installed tudarules correctly, so probably it would help to simply remove the local copy of the outdated tudaletter.cls. But this might also apply to other files afters.

**Comment by volkerbetz** [comment]
Thanks a lot, this solved it. I am very impressed by the speed (and quality) of your response, I must say!

Best wishes,
Volker
