### ISSUE TITLE
Using '\and' to show multiple authors but failed

### ISSUE THREAD

**Issue by ututono** [tudace/tuda_latex_templates#345]
Hello,

I'm using "Übung TUDaExercise" template.  I want to add two authors for my sheet by executing '\and' into \author{} to sperate two authors, but failed. I also tried some possible solutions from the Internet, unfortunately, neither of them worked. 

My code is as following.
```
\begin{document}
\selectlanguage {english}
\title{XXXXXX}
\author{James \and Hans}
\term{Wintersemester}
\date{01.01.2021}
\sheetnumber{2}
\maketitle
% content
\end{document}
```

Here is the error result.

![chrome_ZBeAAzB07B](https://user-images.githubusercontent.com/32908119/141330143-925163c6-9786-4c12-b903-ea5829f7fd76.png)

Is any possible to add multiple authors in this template. If so, how can one achieve that?

Thank you in advance.

Regards,
ZY.

**Comment by ututono** [comment]
Thanks for your answer.

The version of `DEMO-TUDaExercise.tex'  is 3.16 (2021/06/03), I don't know whether it is the latest version.

**Comment by TeXhackse** [comment]
You downloaded or are compiling inside sharelatex? the link is only showing the demo files

The sharelatex instance did not receive updates during the last months. I just was informed about it yesterday but they told me there would an update next week. 

Anyway you should be able to insert the code snipped shown above into your document (before `\maketitle` to affect it).

**Comment by ututono** [comment]
I compiled it inside sharelatex. WoW! it works after I insert your code.

But I also want to append some information like TU-ID or email below names: Normally, I used `\\` to achieve it but in this template it works not perfect. 

```
\selectlanguage {english}
\title{Execrise}
\author{James \\dfdfd \and Hans \\dfasfd}
\term{Wintersemester 2021/22}
\date{09.11.2021}
\sheetnumber{2}
```

![chrome_G8qBZMtEqt](https://user-images.githubusercontent.com/32908119/141335133-03e349da-bf0c-4cbc-a67e-f46d725e8904.png)

**Comment by TeXhackse** [comment]
It works as intended. They are placed next to each other including the „and“

If you want to adjust the alignment you'd probably like to add a table in there (take care of the metadata)

```
\author{\begin{tabular}[t]{@{}l@{}}James\\dfdfd\end{tabular}\and <second tabular>}
```

or combine it within one table.

The easier variant would be to add the additional information in parenthesis or some differekt kind of brackets behind the name without a linebreak.

**Comment by ututono** [comment]
It works as expected. I truly appreciate your timely help.

![chrome_KSSERgG8s2](https://user-images.githubusercontent.com/32908119/141346820-27773cb9-6735-4609-970e-09579ec344b5.png)
