### ISSUE TITLE
Zeilenabstand mit minted highlightlines

### ISSUE THREAD

**Issue by Locke** [tudace/tuda_latex_templates#347]
Ich möchte in einer Präsentation Quelltext zeigen und gewisse Zeilen hervorheben. Dazu verwende ich das [minted](https://github.com/gpoore/minted/) Paket und dessen highlightlines-Option.

In sehr speziellen Umständen bin ich auf eine leichte Verschiebung der Zeilen gestoßen. Da die Verschiebung nur minimal ist und das Problem nur in den speziellen Umständen auftritt, bin ich mir unsicher, ob ich das hier melden sollte oder nicht. Ich denke, es lohnt zumindest als Dokumentation, sollten andere ein ähnliches Problem haben.

Da das Problem nicht mit den Klassen `article` und `scrartcl` bzw. `beamer` auftritt, ist es aber vielleicht doch ein Problem, das hier mit den TU Klassen zu tun hat.

In diesem Screenshot ist zwischen der Zeile 2 und 3 ein weißer Abstand zu sehen, der zur leichten Verschiebung der Zeilen 3ff führt:

![Screenshot from 2021-12-13 22-07-00](https://user-images.githubusercontent.com/53905/145891631-1e5595a0-2d2f-41f0-85de-3cb07d82407d.png)

Eigentlich sollte die grüne Hervorhebung ohne weißen Abstand, wie hier, sein:

![Screenshot from 2021-12-13 22-41-06](https://user-images.githubusercontent.com/53905/145893330-f3b6dc0d-7d94-45a7-ba5d-fe5bce32e0a2.png)

Minimal working example:
```latex
\documentclass{tudabeamer}

\usepackage{minted}

\begin{document}

\begin{frame}[fragile]{Test 2b: problem, with \textbackslash scriptsize}
    \begin{minted}[fontsize=\scriptsize,highlightlines={2-3},highlightcolor=green!10]{java}
class Main {
    public static void main(String[] args) {
        System.out.println("a_0: " + args[0]);
    }
}
    \end{minted}
\end{frame}

\end{document}
```

Ich habe in dieses Repository zwei ausführlichere Beispiele hochgeladen: https://github.com/Locke/tudaci-minted-highlightlines

Da der weiße Abstand die nachfolgenden Zeilen verschiebt, ist gerade bei einer Präsentation beim Wechseln zwischen den Folien 3 und 4 ein Sprung deutlich bemerkbar (während der Wechsel von 1 auf 2 harmonisch ist).

Das Problem tritt nur auf, wenn auf eine hervorgehobene Zeile eine Zeile folgt, in der eckige Klammern `[ ]` sind (mglw. auch andere Sonderzeichen, mir ist es nur mit den eckigen Klammern aufgefallen).

Zudem tritt bei der Präsentation das Problem nur mit `fontsize=\scriptsize` auf - nicht jedoch bei anderen Schriftgrößen. Im Report tritt das Problem bei den Größen `\scriptsize`, `\footnotesize` und `\small`auf.

Zur Verdeutlichung habe ich in den Beispielen und Screenshots `linenos,xleftmargin=0.6cm` hinzugefügt. Dies beeinflusst das Problem nicht, macht es jedoch übersichtlicher.

Edit: Das Problem ist mir in der Version 2.11 aufgefallen, ein Update auf 3.20 hat nichts verändert.

**Comment by TeXhackse** [comment]
Ich kenn das Verhalten wenn Beispielsweise die Zeilennummern größer sind als die Textzeilen. D.h. ich vermute es liegt an den Anpassungen der Schriftgröße, aber werde mir das mal ansehen. Kann aber vermutlich einen Tag oder zwei dauern, bis ich die Zeit finde. Gerade ist sehr viel los.

**Comment by Locke** [comment]
> Kann aber vermutlich einen Tag oder zwei dauern, bis ich die Zeit finde. Gerade ist sehr viel los.

Kein Problem, für mich ist es nicht besonders dringend.

**Comment by TeXhackse** [comment]
Also… tatsächlich ist das nicht wirklich ein Bug. Insbesondere nicht in TUDa-CI.
Das ganze kommt daher, dass die Roboto-Mono, die wir als Schriftart einbinden größer ist, als die übrigen LaTeX-Schriftarten. Schriftgrößen sind einfach … sagen wir witzig.  Ich versuche das mal zu erklären ganz unten eine „Lösung“.

Minimalbeispiel ohne tuda-ci wäre:
```
\documentclass[10pt]{beamer}

\usepackage{roboto-mono}

\usepackage{minted}

\begin{document}
	
\begin{frame}[fragile]{Test 2b: problem, with \textbackslash scriptsize}
\scriptsize
\begin{minted}[fontsize=\scriptsize,highlightlines={2-3},highlightcolor=green!10,numbers=left]{java}
class Main {
public static void main(String[] args) {
System.out.println("a_0: " + args[0]);
}
}
\end{minted}
\end{frame}
```

Das ganze passiert genau dann, wenn die Schriftgrößenboxen eben nicht selbst groß genug sind, sodass LaTeX einen `\lineskip` dazwischen einfügt. 

Bei beamer ohne 10 pt Option passiert das nicht, weil dann eben `\scriptsize` einen größeren Unterschied zwischen dem `\baselineskip` und der Schriftgröße hat. 

––––––––––––––––
Als Lösung könnte man entweder bei minted den baselinestretch erhöhen: 
```
\begin{minted}[fontsize=\scriptsize,highlightlines={2-3},highlightcolor=green!10,numbers=left]{java}
```
Oder an das Paket robot-mono eine Scale-Option schicken, dafür müsste man vor `\documentclass`
```
\PassOptionsToPackage{scale=.9}{roboto-mono}
```

Das das nur für sehr kleine Schriftgrößen passiert würde ich ungerne pauschal alles anpassen. Insbesondere weil das auch wieder Paketabhängig auftreten kann.

**Comment by Locke** [comment]
Vielen Dank für die Untersuchung! Beide Lösungsvorschläge scheinen das Problem zu lösen, ich muss mir noch in Ruhe überlegen und ausprobieren, wie ich es konkret bei mir umsetze.

In dem Vorschlag taucht `baselinestretch` nicht auf, vermutlich wurde die falsche Zeile kopiert.

Daher zur Vollständigkeit mit einem Wert, den ich ausprobiert habe:

`\begin{minted}[fontsize=\scriptsize,baselinestretch=1.1,highlightlines={2-3},highlightcolor=green!10,numbers=left]{java}`

**Comment by TeXhackse** [comment]
Danke, habs oben angepasst und ja, falsch kopiert …
