### ISSUE TITLE
pagestyle adjustment for headings=automark not working as intended 2 (similar to #8)

### ISSUE THREAD

**Issue by Physics13** [tudace/tuda_latex_templates#35]
Hi,

I have a similar problem as in the issue mentioned in the title. If I use the following code 
`\pagestyle{TUDa}`    
`\ihead{}`
`\chead{}`
`\ohead{}`
`\ifoot{\headmark}`
`\cfoot{}`
`\ofoot{\pagemark}`
`\automark[section]{chapter}`
together with `headline=automark` I get this result
![Screenshot from 2019-09-13 14-48-33](https://user-images.githubusercontent.com/55282863/64863689-c0eed880-d635-11e9-8c42-9626ffad1947.png)
`custommargins` is set to false, `marginpar` also. Setting `marginpar` to true makes it even worse

**Comment by TeXhackse** [comment]
I will fix this. As a quick workaround I'd suggest to add 
```
\loadgeometry{TUDa@nomarginpar}
```
right after `\begin{document}`.
