### ISSUE TITLE
TuDaPhD.tex: \tuprints command output is as unexpected

### ISSUE THREAD

**Issue by syamalpraneeth** [tudace/tuda_latex_templates#353]
When I try to add in a tuprints info page with the command:
`\tuprints{urn=1234,printid=12345,doi=10.25534/tuprints-1234,license=cc-by-4.0}`
I get the following error:
`LaTeX3 Error: The key 'TUDa/thesis/doi' is unknown and is being ignored. ...10.25534/tuprints-1234,license=cc-by-4.0}`

Also, the URN and URL info are printed out rather awkwardly, minus the creative commons license logo:
![image](https://user-images.githubusercontent.com/63362007/152856396-a608344e-5a9a-4d1f-aae2-e706f3493a87.png)

**Comment by TeXhackse** [comment]
This seems to be an issue of an outdated installation. 

Please update your TeX distribution.

**Comment by syamalpraneeth** [comment]
Thanks for responding! Indeed you are right, I was still using outdated installation. The file `tudapub.cls' is of version 2.08 (2020/02/10), I downloaded the tuda-ci package available on MikTeX. I currently am building the document on TeXStudio on Ubuntu 20.04.3 LTS.

I now seem to have trouble with getting my TeX editor to use the latest tuda-ci files, instead of the ones from MikTeX. How may I do this?

**Comment by TeXhackse** [comment]
Since Ubuntu is Debian based one could have a look at this for a general discussion of that issue: https://tug.org/texlive/debian.html

In case it's compatible, I did not test it during the last months the  easiest way to use a different package version would be to copy the package files directly to your working directory.  So you download the files you need directly from ctan: 

http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/tex/tudapub.cls
http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/tex/tudathesis.cfg

These two should be enough.

**Comment by syamalpraneeth** [comment]
Thanks, I am trying this out. Unfortunately, my LuaLatex is suddenly completely failing on me, and I can't make anything work as of now. I have made this tex stack exchange post about the same in the meantime: https://tex.stackexchange.com/questions/633076/unable-to-compile-anything-with-lualatex-anymore

I will update on this thread in case I am able to fix the issue with by copying just the tudapub.cls and tudathesis.cfg into my working directory.

**Comment by TeXhackse** [comment]
You now have a MikTeX and a TeX Live installed at the same time?

**Comment by syamalpraneeth** [comment]
Hi @TeXhackse! Your solution worked. I had to delete my MikTeX installation and reinstall it (I have only MikTeX, no TeX Live), and everything works fine.

The \tuprints data is printed as expected. Thanks a lot for your help!

![image](https://user-images.githubusercontent.com/63362007/152976771-309eb03a-62f7-4cca-81ad-649ac891d4cf.png)
