### ISSUE TITLE
TuDaPhD.tex in English: Title page appears in German + 

### ISSUE THREAD

**Issue by syamalpraneeth** [tudace/tuda_latex_templates#354]
Used `\usepackage[english, main=english]{babel}` to set the language to English. Title Page appears in German Language.

Furthermore, on the page generated by \tuprints command, it says: "Review", and I believe it should be "Reviewer"

**Comment by TeXhackse** [comment]
This is true, the titlepage itself always set's the language to German. This was a condition which has been preset for this template.

**Comment by TeXhackse** [comment]
To explain: I was told the text „Dissertation im Fach …“ has to be in German no matter what language is the main langage of the document. That's why it's enforcing the switch.

**Comment by syamalpraneeth** [comment]
Thanks for explaining! Thought it was an issue on my end. The issue is resolved.
