### ISSUE TITLE
Feature request in TuDaPhD.tex: Adding vertical lines in margins beside paragraphs and images  

### ISSUE THREAD

**Issue by syamalpraneeth** [tudace/tuda_latex_templates#355]
Thanks for responding to my previous issues! I would like to mark certain paragraphs and images with vertical lines in the inner margins in the document. This is being used in the Materials Science department to quote verbatim text from papers that the thesis author is the first author of. For eg; see this thesis: https://tuprints.ulb.tu-darmstadt.de/5795/

![image](https://user-images.githubusercontent.com/63362007/152859983-5789881c-bd9f-495b-94e4-5ce4b4cf69c5.png)

I tried using `mdframed` and also `framed` packages as presented in these solutions:
 https://tex.stackexchange.com/questions/86381/adding-vertical-lines-to-each-side-of-a-paragraph
 https://latex.org/forum/viewtopic.php?t=5580

This works with text, but with a few limitations: the paragraph margins are offset when these bars appear. Howeverm it seems to not be working at all for figure environments in TuDaPhD.tex files. Would you have a solution for this, that I could implement locally on my file, or could it somehow be incorporated in the tudapub.cls file?

**Comment by TeXhackse** [comment]
Doe these rules have to include page breaks?

**Comment by syamalpraneeth** [comment]
They can be discontinuous across page breaks, like in this excerpt from this TU Darmstadt thesis: https://tuprints.ulb.tu-darmstadt.de/5795/

![image](https://user-images.githubusercontent.com/63362007/152863290-bc29f304-f474-477f-bd0b-dde5a5cb594d.png)

**Comment by TeXhackse** [comment]
I see. I think it's not a good idea to support it with TUDa-CI by default.

Because it's a too specific. But I created a similar implementation for another project which one could use here. I will run some test on this during the next days and return to you afterwards.

**Comment by TeXhackse** [comment]
I will close this because it's unrelated to TUDa-CI. We resolved it via email. There's a bunch of packages to do this. To name some I'd try  tcolorbox or the changebar package.
