### ISSUE TITLE
\Metadata does not support mixed-case pdfx metadata fields

### ISSUE THREAD

**Issue by op3** [tudace/tuda_latex_templates#356]
`\Metadata{}` passes its arguments to pdfx. The documentation states:

> […] stellt `tudapub` hierfür das Makro `\Metadata{}` zur Verfügung. Hier können sämtliche von `pdfx` verarbeitbaren Variablen nach `Schlüssel=Wert`-Struktur gesetzt werden.

For example, `author=Myself` is turned into `\Author{Myself}` in the generated `.xmpdata` file that is read by pdfx.

However, I could not figure out how to use `\Metadata{}` to set non-capitalized pdfx metadata fields, i. e. field names that do not consist of an uppercase first letter followed by only lowercase letters. In particular, I was interested in setting CopyrightURL, but the same problem also occurs for other fields such as URLlink, ISBN, PublicationType or CoverDate (and others).

Minimum example:
```tex
\documentclass{tudapub}
\begin{document}
\Metadata{
    keywords={cookies\sep muffins},
    CopyrightURL={https://creativecommons.org/licenses/by-sa/4.0/deed.en},
}

\title{My Title}
\author{Myself}
\maketitle
\end{document}
```

`keywords` is correctly turned into `\Keywords{}`, but `copyrightURL` is not. Log excerpt:
```
This is LuaHBTeX, Version 1.13.2 (TeX Live 2021/Arch Linux)  (format=lualatex 2022.1.2)  8 FEB 2022 16:13
 system commands enabled.
 file:line:error style messages enabled.
**mwe.tex
(./mwe.tex
LaTeX2e <2021-11-15> patch level 1

[…]

(/usr/share/texmf/tex/latex/tuda-ci/tudapub.cls
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2021-11-22 L3 programming layer (loader) 

(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-luatex.def
File: l3backend-luatex.def 2021-12-14 L3 backend support: PDF output (LuaTeX)
\l__color_backend_stack_int=\count181
\l__pdf_internal_box=\box50
))
Document Class: tudapub 2022/01/12 v3.21 Publications using TU Darmstadt's Corp
orate Design (TUDa-CI)

[…]

./mwe.tex:11: Package tudapub Error: You used the copyrighturl metadata entry.
(tudapub)                I don't know how to handle that.
(tudapub)                It will be ignored.

[…]
```

Using `copyrightURL=` or `copyrighturl=` instead also does not work.

**Comment by TeXhackse** [comment]
Thanks for reporting. You are right, though the reason is different. 

We are currently converting all the metadata to titlecase. So the first letter will be capitalized and the others will set to lowercase. This doesn't work for the mixed case fields. I will add an exception for those.
