### ISSUE TITLE
Anpassung des Titels auf der Titelseite (Documentation of title= option)

### ISSUE THREAD

**Issue by fihmels** [tudace/tuda_latex_templates#357]
Gibt es eine Möglichkeit bei langen Titeln im TUDaThesis template die Schriftgröße des Titels auf der Titelseite anzupassen bzw. den Titel auf bspw. drei Zeilen zu beschränken?

**Comment by TeXhackse** [comment]
Man kann sie verkleinern mit der Option `title=small`

Begrenzen wäre ja quasi ein abschneiden, falls dieser länger ist, das ist nicht sinnvoll.

**Comment by TeXhackse** [comment]
@fihmels hat das geholfen? Oder was wr das eigentliche Ziel der Anfrage?

**Comment by ILINRIS** [comment]
> Man kann sie verkleinern mit der Option `title=small`

Wo genau finde ich denn diese option bzw. wo muss ich diese einfügen?

**Comment by TeXhackse** [comment]
Ist bei den Möglichkeiten die Titelseite anzupassen beschrieben. Optionen zu den TUDa-CI Klassen setzt man mit bei `\documentclass`

```
\documentclass[<ggf. andere Optionen>,title=small,<ggf. andere Optionen>]{tudapub}
```

**Comment by ILINRIS** [comment]
Danke für die rasche Antwort! Gibt es hier auch eine Option zwischen "small" und der Standartgröße oder die Möglichkeit die Schriftgröße selber festzulegen?
Wo genau finde ich denn die Beschreibung? Ich habe diese weder in DEMO-TUDaThesis.tex noch in DEMO-TUDaPub.tex gefunden.

**Comment by TeXhackse** [comment]
> Danke für die rasche Antwort! Gibt es hier auch eine Option zwischen "small" und der Standartgröße oder die Möglichkeit die Schriftgröße selber festzulegen?

Nein. Das Design hat hier feste Vorgaben. 

> Wo genau finde ich denn die Beschreibung? Ich habe diese weder in DEMO-TUDaThesis.tex noch in DEMO-TUDaPub.tex gefunden.

Danke. Es scheint irgendwie verloren gegangen zu sein. Ich war der festen Überzeugung, dass das dort war, kann es aber gerade selber nicht mehr finden.
