### ISSUE TITLE
\dot{\vec x} creates a loop

### ISSUE THREAD

**Issue by humbertobernui** [tudace/tuda_latex_templates#358]
Hallo! 
Ich habe folgendes Problem. Ich habe gerade das neue Format installiert und hab gemerkt dass es folgendes Fehler anmeldet, wenn ich ein Punkt über den Vektor schreiben will, wie folgt $\dot{\vec r}$ (equation oder align Umgebung machen keinen Unterschied, und ich hab die gebrauchte packages dafür im \usepackage benutzt). Am Ende wenn nur eine von diesen Gleichungen da ist kompiliert es schon und man sieht das Ergebnis. Problem ist wenn mehrere da sind, kann man das nicht builden
Folgendes Fehler für den selben Ausdruck kommen mehrmals.
"Illegal unit of measurement"
"Undefined control sequence"
"Missing number, treated as zero".

Ich kann \dot{r} benutzen und \vec{r} benutzen aber irgendwie lass man mich nicht beide kombinieren (wie im alten Templates)

**Comment by schoeps** [comment]
Welcher compiler, welches Template, welches System? 

Ich habe es gerade mal schnell mit Beamer und Pub auf einem Mac mit Texlive probiert, da geht folgendes einwandfrei:
```
\documentclass[]{tudabeamer} 
\begin{document}
\begin{frame}
$\dot{\vec r}$
\end{frame}
\end{document}
```
und
```
\documentclass[]{tudapub} 
\begin{document}
$\dot{\vec r}$
\end{document}
```

**Comment by humbertobernui** [comment]
Ich musste es mit Lualatex machen. Es funktioniert einwandfrei wenn es nur ein ist, aber ich bekomme ein Error sowieso, bei tudapub. Hab eine neue macro geschrieben und es funktioniert jetzt. Sytem is MacOs Monterrey mit M1 Chip und MikTex

**Comment by humbertobernui** [comment]
![Captura de Pantalla 2022-03-04 a la(s) 11 01 35](https://user-images.githubusercontent.com/50801100/156742369-7dc5a3a9-a6bc-4fc8-803a-59c3ec63d65f.png)
Aber es kompiliert schon

**Comment by humbertobernui** [comment]
![Captura de Pantalla 2022-03-04 a la(s) 11 03 37](https://user-images.githubusercontent.com/50801100/156742714-634dd55b-8ea8-4b4a-b26b-15598d944267.png)
Obwohl das Error da ist, zeigt das PDF das Ergebnis was nicht machbar ist für mehrere, da das Loop das Builden unterbricht

**Comment by TeXhackse** [comment]
Ich würde das gerne rekonstruieren … Also Welcher Dokumententyp? Es wirkt etwas für mich wie eine Kopie von #78. Aber das beschränkt sich auf PDF/A

**Comment by humbertobernui** [comment]
\documentclass[class=report,ngerman,
	accentcolor=1c,% Farbe für Hervorhebungen auf Basis der Deklarationen in den Corporate Design Richtlinien
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
	]{tudapub}

ist mein Starter

**Comment by TeXhackse** [comment]
```latex
\documentclass{tudapub}

\begin{document}
	$\dot{\vec{t}}$
\end{document}
```

So? Dann hätte ich gerne einen kompletten Log zu dieser Datei.

**Comment by humbertobernui** [comment]
Dieses ist das log ohne meine Korrektur mit dem Makro
[TM I_Miniskript.log](https://github.com/tudace/tuda_latex_templates/files/8184999/TM.I_Miniskript.log)

**Comment by TeXhackse** [comment]
Ich glaube das Problem hat erstmal nichts mit tuda-ci zu tun. 

```
\documentclass{tudapub}

\usepackage{amsmath}
\begin{document}
	$\dot{\vec{t}}$
\end{document}
``` 
Macht Probleme, das ist bekannt in #78. Liegt aber nicht an uns …

**Comment by humbertobernui** [comment]
Oh ok, weil ich hab das gleiche mit den alten design kompiliert und es gab keine Probleme, nichtmal das Loop error, aber vielen Dank für die Hilfe

**Comment by TeXhackse** [comment]
Jap, das ist exakt der Fehler aus dem verlinkten Issue. 

Muss es PDF/A sein? Sonst hilft es als Dokumentenklassenoption `pdfa=false` ui setzen

**Comment by TeXhackse** [comment]
Ich schließe das als duplicate of #78

**Comment by humbertobernui** [comment]
Oh ok, wusste nicht das das PDF/A war die Norm, dachte man sollte das als true setzen, sorry für die Zeitverschwendung

**Comment by TeXhackse** [comment]
@humbertobernui Alles gut., dafür sind wir da. 

 PDF/A ist die Voreinstellung, das ist richtig. Wenn es PDF/A sein soll ist im verlinkten Issue ein Patch, wir haben den nur nicht pauschal eingebaut, weil es eben von der Paketkonfiguration abhängt.
