### ISSUE TITLE
Roman Numbering of Bibliography

### ISSUE THREAD

**Issue by marklaz** [tudace/tuda_latex_templates#359]
-------- Weitergeleitete Nachricht --------
Betreff:     Latex Vorlage Referenzen
Datum:     Wed, 16 Mar 2022 10:57:33 +0100
Von:     Janet ...
An:     latex@ce.tu-darmstadt.de

Hallo,

ich habe eine Frage zu Latex und bin leider nicht in GitHub angemeldet, sodass ich dort keine Fragen stellen kann. Also versuche ich es doch einmal über diese Adresse. Ich würde gerne römische Zahlen für meine Referenzen-Seiten in meiner Masterthesis nutzen. Leider funktioniert das nicht so, wie ich mir das vorstelle. Der Code:
\printbibliography
\pagenumbering{Roman}
\setcounter{page}{4}
\addcontentsline{toc}{chapter}{Bibliography}

Nummeriert lediglich die letzte Seite meiner Referenzen mit römischen Zahlen. Der Code:

\pagenumbering{Roman}
\setcounter{page}{4}
\printbibliography
\addcontentsline{toc}{chapter}{Bibliography}

Nummeriert neben der Referenz-Seiten auch die letzte Seite meines Textes (direkt vor den Referenzen) mit römischen Zahlen. Wie kann ich das Problem beheben?

Liebe Grüße
Janet

**Comment by TeXhackse** [comment]
```
\cleardoublepage
\pagenumbering{Roman}
\setcounter{page}{4}%ich tippe, das ist dann überflüssig
\printbibliography
```
Und für den Inhaltsverzeichniseintrag einfach die Option `bibliography=totoc`.

Ich antworte dann noch per Mail direkt
