### ISSUE TITLE
Seitenränder ändern

### ISSUE THREAD

**Issue by Guppi1** [tudace/tuda_latex_templates#361]
Hi ,

Ich hoffe ich frage hier jetzt nichts was andere schon hundertmal gefragt haben.
Mein Problem ist ich kann nicht wie im PDF Tutorial (Einstieg in wissenschaftliches
Arbeiten mit LaTeX) angegeben die Seitenränder ändern. Wenn ich 

```
\documentclass[
	ngerman,
	ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={type=master},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
	accentcolor=1c,% Auswahl der Akzentfarbe
	custommargins=geometry,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}
```

auf geometry umgestellt habe, würde ich gerne die Seitenränder ändern. Haben die schon die einstellung aus der Tutorial PDF?

```
\newgeometry{lmargin=2,5cm, rmargin=2cm, vmargin=1cm}
```
Denn wenn ich diese ZEile einfüge möchte er pt werte haben anstatt cm. Kann man das umstellen oder ist das vordefiniert?

VIelen Dank

**Comment by TeXhackse** [comment]
`\newgeometry` ist an der Stelle nicht nötig `\geometry` reicht. Aber der Fehler kommt aufgrund des falschen Dezimaltrennzeichens.

```
\newgeometry{lmargin=2.5cm, rmargin=2cm, vmargin=1cm}
```
Wäre richtig. Kommata trennen die Elemente, Zahlenwerte werden mit Punkt übergeben.

**Comment by Guppi1** [comment]
Ah ok, Vielen Dank für die schnelle Antwort.
ich verlink mal das Tutorial hier. Ich weiß nicht vom wem das geführt wird aber es gibt eine gute Übersicht über alle wichtige Befehle für einsteiger, 

[13(1).pdf](https://github.com/tudace/tuda_latex_templates/files/8314581/13.1.pdf)

**Comment by TeXhackse** [comment]
Danke, muss ich mal durchsehen. Allgemein würde ich empfehlen in die Doku des Bundles zu gucken. Mal sehen, wann ich zeit finde das durchzusehen.

**Comment by schoeps** [comment]
Pädagogischer Kommentar: Es ist natürlich völlig legitim im Rahmen von Tutorials die Seitenränder ändern zu wollen, aber in der Praxis gibt es selten eine Notwendigkeit dafür. Ich empfehle verfügbare Templates unverändert zu übernehmen, denn die sind meist von kompetenten Leuten gestaltet worden und es gibt meist gute (ästhetische) Gründe für die getroffenen Voreinstellungen.

**Comment by Guppi1** [comment]
Vielen Dank für den Hinweis.

Welche Seitenränder nutzt man denn nun?

ICh schreibe meine Masterarbeit und die Grundeinstellung in dem Template sind in der Präambel mit custommargins=true gegeben. Wenn ich das true zu custommargins=geometry ändere werden die Seiten besser ausgefüllt. ICh weiß aber nicht welche Einstellungen von den Seitenrändern nun vorliegen. Außer ich drucke eine Seite aus und Messe nach. Ist das irgendwo dokumentiert oder lass ich einfach den Wert auf TRUE?

Sry, aber bin ein wenig verunsichert bezüglich der Formatierungen.

Danke im Vorraus

**Comment by TeXhackse** [comment]
Das hängt etwas davon ab, ob es Vorgaben gibt oder nicht. Das ist leider von Fachbereich zu Fachbereich unterschiedlich. 

Wenn es keine feste Vorgabe gibt, würde ich bei `custommargins=true` bleiben. Es ist richtig, dass hier die Zeilenlängen kürzer sind. Das ist allerdings gewollt. Wir berechnen hierbei den Satzspiegel automatisch, sodass eine gut lesbare Zeilenlänge dabei herauskommt. Das ist leider mittlerweile für viele ungewohnt, aber grundsätzlich gibt es dafür typografische Prinzipien, die größere Seitenränder vorsehen als sie leider mittlerweile oft üblich sind.

**Comment by Guppi1** [comment]
Ich finde es auch besser, wurde abe auf die großen Seitenränder angesprochen.

Nochmals vielen Dank und eine schöne Woche.

**Comment by schoeps** [comment]
> Ich finde es auch besser, wurde abe auf die großen Seitenränder angesprochen.

Dann wäre folgendes auch noch eine Variante mit schmalem Rand, die es aber nicht erfordert selbst Hand an `geometry` zu legen 
```
\documentclass[custommargins=false,class=report,thesis={type=master},marginpar=false]{tudapub}
\usepackage{blindtext}
\begin{document}
\blindtext
\end{document}
```

**Comment by TeXhackse** [comment]
Wobei die extrem klein sind und zu lange Zeilen haben. Ich weiß… offizielle Vorgabe aber die beziehen sich auf eine Schriftgröße von 8 pt ;-=

**Comment by schoeps** [comment]
Da die Frage nach den Rändern oft kommt, könnte man ja vielleicht wirklich ein paar Beispiele in der FAQ/Wiki sammeln...

**Comment by TeXhackse** [comment]
Ich hab das bisher nicht gemacht, weil ich bei allem immer einen Disclaimer setzen muss, weil ich ja nicht weiß, ob ggf. irgendwelche Vorgaben gelten. Wenn du das trotzdem für sinnvoll hälst, kann ich das mal mit vorbereiten.

**Comment by Spiekerooger1** [comment]
Ich habe auch Randvorgaben von meinem Fachgebiet. Die ich mit dem corporate design nicht umsetzen kann. Deshalb muss ich \geometry benutzen. Jedoch greift der \geometry Befehl nicht für die Titelseite. Hat jemand da eine Lösung?

**Comment by TeXhackse** [comment]
Die Titelseitenränder sind  durch den Corporate Design Guideline fest vorgegeben. Es geht grundsätzlich allerdings kann dann die komplette Berechnung fehlschlagen, weil das Layout darauf beruht, dass gewisse Größen alleine vom Papierformat abhängig sind. 
Üblicherweise geldten solche Randvorgaben aber nicht für Titelseiten. Ich würde empfehlen ds vorher zu klären und ich würde in keinem Fall das als „Lösung” bezeichnen.

Die Balkenbreiten sind über die Befehle `\coverpageleftmargin` und `\coverpagerightmargin`. Ansonsten lädt die Titelseite im Modus `custommargins=geometry` das Geometry-Layout `TUDa-nomarginpar`  das kann über erneutest setzen mithilfe von `\savegeometry{TUDa-nomarginpar}` bearbeitet werden.

**Comment by Spiekerooger1** [comment]
Vielen Dank, hat alles funktioniert.
