### ISSUE TITLE
Frage zu Pflichtangaben auf dem Titelblatt für Dissertation

### ISSUE THREAD

**Issue by GGottschalg** [tudace/tuda_latex_templates#364]
Hallo, 

bezüglich der Pflichtangaben für eine Dissertation auf dem Titelblatt habe ich folgendes Dokument gefunden: https://www.tu-darmstadt.de/forschen//wissenschaftlicher_nachwuchs_tu/promotionsinteressierte_tu/artikel_details_de_en_176641.de.jsp --> https://www.tu-darmstadt.de/media/dezernat_ii/promotionen_dokumente/Dissertation-Titelblatt.de.pdf

Wenn ich das richtig sehe, ist lediglich die Angabe des Jahres und des Ortes in dem Dokument etwas anders als in der LaTeX-Vorlage. Im Dokument aus dem Link wird auf der Vorderseite des Titelblatts nochmal das Jahr der Disputation hinter dem Erscheinungsort angegeben. Auf der Rückseite ist dann eine andere Angabe zum Dissertationsort inkl dem Zusatz Technische Universität Darmstadt sowie eine weitere Angabe mit dem Jahr der Veröffentlichung auf TUprints vorgesehen.

Gibt es dazu noch eine Option in der LaTeX-Vorlage, die ich übersehen habe? 
Oder gab es eine Abstimmung, dass die LaTeX-Vorlage die Auflagen für ein elektronische Veröffentlichung auch so erfüllt? 

Vielen Dank im Voraus!

**Comment by TeXhackse** [comment]
Das Erscheinungsjahr ist ja im Datum enthalten. Ich kann allerdings nicht wirklich was zu den Vorgaben sagen, weil ich rechtlich keine Auskunft geben kann.

Allerdings ist Darmstadt im Feld `\publishers` hinterlegt und man könnte somit das Jahr auch einfach dort mit ergänzen:

```
\publishers{Darmstadt 2022}
```

Bei der TUprints Angabe wird das etwas komplizierter. Ich werfe nochmal in Ruhe einen Blick in meine Unterlagen dazu.

**Comment by GGottschalg** [comment]
Alles klar, Danke für die schnelle Rückmeldung!

**Comment by schoeps** [comment]
Man muss bei den Vorgaben von TUPrints sehr genau lesen, was wirklich verpflichtend ist und was nur eine Empfehlung ist. Gucken Sie doch einfach mal wie die am Ende publizierten Dissertationen aussehen (sehr viele nutzen da sowieso das Latex-Template): https://tuprints.ulb.tu-darmstadt.de/view/type/thesis.html

**Comment by GGottschalg** [comment]
Alles klar, Danke für den Hinweis!

**Comment by TeXhackse** [comment]
@schoeps das heißt für mich: Passt alles?!

**Comment by schoeps** [comment]
Ich behaupte ja. Zumindest aus meiner AG kamen keine Klagen bei den letzten Einreichungen. Ich schlage vor @GGottschalg meldet sich, wenn es da -wider Erwarten- noch Probleme gibt.

**Comment by TeXhackse** [comment]
Danke. Dann mach ich das vorerst zu

**Comment by GGottschalg** [comment]
Ja, passt. Wir können den Issue erstmal schließen.
