### ISSUE TITLE
Evtl. Anpassung Installationsempfehlung für Linux

### ISSUE THREAD

**Issue by test123-all** [tudace/tuda_latex_templates#365]
Hey,
in der [README.md](https://github.com/tudace/tuda_latex_templates#readme) steht:

> **Sonderfall: Paketverwaltung des Betriebssystems (Linux/BSD)**
> 
> Für einige Linux/BSD-Varianten existieren texlive-Pakete die über die Paketverwaltung des Systems installierbar sind. Da TUDa-CI sehr speziell ist, ist es nur in der Paketen texlive-full enthalten. Falls Sie ein kleineres Setup wünschen, empfehlen wir die Installation über den TeX Live Manager https://tug.org/texlive/doc/texlive-en/texlive-en.html#installation.

Ich hatte unter KDE neon(baut auf Ubuntu auf) die komplette TexLive Distribution über die normalen apt Paketquellen installiert.  Das tuda-ci package war sehr outdated und konnte auch nicht mit dem tmlr geupdated werden. Es hat erst funktioniert, als ich TexLive über die files von der offiziellen Website installiert habe.

Mich würde interessieren ob jemand ähnliche Probleme hat oder hatte? Ich habe erst gemerkt, dass etwas nicht stimmt, als mich mein Betreuer darauf hingewiesen hat, dass ich das falsche Template verwende..

</br>
Falls ja, würde ich vorschlagen, dass man den Absatz etwas umformuliert und klar macht, dass es besser ist TexLive mit den Dateien von der offziellen Website zu installieren. 

(Ich kann mir etwas überlegen und einen Pull-Request machen, wenn gewünscht)

</br>
Viele Grüße

**Comment by TeXhackse** [comment]
Ähm, eigentlich sagen wir doch genau das damit, oder?

Wir empfehlen es über CTAN zu installieren und nicht über die Paketmanager?!

**Comment by test123-all** [comment]
Naja da steht 

> Falls Sie ein kleineres Setup wünschen,

Das "Falls" ist das Problem, es ist viel einfacher und schneller etwas aus den Paketquellen zu installieren also über andere Wege. Die Empfehlung gilt in dem Satzlaut meiner Meinung nach nur, wenn man eine kleinere Installation wünscht.

Ich würde es umformulieren zu:
Für einige Linux/BSD-Varianten existieren texlive-Pakete, die über die Paketverwaltung des Systems installierbar sind. Da TUDa-CI sehr speziell ist, ist es nur in dem Paket texlive-full enthalten. Die texlive-Pakete in den Paketen der Paketverwaltung des Systems können durch längere Update-Zyklen unter Umständen veraltet sein. Wir empfehlen deshalb ausdrücklich die Installation über den TeX Live Manager(tlmr) mit den Installationsdateien von der offziellen Website https://tug.org/texlive/doc/texlive-en/texlive-en.html#installation.

**Comment by TeXhackse** [comment]
Der Englische Text war besser aber mit mehr Typos. Glaube jetzt ist es verständlicher :)

**Comment by test123-all** [comment]
Passt so! Danke :)
