### ISSUE TITLE
TUDa Beamer - Serif Font with recent updates of pdflatex

### ISSUE THREAD

**Issue by unp1** [tudace/tuda_latex_templates#366]
Hi,

 I hope that is not a problem somewhere on my side (in that case, sorry for the noise). But was there a change in the TUDaBeamer class files that switched the font from sans serif to serif? If yes, is there a way to override it manually (I prefer sans serif for slides).

Thanks and best regards,
Richard

**Comment by TeXhackse** [comment]
>  (I prefer sans serif for slides).

guess you mean you prefer serif for slide.

Generally the idea of a Corporate Design is that users don't choose the font themselves.

Anyway ofc one could change this by adding 

```
\renewcommand*{\familydefault}{\rmdefault}
```
after the class was loaded.

**Comment by unp1** [comment]
Hi,

 thanks. I think sans serif. I have attached a PDF file: The first ist the slide from last year and the next one the result, I get when I compile it now. But I assume, the problem is on my side, so I'll check where I corrupted my latex installation :-)

Have a nice week-end and best regards,
Richard

[Differences.pdf](https://github.com/tudace/tuda_latex_templates/files/8351424/Differences.pdf)

**Comment by unp1** [comment]
Hi,
  just for completeness in case someone else comes across the problem as well. I managed to get the correct sans serif fonts back by changing the TeX engine from pdflatex to lualatex. 

My assumption is that some of the recent updates of MacTeX/TeX live) introduced that regression.

Best regards, 
Richard

**Comment by TeXhackse** [comment]
Interesting. I will reopen and have a lok at this, this should not happen.

**Comment by TeXhackse** [comment]
An update of XCharter is resetting the default font family to serif at end of preamble. I will patch this tomorrow. Thanks for reporting :)

**Comment by unp1** [comment]
Hi,

  ah great and thanks a lot! 

Best regards, 
Richard

**Comment by TeXhackse** [comment]
I had a closer look at this yesterday and contacted the author because it's a bit weird to add a hook to override the changes done by XCharter. I think that's the better approach. 

I am awaiting the answer to find out if that's an option for the author. Until this is done one could simply add
```
\AtBeginDocument{\renewcommand*{\familydefault}{\sfdefault}}
```
as a workaround. The font setup internally is still working correctly, only the default is set wrong.

**Comment by unp1** [comment]
Hello,

  thanks a lot for your effort! 

The XCharter update seems to have introduced some more strange behavior: I tried out the work-around and get some inconsistent results: titles are ok, definition environments are ok, block title are ok, but block text not and frame text not.

I attached a minimal tex example (file extension .txt as github does not accept .tex) and the produced pdf. 

Best regards, 
Richard 
[Slidetest.pdf](https://github.com/tudace/tuda_latex_templates/files/8357495/Slidetest.pdf)
[Slidetest.txt](https://github.com/tudace/tuda_latex_templates/files/8357496/Slidetest.txt)

**Comment by TeXhackse** [comment]
Hi Richard,
that's not strange at all. The blocks template included `\sffamily` whereas the definition uses a `\normalfont`  in advance. But for all of them the upper workaround should do it until I receive an answer.

**Comment by unp1** [comment]
Hi Marei,

  what I meant with strange is that despite the workaround the issue does not disappear completely, but the result is a mix of sans serif and serif fonts (the provided tex example includes the work-around).

For me lualatex works at the moment (also it seems to be somewhat slower) and I feel already guilty to waste your time (is there a way to donate for your efforts?). So let's wait for the XCharter author to provide an answer / fix.

Best regards,
Richard

**Comment by TeXhackse** [comment]
Oh I didn't have a look at the pdf just compiled it myself. Cannot reconstruct this. Could you attach a log file?

**Comment by unp1** [comment]
Hi Marei,

  thanks and of course. The log file is attached.

Best regards, 
Richard
[Slidetest.log](https://github.com/tudace/tuda_latex_templates/files/8358050/Slidetest.log)

**Comment by TeXhackse** [comment]
Alright, replace `\AtBeginDocument` With `\AtEndPreamble`  then it should work there as well.  Ensure that you add it after the class (and within this the XCharter package) has been loaded.

**Comment by unp1** [comment]
Hi,

  that worked. Thanks again!

Best regards, 
Richard

**Comment by TeXhackse** [comment]
Status information: The author is fine with adding a change to his package. I will prepare a suggestion. Might take some days but we will include the fix into the XCharter package directly

**Comment by TeXhackse** [comment]
The XCharter update was been published via CTAN yesterday, so all the mirrors should now have it. It's resolved without any further tuda-ci update.

**Comment by unp1** [comment]
Thanks a lot! I tried it out and can confirm that it fixes my issue.

Wish you a nice Easter Monday and best regards, 
Richard
