### ISSUE TITLE
Frage zur Titelseite - Groß- und Kleinschreibung "vorgelegte Dissertation"

### ISSUE THREAD

**Issue by GGottschalg** [tudace/tuda_latex_templates#367]
Hallo, 

ich habe noch eine Frage zur Titelseite bei Dissertationen:

Auf der Vorderseite steht bspw. in der Datei DEMO-TUDaPhD.pdf "Zur Erlangung des Grades eines Doktors der Naturwissenschaften (Dr. rer. nat.) **V**orgelegte Dissertation von ...". Gibt es eine Einstellung, dass ich dort das Wort "**v**orgelegte" kleinschreiben kann?

(Auf der Rückseite des Titelblatts soll es groß geschrieben bleiben, da dort der Satz mit diesem Wort beginnt. Auf der Vorderseite sehe ich den Satzanfang bei "Zur Erlangung...".)

Vielen Dank im Voraus!

**Comment by TeXhackse** [comment]
Guten Morgen. 
Option dafür gibt es keine. Es ist allerdings kein ganzer Satz. Es sind zwei unabhängige Teilsätze, die alle am Anfang groß geschrieben werden.

Ich hab das damals so als Vorgabe bekommen.
Grundsätzlich ist es möglich das `\subject`-Feld auf der Titelseite, das dafür verwendet wird, komplett zu überschreiben.

Ich hab eben mal in ein paar Vorlagen gewühlt und tatsächlich wird das bei der deutlichen Mehrheit der Varianten, die mir vorliegen so gemacht.

**Comment by GGottschalg** [comment]
Danke für die schnelle Rückmeldung!

Das hört sich gut an. Leider weiß ich nicht ganz, wie ich mit dem subject-Feld umgehen kann. Wo müste ich dafür etwas ändern oder gib es dazu vielleicht schon ein Beispiel?

**Comment by TeXhackse** [comment]
`\subject{Inhalt}`

**Comment by GGottschalg** [comment]
Alles klar, Danke. 

Das hat auf der Vorderseite funktioniert. Nun ist es auf der Rückseite allerdings auch klein geschrieben. Kann ich für Vorder- und Rückseite auch unterschiedliche Schreibweisen definieren?

**Comment by TeXhackse** [comment]
Das Feld auf der Rückseite ist `\uppertitleback` müsste man dann eben auch getrennt setzen.

**Comment by GGottschalg** [comment]
Ok, Danke!
