### ISSUE TITLE
Schriftgröße für \titleaddendum ändern/Nummerierungstil \thanks

### ISSUE THREAD

**Issue by ILINRIS** [tudace/tuda_latex_templates#369]
Hallo!  Ich verwende die Thesis-Vorlage basierend auf tudapub für meine Masterthesis. Ich würde gerne wissen, ob es eine Möglichkeit gibt die Schriftgröße in dem mit _\titleaddendum_ erzeugten Zusatz auf der Titelseite zu verkleinern. Grund ist, dass ich diese Funktion nutze, um die Institute meiner verschiedenen Reviewer (externe Thesis) als Fußnote zu ergänzen, diese aber mit der standardmäßigen Schriftgröße nicht in eine Zeile passen.

**Comment by schoeps** [comment]
Ich hätte gesagt, dass man das wie üblich mit `\titleaddendum{\tiny ...}` machen kann (oder `\scriptsize` bzw. einem der anderen Schriftgrößenkommandos). Klappt das nicht?

**Comment by TeXhackse** [comment]
Affiliations gehen bei den Reviwern ebenso wie bei den Autor:innen mit `\thanks{Institut}`

**Comment by ILINRIS** [comment]
> `\scriptsize` bzw. einem der anderen Schriftgrößenkommandos

Das funktioniert hervoragend. Danke!

> Affiliations gehen bei den Reviwern ebenso wie bei den Autor:innen mit `\thanks{Institut}`

Oh ja, das schein noch passender zu sein. Die FUnktion kannte ich nicht. Danke dafür :)
Aber ist es auch möglich den Stil der hierbei entstehenden Fußnoten zu Nummern zu ändern? DIe Lösungen, die ich online dazu gefunden haben, zerschießen alle das Layout der TU-Titelseite.



> Das erscheint allerdings nicht auf der Titelrückseite

Die Titelrückseite ist in meiner Thesis sowieso nicht vorhanden. ABer das scheint ja normal zu sein, wenn ich nicht die zweiseitige Version verwende, wenn ich das richtig verstanden habe...?

**Comment by TeXhackse** [comment]
Das ist richtig. Titelrückseite ist einseitig nicht sinnvoll.

**Comment by ILINRIS** [comment]
> \ExplSyntaxOn
> \makeatletter
> \renewcommand*{\ptxcd_title@footnote}[2][1]{
> 	\textsuperscript{\@arabic{#1}}#2
> }
> \makeatother
> \ExplSyntaxOff

Danke! Allerdings ändert das nur die Symbole in the "Fußnote" selber zu einer Zahl. Hinter dem Autor erscheinen dann immer noch die Symbole.
