### ISSUE TITLE
Reduce spacing Title of TUDaSciPoster

### ISSUE THREAD

**Issue by timbmg** [tudace/tuda_latex_templates#372]
Is it possible to reduce the spacing above the title of the tu TUDASciPoster?
![Screenshot 2022-04-20 at 11 01 55](https://user-images.githubusercontent.com/11020443/164192593-afec75dd-9640-444c-8778-9909b3af626f.png)

**Comment by TeXhackse** [comment]
Not easily. The spacing here is an important part of the design scheme. One would have to touch the internal length definitions to achieve this.

**Comment by TeXhackse** [comment]
To be a bit more clear, because I just had to have a look at some of the definitions anyway: You can copy the overlay definition from tudasciposter and adjust it by overwriting it inside your poster. It's hacky and ofc not officially supported.
