### ISSUE TITLE
tudapub: Farben inkorrekt, wenn xcolor vor Dokumentenklasse geladen wird

### ISSUE THREAD

**Issue by zentox** [tudace/tuda_latex_templates#373]
Wenn man das Package `xcolor` vor der Dokumentenklasse lädt, dann wird eine andere Farbe ausgegeben.

Beispiel:
```tex
\RequirePackage[table]{xcolor} % Remove for comparison
\documentclass[accentcolor=3d]{tudapub}

\title{Title}
\author{Author}
\begin{document}
\maketitle
\end{document}
```

Bild ohne Package vorher laden:
![Bild ohne Package vorher laden](https://user-images.githubusercontent.com/46193012/166122719-335c6e86-5102-468f-9da7-d898c21374e3.png)

Bild mit Package vorher laden:
![Bild mit Package vorher laden](https://user-images.githubusercontent.com/46193012/166122736-bf461313-d6ca-4159-b7ab-00597324e699.png)

**Comment by schoeps** [comment]
Ich bin recht sicher, dass das (wie fast immer in solchen Situationen) durch eine ungewollte CMYK-RGB-Umwandlung kommt. @TeXhackse weiß das bestimmt besser, aber ich vermute die eigentliche Frage ist doch, wie man xcolor mit tudapub verwenden kann, oder? Siehe #44

**Comment by TeXhackse** [comment]
Das ist richtig, weil die Option ja erst in der Klasse an das Paket durchgereicht wird.

Richtig wäre die Option an das Paket durchzureichen statt den Ladezeitpunkt vorzuziehen:

```
\PassOptionsToPackage{table}{xcolor}
```
Das gilt allgemein für alle Pakete und nicht TUDa-CI spezifisch.

**Comment by TeXhackse** [comment]
Das ist richtig, weil die Option ja erst in der Klasse an das Paket durchgereicht wird.

Richtig wäre die Option an das Paket durchzureichen statt den Ladezeitpunkt vorzuziehen:

```
\PassOptionsToPackage{table}{xcolor}
```
Das gilt allgemein für alle Pakete und nicht TUDa-CI spezifisch.

**Comment by zentox** [comment]
Danke für die Aufklärung! Ich war verwundert, wieso dies nur bei `tudapub`auftriftt, aber bei `tudaexercise`nicht.

**Comment by TeXhackse** [comment]
@zentox das liegt am PDF/A tudapub erzwingt normalerweise RGB, weil PDF/A kein CMYK Schema haben darf. 

Bei den exercise-Dateien wird normalerweise kein PDF/A erzeugt. Daher kommt der Unterschied.

**Comment by Croydon** [comment]
For anyone finding this issue because of (newer) color problems, the fix might be here: https://github.com/tudace/tuda_latex_templates/issues/456#issuecomment-1927949941
