### ISSUE TITLE
Zurücksetzen der Chapter Nummerierung | Falsche Verwendung Befehl?

### ISSUE THREAD

**Issue by test123-all** [tudace/tuda_latex_templates#374]
Hey,
ich habe versucht die Nummerierung des Chapters für den Anhang  zurückzusetzen mit:
```
\renewcommand{\thechapter}{\Alph{chapter}}
\setcounter{chapter}{0}

\chapter{Anhang A - Lernressourcen zur einfacheren Einarbeitung}
```
Das erreicht das erzielte Ergebnis, dass die Nummerierung, der nach diesen zwei Zeilen kommenden Chapter nicht mehr in Zahlen sondern Alphabetisch in Großbuchstaben ist. Der `setcounter`-Befehl resetet die Chapter, damit sie im Anhang bei "A" beginnen. Die Seitennummerierung ist, wie gefordert, fortlaufend. 

Beispielscreenshot:
![Screenshot_20220503_134757](https://user-images.githubusercontent.com/84460847/166447899-a159e126-1859-4932-99c8-0b81e534b071.png)

Soweit alles gut.

Wenn ich jetzt versuche im Inhaltsverzeichnis auf die Anhang Kapitel zu klicken(hyperref) lande ich nicht im Anhang sondern auf den Seiten des Hauptteils. Wenn man die .pdf in einem Reader öffnet ist links die Nummerierung des ausklappbaren Inhaltsverzeichnis auch falsch. Siehe:

![Screenshot_20220503_140841](https://user-images.githubusercontent.com/84460847/166450152-84dd7efb-054f-4e2f-bf14-8a64c4826fcb.png)

Ich benutze KDE Neon(basiert auf Ubuntu) in der aktuellen Version.

Benutze ich die Befehle falsch? Ich habe mich an den LaTex How-To Guide der TUDa gehalten, der von Ben Reusch zur Verfügung gestellt wird.

Oder ist das ein Bug in dem package?

Viele Grüße

**Comment by TeXhackse** [comment]
Hallo 

Ohne mehr Infos ist das etwas schwierig zu sagen. 
Tatsächlich funktioniert der manuelle Weg. Schöner wäre es stattdessen einfach mit `\appendix` umzuschalten. Grundsätzlich sollte aber beides funktionieren.

Welcher „LaTex How-To Guide der TUDa“? davon weiß ich leider nichts.

Grundsätzlich funktionieren die Bookmarks im tuda-ci Bundle so wie erwartet. Für eine Genauere Analyse bräuchte ich Code, Screenshots sagen da leider wenig.

Falls das hier doof ist geht auch per Mail.

**Comment by TeXhackse** [comment]
Ich hab das Dokument gefunden und gehe dem nach. Aber das ist unerheblich zu meiner Rückfrage.

**Comment by test123-all** [comment]
Hey :)
ich wusste nichts von dem `\appendix` Befehl. Damit funktioniert es! Es wäre schön, wenn der Guide irgendwie online zugänglich wäre(auf GitHub oder so), da fehlen einfach viele Sachen..

Zurück zum Thema: Das es mit dem `\appendix` Befehl funktioniert, möchtest Du immernoch den Code haben? Da es um meine Bachelorthesis geht, die nicht veröffentlicht wird und bereits zur Korrektur abgegeben ist, würde ich Dir den ganzen Projektordner per Email schicken(~100 MB)(als .zip oder .gz.tar Archiv) oder kann ich das irgendwie zu einem MinimalWorking Example zusammen kürzen?

**Comment by test123-all** [comment]
Okay, da ich keine Anpassungen vorgenommen habe, habe ich das veränderte Template von dem Institut in Verdacht gehabt.
Tatsächlich tritt der Fehler dort auch auf. Ich bespreche mit meinen Betreuern, ob ich dir das Institut Template als MWE schicken darf. Melde mich dann morgen nochmal.

Wegen dem Guide, vielen Dank! :D

**Comment by TeXhackse** [comment]
Ah, das kann auch gut sein, dass das dazu führt. Grundsätzlich bitte Ausrichten, dass ich gerne zumindest Kenntniss von solchen Anpassungen habe. Ich kann dann ggf. zumindest informieren, wenn wir interne Dinge ändern sollten.

**Comment by test123-all** [comment]
Okay, ich habe dir gerade an die Emailadresse, die in den Headern der LaTex Packages hinterlegt ist, eine Email geschrieben.
In der Email ist das Institutstemplate mit einer kurzen Erklärung als MWE.

Dass du gerne Bescheid haben möchtest, wenn neue Versionen erstellt oder Anpassungen unternommen werden, habe ich weiter gegeben :)
