### ISSUE TITLE
Überschrift bei TUDaPub kleiner machen.

### ISSUE THREAD

**Issue by FlixXIV** [tudace/tuda_latex_templates#376]
Hallo ich würde gerne bei meiner Vorlage für die Bachelorarbeit die Überschrift ein wenig kleiner machen. Die Dokumentenklasse lautet konkret:

\documentclass[
ngerman,
ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
thesis={type=bachelor},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
accentcolor=9c,% Auswahl der Akzentfarbe
custommargins=false,% Ränder werden mithilfe von typearea automatisch berechnet
marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
%BCOR=5mm,%Bindekorrektur, falls notwendig
parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}

Wie kann ich dies tun?

**Comment by TeXhackse** [comment]
Welche Überschrift? Den Titel oder die Abschnitts/Kapitelüberschriften?

**Comment by FlixXIV** [comment]
Den offiziellen Titel, also der mit \title{} übergeben wird

**Comment by TeXhackse** [comment]
Als Klassenoption `title=small` mit angeben, dann ist der eine Stufe kleiner.
