### ISSUE TITLE
adding funding acknowledgement 

### ISSUE THREAD

**Issue by 12ert3** [tudace/tuda_latex_templates#377]
Hi, 
I would like to add a standard acknowledgement ("Diese Arbeit wurde vom Ministerium für Bildung und Forschung (BMBF) and dem Bundesland Hessen als Teil des NHR-Programms gefördert." ) for funding on the second page of the thesis, right in the middle between the location "Darmstadt" and "Please cite..." 

How can I do that? Do I need to alter the template? 

Thank you!

**Comment by TeXhackse** [comment]
The “Darmstadt” is placed via `\publishers{Darmstadt}`  maybe it's the easiest to simply extend this field by using `\publishers{arbitary acknowledgement text}` if the placing is not fixed I'd usually use the sponsors fields for that.

**Comment by 12ert3** [comment]
Thank you for the super fast resonse. 
Unfortunately, this leads to the acknowledgement also being displayed on the front page. 
Where in the very sophisticated class-definition would I need to add the acknowledgement sentence?
Thank you!

**Comment by TeXhackse** [comment]
Oh sorry didn't see the “second page”. Well then you can only adjust it by overwiring the whole `\uppertitleback{<content>}` field.

**Comment by TeXhackse** [comment]
I close this as it seems to be resolved for me. In case it's not, feel free to reopen.
