### ISSUE TITLE
Keine Funktion von Biblatex | Literaturverzeichnis fehlt

### ISSUE THREAD

**Issue by test123-all** [tudace/tuda_latex_templates#378]
Hallo Marei,
erstmal sorry, dass ich schon wieder Probleme mache.

Long story short: Wenn ich die Beispieldateien aus dem Bundle erzeuge, funktioniert Biblatex mit der aktuellen Version des packages(version 3.25 (2022/04/25)) nicht und die Seite mit dem Literaturverzeichnis fehlt.
Ich würde erwarten, dass die erzeugte .pdf Datei exakt der Beispiel .pdf entspricht, die dem Bundle beiliegt.

Wenn man alle erzeugten Dateien löscht, wird der folgende Fehler beim erneuten kompilieren/erzeugen angezeigt:
```
This is BibTeX, Version 0.99d (TeX Live 2022)
The top-level auxiliary file: DEMO-TUDaPub.aux
I found no \citation commands---while reading file DEMO-TUDaPub.aux
I found no \bibdata command---while reading file DEMO-TUDaPub.aux
I found no \bibstyle command---while reading file DEMO-TUDaPub.aux
(There were 3 error messages)

Process exited with error(s)
```
Ich habe das gerade sowohl auf Linux als auch auf Windows getestet, bei Beiden besteht der selbe Fehler.

Wenn das ein dummer Anwenderfehler ist, tut mir das sehr Leid. Ich habe keine Ahnung wo ich als nächstes ansetzen soll, außer dir hier zu schreiben. Die .bib Datei ist im Verzeichnis vorhanden.

Liebe Grüße

Sebastian

**Comment by TeXhackse** [comment]
Ähm, BibTeX kann das auch nicht machen. Man muss als Backend im Editor Biber auswählen, damit das läuft. Je nach editor ist die Einstellung an einer anderen stelle.

**Comment by test123-all** [comment]
Danke, das habe ich gerade über Google auch gefunden! Vielen vielen Dank! :D :+1:
