### ISSUE TITLE
optional english translation of affidavit

### ISSUE THREAD

**Issue by schrchr** [tudace/tuda_latex_templates#38]
An additional english translation of the affidavit, which could be toggled on and off e.g. by using a parameter, would be nice. A translation can be found [here](https://www.etit.tu-darmstadt.de/media/etit/01_etit/formulare_studium/richtlinien/richtlinienabschlussarbeiten.pdf)

In code:
```
\paragraph{English translation for information purposes only:}
\vspace{1cm}

\paragraph{Thesis Statement pursuant to § 22 paragraph 7 and § 23 paragraph 7 of APB TU Darmstadt}
I herewith formally declare that I, \textbf{\textcolor{red}{Forename Surname}}, have written the submitted thesis independently pursuant to § 22 paragraph 7 of APB TU Darmstadt. I did not use any outside support except for the quoted literature and other sources mentioned in the paper. I clearly marked and separately listed all of the literature and all of the other sources which I employed when producing this academic work, either literally or in content. This thesis has not been handed in or published before in the same or similar form.
I am aware, that in case of an attempt at deception based on plagiarism (§38 Abs. 2 APB), the thesis would be graded with 5,0 and counted as one failed examination attempt. The thesis may only be repeated once.
In the submitted thesis the written copies and the electronic version for archiving are pursuant to § 23 paragraph 7 of APB identical in content.
```

Finally the page could look like this:

![grafik](https://user-images.githubusercontent.com/50080123/65179682-92209a00-da5b-11e9-9dd8-e44a5208f026.png)

**Comment by TeXhackse** [comment]
I request @marklaz and @schoeps to decide about that.
Would be no problem to add this, but I don't know about different versions and legal requirements on the affidavit for your university.

**Comment by schoeps** [comment]
@schrchr Is someone (your supervisor?) forcing you to put the english statement? It's just for information purpose and not legally binding and thus commonly skipped. This is also stated in the document referenced above. So, I would not recommend enabling it by default if language is set to english. Of course, we could make it optional....

**Comment by schrchr** [comment]
No, it just would be nice if the whole thesis is in english, also the statement has a english version. I think a optional solution would be perfect.

**Comment by slinshady89** [comment]
FYI
The institute rmr treats it that way.

**Comment by TeXhackse** [comment]
Well, I'll keep that one open.

I am not in the posiition to decide about that. Currently the CE department is responsible concerning my work. If I get an official request, it's not hard to be implemented.

I can offer to implement a hook to offer you an easy way for adding custom texts.

**Comment by marklaz** [comment]
I also would suggest to include it as an optional text, which is deactivated by default, but may be activated in addition if required.

Where does the English translation above originate from?

An important point from my side is, that date and signature should definitely be located directly below the German version. The English version, including the statement that it is included for information purposes solely, should be placed below that.

**Comment by TeXhackse** [comment]
@marklaz well then anyone can just add a custom text below the German one. So just let me know, if we need adjustments for that. Until then I will just leave it that way.

**Comment by marklaz** [comment]
I vote for adding a hook to add custom text below the German affidavit incl. signature.
As there seems to be no further reaction, this issue can be closed after the code extension.

**Comment by TeXhackse** [comment]
Suggestion:
```
\affidavit* %deutsche variante ohne abschließenden Seitenumbruch

%Zusätzlicher text in beliebiger Sprache
\begin{affidavit*}[english]{Title}
	additional optional text
\end{affidavit*}
```
it will look like this.

![image](https://user-images.githubusercontent.com/10723888/69001135-0485ed00-08da-11ea-8581-0360cf9d005f.png)


The date is in this example is autotranslated, because I used `\today`. Static days wont. We could think about redefining `\today` to use the submissiondate.

**Comment by marklaz** [comment]
Please remove the second date and signature fields below the translated version. To avoid ambiguity, there should be only one signature on the page directly below the German text.

**Comment by TeXhackse** [comment]
okay, will do. Makes the date to be handled easier. I just thought people might want that. There's a macro for manual addition of signature rules now. In case someone would need that.

**Comment by marklaz** [comment]
Can I close this issue?

**Comment by TeXhackse** [comment]
Nope, I gotta check something first and want to keep it open until I am fine with all features aabout it. otherwhise i'd forget
