### ISSUE TITLE
Math accents not centered

### ISSUE THREAD

**Issue by Fred234567890** [tudace/tuda_latex_templates#381]
Hello,

I have an Issue with the math accents. If I use for example $\hat f$ then the hat is not centered above the f. 
![grafik](https://user-images.githubusercontent.com/38631113/177009165-07580293-db3d-484d-8fa1-cfa0c86aa6fa.png)
It seems like it's centered inside the letter's box. But this is of course unintended because f is italic in math mode. Does anybody have an Idea? I don''t think I'm the first who encountered thus  but I didn't find it in the issues.

Thanks
Frederik Quetscher

**Comment by TeXhackse** [comment]
Hi, thanks for reporting, 

I sadly can't tell you anything else but the fact I don't face this issue. It seems to be some custom setup, without knowing more about how you create the hat, I find it a bit difficult to say anything about the reason. I think it's probably unrelated to TUDa-CI, but I will try to help anyway 

Could you please try using the following minimal example 

```
\documentclass{tudapub}

\begin{document}
	\[\hat{f}  \]
\end{document}
```
For me this gives
![image](https://user-images.githubusercontent.com/10723888/177009482-a538ff35-73a9-4786-8b78-9e48d3d07327.png)
 like intended. 

In case your Code has a different structure I'd need to know this.

Best,
Marei

**Comment by Fred234567890** [comment]
Thanks for your very quick reply. I tried your example and it works fine, as you expected. So I tried to find a minimal example that reproduces the error and found this:
```
\documentclass{tudapub}
\usepackage{mathtools} % erweiterte Fassung von amsmath
\begin{document}
	\[\hat{f}  \]
\end{document}
```
If I use tudapub and replace mathtools with the regular amsmath, then the error still occurs. 

If I switch the documentclass to article, then everything is fine. But of course I want to use tudapub, so this is no option. So it seems to be a problem of using amsmath/mathtools  with tudapub. Or am I missing something?

**Comment by TeXhackse** [comment]
It seems to be an interaction with pdfx. I am currently planning to replace this by the latex kernels pdfmanagement but as long this is not available everywhere i cannot switch to that. 

The pdfx package is responsible for the PDF/A standard support. In case you rely on this I can explain to you how to get it without pdfx, In case you don't you can simply use the `pdfa=false` option to fix it. 

Sadly we were forced to enable the PDF/A mode by default, so I may not do any adjustments until I can ensure all mechanism working with the LaTeXs own pdfmanagement.

**Comment by Fred234567890** [comment]
Hi, thank you for that workaround. It works. But I don't know if I can use it because I'm writing my master thesis and it has to be uploaded to tubama in PDF/A. I mean, I can use it and give my professor both versions. The official and the pretty version. But that is unsatisfying.

**Comment by TeXhackse** [comment]
That' why I asked. It's possible to create a PDF/A differently, it's just not yet completly included in the bundle. 

I'd need to know which TeX Live version you are running and some details to help in that case. Could you add `\listfiles` to the first line of your document and send me a log file at tuda-ci@peitex.de? I'd then send you a more detailed answer. Since it's somehow specific I don't want to paste it here until we are completly switched to the new mechanism.

**Comment by Fred234567890** [comment]
I'll send you the E-Mail in a second. Thank you very much for your help. I just checked an old document which was written with the old template and it didn't have this problem. So maybe they found a solution which still works nowadays.

**Comment by Fred234567890** [comment]
The issue is indeed caused by an interaction of the pdfx package (used in the template) and mathtools/amsmath if a pdfa is created. Marei solved the problem by using the command
`
\makeatletter
\AddToHook{begindocument/end}{\let\mathaccentV\AMS@mathaccentV}
\makeatother
`
before \begin{document}
