### ISSUE TITLE
Option clash for package fontspec

### ISSUE THREAD

**Issue by michaelkennecke** [tudace/tuda_latex_templates#382]
Hello,

unfortunately I have the following error in my Latex project:

![image](https://user-images.githubusercontent.com/48255296/179027814-fe2d4570-406d-4c63-86f0-304f76704ffd.png)

**Comment by TeXhackse** [comment]
I cannot reconstruct this. Option clashes arise if you load a package which has already been loaded. Did you load fontspec yourself after loading the package? What is your current setup? Can you provide more information? I expect this to be cause similar to #383 and #384.

**Comment by TeXhackse** [comment]
probably caused by using an old beta version as described in #384
