### ISSUE TITLE
Unknown option 'paper=section' for package

### ISSUE THREAD

**Issue by michaelkennecke** [tudace/tuda_latex_templates#383]
Hello,

unfortunately I have the following error in my Latex project:

![image](https://user-images.githubusercontent.com/48255296/179028162-55765b82-ccca-4499-8a76-6e530ad6ebf2.png)

**Comment by TeXhackse** [comment]
There was a bug some while ago causing this error. It should be resolved with the current versions of KOMA script. Can you give me more information on the used versions in there or update your TeX distribution?

**Comment by TeXhackse** [comment]
cause by using an old beta version as described in #384
