### ISSUE TITLE
Probleme bei  geforderter Zitation vom Fachgebiet

### ISSUE THREAD

**Issue by Spiekerooger1** [tudace/tuda_latex_templates#385]
Ich würde gerne so Zitieren [Erhard (1993), S20]. 
Gibt es für diesen Stil schon eine Implementation im Template?
Bis jetzt kann ich "Erhard 1993 " durch "authoryear-ibid" implementieren und muss die eckigen Klammern und Seite manuell einfügen. 

Viele Grüße

**Comment by schoeps** [comment]
Sorry, wir können hier keine Speziallösungen für Fachgebiete entwickeln. 

Aber ein ganz naiver Vorschlag: man könnte ein eigenes Kommando, zB `\mycite` mit `\newcommand` bauen, dass die Klammern setzt und die Seiten als Argument nimmt.

**Comment by TeXhackse** [comment]
Ja, es gibt dafür Implementierungen. Grundsätzlich glaube ich aber, dass die Vorgabe mehr umfasst als lediglich die Klammern. Da sind detaillierte Aussagen nicht möglich. 

Nein, diese werden nicht offziell von TUDa-CI unterstützt. TUDa-CI selbst macht absolut gar nichts bezüglich der Literatur, sie ist lediglich in manchen Beispielen als Orientierungshilfe enthalten. 

Grundsätzlich gibt es für solch komische Klammern die Möglichkeit über biblatex `\DeclareCiteCommand` siehe biblatex Dokumentation  (`texdoc biblatex` ausführen oder je nach editor geht das auch über rechtsklick auf den Paketnamen bei `\usepackage`). `\newcommand` ist da doof, weil der anders funktioniert – geht auch, aber nicht sinnvoll. Ggf. ist auch ein Blick in das biblatex-ext bundle hilfreich.
