### ISSUE TITLE
Probleme mit labels bei subtask*

### ISSUE THREAD

**Issue by Rdeisenroth** [tudace/tuda_latex_templates#388]
Wenn man statt dem `subtask` environment das `subtask*` environment benutzt, haben labels den Falschen Text.

Beispiel:
```latex
% Somewhere in preamble
\renewcommand*{\thetask}{%
    H\arabic{task}%
}
\renewcommand*{\thesubtask}{%
    H\arabic{task}.\arabic{subtask}%
}
```
```latex
% after \begin{document}
\begin{task}[points=1]{<Aufgabentitel>}\label{ex:H1}
    <Aufgabentext>
    \begin{subtask*}[points=0]{a}\label{ex:H1.1}
        b
    \end{subtask*}
    \begin{subtask}[points=0]{a}\label{ex:H1.2}
        b
    \end{subtask}
\end{task}
\begin{task}[points=auto]{}
    \ref{ex:H1}  % works as expected, resulting in H1.

    \ref{ex:H1.1} % expected: H1.1, actual: H1

    \ref{ex:H1.2} % expected: H1.2, actual: H1
\end{task}
    ```

**Comment by TeXhackse** [comment]
There was a reason for that grouping. I have to run some more tests on it to ensure it's not breaking anything else..

Anyway what already works with the current version would be adding the label within the title argument of subtask*

**Comment by TeXhackse** [comment]
@Rdeisenroth To explain:

We want to offer the environment as well as the command `\subtask*`

Without the group all local settings made for one subtask would also be applied to the following ones (if not overwritten).

The commit I did is saving the internal `\@CurrentLabel` and allows it to be used outside the group. In case you use the command it will be the active label for `\label` until the next command  is creating one. In case of the environment it's valid until the end of the environment.

**Comment by TeXhackse** [comment]
@Rdeisenroth and since you posted the not directly related part as well:

```
\renewcommand*{\thetask}{%
    H\arabic{task}%
}
\renewcommand*{\thesubtask}{%
    H\arabic{task}.\arabic{subtask}%
}
```
 
should be replaces by:
```
\renewcommand*{\thetask}{%
    H\arabic{task}%
}
\renewcommand*{\thesubtask}{%
    \thetask.\arabic{subtask}%
}
```

You always want to use the macro because one would might have the idea to change the task numbering later. You probably will be aware of but it would be still better to do it correctly.

**Comment by Rdeisenroth** [comment]
> Without the group all local settings made for one subtask would also be applied to the following ones (if not overwritten).

I see. I didn't recognize this reason for the grouping before and thought it might be accidential, since it's not present in the definition of the subtask environment.

> The commit I did is saving the internal `\@CurrentLabel` and allows it to be used outside the group. In case you use the command it will be the active label for `\label` until the next command is creating one. In case of the environment it's valid until the end of the environment.

What i still don't understand is why the grouping is not necessary in the definition of the subtask environment... Does latex3 handle the grouping different when evaluating a boolean argument?

**Comment by TeXhackse** [comment]
`subtask`  should only be used as environment. `\subtask*`  has special requirements because it should allow the smilar syntax as task, therefore this requirement included to it being able to be used as a macro. 

In case one would use `\subtask` directly the group would be necessary here as well. Maybe I should just add it though I'd not recommand that use anyway.
