### ISSUE TITLE
Documents not compiling when used together with siunitx

### ISSUE THREAD

**Issue by Jackd4w** [tudace/tuda_latex_templates#394]
#### Issue description

When using the qty function from the siunitx package the document does not compile anymore with the following error message in the output log:

        Package xcolor Error: Undefined color `8c'.
        
        See the xcolor package documentation for explanation.
        Type  H <return>  for immediate help.
        
        
        l.17 \qty{100}{\litre}

#### MRE

        \documentclass[
		        english,
		        class=report,			% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
		        fontsize=11pt,
        %		landscape,				% Querformat
		        marginpar=false,		% deaktiviert Randnotizspalte
        %		logofile=example-image, % falls die Logo Dateie nicht vorliegen
		        color=8c,				
            ]{tudapub}
        
        %\documentclass{scrreprt}
        
        \usepackage{siunitx}
        
        \begin{document} 		% hier beginnt der Text
        Test
        \qty{100}{\litre}
        
        \end{document}

#### Versions used
        tudapub 2022/08/03 v3.27
        xcolor 2022/06/12 v2.14
        siunitx 2022-08-08 v3.1.6

**Comment by TeXhackse** [comment]
It's not a TUDa-CI problem. siunitx added a color option and is now also using the TUDa-CIs color value. To disable this you have to add the option `color=` with an empty value to your siunitx options.

I will add this to the documentation.

**Comment by TeXhackse** [comment]
To be clear the full example would be

```
 \documentclass[
	        color=8c,				
   ]{tudapub}

 \usepackage[color=]{siunitx}
    
 \begin{document} 
Test
 \qty{100}{\litre}
    
 \end{document}
```

**Comment by Jackd4w** [comment]
That fixed it, thank you very much :)

**Comment by TeXhackse** [comment]
I reopen it as a reminder for me to add this to known conflicts in the docs.

**Comment by schoeps** [comment]
@TeXhackse Can you give me a hint how to fix this for the beamer class?
```
\documentclass[color={accentcolor=3d}]{tudabeamer} 
\usepackage[color=]{siunitx}
\begin{document}
\begin{frame}
x
\end{frame}	
\end{document}
```
gives
`Latex Error: siunitx.sty:8172 Use of \??? doesn't match its definition.`

**Comment by TeXhackse** [comment]
Um the nested definition won't work. You can directly use `accentcolor=3d` . This should have the same effect. If it does not, we have another issue.

```
\documentclass[accentcolor=3d}{tudabeamer} 
\usepackage[color=]{siunitx}
\begin{document}
\begin{frame}
x
\end{frame}	
\end{document}
```

**Comment by schoeps** [comment]
> ```
> \documentclass[accentcolor=3d]{tudabeamer} 
> ```

This works, thanks. Not sure why I used the more complex construct `color={accentcolor=3d}` . This helps!

**Comment by TeXhackse** [comment]
I added a passing option to avoid this … no idea why I didnt think of that before now
