### ISSUE TITLE
Table in scientific poster

### ISSUE THREAD

**Issue by long21wt** [tudace/tuda_latex_templates#395]
Hi

Is there any way to integrate a table into a scientific poster?
Using the table environment always leads to an error

Thanks

**Comment by TeXhackse** [comment]
The table environment is a floating environment. You don't want a float within a boxed at fixed position. You can simply leave it out. 

To get a caption use `\captionof{table}` as shown for a figure in the demo poster.

**Comment by long21wt** [comment]
Thanks for the tips!
