### ISSUE TITLE
Literaturverzeichnis im Inhaltsverzeichnis anzeigen lassen

### ISSUE THREAD

**Issue by FlixXIV** [tudace/tuda_latex_templates#398]
Hallo,

der Titel ist Programm. Ich verwende die Dokumentenklasse tudapub und Biber für die Literatur. Der Befehl bibtotoc funktioniert jedoch nicht bei den Klassenoptionen.

**Comment by TeXhackse** [comment]
`bibtotoc` ist schon lange veraltet. `bibliography=toc` oder `bibliography=totoc` vgl.  http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide-de.pdf#page=157
