### ISSUE TITLE
Adding chapter

### ISSUE THREAD

**Issue by e1339g** [tudace/tuda_latex_templates#399]
Hello, I am using the old version of template 0.96 in Overleaf. Everything works except I can not add chapter. So instead of the chapter, I am using section. How can I add the \chapter? I have tried to just add chapter, but it does not work. I have also tried to add class=report and it does not work.

> `\documentclass[article,type=msc,colorback,accentcolor=tud9c,12pt, paper=a4report, class=report ]{tudthesis}`

Here is my tudthesis.cls.

```
% tudreport is the report-class as described in the TUD-Design-Manual
% It is based on (makes heavy use of) the KOMA-Class scrreprt
% This class is provided "as is", the authors take no responsibility
% for any effects the style file has on the user, the user's life, family,
% pets, scientific or other career etc.
% 
% When making changes to this style file or the accompanying package files
% please notify the authors:
% tud-design@pro-kevin.de
% Good luck!

\def\fileversion{0.96}
\def\filedate{2009/05/15}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tudthesis}
 [\filedate\space\fileversion\space 
   Joe Werner's TUD-Design-Manual package]

\newif\ifTUD@thesis@type \TUD@thesis@typefalse

\RequirePackage{xkeyval}
% Verarbeitung der Optionen

 \DeclareOptionX<\@currname>{type}{%
   \TUD@thesis@typetrue
   \PassOptionsToPackage{type=#1}{tudthess_title}}

 \DeclareOptionX<\@currname>{dr}{%
   \PassOptionsToPackage{dr=#1}{tudthess_title}}

 \DeclareOptionX*{%
   \ClassInfo{\@currname}{Unknown option '\CurrentOption`. Pass to tudreport class.}
   \PassOptionsToClass{\CurrentOption}{tudreport}}

\ProcessOptionsX<\@currname>
%\let\@classoptionslist\relax

\ifTUD@thesis@type\else
  \ClassError{\@currname}{Missing option 'type=<thesis type>` !}
\fi

% Load the KOMA-Class
\LoadClass{tudreport}
\RequirePackage{tudthess_title}

\date{%
  \ifcase\month%
    \or January%
    \or February%
    \or March%
    \or April%
    \or May%
    \or June%
    \or July%
    \or August%
    \or September%
    \or October%
    \or November%
    \or December%
  \fi\ \number\year%
}

\endinput
```

Also, I have tried the new version in Overleaf, but declaration is written in German and I can not find the list of figures and list of tables. Please help to solve the problem

**Comment by TeXhackse** [comment]
I have no idea which old version you are using, but tudthesis never was part of tuda-ci. This was created before we started developing these. 

You should be able to use the new version in Overleaf and also simply use the generic `\listoffigures` and `\listoftable` commands.

The instructions are German only, that's sadly true. But I can try to help out if needed. 
In case you need further assistance we also offer an office hour every wednesday from 14:00–15:30 you find the information at https://www.ce.tu-darmstadt.de/celatex_ce/index.en.jsp

**Comment by e1339g** [comment]
@TeXhackse Thank you very much.
