### ISSUE TITLE
Add mechanism for non free fonts --  (Bitstream) Charter?

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#4]
According to the "Corporate Design Handbuch" the font `Charter` should be used, together with `Frontpage` and `Stafford`. Looks like tudafonts.sty loads roboto, and <https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.de.jsp> states

> Die benötigten Fonts sind in den genannten Distributionen direkt verfügbar und können mit den distributionseigenen Tools nachinstalliert werden, so dass hier keine separaten Installationen mehr notwendig sind

Is roboto an officially accepted replacement for Charter (and the others)?

**Comment by TeXhackse** [comment]
Yes. The replacement was an official decision. To get details @marklaz probably can tell you more about that. Maybe it would be usefull to spread that Information.

**Comment by azrdev** [comment]
@marklaz can you elaborate? Does this apply to all TU members?

If not, would it be much effort to add an option for using the [original fonts](http://exp1.fkp.physik.tu-darmstadt.de/tuddesign/latex/tudfonts-tex/) if available?

**Comment by TeXhackse** [comment]
this would not be much effort for lualatex & xelatex. 
Though I'd prefer to add an option for enforce the choice.
@marklaz is to decide/discuss that.

I'd appreciate, if the document uses the same mode for all installations as a default.

**Comment by schoeps** [comment]
I guess I can close this issue?

**Comment by TeXhackse** [comment]
I labeled it, will rename the title and leave the discussion open

**Comment by schoeps** [comment]
I don’t think we should do it. TU Darmstadt’s department that takes care of CI agreed to our font choices, they actually want to do the same for the word templates. Adding more font support for our templates is probably increasing complexity which is bad for users and maintenance.

**Comment by TeXhackse** [comment]
alright then

**Comment by TeXhackse** [comment]
@azrdev  if you would like that for personal use you could simply change the font configuration in your own documents.

**Comment by azrdev** [comment]
> @azrdev if you would like that for personal use you could simply change the font configuration in your own documents.

thx, I was more worried that this allowance to replace the fonts might only cover CE and not everybody (e.g. me at FB Informatik). Since 

> TU Darmstadt’s department that takes care of CI agreed to our font choices, they actually want to do the same for the word templates

I'm happy to not care at all. Just curious how long it takes them to update e.g. https://www.intern.tu-darmstadt.de/arbeitsmittel/corporate_design_vorlagen/faq_cd.de.jsp

**Comment by schoeps** [comment]
> I'm happy to not care at all. Just curious how long it takes them to update e.g. https://www.intern.tu-darmstadt.de/arbeitsmittel/corporate_design_vorlagen/

The current (MS) templates do not comply with our CI rules for many years, so I don’t expect anything soon.

**Comment by flokli** [comment]
> To be more clear: according to my information TU in general will switch to Roboto soon.

Hell yeah. This will enable having `tuda-ci` properly packaged in distros, without having to download from IP-whitelisted locations or manually after jumping through login wall hoops.

Thanks for your breath in fighting this out.
