### ISSUE TITLE
PHD and Bachelor's Thesis Links swapped

### ISSUE THREAD

**Issue by TCMBoby** [tudace/tuda_latex_templates#40]
The `Example PhD thesis` and `Example bachelor's thesis` links on the CTAN page are swapped and link to the wrong documents.

[https://www.ctan.org/pkg/tuda-ci](https://www.ctan.org/pkg/tuda-ci)

**Comment by TeXhackse** [comment]
Thank you for reporting. I will talk to the CTAN team about that.

**Comment by TeXhackse** [comment]
Since we cannot change that and the request has been sent, I close this one.
