### ISSUE TITLE
Fonts are still non-compliant with the TUDa CD specification

### ISSUE THREAD

**Issue by daveekr** [tudace/tuda_latex_templates#404]
Hello,

I know, that this issue was already discussed in #4 back in 2019, where it was announced that the CD of the TUDa will adapt to Roboto soon. About 3 years have passed since then and the CD specification is still the same and specifying FrontPage/Stafford fonts are part of the CD and have to be used (https://www.intern.tu-darmstadt.de/arbeitsmittel/corporate_design_vorlagen/faq_cd.de.jsp). Unfortunately we are having some people at our department who are able distinguish the FrontPage from the Roboto font and have never heard of the "new" LaTeX template or anything mentioned in #4. Even though the LaTeX template has been accepted by the CI department, it is exhausting to argue why Roboto has been used. I am totally aware, that this is actually no technical issue, however the CD specification should either _finally_ be adapted or there should be a documented work-around how to use the FrontPage and Stafford fonts in order to make picky supervisors happy.

I still have the font files from the old template of the physics department, however I was not able to properly embed them in my report or the template. Any guidance on that would be greatly appreciated.

**Comment by TeXhackse** [comment]
We have the official permission to use Toboto as a replacement. I don't think they will do a change in the guideline. @schoeps @marklaz Is there any different way to handle that? 

Concerning your request.
I don't have the old font files. so I can not explain how to use them. 

Anyway in case you have TTF/OTF files for those you can simply use fontspecs features to load those. Please take care of having a License which allows embedding of glymphs  in that case.

**Comment by daveekr** [comment]
I absolutely understand your point and its also logical that an official template fulfills the CD specification of the TUDa.

However I was requested to use the FrontPage font in the captions and headings of my report as explicitly defined by the CD specification of the TUDa. And this even though my supervisor had access to the LaTeX files of my report. So nobody who is not aware of #4 knows that it is ok to use the Roboto font instead. They do not even have that exception in their FAQ. So if I cannot change the font, I will have to argument that it is the official design and there is a 3 year old issue on the GitHub page stating, its ok to use Roboto. In the end I will be blamed for not using the approved font type, no matter how reasonable and permitted the switch to Roboto is.

**Comment by schoeps** [comment]
@daveekr What about this: you write to cd@pvw.tu-darmstadt.de (put me and @TeXhackse in cc) and kindly ask if they can add a remark in their FAQ? If necessary, we can support your request.

**Comment by TeXhackse** [comment]
I just received a confirmation that they will add a hint to their FAQ. I will link it here as well as in the other issue as soon as it's online.

**Comment by schoeps** [comment]
The FAQ is still not updated or did I miss something? @TeXhackse: can you send a reminder, please?

**Comment by TeXhackse** [comment]
Did - right before christmas, got no answer.  Next one is scheduled for next week.

**Comment by TeXhackse** [comment]
Just that noone is confused about this one still being open… I was asked to suggest some text to be placed there, but as far as I can see it still was not added. Sent the regular reminder once again.

**Comment by TeXhackse** [comment]
It only took … a few years … but we finally have something https://www.intern.tu-darmstadt.de/arbeitsmittel/corporate_design_vorlagen/index.de.jsp

I told them the wording is a bit weird. But actually it's much better than everything we had before… So I will stop annoying them regularly and close this issue.
