### ISSUE TITLE
Avoid ruledheaders for \subsubsection

### ISSUE THREAD

**Issue by schokakola** [tudace/tuda_latex_templates#405]
Hello. 
Is it possible to obtain with the ruledheaders options the lines only for \chapters, \section and \subsection (and not \subsubsections)?

thanks!

**Comment by TeXhackse** [comment]
Hi, yes it is possible but not officially supported. 

The main reason for not allowing all levels to be disabled individually is that this would increase the maintanance effort. 

The ruledheaders option only supports the values described in the documentation. 

You could copy the definition of `\sectionlinesformat` corresponding to the `ruledheaders=section` value and replace that by subsection. If that's not clear enough please use the TeXnical office hour tomorrow. https://www.ce.tu-darmstadt.de/celatex_ce/index.en.jsp

**Comment by TeXhackse** [comment]
Will close this as it seems to be resolved.
