### ISSUE TITLE
Add Department Logo to TUDaReport

### ISSUE THREAD

**Issue by timbmg** [tudace/tuda_latex_templates#406]
Hi, is it possible to add a department logo in the TUDaReport? I would ideally like to have both the TU logo and the logo of the department (e.g. below the TU logo). I saw an option in [tudapub.cls#L153](https://github.com/tudace/tuda_latex_templates/blob/f18c3b48544f8d6ab95c55698ae924b4a2a58c35/tex/tudapub.cls#L153) and tried adding it like this, but it does not seem to work.
```latex
\documentclass[
        english,
	accentcolor=9c,
	type=intern,
	marginpar=false,
	departmentlogofile=ukp_logo.pdf
]{tudapub}
```

**Comment by TeXhackse** [comment]
The option `departmentlogofile` only existis within department specific adjustments. Otherwise it's not used. The only variant shipped with TUDa-CI currently is `department=mecheng`.

But you can – of course – add a departmentlogo in the same way as with tudapub itself:

```
\addTitleBoxLogo{example-image}
\addTitleBoxLogo*{\includegraphics[width=.3\linewidth]{example-image}}
```

**Comment by timbmg** [comment]
Thanks! Adding a title box does exactly what I needed:)
