### ISSUE TITLE
remove \reviewer from title page

### ISSUE THREAD

**Issue by Spiekerooger1** [tudace/tuda_latex_templates#407]
Kann man bei type=bachelor das Feld \reviewer irgendwie als nicht notwendig kennzeichnen, da es nicht auf meiner Titelseite erscheinen soll. 
Vielen Dank für die Hilfe
VG

**Comment by Spiekerooger1** [comment]
okay schade, trotzdem vielen Dank.

**Comment by TeXhackse** [comment]
Ähm das „schade“ stört mich gerade etwas. Einfach mal `type=Bachelorarbeit` eingeben. Ich gehe davon aus, dass das dem entspricht. Alternativ kann man auch das `\subject` Feld komplett überschreiben.

**Comment by Spiekerooger1** [comment]
LaTeX3 Error: Key 'ptxcd/pub/type' accepts only a fixed set of choices. \ProcessKeysOptions{ptxcd/pub}
das bekomme ich als Fehlermeldung.

**Comment by TeXhackse** [comment]
Als thesis-type. Also bei der Dokumentenklasse dann z.B. so:

```
\documentclass[
	ngerman,
	ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={type=Bachelorarbeit},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
]{tudapub}
```

**Comment by Spiekerooger1** [comment]
ja vielen Dank!, das hat geklappt.
