### ISSUE TITLE
! Undefined control sequence. \hook_new:n in tudacolors.sty

### ISSUE THREAD

**Issue by grunu** [tudace/tuda_latex_templates#408]
Hello everyone,

I am working with Texmaker on my DEMO-TUDaPhD.tex, where I am getting the error:

`...\MiKTeX\2.9\tex\latex\tuda-ci\tudacolors.sty | line 104 | ! Undefined control sequence. \hook_new:n`

I compiled my project over a year ago successfully on my old laptop, but with my new laptop it does not work anymore. The tuda-ci package is apparently installed (since the path exists).

Do you have any advice or need further information? Thanks in advance!

PS: The code snippet from tudacolors.sty looks like this:

```
\hook_new:n {ptxcd/init-colors}
\hook_gput_code:nnn {ptxcd/init-colors} {tudacolors} {
```

**Comment by TeXhackse** [comment]
You TeX distribution is outdated. So you probably use the new tuda-ci but with an much older LaTeX kernel. 

Please install tuda-ci matching your LaTeX version or update the kernel.

**Comment by grunu** [comment]
Wow, thanks for the quick response!

Is it possible to install older versions of tuda-ci through MikTex? And is there a List which version matches with which latex version?

And this is probably a beginner question, but: How do I update my latex kernel? I just today installed MikTex and Texmaker, should it enough to check for updates in MikTex and install them?

**Comment by TeXhackse** [comment]
> Is it possible to install older versions of tuda-ci through MikTex? 

No. usually the matching version is linked by the repository. MikTeX does not have the same mechanism as TeX Live does. (I'd install that one instead anyway) But you have a date on your LaTeX kernel and can check the changelog which release would match that. 

To update miktex simply update all the packages. There's a package called latex which included the kernel.

**Comment by TeXhackse** [comment]
@grunu it would be great if you could either close this, when resolved or add more information if it's not.
