### ISSUE TITLE
Missing \item when using solution

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#410]
Hey,
I have a weird error that I don't really understand.
I have the following subtask
```
\begin{subtask}
	Task description blabla.

	\begin{solution}
		Some Text
	\end{solution}
\end{subtask}
```

I'm getting the error `Something's wrong--perhaps a missing \item.`
If I change `solution` to `solution*`, the code compiles without error.
Any idea what may be causing this?
The previous and the following subtask uses an enumerate for sub subtask with solution environment for each item.
That compiles without issue but might be relevant :shrug:

**Comment by TeXhackse** [comment]
Hi, did you do any custom setup things in there? using it standalone with tudaexercise.cls doesn't throw any error message.

**Comment by StefanFabian** [comment]
Ah, good point, yes, we have added a left margin to the solution environment, seems like some change broke that.
```
\AddToHook{env/solution/before}[solutionindent]{\begin{addmargin}[2em]{0pt}}
\AddToHook{env/solution/after} [solutionindent]{\end{addmargin}}
```
If I remove that, it compiles again.
Do you happen to know why this isn't working anymore and have a quick fix?

**Comment by TeXhackse** [comment]
Still cannot reconstruct the error. The addmargin internally is a list, so that explaints parts of it. 

The TeXnical office hour is running right now, and we already resolved all open questions for today, so we could also have a look at it together: Access link and info is here: https://www.ce.tu-darmstadt.de/celatex_ce/index.en.jsp

**Comment by TeXhackse** [comment]
I have to dig a bit deeper into this. Actually it seems like some boolean is not reset correctly within the structure depending on some weird combination of actions. What currently works would be 

```
