### ISSUE TITLE
subtask=runin not showing up heading

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#411]
@StefanFabian reported the subtask numbers didn't show up anymore when one is using subtask=runin. This is due to a change within KOMA-Script. This is fixed within the repo already. 

I am awaiting some tests to resolve #410 and aftewards release those two fixes together.

**Comment by StefanFabian** [comment]
Any chance of having a new release on Monday?
Or is there a workaround for this issue as well that I can use until the next release?

**Comment by TeXhackse** [comment]
it's fixed within the repo already - i edited the commit to mention. 

You could use the version from here. I think I can manage to do the upload tomorrow, but has been an extremly busy week.  And then we still rely on the CTAN maintainers who usually are really quick but one cannot promise.

Do you know how you could locally replace the file with the one from the repo? Otherwise I could add a short l3build instruction which was planned anyway.

**Comment by TeXhackse** [comment]
@StefanFabian upload is done. in case you need help with it because CTAN is slower, just let me know. We should be able to solve that quickly. There is a workaround, but i'd prefer the update.

**Comment by StefanFabian** [comment]
> Do you know how you could locally replace the file with the one from the repo? Otherwise I could add a short l3build instruction which was planned to be added some time anyway.

Unfortunately not. Any help here would be much appreciated since the CTAN update didn't propagate to my mirror yet.

**Comment by TeXhackse** [comment]
Since the release is already done you can either download the release.zip and take tudaexercise.cls from there to place it in your working directory until you received the update. Or you take the file directly from a mirror, which is already synct. e.g. https://packages.hs-regensburg.de/ctan/macros/latex/contrib/tuda-ci/tex/tudaexercise.cls
