### ISSUE TITLE
syllabifiction

### ISSUE THREAD

**Issue by lueck1803** [tudace/tuda_latex_templates#414]
Hi,
since the last update syllabification at tuda documents does not work anymore.
But only on linux or macos, on windows it works.

This is no special case for my operating systems i use.

Kind regards
Lukas Walter

**Comment by TeXhackse** [comment]
Hi, actually TUDa-CI is not doing any setup there. Did you get a warning, that there are language files missing? How did you install it? Which TeX Distribution are you using?

**Comment by lueck1803** [comment]
Yes there is a warning:

> No hyphenation patterns were preloaded for(babel) the language 'German (new orthography)' into the format.

I experienced it with the example files, delivered with the documentation.

A friend of mine contacted me who is writing a seminar handout. I reduced it to a minimal example, cause i thought it could be some messed up package use.
Since I couldn't figured out the problem I tested the examples. 
At my windows system this did not happened but on linux subsystem it happened again.

Today I talked to my girlfriend who submitted her proposal for her master thesis this week and asked if she recognised the problem too. That when she compiled at university on Ubuntu this problem occurred too, but she forgot about it because at home she uses windows and there she made her last compilations.

The TeX Distribution we use is Miktex.

Now i guess its a distribution problem. I did not experienced it before at another latex document where I dont use tuda design templates, but now it happens there also.

**Comment by TeXhackse** [comment]
Alright yes, that's the reason. 

In case you use MikTeX and enable the „by need“ package installation mode it is only installing packages when they are preloaded. Since those files are not loaded by `\usepackage` you have to install them. Search in the MikTeX console for babel-german. If I remember correctly that should solve this.

With a MikTeX full installation or a correctly installed TeX Live this would not happen. But it's of course up to your which one you prefer to use.

**Comment by lueck1803** [comment]
Thanks,

babel-german was not the problem. This package I already installed and reinstalled before.

The packages:
hyph-utf8
dehyph-exptl

I had to install.

I saw that the problem also happend with english text, but it does not attract attention that much because of the in the middle much shorter words.

**Comment by TeXhackse** [comment]
thanks. I would have had to check the package naming scheme in MikTeX for that. Anyway closing this as unrelated and I can do nothing about it.
