### ISSUE TITLE
error with TUDaThesis type=pp

### ISSUE THREAD

**Issue by laalica** [tudace/tuda_latex_templates#418]
Hey, 
I opened the template for the TUDaThesis on sharelatex for TU Darmstadt. For the type=pp (proposal) I recieved an error while compiling. At first no pfd file could be generated. And the second error appears in line 137 between \maketitle and \affidavit. It says "Package tudapub/thesis Error: You did not provide date data for the title." I had this error also when I tried to compile my project and wanted to check if it happens also with the template (I just changed the type). I think there is a problem with the thesis type.

I'm not really a pro in latex (more a noob), so I would be happy if someone can help me.

**Comment by TeXhackse** [comment]
You need to add `\title{title}` and `\date{date}` before invoking `\maketitle`. This is required for `type=pp`. In case you don't want to stick to that you can use a custom text instead of a predefined type.

**Comment by laalica** [comment]
This helps a bit. But now I have two dates on the title page because I also use `\submissiondate`. Is there a way that I can use `\date` but it is not showing? When I do `\date{}` then just the submission date is showing and it compiles but the error from before is here again.

**Comment by TeXhackse** [comment]
The setup of pp does not allow this. It was a requirement. 

You can use a custom String instead of the pp key. That's allowing you do not rely to the restrictions.

**Comment by laalica** [comment]
Yeah this helped, thank you a lot!
