### ISSUE TITLE
Suppress page numbers before TOC

### ISSUE THREAD

**Issue by plsbstn** [tudace/tuda_latex_templates#419]
Hi,
I'm wondering how to suppress page numbers before the table of content appears.
I'm using the Overleaf template version 3.23 (2022/03/21) and also tried with the latest 3.29 (2022/12/11).
Unfortunately, just the pre-sections 'Vorwort' and abstract in German are allowed to suppress the page number.
The abstract in english remains with a page number, resulting in Roman numbering III for table of content.

I tried several ways using `\pagenumbering{gobble}` or `\pagestyle{empty}` - nothing worked yet.
Here's the corresponding section of the code:

```
\maketitle
\pagenumbering{gobble}
\addchap*{Vorwort}

\begin{abstract}
    Deutsche Zusammenfassung
\end{abstract}

\begin{abstract}[english]
    English Summary
\end{abstract}

\pagenumbering{Roman}
\tableofcontents
```

Any suggestions or similar issues solved?
Thanks folks! :)

**Comment by TeXhackse** [comment]
This is not directly related to TUDa-CI but a general question. 

You are activating `\pagenumbering{Roman}` on the page of the abstract… So of course this is not starting with the \tableofcontents. 
`\clearpage`/`\cleardoublepage` before changing the `\pagenumbering` should help with that. 
Take care of the pagebreaks when changing the numbering.

Anyway. `\pagenumbering{gobble}` is also removing the internal number counter which can lead to the fact that multiple pdf pages have the same identifier which is never a good idea. Please take a different number scheme.

**Comment by plsbstn** [comment]
Thanks @TeXhackse! Works fine in that order

```
\begin{abstract}
    Deutsche Zusammenfassung
\end{abstract}

\begin{abstract}[english]
    English Summary
\end{abstract}

\clearpage
\cleardoublepage
\pagenumbering{Roman}
\tableofcontents
```
