### ISSUE TITLE
Adjust color box's height of frame title

### ISSUE THREAD

**Issue by im-Kitsch** [tudace/tuda_latex_templates#420]
Hi, 

thanks for the contribution, I just found that if I never enable to show TUDa's logo in slide page. The frametitle's colorbox will be too big for frame title. As shown in attached figures, in first figure the TUDa's logo is shown, there is no problem. But in the second figure if I disable to show logo, its height becomes too big for frame-title text.  It would somehow occupy too much space and it's too big, if I never enable it.  The frame title occupies obviously too much space especially if I set `colorframetitle` as false. 

So I wanna to ask if I can manually set the height of colorbox? Or can I center the frame title vertically?

Thanks a lot in advance.

<img width="400" alt="t2" src="https://user-images.githubusercontent.com/33943000/213942008-6038bbd3-b431-41a5-8b9c-931b4fd7ecf5.png">
<img width="400" alt="t1" src="https://user-images.githubusercontent.com/33943000/213942010-d1e12a29-f28b-4cce-a044-d139e103d6c8.png">

**Comment by TeXhackse** [comment]
the design requires that height. It's not our choice. So no, it's not really adjustable as it's a corporate design requirement. It's one of the things discussed with the current redesign at the moment as far as I know.

Anyway, there is an option to center it (though this is not matching the official guidelines) you can set `centerframetitle=true` as a class option or pass it directly to the outer theme.

**Comment by TeXhackse** [comment]
Since it would be breaking the corporate design guidelines, centering is possible and I received no further reply I will close this.

**Comment by im-Kitsch** [comment]
Hi, thanks a lot for the reply, 

but to be honest, I really highly recommend that we can customize the setting of frametitle. Even if we centered the frametitle, it still looks too empty in the following visualization.  We can say that how to such thing is a aesthetic and subjective problem, but I am quite sure some times this setting cooprates not well with beamer content. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/33943000/227058927-0570e361-8b0e-4624-a2f1-b1e047a82942.png">
