### ISSUE TITLE
TUDa PhD document does not span over the Complete A4 page

### ISSUE THREAD

**Issue by m0m0khan** [tudace/tuda_latex_templates#423]
Hello, I am using the latest release of latex template. The installation and compilation of the document work successfully for me, but the content does not span completely over the page rather it is confined to a small area on the page.
Could you please let me know how to print the content on the complete page of the document?

**Comment by TeXhackse** [comment]
remove the `custommargins=true`.  This is described in the docs  but since those sadly only are available in German I repeat it here.

**Comment by m0m0khan** [comment]
Oh, I tried to read it but maybe didn't understand that. Thanks for your help, that worked for me!
I have another question in this regard: Now the document spans over the complete page but the chapter headings start with a lot of vertical space from the top of the paper. Is this intended or could this be fixed as well somehow? I have attached a pic for better understanding.

![image](https://user-images.githubusercontent.com/57805502/217474863-832bf635-5d26-4c89-9860-897f29a0d203.png)

**Comment by TeXhackse** [comment]
The more detailed description is in the TUDaPub docs. you can set `custommargins=geomtry` and manual set the margins or return to `custommargins=true` and increase the DIV value using e.g. `DIV=12` for a detailed description on that mechanism have a look at the KOMA-Script docs.

**Comment by m0m0khan** [comment]
Perfect. Thanks, I'll look into that.
