### ISSUE TITLE
Affidavit: Architektur-Zusatz

### ISSUE THREAD

**Issue by fdamken** [tudace/tuda_latex_templates#426]
In Absprache mit der Prüfungskommission am Fachbereich Informatik hat sich ergeben, dass der Zusatz

> Bei einer Thesis des Fachbereichs Architektur entspricht die eingereichte elektronische Fassung dem vorgestellten Modell und den vorgelegten Plänen.

wirklich nur bei Arbeiten am Fachbereich Architektur notwendig ist. Wäre es möglich, dem `\affidavit`-Makro eine Option hinzuzufügen, die den Zusatz ausblendet?

**Comment by TeXhackse** [comment]
Ja, allerdings würde der default beim allgemeinen Text bleiben, um eine Veränderung bei Arbeiten, die das schon benutzen zu vermeiden.

**Comment by D4nieBo** [comment]
Hallo, 
leider habe ich es nicht geschafft den achitecture Teil zu entfernen. 
Wo muss ich den Befehl einfügen?

**Comment by TeXhackse** [comment]
die neue version ist noch nicht voll released. Ich wollte mit de release ein paar Dinge zusammen einbauen. Was geht ist die Version aus dem Repo ins aktuelle Verzeichnis kopieren und dann eben die Option benutzen. Mit bei den Dokumentenklassenoptionen. ODer eben den Text ganz überschreiben.
