### ISSUE TITLE
Chapter and section name not showing under footer in TUDaPhD

### ISSUE THREAD

**Issue by m0m0khan** [tudace/tuda_latex_templates#427]
Hello, I am using the latex version of TUDa-CI (v3.29) and would like to have the chapter and section names shown just below the footer. This my preamble:

``` latex
\documentclass[
	english,
	ruledheaders=section,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=scrreprt,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=ing
	},
	accentcolor=2b,% Auswahl der Akzentfarbe
	custommargins=geometry,% Ränder werden mithilfe von typearea automatisch berechnet
	%DIV=12,
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	BCOR=12mm,%Bindekorrektur, falls notwendig
	BCORtitlepage=true,
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
	twoside,
	open=right,
        headline=automark,
	IMRAD=false
]{tudapub}

\geometry{ reset, top=28mm, left=27mm, right=15mm, bottom=37mm, }
```

The problem is that I am not seeing any chapter or section name printed below the footer. Rather, it is printed below the next page's header, which you can see below:

![image](https://user-images.githubusercontent.com/57805502/229093500-77547830-8072-4238-a365-af4ff8573b44.png)

How can I solve this issue?

**Comment by TeXhackse** [comment]
Headline=automark is adding it to the headline, thats true. For every other use please have a look at the scrlayer-scrpage documentation.

**Comment by TeXhackse** [comment]
Ah then you switch those around -> but still this is ot a ressource but the documentatio is 

```
\automark*[chapter]{section}
\ifoot{headmark}
```

**Comment by m0m0khan** [comment]
Thanks a lot!
