### ISSUE TITLE
Change margins

### ISSUE THREAD

**Issue by CobeA527** [tudace/tuda_latex_templates#43]
Hi everyone,

I am using the tudapub class and I want to change the size of the margin (black box in picture) because I don't need marginnotes and i want to use the full page to write. Also i am using the twocolumn.  I tried to use the geometry package it doesn't work.  Any advice how to change the margin ?
![Bildschirmfoto 2019-10-02 um 15 50 37](https://user-images.githubusercontent.com/40291778/66050008-b2a52580-e52c-11e9-90e0-57530dbf14d5.png)

Thanks,

Cobe

**Comment by TeXhackse** [comment]
Did you try to add the class option `marginpar=false`?

**Comment by CobeA527** [comment]
Nice it works ! that was simple... I didn't find this option in the documentation... might have overlooked it
