### ISSUE TITLE
\titlegraphics not working

### ISSUE THREAD

**Issue by entropybit** [tudace/tuda_latex_templates#430]
Hi depending on where I put \titlegraphics this either gives me the image on an additional page that appears before the title or I get an error:

```
Undefined control sequence. \titlegraphic
```

has anyone seen something like this before ?
To test that this has nothing to do with my tex file I downloaded the PhD demo and tried it out in there with the same result ...

**Comment by TeXhackse** [comment]
Nope. Cannot reconstruct with the current release of TUDa-CI. Maybe you have some extremly old copy of TUDa-CI installed which didn't know that feature.

**Comment by entropybit** [comment]
Sorry for not replying to this earlier, yeah it weirdly enough works for me now. I am assuming that this is some weird effect of packages not having been up to date before. 
What is even more funny is that in the sharelatex of TU it still produces the same broken behaviour but for now I don't really care about that (sorry thesis writing ...). I can try to provide you a minimal working example from the document that I have in overleave and post you a code for sharing here.
