### ISSUE TITLE
TOC entries with a page number of over 99 cause an overfull hbox when using the tudapub class

### ISSUE THREAD

**Issue by snsmac** [tudace/tuda_latex_templates#431]
When having entries with a page number with more than two digits in the TOC, the page number slightly overflows.
For example, I get following warning `"Overfull \hbox (1.29207pt too wide) detected at line 53"` for all TOC entries with more than three digitis. 

I fixed this with the command `\DeclareTOCStyleEntries[pagenumberbox=\mbox]{tocline}{part,chapter,section,subsection}` for my document, but I'm not sure if this has any unintended side effects

**Comment by snsmac** [comment]
Thank you for your helpful answer

**Comment by TeXhackse** [comment]
https://github.com/tudace/tuda_latex_templates/wiki/Table-of-Contents#page-numbers-lap-into-the-margin
