### ISSUE TITLE
Affidavit text differs from TU Template

### ISSUE THREAD

**Issue by snsmac** [tudace/tuda_latex_templates#432]
The text in the latex template is shorter than the one found at https://www.tu-darmstadt.de/studieren/studierende_tu/studienorganisation_und_tucan/hilfe_und_faq/artikel_details_de_en_37824.de.jsp  

It is especially missing the sentence:
> "Die von mir bei der Anfertigung dieser wissenschaftlichen Arbeit wörtlich oder inhaltlich benutzte Literatur und alle anderen Quellen habe ich im Text deutlich gekennzeichnet und gesondert aufgeführt. Dies gilt auch für Quellen oder Hilfsmittel aus dem Internet."

**Comment by TeXhackse** [comment]
Thanks for the report. 

This seems to be a new version. Dated april this year. I will update the text and release a new version asap.

**Comment by TeXhackse** [comment]
@snsmac Do you know where to find the text for the not-online-only submission? I want to check that one as well.

**Comment by snsmac** [comment]
@TeXhackse Sadly not

Another thing I noticed is that the "g__ptxcd_architecture_note_bool" flag does not work for the digital affidavit, it only changes the behaviour for the print one

**Comment by TeXhackse** [comment]
Ah thanks, that's a bug. Will be included in the change. I try to find out where to find the standard text, and maybe there is a way to get notified when they change that again.

**Comment by TeXhackse** [comment]
Hm it's a bit weird… I found an old version as docx at https://www.tu-darmstadt.de/media/dezernat_ii/referat_iig/formulare_vorlagen/pm_1/erklaerungen/Erklaerung_zur_Abschlussarbeit_Vorlage.docx But ever web link is now only linking to the digital copy. So maybe they removed that difference … But I will wait with the release until I got an answer.

**Comment by TeXhackse** [comment]
Hm I did not yet receive any answer. Due to #433  I will do a release today. Since I realized the texts only differed by the heading it seems like they removed that difference. Anyway I will only change the digital variant's text until I can ensure that's the intention.

**Comment by TeXhackse** [comment]
Finally found someone in charge for this. The text no longer is different between online and print because print is no longer supported. Therefore I will do another update today …

**Comment by TeXhackse** [comment]
This issue has caused some more discussion. According to TUCan we shall remove the affidavit from the templates, because students are asked to use the docx file, print it, sign it, scan it and include that one to the PDF using pdfpages.

I updated the demo file but did not remove the functionality because we rely on that one for other templates as well.
