### ISSUE TITLE
Automatic computation of points

### ISSUE THREAD

**Issue by unp1** [tudace/tuda_latex_templates#433]
Hello,

  first thanks a lot for your effort. I encountered the following problem when using automatic computation of points. The command "\getPointsTotal" seems to compute as total twice the number of points. 

A minimal example where this occurs for me (I am using tudaexercise 2023/04/24 v3.30) is:

\documentclass[oneside,
	colorback=false,
	accentcolor=9d,
	points=auto,
	]{tudaexercise}

\begin{document}

Total: \getPointsTotal{}

\begin{task}{Some Title}
\begin{subtask}[title=subtask, points=6]
\end{subtask}
\end{task}

\end{document}

The total given is 12 instead of 6.

 Is that a bug or a problem on my side?

Thanks a lot and best regards, 
Richard

**Comment by TeXhackse** [comment]
Thanks for reporting. You are right, without having a closer look atm I think that's a bug.  I will try to find some time to have a look at it today and provide a fix asap.

**Comment by unp1** [comment]
Good morning,

  thanks a lot!

Best regards, 
Richard
