### ISSUE TITLE
Broken links to ULB Latex page in README.md

### ISSUE THREAD

**Issue by Candeler0** [tudace/tuda_latex_templates#434]
Hi, 
I just stumbled upon the issue that the ULB website apparently changed the location of their Latex support pages, which in turn makes some of the links provided in the README for this repository on longer work.

More specifically, the site previously located at https://www.ulb.tu-darmstadt.de/finden_nutzen/medien_nutzen/texte_verarbeiten/latex/index.de.jsp is now found at https://www.ulb.tu-darmstadt.de/finden_nutzen/medien_nutzen/dokumente_erstellen/latex/index.de.jsp

The broken link appears three times in the readme: In the german sections "Support und Hilfe" and "Logos & verwendete Bilddateien" as well as the english section "Support".

I am not sure if this qualifies as a real issue, so feel free to close it right away. I did however want to let you know to give you a chance to fix the links.

**Comment by TeXhackse** [comment]
Thanks I will update those. Actually I had asked for those to be stable, but seems like that failed.
