### ISSUE TITLE
Spelling mistakes in affidavit since 8db26fe

### ISSUE THREAD

**Issue by georg-jung** [tudace/tuda_latex_templates#436]
8db26fe updates the affidavit text, see also #432.

However, the new text is not an exact copy of the TU template. It contains some errors:

> der TU Darmstadt selbtständig, ohne Hilfe Dritter

An `s` is missing in `selbtständig`.

The full stop `.` is missing at the end of the same sentence.

**Comment by TeXhackse** [comment]
Funny, because this was a copy+paste. Will fix it today.

**Comment by TeXhackse** [comment]
Thanks for the report, of course.

**Comment by georg-jung** [comment]
Thanks for the super-fast reaction!

**Comment by TeXhackse** [comment]
Thanks for the trial to provide a PR  :) - just was bit too fast, so it's done asap. I will upload the release to CTAN in the  evening, simply because there might be other reports in the TeXnical office hour today and I don't want to bother the CTAN team with 2 updates on a day.
