### ISSUE TITLE
Glossary does not show up in TUDaThesis

### ISSUE THREAD

**Issue by ChristophReich1996** [tudace/tuda_latex_templates#440]
Hi,

I'm trying to utilize a glossary in my thesis. However, whatever I tried ShareLaTeX does not print the glossary, only the abbreviation itself is shown. Here is the code to reproduce this issue:

```latex
%%
% !TeX program = lualatex
%%

\documentclass[
	ngerman,
	ruledheaders=section,
	class=report,
	thesis={type=master},
	accentcolor=9c,
	custommargins=true,
	marginpar=false,
	parskip=half-,
	fontsize=11pt,
]{tudapub}

\usepackage{iftex}
\ifPDFTeX
	\usepackage[utf8]{inputenc}
\fi

\usepackage[english, main=ngerman]{babel}
\usepackage[autostyle]{csquotes}
\usepackage{microtype}

\usepackage{biblatex}
\bibliography{DEMO-TUDaBibliography}

\usepackage{tabularx}
\usepackage{booktabs} 

\let\file\texttt
\let\code\texttt
\let\tbs\textbackslash
\let\pck\textsf
\let\cls\textsf

\usepackage{pifont}
\newcommand*{\FeatureTrue}{\ding{52}}
\newcommand*{\FeatureFalse}{\ding{56}}

\usepackage{glossaries}
\makeglossaries
\newacronym{miou}{mIoU}{mean Intersection-over-Union}

\begin{document}

\Metadata{
	title=TUDaThesis - Abschlussarbeiten im CD der TU Darmstadt,
	author=Marei Peischl
}

\title{TUDaThesis -- Abschlussarbeiten im CD der TU Darmstadt}
\subtitle{\LaTeX{} using TU Darmstadt's Corporate Design}
\author[M. Peischl]{Marei Peischl}
\birthplace{Geburtsort}

\reviewer{Gutachter 1 \and Gutachter 2 \and noch einer \and falls das immernoch nicht reicht}

\department{ce}
\institute{Institut}
\group{Arbeitsgruppe}

\submissiondate{\today}
\examdate{\today}

\maketitle

\affidavit

\printglossaries

\tableofcontents

\chapter{ABC}

\Gls{miou}

\printbibliography

\end{document}

```

Any idea how to fix this? Thanks for your help! :)

PS: Compiling from scratch or compiling multiple times does not help.

**Comment by TeXhackse** [comment]
Compiling from scratch means probably you are on the TUDa Overleaf server . Issue is depending on the server config. You need to run makeglossaries. To do this on sharelatex you can add a custom latexmkrc config (or edit your own one).

I add a hint on that to the Wiki. 

Example project: https://sharelatex.tu-darmstadt.de/read/vjmscympytds

**Comment by ChristophReich1996** [comment]
@TeXhackse thanks for the very quick response and thanks for sharing the example project. However, when naively compiling the project still the glossary does not show up. What am I doing wrong do I need to link the custom latexmkrc somehow?😬

**Comment by TeXhackse** [comment]
So you are on ShareLaTeX? And no you don't the latexmkrc is linked via the filename, if you are there of course.

If not we have to do that differently. Then it depends on how you compile.

**Comment by ChristophReich1996** [comment]
Yes I’m using the TU ShareLaTeX however the latexmkrc file does somehow not work for the example. The glossary is still not printed…

**Comment by TeXhackse** [comment]
Oh I see … When one is clearing the cache it needs 2 runs … yes… that seems to be a sharelatex issue. I can try to find out whats doing wrong there, but I don't know the default config they use.

**Comment by ChristophReich1996** [comment]
Thanks for the great support!

**Comment by ChristophReich1996** [comment]
Using `\makenoidxglossaries` and `\printnoidxglossaries` seems to work but is probubally not the cleanest solution.

**Comment by TeXhackse** [comment]
What also works is using the `automake` option for the glossaries package.

**Comment by ChristophReich1996** [comment]
`automake` works best for me! Thanks for the help🚀
