### ISSUE TITLE
Lualatex in TU Design mit epslatex terminal in Gnuplot macht Probleme

### ISSUE THREAD

**Issue by aroojsajjad** [tudace/tuda_latex_templates#441]
Hallöchen!
Mittels Gnuplot erstelle ich plots, die über das epslatex terminal latex-freundliche Vektorgrafiken (im Format .eps) und zusätzlich eine .tex File erzeugen, welche ich wie folgt einbinden kann:
*edit1* Ich habe mit den packages

`\usepackage{graphicx}
\usepackage{epstopdf}`

und diesem Code:
```
\begin{figure}
	\centering
	\resizebox{0.8\textwidth}{!}{{\graphicspath{{./plots/g(r)-masterplot}}\input{./plots/g(r)-masterplot/g(r)-masterplot.tex}}}
	\vspace{30pt}
	\caption{}
	\label{plot:g(r)-masterplot}
\end{figure}
```
*edit2* Nun diese Fehlermeldung:

Package luatex.def Error: File `./plots/g(r)-masterplot/g(r)-masterplot-eps-converted-to.pdf' not found: using draft setting. ....00bp},height={252.00bp}]{g(r)-masterplot}}

Was kann ich alternativ machen?
In früheren Versionen des TU Designs konnte ich so meine Plots schön einbinden und anschließend problemlos kompilieren. Die Schrift schien in entsprechender Latex Schrift an Ort und Stelle, so wie es sein sollte.

Offensichtlich wird das Bild nicht erzeugt

Danke im Voraus und LG von Arooj

**Comment by TeXhackse** [comment]
Das Bild wird nicht erzeugt, oder nicht eingebunden? In Summe glaube ich nicht, dass es was mit TUDa-CI zu tun hat. epstopdf läuft so auch, wie es soll. Mich wundert eher das komische Konstrukt den graphicspath lokal zu setzen.

Individuelle LaTeX-Unterstützung macht mittlerweile das Team-Infokompetenz, Kontakt unter https://www.ulb.tu-darmstadt.de/lernen_arbeiten/lehr_und_lernformate/textverarbeitung/textverarbeitung.de.jsp oder über die TeXnische Sprechstunde, Termine sind auch unter dem Link. Dann können wir das gerne zusammen angucken.

**Comment by aroojsajjad** [comment]
Ich hab das Problem mittlerweile endlich gelöst. Man muss, wenn man eine bestimmte Größe mittels
`set terminal epslatex size 3cm,3cm`
setzen will, in Gnuplot zweimal plotten, beim ersten mal ist der .tex-Output beschädigt bzw unvollständig.
Kann auch sein, dass das einfach an meinem Gnuplot liegt. Habe es allerdings schon zwei mal gepurget und dann jeweils neu installiert, das Problem bestand trotzdem.
Dann habe ich einfach ein bisschen rumgetestet und festgestellt, dass der fehlende Code für die begingroup ergänzt wird.
Hokus Pokus.
Na Hauptsache es funktioniert... xD
Schönes Wochenende wünscht Arooj

P.S.: Wenn ich die size auf default lasse, klappt auch alles.
Und ja das komische Konstrukt braucht man wirklich nicht.
`\begin{figure}[h]
	\centering
	\input{quadratquadrat.tex}
%	\caption{f}
\end{figure}`

Die Umgebung langt vollkommen.
