### ISSUE TITLE
Undefined control sequence durch Bibliografie

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#442]
Hi zusammen,
ich bin aktuell am Literatur für die Diss sortieren und habe einen Stapel Citations in eine leere bib-Datei reingelegt. Aus mir unerklärlichen Gründen sorgt \printbibliography für folgende Fehlermeldungen.

![image](https://github.com/tudace/tuda_latex_templates/assets/62886054/49c05b73-7b58-4f91-8e8f-a62dbf96fa31)

Kommentiere ich o.g. Befehl aus wird das Dokument ohne Probleme kompiliert. Google spuckt für die Fehlermeldung als Grund ein falsch gesetztes "\backslash" aus, das von TeX als Befehl eingelesen wird. Ich habe nun sämtlich Zitationen Blockweise auskommentiert und jedes mal die *.bbl-Datei gelöscht - keine Besserung. Nun habe ich alle Bib-Einträge händisch auf backslash's durchforstet und alles was ich finden konnte entfernt... Immer noch obige Situation... So langsam bin ich mit meinem Latein am Ende. Gibt's heirfür einen schnellen/sinnvollen Trick, die Problemstelle zu indentifizieren? Die Fehlermeldung in der tudapub.cls bringt mich leider nicht weiter...

LG

**Comment by TeXhackse** [comment]
Ist das Paket biblatex geladen?

**Comment by BPollicino** [comment]
Ja, mit folgenden Optionen: \usepackage[backend=biber,autocite=superscript,sorting=none,style=chem-angew]{biblatex}

Selbiges Command hatte ich schon in anderen Doc's und es hat problemlos funktioniert. Die Option chem-angew für den Zitationsstil ist eigentlich eine kompatible Erweiterung von biblatex selbst.

**Comment by TeXhackse** [comment]
In der Log Datei steht dahinter welcher  Befehl es direkt ist, dass ist es ein Makro innerhalb der Literaturdatei. Also wenn da z.B. ein  Bashlash im Titel vorkommt oder sowas.  Nochmal in die Log-Datei gucken. Ansonstne bitte an das Team Infokompetenz wenden, weil das kein  Bug ist, sondern ein allgemeiner LaTeX Fehler und den Support dafür machen die. Kontakt unter https://www.ulb.tu-darmstadt.de/finden_nutzen/medien_nutzen/dokumente_erstellen/latex/index.de.jsp

**Comment by BPollicino** [comment]
Das muss man aber auch wissen... Da hatte sich in einer Zitation ein amp$\mathsemicolon$ versteckt, das nicht verarbeitet werden konnte... Musste ich allerdings händisch aus der *.bbl entfernen... jetzt gehts wieder ohne Fehler.

Danke für die schnelle Hilfe!!!
