### ISSUE TITLE
\submissiondate and \examdate on first and second title page in different languages

### ISSUE THREAD

**Issue by EFitzke** [tudace/tuda_latex_templates#443]
I am using the template for PhD theses in English, 
with \usepackage[ngerman, main=english]{babel} and I set

\submissiondate{1. Januar 2024}
\examdatedate{1. Januar 2024}

On the title page, <the exam date> and <the submission date>
automatically apper after "Tag der Einreichung" and "Tag der Prüfung:". Here, I would like to have a German date format such as "1. Januar 2024".

However, on the second title page, where the dates are automatically set after "Date of Submission:" and "Date of thesis defense:", I would like to have an English date format, such as "January 1, 2024".

How can I set the dates so they are displayed in German on the title page and in the affidavit, but in English on the second title page?

**Comment by TeXhackse** [comment]
There are 3 options to resolve this.

1. Use ISO dates. Since DIN5008-2020 those are the preferred date formats in German documents as well.
2. Use the babel mechanism:
     ```
        \iflanguage{english}{<english date>}{<other date}
     ```
3. Define a macro which is language depending and holds the date
4. Adjust `\today` and use the format saved there
     ```
    \day=1\month=1\year=2024
     ```
Then `\today` will give you that date instead of the current one.

**Comment by EFitzke** [comment]
In general the dates for \submissiondate and \examdate different, so I opted for defining two language-dependent macros:

```
\newcommand{\mysubmissiondate}{%
  \iflanguage{english}{January 1, 2024}{1. Januar 2024}%
}

\newcommand{\myexamdatedate}{%
  \iflanguage{english}{February 2, 2025}{2. Februar 2025}%
}

\submissiondate{\mysubmissiondate}
\examdate{\myexamdatedate}
```

**Comment by TeXhackse** [comment]
You don't need to wrap macros that way

```
 \examdate{\iflanguage{english}{February 2, 2025}{2. Februar 2025}}
```

works fine. 

And you could also do the `\month=2` within the `\examdate` variable in case you want to use two different dates and rely on `\today`
