### ISSUE TITLE
New Slide Layout via design2023 (beta)

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#444]
Currently the repo status includes the beta version of the new slide layout with tudabeamer. It's not activated by default but this will change as soon as it's approved. 

I added a l3build script to the repo. You can either run 
```
l3build doc
```
to build all examples files or copy the files from the `tex/` directory into your working directory and compile `DEMO-TUDaBeamer2023.tex` on it's own.

l3build also supports a local installation using `l3build install` which can be undone by `l3build uninstall`. For more information on that mechanism have a look at the l3build documentation (`texdoc l3build`).

Compiled version of the demo file [DEMO-TUDaBeamer2023.pdf](https://github.com/tudace/tuda_latex_templates/files/12855867/DEMO-TUDaBeamer2023.pdf)

**Comment by TeXhackse** [comment]
the design was released today in version 3.35 -> version 4.00 is close but I want the English documentation to be included in that one. 

The design=2023 still is not set to default, this will be the case when 4.00 will be released.

**Comment by long21wt** [comment]
Hi
I have a problem when try adding logo to the new design
![image](https://github.com/tudace/tuda_latex_templates/assets/46249208/7017e487-302f-4141-a543-6a216b17f99f)
```tex
\sublogo*{\includegraphics{logo.png}\rule{\width}{\height}}
```
The result is less than satisfactory in comparison with PowerPoint. The Latex template is misaligned.
![image](https://github.com/tudace/tuda_latex_templates/assets/46249208/4b76e7b3-fd01-427d-8b9a-623789dbe3c8)

**Comment by TeXhackse** [comment]
@long21wt  I moved you request to a separate issue as I was going to close this one anyway.
