### ISSUE TITLE
How to use BCORtitlepage=true with custommargins=true?

### ISSUE THREAD

**Issue by EFitzke** [tudace/tuda_latex_templates#445]
I am using the tuda-ci Dissertationstemplate on Sharelatex and I would like to activate the binding correction for the title page:
```
\documentclass[
	ngerman,
	ruledheaders=chapter,
	class=book,
	thesis={
		type=dr,
		dr=rernat
	},
	accentcolor=9c,
	custommargins=true,
	marginpar=false,
	BCOR=5mm,
	BCORtitlepage=true,
	fontsize=11pt,
]{tudapub}
```
This still yields symmetric left and right margins for me. However, when I set `custommargins=false`, the binding correction for the title page works as expected. How can I activate binding correction for the title page while keeping the improved page layout generated with custommargins=true for the rest of the document?

**Comment by TeXhackse** [comment]
That's a bug I guess. I will have a closer look in during the next days. Hope it's not too urgent.

**Comment by TeXhackse** [comment]
@EFitzke I will fix that. As a workaround you can insert the following before `\begin{document}`

```
\UseName{bool_if:cT} {g_ptxcd_BCOR_titlepage_bool} {\xdef\coverpageleftmargin{\the\dimexpr\coverpageleftmargin+\expandafter\the\UseName{ta@bcor}}}
```
