### ISSUE TITLE
License w/o TUPrints Info

### ISSUE THREAD

**Issue by ChristophReich1996** [tudace/tuda_latex_templates#446]
Hi, is there an option to use a license notice without printing the TUPrints info? I'm using the tudapub document (`thesis={type=master}`). I want to omit the "Bitte zitieren Sie dieses Dokument also: ..." while still printing the license notice. Thanks for the help :)
<img width="443" alt="Screenshot 2023-10-25 at 16 42 20" src="https://github.com/tudace/tuda_latex_templates/assets/34400551/091e3d64-ec0c-4e7a-b2b3-d81c40e7368d">

**Comment by TeXhackse** [comment]
There is no option to add a license without TUprints. It might be an option to add that one together with #294 if that enhancement is either done by anyone else or approved to be done by myself. 

But it's of course possible to use KOMA-Sripts `\lowertitleback`  with an own text.
You can therefore.

With a current TeX Live this could also reference the License text if you set that via the thesis options:

```
\lowertitleback{\UseName{g_ptxcd_license_info_tl}}
```

In case you want to have the same layout as the license usually has, you also might want to add an `\urlstyle{same}`

```
\lowertitleback{\urlstyle{same}\UseName{g_ptxcd_license_info_tl}}
```

**Comment by ChristophReich1996** [comment]
Thanks for the support! Could you provide a minimal working example of your workaround because `\lowertitleback` seems not to work?

**Comment by ChristophReich1996** [comment]
Solved by customizing the `\tuprints` command.

**Comment by TeXhackse** [comment]
Oh sorry, I thought i had answered here - seem like this was not posted due to bad connection on train …  I add it now for reference. You dont have to redefine tuprints

**Comment by TeXhackse** [comment]
There you go - know that it's too sad but maybe it helps you or others to understand how I meant it to be used. I had also wanted to ask what you meant by “does not work” because that confused me. 

```
\documentclass[
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=rernat
	},
]{tudapub}

\usepackage[ngerman]{babel}

\begin{document}
\title{TUDaPhD -- \LaTeX-Dissertationstemplate im CD der TU Darmstadt}
\subtitle{\LaTeX{} using TU Darmstadt's Corporate Design}
\author[M. Peischl]{Marei Peischl}%optionales Argument ist die Signatur,
\birthplace{Geburtsort}%Geburtsort, bei Dissertationen zwingend notwendig
\reviewer{Gutachter 1 \and Gutachter 2 \and noch einer \and falls das immernoch nicht reicht}%Gutachter
\institute{Institut}
\group{Arbeitsgruppe}

\submissiondate{\today}
\examdate{\today}

\tuprints{license=cc-by-4.0}
\lowertitleback{\UseName{g_ptxcd_license_info_tl}}

\maketitle

\end{document}
```

**Comment by ChristophReich1996** [comment]
Hi, thanks for the great support! When I compile the following code only the title page and the dedication page are printed and not the title back page. I'm using the TU ShareLaTex.

```latex
\documentclass[
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=rernat
	},
]{tudapub}

\usepackage[ngerman]{babel}

\begin{document}
\title{TUDaPhD -- \LaTeX-Dissertationstemplate im CD der TU Darmstadt}
\subtitle{\LaTeX{} using TU Darmstadt's Corporate Design}
\author[M. Peischl]{Marei Peischl}%optionales Argument ist die Signatur,
\birthplace{Geburtsort}%Geburtsort, bei Dissertationen zwingend notwendig
\reviewer{Gutachter 1 \and Gutachter 2 \and noch einer \and falls das immernoch nicht reicht}%Gutachter
\institute{Institut}
\group{Arbeitsgruppe}

\submissiondate{\today}
\examdate{\today}

\tuprints{license=cc-by-4.0}% required to select the license
\lowertitleback{\UseName{g_ptxcd_license_info_tl}}% override the lowertitleback to not try to place tuprints data

\dedication{%
Bla%
}

\maketitle

\end{document}
``` 
<img width="302" alt="Screenshot 2023-10-28 at 00 34 16" src="https://github.com/tudace/tuda_latex_templates/assets/34400551/0ab6e569-546a-4842-9097-1afe97ebd23b">

**Comment by TeXhackse** [comment]
reduced it too much. You need twoside or class=book to get a titleback, otherwhise the page doesn't have a back.
