### ISSUE TITLE
tudasciposter change boxstyle within document

### ISSUE THREAD

**Issue by ChristophReich1996** [tudace/tuda_latex_templates#449]
Is there a clean solution to change the boxstyle of the tudasciposter class within the document? In particular, I would like to use different colors for different blocks. Additionally, is there an option to utilize a different background color (e.g., gray)?

Thanks for the help!

**Comment by TeXhackse** [comment]
Sure, you can define custom styles. See the [tcolorbox documentation](texdoc.net/serve/tcolorbox/0) for details on the color naming , e.g. 

```
\tcbset{
	TUDa-other-colored/.style =
	{
		TUDa-colored,
		colbacktitle=black!10,
		colback=black!10,
	},
}
```
