### ISSUE TITLE
\tuprints new additional licence preset for copyright (ULB request)

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#450]
Hi,
some TUprints-publications arent licenced with Creative Commons but protected by copyright (eg Kumulative Dissertation/article-based-thesis: journal/publisher doesnt allow the licence).
Hence we ask for a new preset 'copyright' for this occurence. Is this feasible?

Text example DE: 
> Die Veröffentlichung ist urheberrechtlich geschützt
> https://rightsstatements.org/page/InC/1.0/

Text example EN: 
>This work is protected by copyright
>https://rightsstatements.org/page/InC/1.0/

**Comment by TeXhackse** [comment]
Yes, it is, we already did that before. I'd recommend that to avoid confusion we have some deprecation time, so with the release I'd state a warning that it will be changed, and we implement this as an option. 

After some time (I think last time we had 3 months) we change the preset value and change the warning, so that people know how to switch back.

**Comment by sepki** [comment]
Im not sure if there is an misunderstanding regarding the switchback and deprecation time. I dont meant it as an "override", but as a new permanent addition beside the other presets.

**Comment by TeXhackse** [comment]
So the default stays the same? Then the warning and deprecation time is not needed.

**Comment by sepki** [comment]
Yes! Default is still cc-by-4.0

**Comment by TeXhackse** [comment]
I renamed it to `license=inc-1.0` as I find it important to stick to a version when manually selecting one. `copyright` might be missunderstood, as there are local differences on the understanding of that term. I can add that as an alias but would prefer not to.

**Comment by TeXhackse** [comment]
I close this as there was no reply against the adjustment.

**Comment by sepki** [comment]
Yes, sorry. No complaints here. 🙂

**Comment by TeXhackse** [comment]
No need to be sorry, as long as it's okay I handle it that way :)
