### ISSUE TITLE
\tuprints add 's' for https links (ULB request)

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#451]
Hi,
we noticed, that the tuprints-links http://tuprints.ulb.tu-darmstadt.de (generated with \tuprints) are using HTTP, instead of HTTPS. Can you update this?

affected:
- the URL in the TUprints-Text (Dieses Dokument wird bereitgestellt von tuprints, E-Publishing-Service der TU Darmstadt http://tuprints.ulb.tu-darmstadt.de)
- the URL generated by printid (Bitte zitieren Sie dieses Dokument als:.. URL: )

**Comment by TeXhackse** [comment]
I am already aware of this and it is planned to include this together with some other wishes by the Publication Service Team. They promised me to add all their requests here. Just to ensure, are you that person or just found that yourself?

**Comment by sepki** [comment]
You mailed with my colleague, just wanted to put the issue "officially" here. I should have mentioned this 🙂
