### ISSUE TITLE
\tuprints Text in docu/demo-file TUDaPhD+Thesis (ULB request)

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#452]
Hi,
Id like to ask for additions/changes for the documentation text in the demo file (Verwendung -> Übergabe der Titeldaten).

- [x] change order of urn and printid, so printid is mentioned first
- [x] change 'urn=1234' to 'urn=123456'
- [x] add 'license=cc-by-4.0' as example key
- [x] add this text: "Die printid ist die ID-Nummer Ihres TUprints-Eintrags. Ein URN ist ein zitierfähiger Persistent Identifier und entspricht Ihrer printid mit Ausnahme einer zusätzlichen Prüfziffer. Beide Angaben finden Sie in den Details Ihres TUprints-Eintrags."
- [x] is the text for 3.08 still up to date, since I got the new default already in 3.35? "...und 
eine Anpassung der Voreinstellung bei TUDa-CI ist für Version 4.0 vorgesehen."
  - [x] If not, please change the paragraph to: "Ab Version 3.08 existieren vorgefertigte Werte für die Option license, um für die Creative Commons 4.0 Lizenzen eine einfachere Anpassung zu ermöglichen. Unterstützung bei der Wahl einer passenden Creative Commons Lizenz erhalten Sie von der Universitätsbibliothek unter https://www.ulb.tu-darmstadt.de/dpub oder direkt beim Projekt über seinen Lizenzfinder unter http://creativecommons.org/choose/. Die TU Darmstadt empfiehlt in Ihrer Publikationsrichtlinie und Open-Access-Policy die Nutzung der offenen CC BY 4.0 Lizenz."
  - [x] (perhaps provide the cc-presets as bullet points?)
- [x] add text, if the copyright preset ist available  ( #450): "Ab Version x.xx können Sie mit dem Wert _copyright_ einen Vermerk zum Urheberrechtsschutz hinzufügen, wenn Sie für Ihre Veröffentlichung keine CC-Lizenz nutzen dürfen oder möchten.

**Comment by TeXhackse** [comment]
I'd not add all of this to the example files but extend the documentation and refer to that. 

v4.0 will reduce the example files and extend + unify the documentation + add an English version.

**Comment by TeXhackse** [comment]
If it's okay, I'd leave that one open until the rest for 4.0 is finished, and do a minor release today including the changes of #450 and #451

**Comment by sepki** [comment]
Yes, thats okay.

**Comment by TeXhackse** [comment]
>  is the text for 3.08 still up to date, since I got the new default already in 3.35? "...und
eine Anpassung der Voreinstellung bei TUDa-CI ist für Version 4.0 vorgesehen." 

The default still should be `cc-by-nc-nd-2.0-de` as i wrote there 4.0 I could not change it before we have that step, because people might rely on that information. But we are close to that anyway. I am in the last steps of restructuring

**Comment by TeXhackse** [comment]
Ah I found the reason, the template is enabling a different license, which is totally okay, but the default the class activates is `cc-by-nc-nd-2.0-de`.

**Comment by TeXhackse** [comment]
>  add this text: "Die printid ist die ID-Nummer Ihres TUprints-Eintrags. Ein URN ist ein zitierfähiger Persistent Identifier und entspricht Ihrer printid mit Ausnahme einer zusätzlichen Prüfziffer. Beide Angaben finden Sie in den Details Ihres TUprints-Eintrags."

I struggle a bit with the direct addressing the reader, as we don't use it in any other part of the demos. Would it be okay to write: 

> Die printid is die ID-Nummer des TUprints-Eintrags. Die urn ist ein dauerhaft eindeutig zitierfähiger Bezeichner für das Dokument. Die Nummer entspricht bei TUprints der printid mit Ergänzung einer Prüfzimmer. Beide Angaben sind in den Details des TUprints-Eintrags zu finden. 

Is there any option to find more information on the process without logging in? Just am curious. 

> add 'license=cc-by-4.0' as example key

Is that necessary if it's the default from 4.0?

**Comment by sepki** [comment]
> I struggle a bit with the direct addressing the reader, as we don't use it in any other part of the demos. Would it be okay to write:...
Yes, if the wording fits better with the rest of the document, feel free to adjust it.

> Is there any option to find more information on the process without logging in? Just am curious.

Not at the moment, sadly. But we are currently reworking our information/instructions on the website for the thesis. Perpahps we add the information on the website

> Is that necessary if it's the default from 4.0?
It doesn't necessarily have to be included. For me personally, the demo for \tuprints then feels more "complete".

**Comment by TeXhackse** [comment]
alright. will be done. Hopefully I finish that work fast.
