### ISSUE TITLE
Typst port of tudapub thesis template - how font sizes are calculated

### ISSUE THREAD

**Issue by JeyRunner** [tudace/tuda_latex_templates#453]
I created a port of the tudapub template to write a thesis with [Typst](https://github.com/typst/typst) (a new modern typesetting system inspired by Latex).
Everything is working well and looking good so far with the new template port [tuda-typst-templates](https://github.com/JeyRunner/tuda-typst-templates):

| <img src="https://github.com/tudace/tuda_latex_templates/assets/10253859/371f8673-cf83-4f3e-a923-0723c6429e37" height="300px"> | <img src="https://github.com/tudace/tuda_latex_templates/assets/10253859/4a965d92-3601-49cf-8fe6-b7845cd7e83a" height="300px"> | <img src="https://github.com/tudace/tuda_latex_templates/assets/10253859/9498d35a-9747-4b50-8c83-ea84c12f5d27" height="300px"> |
|-|-|-|

(Here is the full pdf,  [example_tudapub.pdf](https://github.com/JeyRunner/tuda-typst-templates/blob/main/example_tudapub.pdf), and the typst file that produced the pdf,  [example_tudapub.typ](https://github.com/JeyRunner/tuda-typst-templates/blob/main/example_tudapub.typ) )

For the current implementation, I hardcoded all font sizes to make it look like the original latex template. But I guess that in the latex template, all font sizes (e.g. for headings) are calculated based on the `fontsize` property of `tudapub`.
But I could not figure out how this is calculated (also why is the main document font in the resulting pdf 10.9091pt even though I set 11pt for `fontsize`)

**Comment by TeXhackse** [comment]
There is a difference in pt and pt depending on what scheme you use. TeX defines 1pt =1in/72.27 as it was used in classic book printing. DTP software usually uses a different definition, which is 1pt = 1in/72 = 1bp. TeX defines that as 1bp, namely big point.

**Comment by JeyRunner** [comment]
Thank you :)
I guess I could just add some conversion function then (at least for the main document font).

Yes sadly PDF/A export is not supported yet (https://github.com/typst/typst/issues/2942) which is required for submission in TUbama. But I tested just using a converter to convert the pdf from typst to pdf/a and it seems to work fine (https://www.ilovepdf.com/de/pdf-in-pdfa-konvertieren).

Regarding cmyk colors, at least for my case I guess I don't need them, so this is fine (currently a thesis just has to be submitted online). But this will be fixed once https://github.com/typst/typst/issues/2942 is implemented.

**Comment by TeXhackse** [comment]
I know it's technically possible, just were those things i just stumbled across -> I'd prefer if you add those in the readme in your repo or make issues there waiting for those issues you just linked. , as it doesn't help anyone in here if you link unrelated typst issues ;-)

**Comment by JeyRunner** [comment]
I added the issues to the readme (so anyone will be aware of the limitations).

Nevertheless, is there an obvious method how the heading font sizes are calculated from the main document font size, or is this just Latex "magic" in the sense that it can't be reimplemented?

**Comment by TeXhackse** [comment]
Ah, sorry, got that wrong. I was a bit confused about how you mean “calculate” the header font sizes.
Those are set by the design guideline. 

The setup is done in the clo-files (e.g. https://github.com/tudace/tuda_latex_templates/blob/c87120160af94705676d95b475e241604e651c15/tex/tuda-a4paper.clo#L33) beside that the requirements matched the standard setting of KOMA-script (except for the letter template). 

So generally LaTeX doesn't do any magic here but has predefined scaling setup done via clo-files. We don't rely on the base fontsize setup and use as far as possible the KOMA implementation. sources for those can be found here: https://mirrors.ctan.org/macros/latex/contrib/koma-script/scrkernel-fonts.dtx

**Comment by JeyRunner** [comment]
Ah that's the info I needed, I'll look at the files.
Thank you :)
