### ISSUE TITLE
Undefined control sequence \ProcessKeyOptions [ptxcd/pub] when running TUDa-PhD v3.36

### ISSUE THREAD

**Issue by m0m0khan** [tudace/tuda_latex_templates#454]
Hi, I am using TUDa-CI v3.36 with TeXlive 2022, pdfTeX Version 3.141592653-2.6-1.40.22. When I compile DEMO-TUDaPhD.tex I get this error:

`ERROR: Undefined control sequence.

--- TeX said ---
l.197 \ProcessKeyOptions
                        [ptxcd/pub]
`

I have also attached .log file. Could you please help me to resolve this?
[DEMO-TUDaPhD.log](https://github.com/tudace/tuda_latex_templates/files/13961674/DEMO-TUDaPhD.log)

**Comment by TeXhackse** [comment]
As we are close to TL 2024 I'd have loved to drop the obsolete l3keys2e package. Is there a reason you can't update to TL2022 june at least? There it would work without issues. 

You should be able to workaround by adding

```
\expandafter\ifx\csname ProcessKeyOptions\endcsname\relax
\RequirePackage{l3keys2e}
\def\ProcessKeyOptions[#1]{\ProcessKeysOptions{#1}}
\fi
```

before `\documentclass`

**Comment by m0m0khan** [comment]
I tried updating and upgrading my packages, but somehow it didn't work.
Nevertheless, it worked now with the solution you provided! Thanks!
