### ISSUE TITLE
Fehlt folgende Pflichtangabe: "Jahr der Veröffentlichung der Dissertation auf TUprints: 2024"

### ISSUE THREAD

**Issue by brunomorampc** [tudace/tuda_latex_templates#455]
Hallo, 

Wie kann ich die Angabe  "Jahr der Veröffentlichung der Dissertation auf TUprints: 2024" auf der zweiten Seite hinzufügen?

**Comment by TeXhackse** [comment]
Also hängt etwas von der Version ab, ggf. Update notwendig, aber : 

https://github.com/tudace/tuda_latex_templates/blob/549e0a6073e37ae3f900c41f5a7676081f39e37b/example/DEMO-TUDaPhD.tex#L144
