### ISSUE TITLE
Problem with citations on sharelatex

### ISSUE THREAD

**Issue by SirCodealot-py** [tudace/tuda_latex_templates#458]
Unfortunately, since yesterday there has been a problem with creating quotations in the text. Apparently the bib-file cannot be read correctly.  In addition, the bibliography is no longer displayed.

**Comment by TeXhackse** [comment]
As you don't provide further information idk if it's only happening on the TUDa sharelatex instance or a general issue. Please either give me more information or ask the general support for LaTeX that's ”[Team Infokompetenz](mailto:infokompetenz@ulb.tu-darmstadt.de)” and the sharelatex instance also has a [support email address](mailto:sharelatex@hrz.tu-darmstadt.de).

In case it's not urgent you can also visit the office hour next week and we can have a look at it together.

**Comment by TeXhackse** [comment]
closed as probably unrelated and there was no further information.
