### ISSUE TITLE
Incompatibility with marvosym

### ISSUE THREAD

**Issue by pvogt09** [tudace/tuda_latex_templates#46]
When loading the `marvosym` package, compilation crashes with
```
Package: marvosym 2011/07/20 v2.2 Martin Vogel's Symbols font definitions
! LaTeX Error: Command \EUR already defined.
               Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                             
l.154 \newcommand\EUR{\mvchr{164}}
```
The reason is that the `tuda-ci` classes [load `eurosym`](https://github.com/tudace/tuda_latex_templates/blob/master/tex/tudafonts.sty#L20) which already defines `\EUR`. Is it really neccessary to already load this symbol or shouldn't it be up to the user to deside which symbol to use fo € (the FKP template did not load `eurosym` and `marvosym` is more recent)?

A workaround would be to `\let\EUR\relax` after documentclass.

**Comment by TeXhackse** [comment]
Thanks for reporting. The idea was, that € can be used directly even in pdflatex. It would also be possibility to change that by passing options to eurosym. 

This is of course not necessary was just an idea to simplify. Another possibility would be to set € to use the `\EUR` defined at `\begin{document}` or just load the character directly to € without the package.

I think about that.

**Comment by TeXhackse** [comment]
I will change the implementation so it will directly load the symbol of the basic fonts for €. Then this shouldn't be a problem anymore. I will just do the same thing without the \EUR macro.
