### ISSUE TITLE
Colors in frametitle (design=2023)

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#460]
TUDa colors seem to be not available in frametitles:
```
\documentclass[design=2023]{tudabeamer}
\begin{document}
\begin{frame}
\frametitle{Test \textcolor{TUDa-1b}{Test}}
\end{frame}
\end{document}
```

**Comment by TeXhackse** [comment]
Color is there, but the case changing is breaking it. 

Actually – you should not use the color directly in there but you can wrap it… 

```
\documentclass[design=2023]{tudabeamer}
\begin{document}
\begin{frame}{Test \NoCaseChange{\textcolor{TUDa-1b}{\MakeUppercase{Test}}}}
\end{frame}
\end{document}
```
And thanks for providing an example for the documentation!

**Comment by schoeps** [comment]
I am personally not a big fan of colors in headlines but people sometimes want to use it anyway... can we fix it globally? Is there a way to sneak in the color definitions into the capitalization (which I am also not a fan of :) ).

**Comment by TeXhackse** [comment]
Sure there is, but it will confuse users even more if it works for those colors but not for others. So I don't think it's a good idea. 

What would work for those users would be creating some macro taking care of it.  Those are handled without case change. Just arguments are not.

**Comment by schoeps** [comment]
Would it be enough to define the TUDa colors (additionally) in capitals?

**Comment by TeXhackse** [comment]
Yes. For that specific usecase it would work.  But as I said I don't think it's a good idea to do that in the bundle. People who are debugging might be confused of this. 

I still will use your example for the docs and  I will also add an option to deactivate the case change using an option, as there might be more complex use cases.
