### ISSUE TITLE
Zweites Logo auf Titelseite einfügen

### ISSUE THREAD

**Issue by larsfw** [tudace/tuda_latex_templates#461]
Hallo,

gibt es für externe Abschlussarbeiten die Möglichkeit, neben dem TU Da Logo auf der Titelseite noch ein zweites Logo einzufügen?

Ich konnte es mit `\includegrphics` in `\group` platzieren, das sieht aber nicht so schön aus mit dem Text in der gleichen Box. Ich habe auch eine .png-Datei mit beiden Logos erstellt und über `logofile=` in `\documentclass` eingelesen, aber das wird dann so skaliert und geschnitten, dass die Logos abgeschnitten werden oder nur sehr klein mit viel weiß drumherum zu sehen sind.

Ansonsten könnte ich das Logo bestimmt nachträglich mit z.B. PDF24 auf das kompilierte PDF setzen. Wenn es jedoch eine Möglichkeit gibt, das Logo direkt mit LaTeX einzubinden, würde ich das bevorzugen.

Liebe Grüße
Lars

**Comment by TeXhackse** [comment]
http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/doc/DEMO-TUDaPub.pdf#page=4
