### ISSUE TITLE
Regression on 2023 beamer (recent commits) ?

### ISSUE THREAD

**Issue by long21wt** [tudace/tuda_latex_templates#462]
Hi,

I think recent commits introduced a few regressions to the new beamer 
![image](https://github.com/tudace/tuda_latex_templates/assets/46249208/729af584-4f1d-4ae3-a9bb-0c7a0219a06c)
Left is 3.36 released on GitHub, Middle is the deployed on TU Overleaf instance, and right is the latest commit from Git.
The top left title is bold on the old version and not on the newest. The section title on the git version is also smaller than the old one. Somehow, the deployed version of TU Overleaf displays the date on the front page.

**Comment by TeXhackse** [comment]
Thanks - yes there even are a few more. Due to the restructuring. They will fixed before the release, but actually I took as a reminder to also add the section page to the regression test files for beamer.

**Comment by TeXhackse** [comment]
I just added test to avoid this to happen in the future. During that I realized that the change you show about the date doesn't seem to be created by tuda-ci. I compared both versions again on the same LaTeX & beamer version and cannot reconstruct. 

In  case you don't want the large date on the title frame you can still use the short version to avoid this.

```
\date[extra short date for the footer]{}% empty long date and short one will be used for the footer
```
