### ISSUE TITLE
Beamer 2023: Unclear how to use authorontitle option

### ISSUE THREAD

**Issue by mrd0ll4r** [tudace/tuda_latex_templates#466]
Hey, it's me again, still beta-testing the 2023 example, the correct version this time :)

I found the note about `authorontitle=true/false`, so I gave that a shot.
It wasn't obvious for _what_ this was an option, so I just threw it into the options for the class:

```
\documentclass[
english, % main language as globale option
%	logofile=example-image, % in case you are missing the logo files
design=2023, % new slide design - will be default after official release
authorontitle=false,
]{tudabeamer}
```

From what I can observe, this is how it behaves:
- `authorontitle=true` => author and institute appear below the title
- `authorontitle=false` => author and institute still appear below the title
- not specified => author and institute do not appear below the title

As such, I'm confused. Not a pressing issue, both results can be achieved.

**Comment by TeXhackse** [comment]
Thanks, that's a bug. Generally false should be the same as the default.
