### ISSUE TITLE
\department not using prefix on thesis titlepage

### ISSUE THREAD

**Issue by maxkratz** [tudace/tuda_latex_templates#468]
Hi,

a student of our group asked about the thesis template and we had some confusion around the "field of study".

- For reference, if I add a department configuration like `\department{etit}`, I get the front page below [1].
- However, if I add a field of study configuration like `\department{ist}`, I get the front page visible in [2].

Our confusion emerged around the extra strings in the sub headline (e.g., *Master thesis **in the ﬁeld of study “Information Systems Technology”** by [...]*) and on the ride side of the document (***field of study:** Information [...]*).

Is this desired behavior? If so, why are fields of study treated so differently compared to "normal" departments? Is there a specific rule at the university that regulates this kind of descriptions on student theses?

Are students supposed to use their "field of study" definition or can they just use the department they belong to? (In our case, iST is part of the department etit, if I'm correct here.)

Thank you for your time and your help.

Best regards,
Max

---

Systems used to create the example documents:
- ShareLaTeX instance of TU Darmstadt (https://sharelatex.tu-darmstad.tde)
- Template `TUDaThesis-3.35`

---

[1]
![etit-1](https://github.com/tudace/tuda_latex_templates/assets/20956405/116531e9-8753-480b-8bbf-0ea3b474198d)

[2]
![ist-1](https://github.com/tudace/tuda_latex_templates/assets/20956405/97e4de2d-4034-4d9c-b57b-9020a3a59a22)

**Comment by TeXhackse** [comment]
Thanks for reporting. This is a bug. Actually it's intended to use the „in department/field of study“ part for all of them. It seems like I did a mistake during refactoring the bundle. Will be fixed.
