### ISSUE TITLE
TUDaPhD Affidavit: Adjustment due to the updated amendment of the doctoral regulations (§ 9 Abs. 1 PromO)

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#469]
Hi @TeXhackse ,
There was an amendment of the doctoral regulations, therefore the text has to be updated.

From:
https://github.com/tudace/tuda_latex_templates/blob/18ede87f9c64b2d70738dfc8bff3a1cb6ffe1306/tex/tudathesis.cfg#L674

To:
Ich versichere hiermit, dass die vorliegende Dissertation - abgesehen von den in ihr ausdrücklich genannten Hilfen - selbstständig verfasst wurde und dass die "Grundsätze zur Sicherung guter wissenschaftlicher Praxis an der Technischen Universität Darmstadt" und die "Leitlinien zum Umgang mit digitalen Forschungsdaten an der TU Darmstadt" in den jeweils aktuellen Versionen bei der Verfassung der Dissertation beachtet wurden.

Thanks!

**Comment by TeXhackse** [comment]
@sepki thanks - I followed the email discussion and will include that.
