### ISSUE TITLE
TUDaPhD Affidavit: Another adjustment (§8 Abs 1 lit c)

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#470]
Hi @TeXhackse,
We noticed another adjustment in the amendment of the doctoral regulations. It does no longer explicitly requires this part for the affidavit mentioned here. We would therefore remove the subsection for §8 Abs 1 lit c:
https://github.com/tudace/tuda_latex_templates/blob/18ede87f9c64b2d70738dfc8bff3a1cb6ffe1306/tex/tudathesis.cfg#L668-L669

**Comment by TeXhackse** [comment]
Thanks for the information. I removed it and will prepare a release by the end of the week.
