### ISSUE TITLE
Improve installation instructions for linux

### ISSUE THREAD

**Issue by Axolord** [tudace/tuda_latex_templates#471]
The installation instructions for linux are currently lacking and should be improved. 

For Debian/Ubuntu based distros, the `texlive-publishers` package includes tuda-ci.
For fedora, there is `texlive-tuda-ci`
The AUR has `latex-tuda-ci`
And NixOS has `texlivePackages.tuda-ci`

Other distros probably also package tuda-ci into texlive-publishers.

**Comment by TeXhackse** [comment]
There is a huge issue about this:
Those are most of the time not up to date. Therefore we decided to not officially support that way and will keep recommending the installation procedure using tlmgr. There we can keep track of the latest version.
