### ISSUE TITLE
Letter template and updated reference mechanism

### ISSUE THREAD

**Issue by TeXhackse** [tudace/tuda_latex_templates#473]
> Should help to set pdfa=false. Will explain as soon as possible.

If I compile once then yes. If I compile multiple times there is again an error.

_Originally posted by @schoeps in https://github.com/tudace/tuda_latex_templates/issues/472#issuecomment-2152071776_

That's caused by a change of the LaTeX kernel, we didn't detect yet, as hyperref was loaded by default when `pdfa=true`

**Comment by schoeps** [comment]
Yes, hyperref fixes the issue! Since I was dealing only with letters, I did not load hyperref (but it does not hurt either). Thanks.

**Comment by TeXhackse** [comment]
The new version will not need it anymore if `pdfa=false`, with `pdfa=true` it's loaded automatically.
