### ISSUE TITLE
How to add a abbreviation and notation in tex

### ISSUE THREAD

**Issue by Fighting-bruceCHN** [tudace/tuda_latex_templates#478]
Hi,

I am currently using the latex_template for my master thesis and would like to kindly ask how to add an "Abbreviations and Notations" section to this template. I have tried using the glossaries package, but the results were not satisfactory. I am using Overleaf as my TeX compiler.

Thank you very much for your assistance.

Kind regards,
Aobo

**Comment by TeXhackse** [comment]
Hi, I don't think it's a general issue, as there are too many options to solve this. 

Actually that's the reason why I did not add a recommendation, as it depends on your exakt use case. 

We have the TeXnical office hour this afternoon. Maybe it's an option you atttend there and can describe me what you expect and afterwards I can let you know what I think is the best option for you.
