### ISSUE TITLE
Fonts with better Unicode coverage

### ISSUE THREAD

**Issue by mohe2015** [tudace/tuda_latex_templates#479]
Hi,

you probably can't change this but maybe you can influence the people who can :-)
It seems like the used fonts Charter and Roboto Mono have really bad Unicode coverage.
For example 
![image](https://github.com/user-attachments/assets/5508caf4-4829-4b48-9f4d-bb01d8966ffd)
![image](https://github.com/user-attachments/assets/32a9a382-0a39-4294-9ae5-ec2a4af26483)
both seem to be missing in Roboto Mono and the delete to the left key is missing for Charter.

**Comment by TeXhackse** [comment]
The mono fonts sadly have less coverage over all. So probably it's hard to find any mono font covering those. 

So yes I can't do anything about it, especially as the font choice is not up to us. You could ask the Corporate Design Department which fonts they would prefer there, then it would be possible to define some fallback. Though combination of mono fonts is always a bit weird. 

You can always replace it yourself or choose an own fallback setup for characters not covered by the font.

**Comment by mohe2015** [comment]
I found that Inconsolata (https://fonts.google.com/specimen/Inconsolata?preview.text=%E2%8C%AB%E2%90%A3) has better unicode support I think

**Comment by TeXhackse** [comment]
There are tons of fonts with better unicode support. There is none complete one so it also depends on the characters you want to use.  … I still don't know what you are expecting from me to do, as the font choice is not up to me at all. Your suggestion includes the visible space but not the other character.

To find installed fonts with specific letters you could use albatross: https://gitlab.com/islandoftex/albatross

```
albatross  0x232b 0x2423
```
gives you all usable fonts on your system which have those two characters.
You can also insert the Unicode Glyphs directly but there you have to ensure the encoding matches.

**Comment by mohe2015** [comment]
Thank you for the suggestion to use albatross. I'm gonna close this issue as there is nothing you can do here.

Based on the website it seems to me that Inconsolata has both characters and `albatross 0x232b 0x2423` also lists it after I installed it.

**Comment by TeXhackse** [comment]
My fault - I used the variant included in TeX Live instead -> so that one might need an update.
