### ISSUE TITLE
Examples for custom title data (TUDaThesis)

### ISSUE THREAD

**Issue by pvogt09** [tudace/tuda_latex_templates#48]
It would be helpful, if not only the predefined types of theses were available, but also:
- [ ] Projektseminar
- [ ] Proseminar (at least needed for B.Sc. ETIT)
- [ ] Seminararbeit (may be needed at human sciences departments)
- [ ] `report`, for reports of (industry-)projects and the like called  "Bericht" or "Projektbericht"
- [ ] a user selectable type of thesis, if the predefined descriptions do not fit well

At IAT we already have something similar for the FKP templates (https://git.rtm.e-technik.tu-darmstadt.de/public-reps/thesis_template_latex). Feel free to take anything that seems helpful from there, although it is not `expl3` syntax.

**Comment by TeXhackse** [comment]
There is some kind of user selectable type already. If the value of `type` is not known if will be printed directly. The rest of the title data will be treated as common as possible. 
This is also mentioned in the Demo/documentation document 
> Wird ein Typus angegeben, der nicht erkannt wird, so wird der Text direkt übergeben.
Notwendige Titelfelder über den Titel hinaus gibt es in diesem Fall nicht.

You should be able to use that for any custom definition. Beside that if someone wants to add that, feel free to create a pull request. These Enhancements are not part of my task here. 

Sure it is possible to add your custom templating mechanisms. The descision about that doesn't deppend on me in general. Currently it's not part of my tasklist.

**Comment by marklaz** [comment]
> Projektseminar
> Proseminar (at least needed for B.Sc. ETIT)
> Seminararbeit (may be needed at human sciences departments)

We are talking about document types/names here to be placed on the title page?
Or are you thinking of a modified affidavit?

Otherwise, I do not get the point, as there should be no significant difference between seminar and thesis work concerning formal requirements.

> report, for reports of (industry-)projects and the like called "Bericht" or "Projektbericht"

An additional demo file for that is already work in progress. 

> a user selectable type of thesis, if the predefined descriptions do not fit well

Just use (DEMO)TUDaPub for that purpose.

**Comment by TeXhackse** [comment]
> An additional demo file for that is already work in progress.
@schoeps as far as @marklaz told me this file shall only me a minimal Variant of tudapub template. If you got different requirements for that, we should talk about that. Because the minimal Variant is already present in the development repo.

**Comment by schoeps** [comment]
It is also not clear to me why we would need all these different types (from Latex' point of view there is hardly any difference). However, if they are used at IAT, then you are free to distribute more fine-grained templates yourself (as it seems to be the case for the old templates as well)? Eventually, you could make a merge request and then we could discuss again but with information.

@pvogt09 what do you think?

**Comment by pvogt09** [comment]
> > Projektseminar
> > Proseminar (at least needed for B.Sc. ETIT)
> > Seminararbeit (may be needed at human sciences departments)
> 
> We are talking about document types/names here to be placed on the title page?
Yes, and also in the affidavit, although the affidavit might not be neccessary for Proseminar.

Maybe there is a simple way to rename e.g. "Bachelorarbeit" to "Proseminar" which I simply missed or overlooked and that would solve the issue.

> It is also not clear to me why we would need all these different types (from Latex' point of view there is hardly any difference). However, if they are used at IAT, then you are free to distribute more fine-grained templates yourself (as it seems to be the case for the old templates as well)? Eventually, you could make a merge request and then we could discuss again but with information.

Well at IAT you could write your Bachelor and Master thesis, a Studienarbeit and Diplomarbeit or a Proseminar and do a Projektseminar on the student side and lots of colleagues (including myself) use the same template (without affidavit and Gutachter and the like) for their reports for industry projects on the WiMi side. Therefore we wrote a package that can switch between all these different types by simply passing one option and then changing the title information automatically to make it easier for students and only one template file is needed for all reports and one more for the beamer presentations. If this is not a use case for the new template or can be archieved already in a different way, feel free to close this issue.

I have never worked with `expl3` so I can hardly contribute anything useful in a merge request to this project, sorry.

**Comment by TeXhackse** [comment]
@pvogt09 It's possible to use a custom type of theses. You can also overwrite the text elements on the titlepage. If you send me examples on the data positioned there we could talk about extending the documentation with some notes for your special cases and how to achieve those. (marei@peitex.de) Or create some custom examples for the specific document types, which I'd not add to the CTAN release, but maybe add them here as custom examples.

If I get further information on the differences I maybe can help better.

Beside that for these adjustments no serious expl3 knowledge is necessary, since it's just copy pasting and adjusting code + I'd review that before merging anyway. But I can understand if you find the syntax confusing.

**Comment by marklaz** [comment]
We will keep the idea of providing custom examples separately from the main package, e.g., on the web page LaTeX@TUDa.

As there seems to be no further reaction for now, I will close this issue.

**Comment by pvogt09** [comment]
Here are the PDFs produced for Projektseminar, Bachelorarbeit and Proseminar by our template/the old tudreport template. They mainly differ in the subtitle that is used, authors, supervisors and the like are identical.

[sada_tudreport_Projektseminar.pdf](https://github.com/tudace/tuda_latex_templates/files/3864994/sada_tudreport_Projektseminar.pdf)
[sada_tudreport_Bachelorarbeit.pdf](https://github.com/tudace/tuda_latex_templates/files/3864995/sada_tudreport_Bachelorarbeit.pdf)
[sada_tudreport_Proseminar.pdf](https://github.com/tudace/tuda_latex_templates/files/3864996/sada_tudreport_Proseminar.pdf)

**Comment by TeXhackse** [comment]
@pvogt09 Thank you. This is quite easy. So it's no problem to add examples for that.

**Comment by TeXhackse** [comment]
I added some hooks, including `\titleintro` and `\titleaddendum` + made the signature field splitable. You can now create personal signature boxes with
```
\SignatureBox[customwidth, if not 5cm]{Name}
```
Most of your settings can either be created by redefining the complete `\subject` fieldas it was already mentioned.

You can now also add custom info before (`\titleintro`) and after (`\titleaddendum`) the automated generaded fields. Therefore the “Betreuer” setting would be able to be done, by
```
\titleaddendum{Betreuer: …}
```
The images could also be placed before. 

If the line breaking between thesis-type and Author in your examples doesn't matter at all you can still use the automated mechanism for a custom type.

I hope this information helps so far, here also comes a simple custom example:
```
thesis={type=Proseminar}
```
and the title information:
```
\title{\LaTeX{} im Corporate Design der TU Darmstadt}
\author{Person 1 \and Person 2 \and Person 3}
\department{physics}
\date{\today}
\titleaddendum{Betreuer: \ldots}
\publishers{}
```
I also extended the information on the Title information macros. See the demo files for descriptions.

Will include that in todays release
