### ISSUE TITLE
Hinweis über "Geburtsort"-Pflicht entfernen

### ISSUE THREAD

**Issue by sepki** [tudace/tuda_latex_templates#480]
Liebe @TeXhackse 
Wir wurden durch eine Nutzeranfrage auf den Hinweis bezüglich der Geburtsort-Pflicht bei Dissertationen aufmerksam gemacht ("Bei Dissertationen zwingend notwendig"). Weder in der [Promotionsordnung](https://www.tu-darmstadt.de/media/dezernat_ii/ordnungen/promotionsordnung.pdf) noch in den [Vorgaben zum Titelblatt](https://www.intern.tu-darmstadt.de/verwaltung/dez_ii/hochschulrecht/promotion_an_der_tu_darmstadt/faq_6/artikel_details_de_en_dezii_176641.de.jsp) gibt es diese Vorgabe, daher sehen wir die Info als veraltet an und bitten um die Entfernung an den jeweiligen Stellen.

https://github.com/tudace/tuda_latex_templates/blob/03ad5b76bfae7b927f20a0a0418885c99ed71cf6/examples/DEMO-TUDaThesis-de.tex#L110

https://github.com/tudace/tuda_latex_templates/blob/03ad5b76bfae7b927f20a0a0418885c99ed71cf6/examples/DEMO-TUDaThesis-de.tex#L221

https://github.com/tudace/tuda_latex_templates/blob/03ad5b76bfae7b927f20a0a0418885c99ed71cf6/examples/DEMO-TUDaThesis-en.tex#L88

https://github.com/tudace/tuda_latex_templates/blob/03ad5b76bfae7b927f20a0a0418885c99ed71cf6/examples/DEMO-TUDaPhD-de.tex#L204

https://github.com/tudace/tuda_latex_templates/blob/03ad5b76bfae7b927f20a0a0418885c99ed71cf6/examples/DEMO-TUDaPhD-en.tex#L95

**Comment by TeXhackse** [comment]
Danke für den Hinweis. Man kann ja umschalten, dass es nur eine Warnung ist. Also d.h. die Pflicht ist mehr so semi-strinkt. 

Ich hab keine Ahnung wo das herkam, war nur damals die explizite Anforderung, weil ich damals auch nachgefragt hatte.  Nehm ich raus.
