### ISSUE TITLE
beamer 2023: long titles are not vertically aligned

### ISSUE THREAD

**Issue by mrd0ll4r** [tudace/tuda_latex_templates#481]
Hello!

I'm creating a presentation with a very long title (not by choice).
It looks like only the first line of the title is vertically centered.
Subsequent lines are placed below, which in my case shifts the lists of authors further down on the title slide.
More importantly, it leaves an unsightly amount of whitespace above the title...

I'm not sure if this is something you can fix or if it's intended behavior for the corporate identity,
but I wanted to try anyway :)

Best,
Leo

**Comment by TeXhackse** [comment]
Hi, if I remember correctly this was one of the issues I reported during the creation of this beamer theme. Sadly it's a design requirement so I may not do anything about it, but you could adjust the template using something like 

```
\addtobeamertemplate{title}{\vspace{-1cm}}{}
```

As some kind of workaround within your preamble.

Alternatively it's maybe also an option to reduce the font size…

**Comment by mrd0ll4r** [comment]
Thank you very much :)
