### ISSUE TITLE
Text for "Erklärung laut Promotionsordnung" changed

### ISSUE THREAD

**Issue by jbund256** [tudace/tuda_latex_templates#484]
Hello,

on the website of the electrical engineering department of TU Darmstadt, there is a template text for the "Erklärung laut Promotionsordnung" that has to be added in dissertations (see [here](https://www.etit.tu-darmstadt.de/media/etit/01_bilder/promotion_1/Erklaerung_laut_Promotionsordnung_9.pdf)). This text differs from the current text that is printed with the `\affidavit` command. 
I am not sure if this text applies exclusively to this department or for the total university. If the latter is the case, the text should be changed. 

Thank you.

**Comment by TeXhackse** [comment]
Do you have any information when this change was made? Last change we had, was #470 which is not too long ago.
Usually I wait for an official request. 

You always can replace the text yourself anyway.

**Comment by jbund256** [comment]
I don't know when this change was made. The pdf I attached to the original message is the only instance of an exemplary text I could find. There, it looks like the changes comes from the 9th amendment.

I will change it in my text.

**Comment by TeXhackse** [comment]
I still want to leave it open as a reminder, as long as I don't know if there is another change necessary it's worth it. Will try to find out if I find time for it, and in case someone else is having that question it's better if I don't have to answer again.

**Comment by sepki** [comment]
Das verlinkte Dokument ist inhaltlich identisch zur Vorlage, das ist vermutlich "nur" ein Formulierungsbeispiel am Fachbereich (daher auch Wasserzeichen `Muster`).

seit #470 hatten wir noch keinen neuen Änderungswunsch von TU Dezernat 2, Referat Hochschulrecht mitbekommen.

**Comment by TeXhackse** [comment]
Dankeschön Dann mach ich das zu.
