### ISSUE TITLE
Letter template broken?

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#487]
I recently updated my texlive installation and the result of
```

\documentclass[paper=a4,accentcolor=3d,premium=true,]{tudaletter}
\begin{document}
\begin{letter}{}
\setkomavar{subject}{Betreff}
\opening{Sehr geehrte Damen und Herren,}
dies und das.
\closing{Mit freundlichen Grüßen}
\end{letter}
\end{document}
```
is the attached picture without bar on top. Is it just me?
<img width="393" alt="Bildschirmfoto 2024-10-21 um 13 41 16" src="https://github.com/user-attachments/assets/0d2dac03-f5a6-4854-94ea-7d2b42c95b20">

**Comment by TeXhackse** [comment]
Nope. It's a bug in scrletter. I am on this already.

**Comment by TeXhackse** [comment]
I fixed it in KOMA-Script but idk how long it will take to get a release there. I requested one.

As a workaround one could add the following before loading tudaletter:

\makeatletter
\AddToHook{package/scrletter/after}{
	\RenewDocumentCommand{\setkomavar}{smo+m}{%
	  \Ifkomavar{#2}{%
	    \IfValueT{#3}{\@namedef{scr@#2@name}{#3}}%
	    \@namedef{scr@#2@\IfBooleanTF{#1}{name}{var}}{#4}%
	    \csname scr@#2@postset\IfBooleanTF{#1}{name}{var}\endcsname
	  }{%
	    \@koma@var@err{set}{#2}%
	  }%
	}
}
\makeatother

**Comment by TeXhackse** [comment]
The fixed version of koma-script is available via CTAN and should now be synced to all mirrors.
