### ISSUE TITLE
Backwards compatibility: Colortitleback option missing

### ISSUE THREAD

**Issue by YingYanJing** [tudace/tuda_latex_templates#49]
I have a question concerning the comparsion of this template with the earlier one by the Benner Boys. They provided a class option `colortitleback`, coloring the area around/behind the title but forcing the region below the title/left to the institution white. As far as I know, that conforms with the Corporate Design and sometimes looks better than the colored lower part of the first page. If it is possible, the implementation of this option would be nice. If that is already possible but I missed it I am sorry (it is the first time following a GitHub project for me). 

P.S. If I did something incorrectly regarding the submission of the issue or anything I would be glad to know.

**Comment by TeXhackse** [comment]
Somehow this option seems to be lost. Idk how that happened, thought we implemented that.

anyway as a short variant, one could just turn off colorback in general and add 
```
\titleimage{\color{accentcolor}\rule{\width}{\height}}
```

Though I am planning to readd that option to the next release 

> P.S. If I did something incorrectly regarding the submission of the issue or anything I would be glad to know.

It's fine that way, I will just edit the title. Usally everyone is fine if you just use one Issue per problem and don't mix things up. So it's a good first trial.

**Comment by TeXhackse** [comment]
added as an alias to 
```
logo=head,colorback=false
```
adding comment to demo
