### ISSUE TITLE
Hausaufgaben bzw. Abgaben Template / Homework or assignment template

### ISSUE THREAD

**Issue by tobiasjoergwilhelm1810** [tudace/tuda_latex_templates#492]
Englisch Version Below

---

Sehr geehrte Damen und Herren,

ist es möglich ein Abgabe Template für Studenten zu bekommen?

Momentan arbeite ich mit dem Bachelor Template für Hausaufgaben und Abgaben. Jedoch ist dies ja Formell falsch. Gibt es eine Möglichkeit dieses Template auch für Abgaben umzugestallten?

Über eine Antwort würde ich mich sehr freuen.

Mit freundlichen Grüßen
Tobias

---

Ladies and Gentlemen,

Is it possible to get a submission template for students?

I am currently working with the Bachelor template for homework and assignments. However, this is formally incorrect. Is there a way to reorganize this template for assignments?

I would be very happy to receive an answer.

Kind regards
Tobias

**Comment by TeXhackse** [comment]
Hi Tobias,
erstmal entschuldige die späte Rückemeldung, ist gerade alles extrem stressig. 
ich mach mal Deutsch, weil die Frage etwas speziell ist. 

Also naja… grundsätzlich kann man das tudaexercise Template so nehmen und einfach statt einer Aufgabenstellung eine Lösung hinschreiben. Aber erstmal ist das nicht explizit vorgesehen. 

Grundsätzlich nehme ich den Wunsch aber mal mit auf. Ich hab allerdings definitiv zu wenig langeweile und muss bei der Zeit, die ich dem Projekt hier zugesagt habe natülich immer etwas abwägen. 

Ich kann aber anbieten, dass wir sonst in der TeXnischen Sprechstunde mal über deine Vorstellung sprechen und vielleicht ist das ja doch leichter lösbar als gedacht?!

**Comment by tobiasjoergwilhelm1810** [comment]
Hi Marei,

vielen Dank für deine Antwort :)

Kann ich verstehen. Als Sysadmin / Support Team hat man leider immer viel Stress, vor allem in der Weihnachtszeit (Kenne ich , da ich als Sysadmin / CICD beauftragter in meiner Firma agiere)

Das mit der Sprechstunde klingt super :) Könntest du mir hier einen Link o.ä. zukommen lassen, wo man sich eintragen kann?

**Comment by TeXhackse** [comment]
Gibt (leider) keine Anmeldung aber der nächste termin wäre heute  https://www.ulb.tu-darmstadt.de/die_bibliothek/aktuelles/veranstaltungen/veranstaltung_details_182611.de.jsp

**Comment by tobiasjoergwilhelm1810** [comment]
Vorgang hat sich geklärt!!!

Einfachste Lösung:

Man nimmt die Documentenklasse für z.B. tudapub und ändert hier den thesis type in den gewünschten Title

``` Latex
\documentclass[
	ngerman,
	ruledheaders=section,%Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=report,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={type=Hausarbeit},% Dokumententyp Thesis, für Dissertationen siehe die Demo-Datei DEMO-TUDaPhd
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}
```

Dies würde dann den Type in Hausarbeit ändern statt z.B. BA-Thesis
