### ISSUE TITLE
Aktuelle Kompilierungsprobleme via sharelatex.tu-darmstadt.de

### ISSUE THREAD

**Issue by DeltaE7** [tudace/tuda_latex_templates#493]
LaTeX Vorlage tudapub

Hallo liebes ULB-Team,

seit heute Mittag haben wir ein Problem mit der tudapub Vorlage. Seit Anfang des WiSe 23/24 verwenden wir diese Vorlage bzw. eine Praktikumsprotokollvorlage des FB11 im Moodle Kurs "Grundpraktikum Materialwissenschaft III - 11-01-1021-pr", die die tudapub Vorlage verwendet. Seit heute kriegen wir einen "File `tudapub.cls' not found" Fehler (anbei angefügt) beim Kompilieren unserer aktuellen, sowie alter Protokolle auf verschiedenen Geräten und Betriebssystemen. Wir verwenden aktuell sharelatex der TU Darmstadt. In Overleaf dagegen können die Protokolle kompiliert werden, das können wir allerdings nicht mehr verwenden, da die gemeinsame Bearbeitung mit kostenlosen Accounts eingeschränkt wurde.

Wir würden uns über Hilfe mit unserem Problem freuen.

Mit freundlichen Grüßen
Antonio Gundermann, Semir Eminovic

**Comment by TeXhackse** [comment]
Hallo. Das Problem bezieht sich ausschließlich auf den sharelatex Sever. Damit hab ich grundsätzlich erstmal nicht direkt zu tun und kann auch leider nichts daran machen. 

Allerdings gibts einen Workaround, bis das ganze hoffentlich komplett gefixt ist: Man muss in en Projekteinstellungen die Version ändern, dann sollte es laufen, nur der default ist aktuell doof. Das wissen die auch und sind dran.

**Comment by TeXhackse** [comment]
Und ich hab übrigens keine Ahnung um welche Praktikumsprotokollvorlagen es da geht. Grundsätzlich fände ich es immer cool, wenn Herausgeber*innen von eigenen auf TUDa-CI basierenden Vorlagen zumindest mal Bescheid geben würden… alls ihr da also Kontakt habt, gerne darauf hinweisen.

**Comment by tobiasjoergwilhelm1810** [comment]
Hi,

ich habe soeben ein Ticket erstellt [Ticket Nummer: 2024121876000392](https://ticket.hrz.tu-darmstadt.de/kix/customer.pl?Action=CustomerTicketZoom;TicketNumber=2024121876000392)

Es geht warscheinlich grundlegend darum, dass momentan Sharlatex nicht nutze
n kann, da hier ein kompilierungsfehler ist. Bei mir ist das auch so mit dertudapub Vorlage.

Logs lasse ich auch mal hier :) 

[output.log](https://github.com/user-attachments/files/18178032/output.log)

**Comment by TeXhackse** [comment]
Wie gesagt das hat hiermit absolut nichts zu tun. Ich hab keinen Zugriff auf das Ticketsystem und bin für den Server absolut nicht verantwortlich. Workaround steht oben. Einfach eine andere Version auswählen. Logs helfen absolut nicht, weil der server leider (wie man sieht) eine 2017er Version startet.
