### ISSUE TITLE
.xmpdata missing for PDF/A

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#5]
according to <https://www.tu-darmstadt.de/studieren/studierende_tu/studienorganisation_und_tucan/hilfe_und_faq/artikel_details_de_en_26885.de.jsp> it is required to include .xmpdata metadata, but it seems like the built pdf does not include those.

**Comment by TeXhackse** [comment]
For correct compilation of PDF/A you are required to use lualatex. If you do so (with pdflatex this part should work as well) you generate an .xmpdata file on first run and it will be include as metadata on second. 

Ensure you didn't switch of the pdfa mode.

**Comment by schoeps** [comment]
@TeXhackse Vielleicht sollten wir schon in README.md darauf hinweisen, dass lualatex empfohlen wird? Die Frage kommt sonst sicher öfter....

**Comment by TeXhackse** [comment]
@schoeps siehe Verwendungshinweis im README ;-)

**Comment by schoeps** [comment]
Sorry, ich hatte extra noch einmal das Readme quergelesen und es nicht gesehen (wohl zu “quer”). Danke!

**Comment by azrdev** [comment]
Sorry, seemed to be my problem:

> For correct compilation of PDF/A you are required to use lualatex

I did so, running `pandoc content.md --pdf-engine=lualatex -o content.pdf`.

Actuall that includes the xmpdata, as I can see with `pdfinfo -meta output.pdf`. I was confused because I expected my pdf viewer okular to display the .xmpdata as an attached file.

Maybe someone can & wants to run [verapdf](https://github.com/veraPDF/veraPDF-library) on some generated PDFs to check PDF/A compatibility… or maybe better not

Thank you!

**Comment by TeXhackse** [comment]
I know about verapdf and currently I am validating using acrobat. It is possible to generate valid PDF/A from tuda-ci. 

Anyway the thing about pdf/a is, that it strongly relies on the images you add. If your Images don't have included color profiles it won't be valid anymore. 

This is another kind of issue we already discussed.
