### ISSUE TITLE
headinclude und footinclude zeigen keine Wirkung

### ISSUE THREAD

**Issue by Mori22** [tudace/tuda_latex_templates#50]
Aktuell scheinen die beiden KOMA-Script Optionen headinclude und footinclude nicht berücksichtigt zu werden bzw. automatisch auf true gesetzt.

Zum Beispiel liefert (`footinclude=false`):
```latex
\documentclass[
	ngerman,
	ruledheaders=chapter,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=book,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=rernat
	},
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Sript
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
	headinclude=true,
	footinclude=false,
	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}
```
exakt das gleiche Ergebnis wie (`footinclude=true`):
```latex
\documentclass[ \ 
	ngerman,  
	ruledheaders=chapter,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub  
	class=book,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=rernat
	},
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Sript
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
	headinclude=true,
	**footinclude=true,**
	logofile=example-image, %Falls die Logo Dateien nicht vorliegen
]{tudapub}
```
Und zwar das in beiden Fällen footinclude als true verarbeitet wird.

Beim Suchen nach einer Ursache bin ich in tudapub.cls auf den folgenden Code gestoßen:
```latex
	\KOMAoptions{headinclude, footinclude=false, headwidth=text,footwidth=text}
	\let\TUDa_disable_marginpar:\relax
	\def\TUDa_restore_typearea:{
		\KOMAoptions{headinclude, footinclude=false, headwidth=text,footwidth=text}\recalctypearea
	}
```
Scheinbar wird hier headinclude und footinclude auf immer auf true gesetzt und anschließend der Satzspiegel neu berechnet, wodurch alle in der Klasse übergebenen Optionen überschrieben werden. Dies kann man auch im log sehen, da typearea zwei mal mit unterschiedlichen Werten ausgeführt wird.

Ist es gewollt, dass der user keine Möglichkeit hat Einfluss auf headinclude und footinclude zu nehmen oder handelt es sich hierbei um einen bug?

**Comment by TeXhackse** [comment]
Danke für die Meldung. Es ist in der Tat momentan statisch so gesetzt, da die Vorgaben dies notwendig machten. Zum Zeitpunkt der implementierung war die gesamte Abweichung noch nicht vergesehen.

Darüber hinaus sind die Linien Teil des Stiles. Typografisch wirken die Kopf- und Fußzeile daher eher als Teil des Textes als als ein Teil des Randes, da Sie die volle breite belegen. Daher wäre ein anderes Setup nicht wirklich sinnvoll.

Wenn man nun die Kopf und Fußzeilen komplett anders gestaltet, dann ist die Intention der Änderung nachvollziehbar.

Allgemein ist eine Änderung nach wie vor über `\KOMAoptions{headinclude=false}` möglich. Danach sollte jedoch der Satzspiegel mit `\recalctypearea` im Fall`custommargins=true` neu berechnet werden.

Ich hoffe dieser Erläuterung hilft weiter.

**Comment by schoeps** [comment]
Ich möchte @TeXhackse beipflichten: die Vorlagen sind dazu gedacht das corp. design zu implementieren. Flexibilität gegenüber Änderungen war nicht das Ziel. Andererseits wollen wir das auch nicht aktiv verhindern....go ahead but you are on your own :)

**Comment by Mori22** [comment]
Ich wollte mit meiner Meldung auch gar nicht eine Debatte darüber lostreten, inwieweit man die Vorlage anpassbar halten soll. 

Wobei ich tatsächlich der Meinung bin, dass man, im Gegensatz zu dem header, bei der Fußzeile durchaus darüber diskutieren kann, ob diese als Teil des Textes wahrgenommen wird oder nicht. (daher ja auch mein Versuch mit footinclude)

Als kurze Info für alle anderen die ggf. mal mit der Option spielen wollen:

Die Anpassung über `\KOMAoptions{footinclude=false}` funktioniert nur, wenn der Befehl und das anschließende `\recalctypearea` **nach** `\maketitle` ausgeführt werden.

**Comment by TeXhackse** [comment]
Das mit der Reihenfolge ist etwas komplex, das stimmt. Liegt an der bescheuerten Struktur der Randnotizspalte. Da schreibe ich gerade ein bisschen an der ergänzenden Info. 

Ich hab den Mechanismus im Testsystem fürs Option passing ergänzt. Wird folgen. Danke.
