### ISSUE TITLE
Datumsverarbeitung/notwendige Titeldaten

### ISSUE THREAD

**Issue by Mori22** [tudace/tuda_latex_templates#52]
Hallo,

mir ist eben gerade aufgefallen, dass es bei der Nutzung des Typs sta für Studienarbeiten scheinbar noch einen Fehler gibt:

Wenn man im mitgelieferten Beispiel für Thesis Dokumente den type von `bachelor` in `sta` ändert erhält man die folgende Fehlermeldung beim setzen:

```
! Package TUDapub/thesis Error: You did not provide date data for the title.
(TUDapub/thesis)                Either provide it or change your publication
(TUDapub/thesis)                type.
```

**Comment by TeXhackse** [comment]
Die Fehlermeldung sagt eigentlich genau, wo das Problem ist. Der Typ sta braucht eine Datumsangabe. Wenn innerhalb der Titeldaten ein Datum über `\date{}` übergeben wird, dann funktioniert alles wie vorher.

**Comment by Mori22** [comment]
Hierzu eine kurze Rückmeldung:

Wenn man in der Beispieldatei `\date{}` hinzufügt kommt die Fehlermeldung wie zu erwarten war nicht.

Allerdings wird dann auf der Titelseite das Datum UND der Tag der Einreichung (siehe Screenshot):

![image](https://user-images.githubusercontent.com/31470057/66990300-3aab3380-f0c6-11e9-9e47-ecf92b3ee02c.png)

Ist das gewollt? Wäre es nicht sinnvoller, dass die der Typ Studienarbeit sich so verhält wie die anderen Typen, also kein `\date{}` erwartet, sondern lediglich mit `\submissiondate{}` arbeitet?

Wenn man `\submissiondate{}` in der Datei weglässt und lediglich z.b. `\date{\today}` verwendet, gibt es das weitere Problem, dass ohne `\submissiondate{}` gar kein Datum auf der Titelseite ausgegeben wird: 

![image](https://user-images.githubusercontent.com/31470057/66990803-2ca9e280-f0c7-11e9-82a3-b7b31b22afe3.png)

**Comment by TeXhackse** [comment]
Die Idee dahinter war eigentlich bei diesem Fall nur `\date` und nicht auch `\submissiondate` anzugeben. Ich kenne die Struktur der Arbeiten nicht. Nach meiner bisherigen Erfahrung mit Studienarbeiten war es so, dass dort nur ein Datum stehen musste und das Einreichungsdatum nicht die große Rolle spielt, da es in der Regel eine Frist gibt, vor dieser eingereicht werden muss. Bei Abschlussarbeiten ist dies ein Unterschied.

Tatsächlich habe ich diese Struktur von den älteren Varianten übernommen, eben weil keine besondere Information dazu habe. Um das zu vereinfachen, kann ich vielleicht inden Demo-Files noch etwas ausführlicher werden. Falls Sie diesbezüglich Vorschläge haben, bin ich dankbar.

Bezüglich der notwendigen Variablen wurden mir Vorgaben gegeben, die ich lediglich umgesetzt habe. Falls das für Sie ein Problem ist, besteht immernoch die Möglichkeit als `type` eine beliebige Bezeichnung zu setzen und so die notwendigen Variablen zu umgehen.

**Comment by Mori22** [comment]
Nein, grundsätzlich finde ich es absolut okay, dass man bei Abschlussarbeiten ohne festes Abgabedatum lediglich `\date{}` verwendet. Wobei es dann vermutlich sinnvoll wäre diese Tatsache in der Dokumentation zu ergänzen. Vielleicht:

```
Wird ein Typus angegeben, der nicht erkannt wird, so wird der Text direkt übergeben. Notwendige Titelfelder über den Titel hinaus gibt es in diesem Fall nicht
Bei Typen die kein festes Abgabedatum haben (\code{sta} und \code{pp}) sollte statt \code{\submissiondate{}} und \code{\submissiondate{}} lediglich \code{\date{}} verwendet werden.
```

Kurz aber nochmal zur Verwendung z.B. bei dem typ `sta`:

Wenn ich in dem Dokument lediglich z.B. `\date{\today}` dann erhalte ich das folgende Ergebnis 

![image](https://user-images.githubusercontent.com/31470057/67006622-e2842980-f0e5-11e9-8471-222c428fae37.png)

d.h. es wird gar kein Datum angezeigt, wenn ich zusätzlich `\submissiondate{\today}` angebe erhalte ich:

![image](https://user-images.githubusercontent.com/31470057/67006686-119a9b00-f0e6-11e9-80ee-2ba4b61bd741.png)

Gibt es hier ggf. ein Problem in der Klasse? Anbei ein Minimalbeispiel auf Basis der Dokumentation. Relevant sind die Zeilen 114-117.

**Comment by TeXhackse** [comment]
oh, jup. das ist ein fehler, ich kümmere mich drum
