### ISSUE TITLE
German sharp s

### ISSUE THREAD

**Issue by YingYanJing** [tudace/tuda_latex_templates#53]
There seems to be an issue with the encoding of the German ß in the different fonts used. For example in the affidavit headline it is set correctly while it falls back to SS in the actual declaration (as shown in the picture). I am not sure if I miss a package or a font but I use mathdesign with option charter as suggested in another issue and babel as well as csquotes and microtype. A quickfix is writing \ss instead of ß, which worked if the modified tudathesis.cfg is in the same directory as the tex-file. However, it is inconvenient if everyone has to to that. 

![AffidavitMitFalschemSS](https://user-images.githubusercontent.com/56351133/66745894-92585d80-ee80-11e9-9527-e5592ccd596e.png)

**Comment by TeXhackse** [comment]
could you please attach a log file? We will try to reconstruct that issue.

**Comment by YingYanJing** [comment]
That was a fast reponse. I attached u the log-file and only exchanged my name from it. 

[thesisMainNewDesignNameExchanged.txt](https://github.com/tudace/tuda_latex_templates/files/3724125/thesisMainNewDesignNameExchanged.txt)

**Comment by TeXhackse** [comment]
Thank you. I could reconstruct it and found the Bug. Will be fixed for the next Release. I will try to manage that during in the next days

**Comment by YingYanJing** [comment]
Unfortunately, I don't fully understand the issue, but thank you for the effort and the fix.

**Comment by TeXhackse** [comment]
If you are interested I mark this to be explained, for the case I am bored ;-)

**Comment by YingYanJing** [comment]
I'am always interested in new latex stuff, and especially how you found that bug in the log file. But don't bother right now, since I won't have any time understanding it in the next three weeks anyway ;).

**Comment by TeXhackse** [comment]
tests finally finished, will be included in 1.2
