### ISSUE TITLE
information Systems Technology instead of information Systems Engineering

### ISSUE THREAD

**Issue by davidgith** [tudace/tuda_latex_templates#56]
I have a question about my field of study "ist". The official name of it is "Information Systems Technology" but in the design, it says "Information Systems Engineering". Does it need to be changed? Correct me if I'm wrong.

**Comment by TeXhackse** [comment]
Thanks for reporting. 
This is strange - if i remember correctly we had fixed that long time ago. I will have a look at the history and fix that afterwards.

**Comment by TeXhackse** [comment]
I mixed that up, with something different.
> Information Systems Engineering 
Is the string I was told to place there. 

@marklaz: I would change that, since  @davidgith seems to be right, as far as I can see. Let me know if i shouldn't do that for some´reason
