### ISSUE TITLE
Undefined control sequence.

### ISSUE THREAD

**Issue by lilyshuang** [tudace/tuda_latex_templates#57]
for master thesis template, it's always so slow to complie and always error message: 
 
/tudapub.cls, line 4
The compiler is having trouble understanding a command you have used. Check that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \usepackage{...}.

<argument> \filedate 
                      \ifx \relax \fileversion \relax \else v\fileversion \s...
l.4 ...ng TU Darmstadt's Coporate Desing(TUDa-CI)}

what should i do for this ?

**Comment by TeXhackse** [comment]
You should not directly use the repository data. You need to run the ./addlicense.sh script first.

The recommended way of using tuda-ci is installing it using a common TeX distribution or download the latest release either here or via CTAN

**Comment by lilyshuang** [comment]
thank you , but i don't understand you , what do you mean by runnung ./addlicense.sh first? where should i run this? what i use is just online overleaf, but it's soooo slow ...

**Comment by lilyshuang** [comment]
I downloaded from https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.en.jsp and then uploaded to overleaf

**Comment by schoeps** [comment]
I just tried the same, i.e., I created a new repository in overleaf, imported all files from tex/tuda/latex/tuda-ci (version 1.11 from 2019/09/27) and then compiled `DEMO-TUDaThesis.tex` in the same directory. This works me.

**Comment by TeXhackse** [comment]
There was a a version on the intern website where ./addlicense did not run before. See #41. @lilyshuang: maybe you downloaded that before we fixed that?

**Comment by lilyshuang** [comment]
thank you two very much ,@schoeps @TeXhackse , I just downloaded again and tried it in overleaf, the Problem i mentioned before is gone , but one new Comes:
(it can compile and generate pdf, but i am not sure if this problem influences something?? like compiling speed?)

### Undefined control sequence.
usr/local/texlive/2018/texmf-dist/tex/latex/pdfx/pdfx.sty, line 2361
The compiler is having trouble understanding a command you have used. Check that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \usepackage{...}.
\GenericError  ...                                
                                                    #4  \errhelp \@err@     ...
l.2361 ...eneratePdfString\pdfx@pdfTitle\xmp@Title

**Comment by lilyshuang** [comment]
Thank you very much @schoeps  @TeXhackse , I just downloaded the newest Version again, now no serious Problem anymore, just some warnings, like These:

###Package scrlayer Warning: change of layer mode could result in unexpected output and errors on input line 519.      doc/latex/tuda-ci/example/tudapub.cls, line 519

###Package TUDaPub Warning: You did not provide a Label for key introduction. Either you need to recompile your document or add a label using \IMRADlabel.

But at least i can compile and generate pdf, so if These warnings don't matter, i will just ignore them .

**Comment by TeXhackse** [comment]
@lilyshuang  Those two warnings have nothing to do with it working IMRAD is mentioned in tudapub demo. You can switch that off. The other one has been reimplemented some days ago, but you don't have to worry about that one. 

Generally it's not a good idea to ignore  warnings as long as you cannot be sure, if they matter or not.

**Comment by lilyshuang** [comment]
thank you very much. :)
