### ISSUE TITLE
\appendix changes names of figures in main text

### ISSUE THREAD

**Issue by felixschmitt** [tudace/tuda_latex_templates#59]
when using the \appendix command, the name of all figures in the text BEFORE the appendix changes from e.g. Abbildung 1.1. to Abbildung 1.1.. (two dots instead of one)

**Comment by TeXhackse** [comment]
This is a KOMA-Script Feature. If you use section-numbers containing non-numeric characters it will change that. You can adjust that using the `endperiod/noendperiod/autoendperiod` options of KOMA-Script.

See the KOMA-Script manual (texdoc scrguien or http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide.pdf) for further information.

**Comment by felixschmitt** [comment]
would you be able to explain this a little further? unfortunately I don't know where to change this and I didn't find anything about it on the internet. a workaround would also be fine...

**Comment by schoeps** [comment]
Did you search for "noendperiod" in the manual?

**Comment by felixschmitt** [comment]
yes, my problem is that I do not know which file I have to change. I'm using Overleaf and I'm very new to latex

**Comment by schoeps** [comment]
It is common practice to post a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) in such issues trackers which demonstrates the problem. Maybe you can do so and then someone will surely help (although it's off topic and you could use google to search for "koma" and "noenddot" or "scrarticle" etc).

See here an MWE how to use `noenddot`:
```
%!TEX TS-program = lualatex
\documentclass[pdfa=false,numbers=noenddot]{tudapub}
\begin{document}
\section{Head 1}
\subsection{Head 2}
\begin{figure}
	\caption{text}
\end{figure}
\appendix
\end{document}
```

**Comment by TeXhackse** [comment]
reopened, because the two dot thingie should not happen in any way. will have a look at tht

**Comment by schoeps** [comment]
However `noenddot` is working as expected, see above.

**Comment by TeXhackse** [comment]
@schoeps thx ;-)

@felixschmitt did you add any other changes on the captions? Because I can't reconstruct that.

**Comment by felixschmitt** [comment]
@schoeps thanks a lot, I literally didn't know that you have to put it in the \documentclass[].
Works fine now!

@TeXhackse yes I'm also using this piece of code to modify the caption, but it still seemed to make two dots without it:

%\DeclareCaptionLabelSeparator*{spaced}{\\[2ex]}
\captionsetup[table]{textfont=it,format=plain,justification=justified,
  singlelinecheck=false,labelsep=spaced,skip=0pt}
\captionsetup[figure]{labelsep=period,labelfont=it,justification=justified,
  singlelinecheck=false}%,font=doublespacing}

**Comment by felixschmitt** [comment]
It is possible that I also changed something else that I don't remember, so if you can't replicate it, it might have been my fault. 
If so, I'm sorry but thanks a lot for the help ;)

**Comment by TeXhackse** [comment]
There you go, you add a period manually -> this leads to two. You do that with `labelsep=period`


You should not use a special package for that kind of changes. Have a look at the KOMA-Script manual, you can do everything using this or even without both. This would also help you learning how the setup works.

Just as a general advice: Try to solve such Issues using KOMA-Script. Then you would not run into such problems and blame me for your issues ;-)
