### ISSUE TITLE
tudabeamer: make use of author and institute fields on titlepage 

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#6]
Wouldn't it make sense to include the 'detail' information from `\author[short]{detail}` and `\institute[short]{detail}` on the titlepage, e.g. below the subtitle? (Maybe in a smaller font size, we a nice formatting for the posters in place if I recall correctly)

**Comment by TeXhackse** [comment]
Sure that is possible, though I'd suggest to add that as an option, since your Guidelines do not allow it.

**Comment by TeXhackse** [comment]
an idea how to call the option? I'd not enable it by default, due to your guidelines.

**Comment by schoeps** [comment]
Ich bin schlecht im Festlegen von APIs. Ich finde meine Entscheidungen meist schon am Tag danach schlecht.... aber wie wäre so etwas wie "titleauthor=true"?

**Comment by TeXhackse** [comment]
wurde jetzt authorontitle, weil das andere gibts in zu vielen untershiedlichen varianten bei paketen

![image](https://user-images.githubusercontent.com/10723888/67245732-fb316e00-f45c-11e9-9671-6e30763d3c01.png)

notiz folgt
