### ISSUE TITLE
MWE tudapub does not work

### ISSUE THREAD

**Issue by tc88** [tudace/tuda_latex_templates#61]
I have a problem with the following MWE that does not compile with my installed TeX Live 2017 (pdfTeX 3.14159265-2.6-1.40.18)

```
\documentclass[
english,
ruledheaders=section,
class=report,
thesis={type=dr,dr=ing},
accentcolor=3d,
marginpar=false,
twoside=true,
parskip=half+,
pdfa=false,
fontsize=11pt
]
{tudapub}

% Der folgende Block ist nur bei pdfTeX auf Versionen vor April 2018 notwendig
\usepackage{iftex}
\ifPDFTeX
\usepackage[utf8]{inputenc}%kompatibilität mit TeX Versionen vor April 2018
\fi

\begin{document}

\chapter{Introduction}
This is a test

\end{document}
```
It throws the following error message no matter whether compiled with pdflatex, lualatex, or xelatex:
```
(/home/casper/texmf/tex/latex/tuda_latex_templates/tex/tudapub.cls
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
! Undefined control sequence.
<argument> \filedate 
                      \ifx \relax \fileversion \relax \else v\fileversion \s...
l.4 ...g TU Darmstadt's Coporate Desing (TUDa-CI)}
```
This problem occurs on the current master (`407c346`) as well as with versions 1.20beta, 1.11, 1.10, 1.01 and 1.00. Interestingly, I do not have this problem when checking out the CTAN version 1.11.

I would be very glad to receive some help here, thanks!

**Comment by TeXhackse** [comment]
This is a development Repo. You should Download the CTAN zip or run the addlicense.sh script first. 

I am currently adding a note on all additional scripts i the repo.
