### ISSUE TITLE
lualatex fails with formatting in \title

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#62]
If I include text formatting in `\title`, compiling with lualatex (`latexmk -pdflua mwe.tex`) fails, apparently somewhere in building PDF/A. pdflatex (`latexmk -pdf mwe.tex`) doesn't fail. MWE:
~~~latex
\documentclass[
english,
class=report,
thesis={type=master},
]
{tudapub}

\title{\emph{bar} foo}
\department{inf}
\author{john doe}
\reviewer{jane doe}

\begin{document}
\maketitle 
test

\end{document}
~~~

output ends with
~~~
** pdfx: Metadata file mwe.xmpdata read successfully.
(./mwe.xmpdata)<<sRGB.icc>>

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2390 ...xpandafter\ifx\expandafter\relax\xmp@Title
                                                  \relax\else
~~~

maybe related: #61

**Comment by TeXhackse** [comment]
No, it's not related.

This happens because you use a macro inside title which is passed to the metadata field. This would also happen if you try to add any formatting to a pdfstring. 

the '\emph' will be written to the xmpdata. You must not use any macros within there. 

If you want to stick to pdfa-mode you should provide a replacement for the metadata as shown in the DEMO-TUDaPub.tex

**Comment by TeXhackse** [comment]
@azrdev did you manage that?

**Comment by azrdev** [comment]
> @azrdev did you manage that?

sorry, did not attempt because I submitted my thesis in the meantime. \o/

But yes, it's documented here: https://github.com/tudace/tuda_latex_templates/blob/052cec8b5c99d19383563f5cdd0d1e099fbfc07d/example/DEMO-TUDaPub.tex#L175
and when using `\Metadata{title=my title without macros}` and `\title{with \macros}` it builds a document without error (and the macro working).

thanks!
