### ISSUE TITLE
Font Embedding

### ISSUE THREAD

**Issue by YingYanJing** [tudace/tuda_latex_templates#63]
Hello again, 

I may have missed an issue where my problem is solved but I need to hand in my thesis in a week and tried a test upload in TUBaMa today. Unfortunately, the website told me that the document has not the right format, as the fonts are not embedded: "Die PDF-Datei hat kein korrektes Format - Schriften sind nicht eingebettet (es müssen zumindest die subsets, also die verwendeten Zeichen eingebettet sein)." 
As a first fix i tried to add the lines that are suggested by the not-very-helpful TU webpage \usepackage{hyperref}
\usepackage[a-1b]{pdfx}. 
Surprisingly, that didn't throw and error but didn't solve the problem either. Any ideas how that might have happened and how to fix that? For some additional information I will append a log file. Also the TU webpage tells me that every imported pdf needs to be in pdf-a format already. Is that actually the case and if so how can u assure that? I am asking since I do a lot of sketches in Inkscape and export them as .pdf_tex files to get a more uniform look. Furthermore, I export my Origin graphs in pdf format to shrink the size of the document a bit and speed up the compilation time. 

[thesisMainNewDesignLog191029NameExchange.txt](https://github.com/tudace/tuda_latex_templates/files/3786033/thesisMainNewDesignLog191029NameExchange.txt)

**Comment by TeXhackse** [comment]
I guess it is about figures. For Originlab it was necessary to tell it to embed fonts. Idk if this is still the case. 

Anyway: LaTeX always embeds the font if you don't fore it to do different.

**Comment by schoeps** [comment]
If you compile in draft mode, then you should generate a PDF without images. You could try uploading this pdf to tubama. If this works then you know for sure that the images are the culprits.

**Comment by YingYanJing** [comment]
Draft mode is a really nice feature I didn't know about. And you are right, when I activate it then the updload is fine, so I need to check the figures I guess. The hint with Origin sounds sensible to me, I will check them first

**Comment by TeXhackse** [comment]
@YingYanJing did it help? i'd like to know if we can mark that as solved, though it's a general question.

**Comment by YingYanJing** [comment]
I am sorry I did not respond, yet. I am planning to rework the images this weekend and report the problem when I localised it. I am sorry tor the delay but I need to finish some chapters first.

**Comment by TeXhackse** [comment]
no need to be sorry, just was curious, since today is planned to be spent on that project.

**Comment by YingYanJing** [comment]
Heyho, I fixede the including of my images. The error was actually caused by the lack of font embedding in Origin plots as well as some chemical formulae from ChemSketch. So thank you for your tips. Maybe you can add this hint about font embedding of external pdfs to the documentation, since I was not aware that this may cause a problem.
