### ISSUE TITLE
Add color passOption to tudaexercise.cls

### ISSUE THREAD

**Issue by iibPScheich** [tudace/tuda_latex_templates#64]
Hello,
how can I change the accentcolor of an exercise? 
`
\documentclass[
	ngerman,
	color={accentcolor=9c}...
`
doesn't work.

**Comment by TeXhackse** [comment]
tudaexercise is missing the color option wrapper up to now. 
I will add that one for being consistent.

Anyway you can simply use 
```
\documentclass[ ngerman, accentcolor=9c.
```
though this will only change the accentcolor, not the identbarcolor. if you want to change all, just use `color=9c`

**Comment by TeXhackse** [comment]
A check of all implementations made me realize that 
```
color={accentcolor=9c}...
```
would not work in any case up to now. therefore i will drop that enhancement. The passing has been enhanced as for other classes.
