### ISSUE TITLE
Font for caption is Charter not Roboto

### ISSUE THREAD

**Issue by mthf93** [tudace/tuda_latex_templates#65]
According to TU guidelines Frontpage should be used for captions. I figured from previous posts, that FrontPage is changed to Roboto.
If I use captions in tudapub Charter is used for captions not Roboto. What do I need to do to change it to Roboto?
Thanks for helping!

**Comment by mthf93** [comment]
\usepackage[textfont={footnotesize,sf}, labelfont={footnotesize,sf}]{caption}
I solved my problem, but in case someone has the same question, above is an answer. Maybe there is a more elegant solution.

**Comment by schoeps** [comment]
@TeXhackse if Roboto is enforced for captions by the style guide then this is actually a bug report!?

**Comment by TeXhackse** [comment]
@schoeps yep, it is. I will solve that.

@mthf93: without the caption package it would be 
```
\addtokomafont{caption}{\sffamily}
\addtokomafont{captionlabel}{\sffamily}
```
Additional size adjustments, could be places there as well.
