### ISSUE TITLE
Simplify setspace usage

### ISSUE THREAD

**Issue by YingYanJing** [tudace/tuda_latex_templates#67]
Heyho, I was trying to change the line spreading of my document to make commenting inline easier. Thereby, i noticed that the `setspace` package does not do what it should, but only increases the distance in the headlines (see attached images). Did I miss the option in the documentation or are we not supposed to change the line spread? 

![Linespread1](https://user-images.githubusercontent.com/56351133/68074555-918a5b80-fd9c-11e9-8e27-74271f0754bd.png)
-----
![Linespread2](https://user-images.githubusercontent.com/56351133/68074556-918a5b80-fd9c-11e9-8f7e-4090f25cd13f.png)
-----
![Linespread3](https://user-images.githubusercontent.com/56351133/68074557-918a5b80-fd9c-11e9-8e01-92b305256931.png)

**Comment by TeXhackse** [comment]
Did you try to enable the increased Spacing after the title?

And for sure, thats one of the problems you will always face with adjusting the interline spacing, because the extra space will be added everywhere. You can workaround that by adding the commands beside special elements.

**Comment by marklaz** [comment]
Actually, there are some institutes which expect 1 1/2 or even 2 line spacing for their theses/seminar work. CI does not play the major role here, as text revision/correction is in focus.

I guess, we should keep that in mind for a later release.

**Comment by TeXhackse** [comment]
Yea, but those just want it for normal Text. Usually you only enable increased spacing for the content. Not for the title material or toc/lof/lot as well as for appendix.

It will work fine, if you just load the package and enable `\onehalfspacing` after `\maketitle` or after `\ŧableofcontents`

It's not more complicated than it would be with normal LaTeX documents.

**Comment by marklaz** [comment]
Ok, then I probably got the OP wrong.

If the setspace package is working fine for the main text, this issue can be closed and a short note in the documentation will be sufficient (as you suggested). No enhancement required.

**Comment by TeXhackse** [comment]
Ok I will add a specific not on that to the thesis & PhD file. (Though it's a general LaTeX Question)

**Comment by TeXhackse** [comment]
Added a note to the demo files -> v2.01 in preparation
