### ISSUE TITLE
footergraphics in TUDaAnnouncement?

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#68]
Can we have `footergraphics` in [TUDaAnnouncement](https://github.com/tudace/tuda_latex_templates/blob/master/example/DEMO-TUDaAnnouncement.tex), e.g. to be displayed instead of the qrcode (`footerqrcode`)? Maybe it's already there and I just did not see it? Thanks!

**Comment by TeXhackse** [comment]
Similar to the extra logos for the scientific posters? Yes you could, though the idea behind this was to use it for smaller papersizes. But it wouldn't be much effort to add that.

There will be a marginpar mode added, for additional logo data. Quite similar to the letter Layout. 
I am currently woring on that.

As as a quick workaround for the current status (and it is not yet finished!) you can use:
```
\ModifyLayer[
	contents={
		place the img here
         }
 	]{TUDa.poster.qrcode}
```

**Comment by schoeps** [comment]
Workaround indeed works, thanks! (I will put our institute logo in the footer. I don't like it in the header...).

**Comment by TeXhackse** [comment]
```
\footerqrcodeimg{\includegraphics[width=\width]{example-image}}
```
now overwrites possible qrcode settings with its content
