### ISSUE TITLE
Font Issues with v2.00

### ISSUE THREAD

**Issue by HackHerz** [tudace/tuda_latex_templates#71]
Currently i am using v1.11 and everything seems to be working fine. I tried updating to v2.00 and i cannot compile the _DEMO-TUDaThesis.tex_ anymore (my own Thesis won't compile either). The Error seems to be related to xcharter and the needed encoding file is not part of the xcharter package (at least not on ctan).

```
! error:  (type 1): cannot find encoding file 'xch_tuu2ww.enc' for reading
!  ==> Fatal error occurred, no output PDF file produced!
```

I attached the relevant logfile, hopefully this helps [DEMO-TUDaThesis.log](https://github.com/tudace/tuda_latex_templates/files/3827109/DEMO-TUDaThesis.log)

I am compiling with lualatex version 1.10.0, texlive 2019 on Arch Linux.

**Comment by schoeps** [comment]
I had a similar font issues until I cleaned my local `texmf` tree, i.e., I removed all previously installed fonts due the old TU Darmstadt style. Then I run `updmap-user` and everything was fine afterwards.

**Comment by HackHerz** [comment]
This worked for me. Thank you very much.
