### ISSUE TITLE
titlegraphic in TUDaAnnouncement

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#72]
It's probably not a bug but a design decision: when using `titlegraphic` with `TUDaAnnouncement` the box does not span the whole width (see attached). This looks a bit odd, no?

<img width="606" alt="screen" src="https://user-images.githubusercontent.com/868081/68542949-927d4780-03b1-11ea-8995-caa4469797c3.png">

**Comment by TeXhackse** [comment]
I actually did not expect anyone to use the titlegraphic + the marginpar.

The Examples I received only either used a titlegraphic as in tudaposter or the marginpar without. Thats why I did not expect that usecase. (And would actually prefer the tudaposter example layout in that case.)

We could change that of course…

**Comment by schoeps** [comment]
How bad is it? Just shifting a few numbers or is a refactoring necessary? 
We have been using it like [this](https://www.cem.tu-darmstadt.de/media/cem/thesis/mode_identification.pdf) but I can adapt...

**Comment by TeXhackse** [comment]
If I remember correctly it should be easily doable. As I said I just didn't think there is such a usecase, the shown one is a good example, where it might make sense. 

I will have a look as soon as I find time for that. If it's something urgent, let me know.

**Comment by marklaz** [comment]
Just to add another alternative of the same concept: [gscaushang_bsp.pdf](https://github.com/tudace/tuda_latex_templates/files/3829983/gscaushang_bsp.pdf).
We have used that so far for our theses announcements. 

Moving "Requirements" to the marginal column is a most welcome improvement, which allows for additional text (and todo topics ;) in the main column.

**Comment by marklaz** [comment]
I guess, we might live with the resulting ci-conflict.

Another solution would be to flip the upper two boxes, i.e., put image and TUDa logo to the top and let it be followed by the topic in full linewidth.

**Comment by TeXhackse** [comment]
I will make titlegraphic simply to be undependent on the column mode. That should be easy. Then you can also use the logo option move down the logo.

And @marklaz 
I don't like the last one. We have an option to scale down the Title. You can get a special option for that. I don't want to encourage people using this. But this I will not discuss here, since it's totally against your design rules :D

**Comment by marklaz** [comment]
Actually, I like the last one quite a bit in the meantime... ;-) 

Sorry, I do not get the point of the rest of your remark. 
Why should we scale down the title?

**Comment by TeXhackse** [comment]
As I said you are in the position to get a personal option =P
Anyway we should not officially add that. I already messed up your whole guidelines, if you remember last year. 

If you have too long titles theres an option to do that. So if you want to reduce the number of lines.
