### ISSUE TITLE
Department/Institution on titlepage when using tudapub (thesis)

### ISSUE THREAD

**Issue by ReinhardDominik** [tudace/tuda_latex_templates#74]
When using the tudapub class for e.g. a bachelor thesis one has to provide the department. If a student studies for example information and communication engineering I use \department{Information and Communication Engineering} so that the study program is specified correctly. However, on the titlepage it automatically prints "Information and Communication Engineering" below the athene logo or the name of the group.
Is it possible to remove the "Information and Communication Engineering" from the right side of the title page and still printing fort example the name of the group?
instbox=false removes the department and the institution.
 In my understanding the study program should appear on the title page in "Master thesis in study program..." and the department should appear in the right box. As an alternative on could specify the study program, which is different from the department.

I found found #51 which is related but not very helpful. Is it a restriction of the tu darmstadt CD or of the latex template?

**Comment by schoeps** [comment]
I am not sure if I understand the issue completely but "Information and Communication Engineering" is a study program. It's not a department, so `\department{etit}` should be the correct choice.

**Comment by ReinhardDominik** [comment]
yes you are right, but `\department{etit}` produces
Master thesis in Electrical Engineering and Information Technology by Name
on the titlepage, which is wrong. That's why I thought I should enter the study program instead of the department to fix it.
Do you get my point?
Is there any other workaround for this problem?

**Comment by schoeps** [comment]
The german version says unambiguously "Bachelorarbeit im Fachbereich Elektrotechnik und Informationstechnik von Marei Peischl". The english version drops "department", i.e. "Bachelor thesis in Electrical Engineering and Information Technology by Marei Peischl" which is still correct but not clear. The easiest fix would adding the word "department". Do you agree?

**Comment by ReinhardDominik** [comment]
Sorry I did not check the German version. I thought in refers to the study program instead of the department.
I agree with your suggestion.

For a future release one can think, whether it makes sense to change this string. Especially if there are some "exotic" study programs it might be better the have "Bachelor thesis in Biomedical Engineering" instead of just the department

**Comment by schoeps** [comment]
@TeXhackse Kannst Du bitte das "department" ergänzen? 
> Bachelor thesis in *the department of* Electrical Engineering and Information Technology by Marei Peischl

und gerne dokumentieren, wie man das überschreiben kann, wenn leicht möglich? Danke!

**Comment by ReinhardDominik** [comment]
#75

**Comment by schrchr** [comment]
I want to add that this can lead to some ugly linebreaks, especially if it gets even longer:
![grafik](https://user-images.githubusercontent.com/50080123/68711857-cbc4db80-059a-11ea-9318-c73cac4380d4.png)

Probably it would be a good idea to give the department its own line.

Maybe:
Bachelor thesis by Sebastian Maximilian Mustermann
in Electrical Engineering and Information Technology

**Comment by TeXhackse** [comment]
@schoeps steht für morgen auf dem Plan. Kümmere mich.

**Comment by TeXhackse** [comment]
> For a future release one can think, whether it makes sense to change this string. Especially if there are some "exotic" study programs it might be better the have "Bachelor thesis in Biomedical Engineering" instead of just the department

Actually that was was the reason why I dropped it for the first version. I will provide an optinal argument to department to exchange that now.

**Comment by TeXhackse** [comment]
Finished with that. Threw to the testing instance. You can try it out, by replacing the *tudathesis.cfg* either by really replacing or by placing the current version in your working directory. You can find it here: https://raw.githubusercontent.com/tudace/tuda_latex_templates/master/tex/tudathesis.cfg

I will work on some other issues and try to quickly release 2.01
