### ISSUE TITLE
Fehler ß oder {\ss} seit Update V2.00 in \metadata

### ISSUE THREAD

**Issue by open711** [tudace/tuda_latex_templates#77]
Hallo zusammen,
seit dem Update auf V2.00 hatte ich eine Fehlermeldung beim Kompilieren erhalten: 
! Undefined control sequence.
\xmp@Title

Ich konnte das Problem auf die Meta-Daten eingrenzen: Das Problem liegt in einem "ß" im Titel in \metadata. Die weiteren Umlaute funktionieren einwandfrei. {\ss} hatte das Problem nicht gelöst. Workaround ß = ss in \metadata.

Ich bin mir nicht sicher, ob es an tuda-ci liegt oder an den anderen Updates, die ich zeitgleich in MiKTeX durchgeführt habe. Vielleicht hilft es ja jemand den Fehler zu lösen, der ebenfalls das Problem hat. Packages die zeitgleich mit tuda-ci aktualisiert wurden: ctablestack, graphics, iftex, I3kernel, lualibs, luatfload, oberdiek.

**Comment by TeXhackse** [comment]
Hallo, 
danke für die Meldung. Ich glaube zu wissen, wo das Problem liegt und versuche mich morgen darum zu kümmern. 

Es wird vermutlich dadurch verursacht, dass wir im pdfa-Modus leider Type1 Schriften erzwingen müssen, umd PDF/A konform zu sein, dadurch wird die kodierung innerhalb des Dokumentes geändert. Bei den Tests hatte ich zwar Metadaten eingetragen, aber nicht über das Makro.

**Comment by TeXhackse** [comment]
Ich hoffe heute im Verlauf des Tages noch die Version 2.01 zu releasen, dann ist das auch direkt verfügbar.
