### ISSUE TITLE
custommargins tudapub

### ISSUE THREAD

**Issue by ni9997** [tudace/tuda_latex_templates#79]
Hallo,
bei mir kommt es zu einem Fehler, wenn ich wie im Beispiel custommargins=true stehen lasse. Die Titelseite ist dann noch in der ursprünglichen Größe und alle anderen Seiten haben eine sehr großen Rand. Beide Varianten entsprechen allerdings nicht den Maßen des Corporate Designs. Die beiden Bilder wurden mit dem Tamplate und lualatex erstellt ohne an den Optionen etwas zu verändern. Das Problem tritt bei mir auf unterschiedlichen Pc auf und sowohl mit der aktuellsten Version in ctan als auch mit der aktuellen Version in Github.
Wenn custommargins=false eingestellt wird, dann sind alle Seiten so groß wie die Titelseite.
![Seite1](https://user-images.githubusercontent.com/3756598/68770598-bd240600-0626-11ea-8a8c-c948919486fc.PNG)
![Seite2](https://user-images.githubusercontent.com/3756598/68770611-c57c4100-0626-11ea-9d7d-4f1470b6529a.PNG)

**Comment by TeXhackse** [comment]
solange `custommargins=true` gesetzt ist, sind die Ränder abweichend. Das ist korrekt, dokumentiert und so gewollt.

`custommargins=false` hält sich an die mir vorliegenden Vorgaben.

Was ist mit Fehler gemeint? Die Abweichungen oder taucht tatsächlich eine Fehlermeldung auf?

**Comment by Alfonso1991** [comment]
Würde mich der Frage gerne anschließen. 

Im Tutorial, wird ja auf die Möglichkeit custommargins=geometry hingewiesen. Diese Funktion muss auch dringend verwendet werden, da einige Fachbereiche ihre eigenen Abstände haben wollen. In meinem Fall benötige ich beispielsweise:
"Oben 3 cm, unten 2,5 cm, Links 3 cm, rechts 2 cm"  
(Bezieht sich auf den Beginn des Textes, nicht der Headergrafik)

Normalerweise würde ich ja jetzt einfach dementsprechend geometry definieren:
\geometry{
  left=3cm,
  bottom=2.5cm,
  right=2cm,
  top=3cm, }

Wenn ich das Dokument aber plotte, so erhalte ich bspw. Links 3,4 cm Rechts 2,8 cm und oben und unten deutlich mehr als die angegebenen Werte. (Ja ich habe es genau nachgemessen).

Wie kann ich denn mit der aktuelle Vorlage genau diese Vorgaben einhalten? Vergesse ich etwas oder gibt es eine andere Möglichkeit?

**Comment by TeXhackse** [comment]
Ähm, kann es sein, dass da noch eine Einstellung, wie „an druckbaren Bereich anpassen“ aktiv war? 
Die Maße stimmen. Auch mit der angegebenen Variante.
Einzige Abweichung ist durch includehead und includefoot möglich. Aber das unterscheidet lediglich, ob ab Kopfzeile oder ab Text (analog Fuß) gemessen wird.

**Comment by TeXhackse** [comment]
@ni9997 hat das eigentlich geholfen? Ich bin mittlerweile unsicher, was von dem Issue erwartet wird und weiß nicht, was ich diesbezüglich tun kann außer darauf hinzuweisen, dass manuelles erzwingen über geometry auf jegliche Weise, die mit eigefallen ist, funktioniert.

**Comment by Alfonso1991** [comment]
![geometry](https://user-images.githubusercontent.com/55798601/70144479-4ebeea80-169e-11ea-90a0-c162f2d933d4.png)
![geometry original](https://user-images.githubusercontent.com/55798601/70144482-4f578100-169e-11ea-9860-cf1831069f63.png)

**Comment by TeXhackse** [comment]
```
\geometry{
	top=3cm,
	bottom=2.5cm,
	left=3cm,
	right=2cm,
	includehead=false,
	includefoot=false
}
```

Ich prüfe nochmal die Default settings und erweitere die Doku ggf. entsprechend. Aber ja, da die Kopf und die Fußzeile den gesamten Textbereich einnehmen, ist es hier durchaus sinnvoll. Zur Umsetzung von komischen, aus der Luft gegriffenen Vorgaben ist das ggf. notwendig zu deaktivieren.

Wobei witzigerweise Word bei der Randeinstellung von oben auch mit Headinclude misst. Zumindest war das bei meinen letzten Tests so.

Allgemein den oberen Rand auf einer Seite ohne Übeerschrift messen. Überschriften haben häufig mehr Abstand nach oben.

**Comment by Alfonso1991** [comment]
![geometry neu](https://user-images.githubusercontent.com/55798601/70146082-c5111c00-16a1-11ea-930a-2318832197c4.PNG)

**Comment by TeXhackse** [comment]
Den rechten Rand messe ich genau nach. Der Rand unten kann durch den erhöhten Zeilenabstand zustande kommen. Man kann alle Abstände dazwischen auffüllen lassen, dazu bräuchte ich mehr Infos.

**Comment by Alfonso1991** [comment]
Mit dem Rand unten kann man denke ich leben, in word ist das ja auch nicht besser gelöst

**Comment by TeXhackse** [comment]
@Alfonso1991 Den Vergleich nehme ich jetzt etwas übel.

Aber das mit dem rechten Rand ist tatsächlich mein Fehler. Ich stand gerade  auf dem Schlauch.
```
includemp=false
```
oder
```
nomarginpar
``` 
lösen das Problem.

Die default-Variante inkludiert auf Randnotizspalte, weil die Vorgaben so *speziell* sind. Es wird bei `marginpar=false` zwar deaktiviert. Aber `\geometry` resettet immer komplett und damit ist es dann wieder aktiviert.
Dann passt alles. 

Hier ist die Randnotizspalte zwar bei einer Breite von Null aber der Spaltenzwischenraum wird trotzdem eingeschoben, weil der Rest von außen berechnet wird.

**Comment by Alfonso1991** [comment]
@TeXhackse Als Anwender, will ich ja auch nur meinen Fachbereich zufrieden stellen.

Das mit dem Header oben habe ich jetzt mit 

> headsep = 0cm

gelöst.

> footsep = 0cm

Mag er irgendwie nicht:
! Package xkeyval Error: `footsep' undefined in families `Gm'.

Die Dokumentation von geometry hatte ich mir schon mal angeschaut, finde ich irgendwie aber nicht so leicht verständlich

**Comment by TeXhackse** [comment]
> @TeXhackse Als Anwender, will ich ja auch nur meinen Fachbereich zufrieden stellen.

Aus meiner Erfahrung: 90% wissen nicht was da drinsteht, weil die Vorgaben oft willkürlich gemacht werden, da $Menschen der Meinung sind, solche Vorgabe seien nötig. Ggf. nachfragen hat tatsächlich zu meiner Studienzeit viel geholfen. Dann war auf einmal alles erlaubt. Ich hab immer gefragt, ob ich es lesbarer machen darf ;-)

Den rechten Rand schiebe ich aus Messgenauigkeit. Es sollte jetzt `\textwidth = \dimexpr \paperwidth -5cm \relax` gelten.  Das tut es bei mir. 

> Passt aber immer noch nicht zu 100%. Ich glaube der Abstand Seitenanfang Header soll 2 cm betragen

Von wo sind denn die lustigen Vorgaben? Und ja, den headsep kann man entsprechend berechnen, aber ich frage mich dennoch wo und wie genau die vorgaben zustandekommen. Sie entsprechen ja nicht den Design richtlinien sondern sind davon abweichend, aber dennoch sehr detailliert. 

> Mag er irgendwie nicht:
! Package xkeyval Error: footsep' undefined in families Gm'.

Das Ding heißt auch `\footskip In der Geometry anleitung sind ein paar Abbildungen, die helfen üblicherweise am meisten

**Comment by Alfonso1991** [comment]
Ok mit der Hilfe, passt jetzt alles so, wie ich bzw. der Fachbereich es haben möchte :)

**Comment by TeXhackse** [comment]
Anmerkung in der Doku ist jetzt ergänzt. Dann sollte das zukünftig keine Probleme mehr machen,
