### ISSUE TITLE
pagestyle adjustment for headings=automark not working as intended

### ISSUE THREAD

**Issue by azrdev** [tudace/tuda_latex_templates#8]
I'd like to add the current top-level heading to the footer, opposite to the page number. As I understand the [komascript guide p.86ff](https://ftp.fau.de/ctan/macros/latex/contrib/koma-script/doc/scrguide.pdf) this is called "running headline" and enabled by `\pagestyle{headings}`, which does nothing for my document (a `thesis={type=master}` with `class=report`, if that matters).
Using `\pagestyle{TUDa.headings}`, instead, removes the colored "accent bars" from the pages, but still doesn't add the chapter titles.

**Comment by TeXhackse** [comment]
You only did half of the work, though I just rechecked it, and I will improve that in documentation, as soon as possible

You also gotta set  headline=automark.
It would be possible to have the colorbar with the running header, but actually then the headline will be larger than the headlines. This is an issue with your Corporate Design in general.

I tried it out and realized that then we get the head twice. centered and on the outer field. This depends on your document class., You can suppress that temporarily using \chead{} as classic KOMA script would allow you to.

**Comment by azrdev** [comment]
> You only did half of the work, though I just rechecked it, and I will improve that in documentation, as soon as possible

danke!

Hatte headline=automark dazu auch ausprobiert, und auch statt der oberen colorbar den titel mittig *und* außen bekommen. `\chead{}`setzt ihn schonmal nur außen, danke!

Was ich eigentlich erreichen wollte war aber die colorbar im head/oben unangetastet zu lassen, und den titel links unten mitzuführen. Das CD Handbuch Seite 42 zeigt da links "Fußzeile" und rechts die Seitenzahl -- das ist noch eine Abweichung in tuda-ci, dort ist die Seitenzahl mittig.

Mit folgendem code bekomme ich auch fast was ich will, nur führt headline=automark dazu, dass unter dem head platz für den titel reserviert wird -- den titel kann ich ausblenden, den platz und die linie darunter aber nicht, und verstehe auch nicht was `tex/tudapub.cls`+KOMA da tun:
~~~tex
\pagestyle{TUDa}
\lohead*{}
\lehead*{}
\ifoot{\headmark}
\cfoot{}
\ofoot{\pagemark}
~~~

**Comment by TeXhackse** [comment]
Oh jetzt hab ich verstanden, was der Plan war. 
Dann genügt es grundlegend automark zu aktivieren und die Felder zu setzen, ja.

Aber den Bug gibts trotzdem ich benenne das mal um.
