### ISSUE TITLE
tuddesign / tudreport

### ISSUE THREAD

**Issue by Rupoman** [tudace/tuda_latex_templates#82]
Hello, i tried to import tuddesigns for latex (mikTex 2.9) (http://exp1.fkp.physik.tu-darmstadt.de/tuddesign/),
unfortenly it doesn't work I alyways get the error, although I follow the introductions:
My first columns in Latex:
\documentclass[nochapterpage,bigchapter,colorback,accentcolor=tud2c]{tudreport}
%%%%%linedtoc,longdoc,
\usepackage{ngerman}

\usepackage[stable]{footmisc}
\usepackage[ngerman]{hyperref}

\usepackage{longtable}
\usepackage{multirow}
\usepackage{booktabs}

\usepackage[utf8]{inputenc}
\usepackage{acronym}
\usepackage{listings}
\usepackage{tabularx}
\usepackage{url}
\usepackage{hyperref}
\usepackage{siunitx}
\usepackage{textgreek}
\usepackage{upgreek}
\usepackage{float}
\usepackage{rotating}
\usepackage{accents}

Errorcode:

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7250 64-bit)
entering extended mode
("D:/Program Files/Latex/Versuch1.tex"
LaTeX2e <2019-10-01> patch level 3

! LaTeX Error: File `tudreport.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 

How can I solve the problem ?

**Comment by Rupoman** [comment]
Windows 10

**Comment by schoeps** [comment]
You are still using the old templates from 2014. This website is about the new ones from 2019. They come directly with miktex: https://miktex.org/packages/tuda-ci. The relevant documentclass is `tudapub`.
