### ISSUE TITLE
Beschriftung von Bildern und Tabellen

### ISSUE THREAD

**Issue by c-schelli** [tudace/tuda_latex_templates#83]
Ich habe festgestellt, dass sich die Art, wie Bilder beschriftet werden, geändert hat. Der erste Screenshot zeigt ein Bild mit einer Beschriftung, wie ich sie üblicherweise in Dokumenten der TUD gesehen habe. Der zweite Screenshot zeigt ein Bild mit Beschriftung, welches ich testweise in die ansonsten unveränderte Datei "DEMO-TUDaThesis.tex" eingefügt habe. Wie zu sehen, ist die Beschriftung in einer anderen Schriftart, das "Abbildung x.y" ist nicht mehr fett, und die Beschriftung befindet sich nicht mehr mittig unter dem Bild.

Ist der neue Beschriftungsstil Absicht oder handelt es sich um einen Bug?

![Bildschirmfoto1](https://user-images.githubusercontent.com/57776743/68904366-13379d00-073e-11ea-826c-ada69eba7d4c.png)
![Bildschirmfoto2](https://user-images.githubusercontent.com/57776743/68904367-13379d00-073e-11ea-9716-ca04d9971e44.png)

**Comment by TeXhackse** [comment]
Seit Version 1 wude die Schriftart geändert, sonst nichts. Das ist richtig. Das liegt daran, dass die Corporate Design Vorgaben die Auszeichnunsschrift dafür vorsehen, siehe #65 

Die Zentrierung ist nicht allgemein deaktiviert. Es ist lediglich die Unterscheidung zwischen einzeiligen und mehrzeiligen captions deaktiviert. Die KOMA-Script-Option `captions=oneline`, die auch als Option zu den TUDa-CI-Klassen übergeben werden kann, stellt den defaultwert um. Zur Caption Position gibt es keine offizielle Vorgabe, da das auch von der Bildposition abhängt. Im Beispiel ist es durchaus sinnvoll eine einzeilige caption zu zentrieren.

**Comment by c-schelli** [comment]
Danke erstmal für die schnelle Antwort, das hilft in der Tat weiter.
Als absoluter Latex-Anfänger stellt sich mir jetzt nur die Frage, wie ich die Caption zentriere.
Mit

`\begin{figure}
	\centering
	\includegraphics[width=0.7\linewidth]{An202}
		{\centering
			\caption{Antonov An-2}
								}
\end{figure}`

funktioniert es genauso wenig wie mit 

`\begin{figure}
	\centering
	\includegraphics[width=0.7\linewidth]{An202}
		\begin{center}
			\caption{Antonov An-2}
		\end{center}
\end{figure}`

Gibt es eine alternative Möglichkeit, die caption zu zentrieren?

**Comment by TeXhackse** [comment]
siehe oben `captions=oneline`. Einfach als zusätzliche Option bei TUDaPub eintragen. 

Und als Tipp: *Niemals* eine Layout-Änderung, die global gelten soll, lokal setzen.
