### ISSUE TITLE
Cannot use italics in thesis

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#84]
Hello,

I tried to write in italics in the text of the thesis by using `\textit{}` but it has no effect, the text remains normal.

When compiling, several warnings related to the font appear in the log:

> Font shape `TU/XCharter-TLF/m/n' undefined(Font) using `TU/lmr/m/n' instead

> Font shape `TU/XCharter-TLF/b/n' undefined(Font) using `TU/XCharter-TLF/m/n' instead

> Font shape `TU/XCharter-TLF/m/it' undefined(Font) using `TU/XCharter-TLF/m/n' instead

> Font shape `TU/RobotoSlab-TLF/m/n' undefined(Font) using `TU/lmr/m/n' instead

> Font shape `TU/RobotoSlab-TLF/m/it' undefined(Font) using `TU/RobotoSlab-TLF/m/n' instead

Can something be done to solve this problem?

Thank you

**Comment by TeXhackse** [comment]
You seem to have some local font variants installed. Could it be, that you manually installed some fonts for an outdated template version?

Remove those files and run updmap/updmap-sys to clean the font cache for Type 1 fonts.

**Comment by JuLateX** [comment]
Yes, I had to manually install some fonts for an older version of the template.

I tried to remove them but I am not certain that I found them. In C:\texlive\texmf-local I had a folder named "fonts". It had several subfolders but all were empty. I moved to it my desktop to test if it was were the fonts were stored and I tried to run the command you mentionned.

I did not know where to run it so I opened TeX Live Shell and clicked on "Actions > Regenerate fontmaps" then I clicked on "Actions > Regenerate formats" and tried to compile my thesis again.

The italics still don't work. If the fonts are not in the "fonts" folder, I do not know where to find them.

**Comment by TeXhackse** [comment]
Can you add a log file please? there we should be able to see that.

**Comment by JuLateX** [comment]
[Log_file_maybe.txt](https://github.com/tudace/tuda_latex_templates/files/3854221/Log_file_maybe.txt)

I hope this is what you asked for, I copied the text appearing in "log" when clicking on "Log File" in TeXstudio.

**Comment by TeXhackse** [comment]
thanks, now i can reconstuct that and thing about a solution.

**Comment by TeXhackse** [comment]
could you try the following?
add the file you find at the link to your local working directory and test if that works out.

https://raw.githubusercontent.com/tudace/tuda_latex_templates/master/tex/tudafonts.sty

ATM it looks like it's my fault. Though I really expected an installation problem. Sorry for that.

**Comment by JuLateX** [comment]
Sure. My local working directory is the one with my thesis or the tex;f-local one?

**Comment by TeXhackse** [comment]
the one, where you placed the tex file you compile.

This is a temporary test. you can delete it afterwards, because a local copy overwrites the installed variant. But if it works, i will just add it to the release currently preparing for publish.

**Comment by JuLateX** [comment]
Done. It no longer compiles. I got the error message 

> Missing \begin{document}. \DeclareUnicodeCharacter{2

followed by many other errors. I join the log file
[Log_file_2.txt](https://github.com/tudace/tuda_latex_templates/files/3854250/Log_file_2.txt)

**Comment by schrchr** [comment]
For me the new "tudafonts.sty" file removes the warnings.

**Comment by JuLateX** [comment]
I found why it was not working for me. I had an error always appearing on what is line 22 of the new .sty file: 

> Missing \begin{document}. \DeclareUnicodeCharacter{2

I understood that this line was related to the € symbol and as I won't need it in my thesis I avoided the problem by commenting lines 18 to 22
`%	\RequirePackage[utf8]{inputenc}
%        \expandafter\ifx\csname texteuro\endcsname\relax
%        \RequirePackage{textcomp}
%        \fi
%        \DeclareUnicodeCharacter{20AC}{\texteuro}`

If I comment these lines once more in the new file the thesis compile but the italics are still not working. I know that my colleagues are also unable to use italics and that they have not commented anything on the .sty file.

**Comment by TeXhackse** [comment]
but you are using lualatex, aren't you? Then you should not even get to this line.

**Comment by JuLateX** [comment]
Yes I am using lualatex and it was also my impression.
At the top of my main file, I have the line:
`% !TeX program = lualatex`

**Comment by TeXhackse** [comment]
Your log file also says that. But the lines you commented are in an that `ifPDFTeX` branch. so anything else is going wrong. 

Are you sure, the file tudafonts.sty in your working directory is a plain text file only containing the data of the file I  uploaded?

**Comment by TeXhackse** [comment]
Um @JuLateX could it be, that you manually load fontspec in your file?

**Comment by JuLateX** [comment]
I copy pasted the text in a new file on notepad and saved it under the name tudafonts.sty

I don't know if it can have an impact but I plotted the figures with tikz and found online that the lines
`\ifx\directlua\@undefined`
`\else`
`\RequirePackage{luatex85}`
`\RequirePackage{shellesc}`
`\fi`

should be added at the top of the main file.

**Comment by JuLateX** [comment]
Yes, I manually load fontspec, and then miama to use as a font on the dedication page.

I wanted the dedication page at a different place than it was in the template so I commented the line `\dedication{For \TeX{} \& Friends}` in the template and afterwards inserted a file containing the dedication where I wanted it. The file contains:
`% !Tex root = PhD_thesis.tex

\cleardoublepage
\newfontfamily\myfont{miama}
\vspace*{\fill}
\begingroup
\centering

{\myfont\Huge{En Français}}

	
\endgroup
\vspace*{\fill}
\cleardoublepage`

**Comment by TeXhackse** [comment]
@schoeps @marklaz: wooohoooo we now got the issue where people are confused by the type1 enforcement for PDF/A

@JuLateX: Sorry, I told them, this would happen some day ;-) 

anyway:
PDF/A mode enforces Type 1 => you cannot use fontspec with that. You can only load classical LaTeX fonts.

Beside that:
General advice: *Don't load non-required packages.*
Don't load any packages when you got no idea what they do. 
luatex85 and shellesc are no longer required, that bug has been fixed long ago and you are using TL19. That should be doable without this.

Template specific advice:
Don't mess up the fonts and blame me ;-)

I am sorry, but I cannot do general LaTeX support for your whole university (At least not in my free time). So I will upload 2.02 now.

**Comment by schoeps** [comment]
@JuLateX TU darmstadt asks for PDF/A to archive theses. I guess your thesis compiles without the specific font?
If you really want to use miama, then you could include the dedication as a graphics object.

**Comment by TeXhackse** [comment]
@schoeps no. because it also depends on the graphics. If you e.g. include a pdf which is not pdf/a valid the resulting output will not as well. Be careful with that. 

@JuLateX you can have a look at https://tug.org/FontCatalogue/miamanueva/ 
The Miamanueva ist part of TeXLive and can be used as Type 1 and activate it using `\fmmfamily` . You can include this.  Pay attention to the encoding.

**Comment by JuLateX** [comment]
Yesm it compiles and the italics works. I will tell my colleagues to download the new version of the template
I will try the solution you propose for the font.

Thank you for your time!

**Comment by schoeps** [comment]
@TeXhackse You underestimate my criminal energy to work around issues like that. I would have converted the fonts to (vector) graphics :)

**Comment by TeXhackse** [comment]
@schoeps At least you got my point. Most people don't.
