### ISSUE TITLE
\tuprints command in TUDaPhD only print CC license 2.0 Deutschland and not others

### ISSUE THREAD

**Issue by m0m0khan** [tudace/tuda_latex_templates#87]
Hello,

If I want to use the license 4.0 International (https://creativecommons.org/licenses/by-nc-nd/4.0/) in my thesis to be appeared on the page after title page, how could I change the text at the bottom from 2.0 Deutschland to 4.0 International?

Regards,
Khan

**Comment by TeXhackse** [comment]
Hello,
I was asking that during working on those templates. But I was told that tuprints requires this license format. That's why it's hardcoded up to now.

You could replace the complete lowertitleback information by using KOMA-Scripts `\lowertitleback{Add information here}`

**Comment by martin-fzd** [comment]
I am afraid I have to repost into this old issue. The current publisher agreement for tuprints by the ULB provides for Creative Commons version 4, alternatively a separate license.

![image](https://user-images.githubusercontent.com/26324188/97969176-f6b5ca00-1dbf-11eb-8bfd-be212b9f91d6.png)


In my experience, the issue of license selection for a work is not given the attention it deserves. It cannot be assumed that the default license (in this case it would be CC 4.0 BY) is always the best choice. Would it be an idea to highlight the license paragraph in the template in a different color to force "active" editing by the user?

**Comment by TeXhackse** [comment]
since this is not exactly the same issue I moved your comment to a new issue. Please consider to open a new issue even if the content seems to be similar.
