### ISSUE TITLE
Titlegraphic does not work for with Announcement and SetMarginpar

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#88]
The text in the margin is not correctly positioned. MWE:
```
\documentclass[paper=a4,type=announcement,]{tudaposter}
\usepackage{kantlipsum}
\SetMarginpar{\kant[1]}
\titlegraphic{\includegraphics[width=\linewidth]{example-image}}
\title{Title}
\subtitle{Subtitle}
\titleinfo{Titleinfo}
\begin{document}
\maketitle
\kant[1]
\end{document}
```
<img width="624" alt="screen" src="https://user-images.githubusercontent.com/868081/68975629-11c8ac00-07f4-11ea-9c15-80ebffdd4155.png">

**Comment by TeXhackse** [comment]
As you could read in the tudaposter doku file, the overlap is intended. Some of the examples used it.

To add a marginpar positioned on a corresponding height in the test you still can use \marginpar. The setup of the complete box overlaps this.

**Comment by schoeps** [comment]
Also marginpar does not help or still requires manual tweaking:
```
\documentclass[paper=a4,type=announcement,]{tudaposter}
\usepackage{kantlipsum}
\titlegraphic{\includegraphics[width=\linewidth]{example-image}}
\title{Title}
\subtitle{Subtitle}
\titleinfo{Titleinfo}
\begin{document}
\maketitle
\marginpar{This overlaps}
\kant[1]
\end{document}
```
<img width="627" alt="screenshot" src="https://user-images.githubusercontent.com/868081/68989979-d5299e80-084d-11ea-9935-645fabd18e25.png">

**Comment by TeXhackse** [comment]
this is because the box is aligned bottom :/ ok I forgot about that.

So how would you prefer it. Aligning it with text by default + adding an option for overlap?

**Comment by schoeps** [comment]
Not sure if get your question right. I would be happy with the marginpar variant if the text of the main column and the text of the marginpar would be top aligned. If this has consequences for other templates then an option for marginpar (align=top or whatever) would be fine for me as well. Thank you!

**Comment by TeXhackse** [comment]
which one of the two cases should be set the default? 
Since we released that some days ago, we still can change that one.

**Comment by schoeps** [comment]
I do not think typically one does NOT want overlap, so I would make the other one default? Does this make sense?

**Comment by TeXhackse** [comment]
Yes it does. Saw examples of this. People using that field to add some address data. Anyway default will be changed to non overlapping. Update incoming.
