### ISSUE TITLE
Undefined control sequence. \bool_lazy_any:nTF

### ISSUE THREAD

**Issue by famura** [tudace/tuda_latex_templates#89]
After copying the folders for the TUDa templates and the urcls package to the Miktex (Windows) tree, I updated Miktex. When I want to complite DEMO-TUDaPhD.tex I get

``Undefined control sequence. \bool_lazy_any:nTF`` from ``URspecialopts.sty`` in ``line 134``.

Thank you in advance.

**Comment by schoeps** [comment]
You do not need to copy anything. Miktex ships with our templates (only the TUDa logo is missing). Just make sure that all Miktex packages are updated (e.g. using the package manager). Please start from scratch and report again. It's for us almost impossible to help you if you have a mixed installation.

**Comment by TeXhackse** [comment]
I will close this, please reopen, if the problem persists afterwards after an update. 
The macro was introduced in 2015, so it could also be the case, that your MikTeX installation is older than that.

**Comment by famura** [comment]
Thank you very much for the quick reply.

Indeed, my MikTex was from 2015. Resinstalling and adding the logo.pdf fixed all problems.
