### ISSUE TITLE
Höhe der Fußzeile in TUDaPub (Doppelseitig) anpassen

### ISSUE THREAD

**Issue by W0ll4ab** [tudace/tuda_latex_templates#92]
Hey, 
ich schreibe im Moment recht viele Protokolle mit der Klasse TUDaPub und hatte mir überlegt, um die zu druckenden Seiten zu halbieren, die zweiseitige Vorlage auszuprobieren. Eigentlich ist das ja bei TUDaPub nicht standardmäßig vorgesehen, aber da die Klasse auch auf die tudapub.cls Datei zugreift wollte ich es mal probieren. 

Dafür habe ich die documentclass wie folgt verändert:

`\documentclass[
ngerman, 
marginpar=false, 
fontsize=11pt, 
ruledheaders=section, 
parskip=half-,
twoside, 
custommargins=true,
accentcolor=4a,
	]{tudapub}`

Auf den ersten Blick sieht das zwar gut aus, jedoch ist die Fußzeile recht hoch. Kann man die irgendwie runter zu setzen?

Und wenn ich mithilfe \input ein Abkürzungsverzeichnis einfüge, passieren ebenfalls komische Dinge (siehe Bild)
![footnotehoch](https://user-images.githubusercontent.com/52467414/69000637-11531280-08d3-11ea-9db8-87b2a1d989b9.png)

Das Abkürzungsverzeichnis könnte ich mehr oder weniger manuell so verändern, dass es nicht über die Fußzeile hinausragt, jedoch fände ich es persönlich schöner, die Fußzeile für das ganze Dokument runter zu setzten.
Daher meine Frage:

**Gibt es so eine Möglichkeit, mit der man die Höhe der Fußzeile verändern kann?**

und wenn ich schon dabei bin, kann man die custommargin width kleiner machen? sodass zwar noch die Seiten einen Abstand zu der Lochung haben, jedoch nicht so einen großen wie voreingestellt?

Ich weiß nicht ob es dazu relevant ist, aber ich habe das Aussehen noch mit
`\setlength{\headsep}{0pt}` verändert.

**Comment by TeXhackse** [comment]
Kurzfassung, da Stress:
Grundsätzlich kann TUDaPub natürlich auch zweiseitig. Das ganze ist so modular gebaut, dass das möglich sein soll. 


> Gibt es so eine Möglichkeit, mit der man die Höhe der Fußzeile verändern kann?

Ja. Einerseits über die Mechanismen die KOMA-Script mit liefert. Andererseits kann der Rand auch mit `custommargins=geometry` durch `\geometry` manuell definiert werden. 

Die Änderung von `\headsep` hat darauf definitiv Einfluss. Allgemein ist es sinnvoll Längen nicht direkt zu ändern, da diese oft auf andere Elemente Einfluss haben. Dafür emfiehlt sich ein Paket, wie z.B. typearea oder geometry. 

Ich hoffe, das hilft erstmal weiter. Die Informationen zu den custommargins, sind jedoch in den Thesis Varianten dokumentiert, aber das werde ich möglichst bald ergänzen.

## Abkürzungsverzeichnis
Das Abkürzungsverzeichnis ist nur einfach zu lang, das sieht aus wie eine Tabelle, die nicht umgebrochen werden kann. Da fehlen mir aber genauere Infos.

**Comment by schoeps** [comment]
Indeed you have a lot of white space... we use this for reports: `\documentclass[pdfa=false,class=report,ruledheaders=all,custommargins=false,marginpar=false,BCOR=5mm,DIV=10,twoside,fontsize=11pt]{tudapub}`

**Comment by W0ll4ab** [comment]
Thank you very much, now it looks exactly as I had imagined ^^
