### ISSUE TITLE
"No color profile found to use for RGB screen colors" despite latest TeXLive2019

### ISSUE THREAD

**Issue by Leistungskurve3000** [tudace/tuda_latex_templates#96]
Hello,

system specifications: OS: Linux Mint 19.2 (based on Ubuntu 18.04), distribution: Texlive2019, GUI: Texmaker

I just downloaded the TeXLive 2019 distribution today from https://www.tug.org/texlive/ , which comes with both the tuda-ci and the pdfx packages installed. When trying to compile any .tex-file with texmaker and the "LuALatex" compiler, I get this error message:

```
No color profile found to use for RGB screen colors
! TUDaPub error: "outdated-pdfx"
!
! Your Version of the PDFx-package is too old to support all methods required
! by tudapubs pdfa-mode.
! Either update your TeX-distribution or switch to pdfa=false.
!
! See the TUDaPub documentation for further information.
```
I also get the same error message when using the pdflatex compiler.

According to the documentation, tuda-ci needs an additional 'colorprofiles' package, which I downloaded from the given URL: http://ftp.fau.de/ctan/support/colorprofiles/

How do I properly install the package to solve the issue?

I tried to extract and move the colorprofiles folder into /usr/local/texlive/2019/texmf-dist/tex/latex/ , then ran texhash.
Unfortunately, this did not solve the problem, as the same error message still appears.

I also downloaded the whole pdfx package from this URL: https://ctan.org/pkg/pdfx?lang=en
Then put the package into /usr/local/texlive/2019/texmf-dist/tex/latex/ and ran texhash, yet, this did not solve the problem either.

**Comment by TeXhackse** [comment]
Can you attack a complete logfile? 

The outdatedpdfx error is created when pdfx is older than 2018/12/01. As the error message already says. You can set `pdfa=false` to be able to compile. Besides that I cannot give any more information on that Error, without having further information.

The colorprofile is part of TeX Live therefore no manual installation is necessary with recent versions.

**Comment by schnake92** [comment]
I had this problem too, running Bash on Ubuntu on Windows.  I'm no way an expert, but it seems like the packages delivered with the Tex Live version available from the Ubuntu repositories are not up to date.

I was able to fix it by installing Tex Live manually and NOT from the repositories. Check the quick install guide for Tex Live on how  to acquire it and add it to your PATH. You can then update your packages with the _tlmgr_ command. Both Tex Live version can be installed simultaneously. That solved the problem for me.

**Comment by TeXhackse** [comment]
It should also be possible without. I am just wondering, because it's also possible to install the ICC profiles using the package management. I'd just like to know about the version details for that. 

I am still thinking about whats the easiest way for ubuntu users to simplify.

**Comment by TeXhackse** [comment]
@Leistungskurve3000: I will close this, as I did not get a logfile. If you want any further reaction I'd need that.
