### ISSUE TITLE
Bold Font in Captions becomes Charter

### ISSUE THREAD

**Issue by W0ll4ab** [tudace/tuda_latex_templates#97]
This issue is similar to issue #65 ...
For the captions the normal fontstyle is Roboto. This works fine for me but when I'm changing the labelfont to bf for bold, Roboto becomes Xcharter.
Could it be, that there is no bold Roboto fontstyle  for captions? Or is it a problem with the size? Because after checking the .log file I found this: 

> Font shape `T1/Roboto-LF/b/n' in size <12> not available

I'm using the cations package with following modifications:

 `\usepackage[font=footnotesize, justification=centering, textfont={footnotesize,sf}, labelfont={footnotesize,bf}]{caption}`

This produces:
![Fontcaptions2](https://user-images.githubusercontent.com/52467414/69451481-c6684d80-0d5f-11ea-9667-3efa7f87d4cd.png)

with:
`\usepackage[font=footnotesize, justification=centering, textfont={footnotesize,sf}, labelfont={footnotesize,sf}]{caption}`
it produces:
![Fontcaptions1](https://user-images.githubusercontent.com/52467414/69451537-eb5cc080-0d5f-11ea-8d59-b3c67edcc5fe.png)

Now everything is fine in terms of Font but the fontlabel (Abbildung X:) is not in bold...
Is there a way to fix this? maybe to install Roboto manually on the PC?

Maybe my recent .log file helps you out...
[Issue97.log](https://github.com/tudace/tuda_latex_templates/files/3880956/Rektification.log)

**Comment by TeXhackse** [comment]
This is no Problem caused by tuda-ci!

 You are overwriting the font setting of tuda-ci with loading the caption package. Thats why you get the default font + bf.

You can use the KOMA-Script method instead and simply adding.
```
\addtokomafont{captionlabel}{\bfseries}
```
