### ISSUE TITLE
English header for "solution" environment in tudaexercise

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#98]
Trying to create a solution environment in a TUDAExercise when `\usepackage[english]{babel}` is used creates the following error:

`!Undefined control sequence.<argument> \solutionname\solutionsep \end{solution}`

By my understanding, this problem occurs due to a typo in the corresponding class. In lines 598 to 600, the following is contained in tudaexercise.cls:
```
\providecaptionname{ngerman, german}{\solutionname}{Lösungsvorschlag}
\providecaptionname{english, american, british}{\taskname}{Solution}
\newcommand*{\solutionsep}{:~}
```
Replacing "\taskname" by "\solutionname" resolved the problem for me.

**Comment by TeXhackse** [comment]
Ups. Thanks for the report. You are right. I failed with copy paste here :)
Will fix that as a workaround you can add 
```
\providecaptionname{english, american, british}{\solutionname}{Solution}
```
before `\begin{document}`
