### ISSUE TITLE
§8 Abs. 1 lit. d PromO

### ISSUE THREAD

**Issue by MJSteil** [tudace/tuda_latex_templates#99]
https://github.com/tudace/tuda_latex_templates/blob/b2f7853afde432a340bd8e1e9f1e83a2e0271a01/tex/tudathesis.cfg#L496

I would suggest removing the second sentence from this point. After the declaration in the first sentence (no prior attempt) the second sentence makes no sense in my opinion.

**Comment by marklaz** [comment]
We took the affidavit from the one suggested at the department of ETIT (https://www.etit.tu-darmstadt.de/forschen/promotion/downloads_und_weiterfuehrende_links/promotion_downloads_1.de.jsp), as we guess that that formulation should cover most relevant cases and should have been revised adequately.

Feel free to modify it for your own PhD to your requirements.
